import {addTranslations,getLang,tf} from '../core/i18n.js';

export const RECORDINGS40=Object.freeze([
 {en:['Crew six. The pickup light has been on since yesterday.','Dispatch says we returned. We are still here.','Take the salvage near this recorder. Leave a place for us aboard.'],tr:['Altıncı ekip. Tahliye ışığı dünden beri yanıyor.','Sevk merkezi döndüğümüzü söylüyor. Hâlâ buradayız.','Kayıt cihazının yakınındaki hurdayı alın. Gemide bize de yer bırakın.'],ru:['Шестая бригада. Сигнал эвакуации горит со вчерашнего дня.','Диспетчер говорит, что мы вернулись. Мы всё ещё здесь.','Заберите груз рядом с диктофоном. Оставьте нам место на корабле.']},
 {en:['Maintenance log. We restored power to the return desk.','The next message was addressed to a crew that no longer exists.','Our last salvage is near the screen. Please take it outside.'],tr:['Bakım kaydı. İade masasının elektriğini açtık.','Sonraki mesaj artık var olmayan bir ekibe gönderilmişti.','Son hurdamız ekranın yakınında. Lütfen dışarı çıkarın.'],ru:['Журнал ремонта. Мы включили питание стойки возврата.','Следующее сообщение пришло бригаде, которой больше нет.','Наш последний груз недалеко от экрана. Пожалуйста, вынесите его.']},
 {en:['Night shift. We kept the aisle clear for the next crew.','The terminal still prints our names every morning. Nobody answers.','Take what we recovered. Follow the entrance signs home.'],tr:['Gece vardiyası. Sonraki ekip için geçidi açık bıraktık.','Terminal her sabah adlarımızı yazdırıyor. Kimse cevap vermiyor.','Kurtardığımız yükü alın. Giriş tabelalarını izleyip eve dönün.'],ru:['Ночная смена. Мы оставили проход свободным для следующей бригады.','Терминал каждое утро печатает наши имена. Никто не отвечает.','Заберите найденное нами. Возвращайтесь по указателям входа.']},
]);
export const ADVENTURE_TEXT40={play:'Play abandoned crew recording [E]',heard:'Recording recovered · salvage near the screen',lead:'LAST CREW: recording near {bay}',notice:'Recover their salvage. MAIN ENTRANCE leads back to the ship.',returned:'Their salvage is aboard. The recording ends with an empty seat.'};
addTranslations({[ADVENTURE_TEXT40.play]:'Terk edilmiş ekip kaydını dinle [E]',[ADVENTURE_TEXT40.heard]:'Kayıt kurtarıldı · hurda ekranın yakınında',[ADVENTURE_TEXT40.lead]:'SON EKİP: kayıt {bay} yakınında',[ADVENTURE_TEXT40.notice]:'Yüklerini kurtar. ANA GİRİŞ gemiye dönüş yoludur.',[ADVENTURE_TEXT40.returned]:'Yükleri gemide. Kayıt boş bir koltukla bitiyor.'},'tr');
addTranslations({[ADVENTURE_TEXT40.play]:'Воспроизвести запись пропавшей бригады [E]',[ADVENTURE_TEXT40.heard]:'Запись найдена · груз недалеко от экрана',[ADVENTURE_TEXT40.lead]:'ПОСЛЕДНЯЯ БРИГАДА: запись у {bay}',[ADVENTURE_TEXT40.notice]:'Заберите их груз. ГЛАВНЫЙ ВХОД ведёт к кораблю.',[ADVENTURE_TEXT40.returned]:'Их груз на борту. Запись заканчивается пустым креслом.'},'ru');
export function recording40(variant){const r=RECORDINGS40[variant]||RECORDINGS40[0];return [...(r[getLang()]||r.en)];}
export function lead40(title){return tf(ADVENTURE_TEXT40.lead,{bay:title[getLang()]||title.en});}
