// DAILY module strings (English key -> TR / RU). Keys another file already translates are not repeated here.
import { addTranslations } from '../core/i18n.js';

addTranslations({
  'DAILY': 'GÜNLÜK',
  'rewards · challenges · season': 'ödüller · görevler · sezon',
  'Login rewards': 'Giriş ödülleri',
  'Challenges': 'Görevler',
  'Season': 'Sezon',
  'Crates': 'Sandıklar',
  'NEW!': 'YENİ!',
  'Streak': 'Seri',
  'best': 'en iyi',
  'Season tier': 'Sezon kademesi',
  'tier': 'kademe',
  'First win of the day: x2 XP ready': 'Günün ilk zaferi: x2 XP hazır',
  'First win bonus used today': 'Günün ilk zafer bonusu bugün kullanıldı',
  'First win: XP x2': 'İlk zafer: XP x2',
  'FIRST WIN OF THE DAY': 'GÜNÜN İLK ZAFERİ',
  'XP x2': 'XP x2',
  'First win of the day: this reward was doubled.': 'Günün ilk zaferi: bu ödül ikiye katlandı.',
  'CLAIMED': 'ALINDI',
  'TODAY': 'BUGÜN',
  'CLAIM DAY {n}': '{n}. GÜNÜ AL',
  'CLAIM': 'AL',
  'CLAIM ALL ({n})': 'HEPSİNİ AL ({n})',
  'OPEN': 'AÇ',
  'COLLECT': 'TOPLA',
  'REROLL': 'YENİLE',
  'Click or press Space to skip': 'Geçmek için tıkla veya Boşluk\'a bas',
  'Your clock looks off. Rewards follow the latest date this account has seen.': 'Saatin tuhaf görünüyor. Ödüller, bu hesabın gördüğü en son tarihi izler.',
  'Grace day used: your streak is safe.': 'Lütuf günü kullanıldı: serin güvende.',
  'Welcome back. A new week starts with a comeback bonus on day 1.': 'Tekrar hoş geldin. Yeni hafta, 1. günde geri dönüş bonusuyla başlıyor.',
  'A fresh week starts.': 'Yeni bir hafta başlıyor.',
  'Day {n} claimed. See you tomorrow.': '{n}. gün alındı. Yarın görüşürüz.',
  'A cosmetic crate is waiting in CRATES.': 'SANDIKLAR bölümünde bir kozmetik sandık seni bekliyor.',
  'You missed a day. Your grace day keeps the streak alive if you claim now.': 'Bir günü kaçırdın. Şimdi alırsan lütuf günün seriyi yaşatır.',
  'The streak ended, so the week starts over. No hard feelings: day 1 pays a comeback bonus.': 'Seri bitti, hafta baştan başlıyor. Darılmak yok: 1. gün geri dönüş bonusu verir.',
  'The week starts over from day 1.': 'Hafta 1. günden yeniden başlıyor.',
  'Today is claimed. Next reward in {h}h {m}m.': 'Bugünkü ödül alındı. Sonraki ödül {h} sa {m} dk sonra.',
  'Total logins': 'Toplam giriş',
  'Best streak': 'En iyi seri',
  'Grace day ready: missing one day will not break the streak.': 'Lütuf günü hazır: bir gün kaçırmak seriyi bozmaz.',
  'Grace day recharges after 3 days in a row.': 'Lütuf günü, üst üste 3 günden sonra yenilenir.',
  'Waiting for the ship (delivered when you are in orbit)': 'Gemiyi bekleyenler (yörüngedeyken teslim edilir)',
  'Reward': 'Ödül',
  'season XP': 'sezon XP',
  'Bonus crate earned. Open it in CRATES.': 'Bonus sandık kazandın. SANDIKLAR\'dan aç.',
  'Challenge replaced.': 'Görev değiştirildi.',
  'One reroll per day, already used': 'Günde bir yenileme, bugün kullanıldı',
  'Swap this challenge for another of the same difficulty (once per day)': 'Bu görevi aynı zorlukta başkasıyla değiştir (günde bir kez)',
  'Daily challenges': 'Günlük görevler',
  'Weekly challenges': 'Haftalık görevler',
  'same three for every player today · resets at midnight': 'bugün herkes için aynı üç görev · gece yarısı yenilenir',
  'Finish and claim all three for a Supply Crate.': 'Üçünü de bitirip alırsan bir Malzeme Sandığı kazanırsın.',
  'resets in {n} days': '{n} gün sonra yenilenir',
  'Claim all three weekly challenges for a Weekly Crate (a rare-or-better cosmetic).': 'Üç haftalık görevi de alırsan Haftalık Sandık gelir (nadir veya daha iyi kozmetik).',
  '{n} days left · free track, earned by playing': '{n} gün kaldı · ücretsiz yol, oynayarak kazanılır',
  'All tiers reached': 'Tüm kademelere ulaşıldı',
  'Tier {tier} · {into} / {need} season XP to the next': 'Kademe {tier} · sonrakine {into} / {need} sezon XP',
  'Season crates are waiting in CRATES.': 'Sezon sandıkları SANDIKLAR\'da seni bekliyor.',
  'Season crate earned. Open it in CRATES.': 'Sezon sandığı kazandın. SANDIKLAR\'dan aç.',
  '{tier} cosmetic': '{tier} kozmetik',
  '{tier} cosmetic crate': '{tier} kozmetik sandık',
  'Season XP comes from challenges, surviving days, quotas, kills and selling scrap. The track restarts every month; anything you earned but did not claim is collected for you.': 'Sezon XP\'si görevlerden, hayatta kalınan günlerden, kotalardan, öldürmelerden ve hurda satışından gelir. Yol her ay yeniden başlar; kazanıp almadığın her şey senin için toplanır.',
  'Last season ended: {n} unclaimed tiers were collected for you (+{coin} Clout, {crates} crates).': 'Geçen sezon bitti: alınmamış {n} kademe senin için toplandı (+{coin} Clout, {crates} sandık).',
  'Supply Crate': 'Malzeme Sandığı',
  'Cosmetic Crate': 'Kozmetik Sandık',
  'Weekly Crate': 'Haftalık Sandık',
  'Season Crate': 'Sezon Sandığı',
  'Quota Crate': 'Kota Sandığı',
  'Parts, Clout and the odd cosmetic': 'Parça, Clout ve ara sıra bir kozmetik',
  'One cosmetic, guaranteed': 'Bir kozmetik, garantili',
  'A rare-or-better cosmetic': 'Nadir veya daha iyi bir kozmetik',
  'A cosmetic of the tier shown': 'Gösterilen kademede bir kozmetik',
  'earned by playing, never bought': 'oynayarak kazanılır, asla satın alınmaz',
  'No crates yet. Day 7 of the login calendar, finishing all daily or weekly challenges, meeting a quota (once a day), season milestones and level milestones all award one.': 'Henüz sandık yok. Giriş takviminin 7. günü, tüm günlük veya haftalık görevleri bitirmek, kota doldurmak (günde bir), sezon ve seviye kilometre taşları sandık verir.',
  'Can contain': 'İçerebilir',
  'Common': 'Sıradan',
  'Uncommon': 'Yaygın Değil',
  'Rare': 'Nadir',
  'Epic': 'Destansı',
  'Legendary': 'Efsanevi',
  'Mythic': 'Mitik',
  'Face': 'Yüz',
  'Back': 'Sırt',
  'Title': 'Unvan',
  'NEW COSMETIC': 'YENİ KOZMETİK',
  'PARTS': 'PARÇALAR',
  'Parts': 'Parçalar',
  'CLOUT': 'CLOUT',
  'DUPLICATE': 'TEKRAR',
  'Delivered to your ship': 'Gemine teslim edilir',
  'Duplicate protection: you own everything, so it turned into Clout': 'Kopya koruması: hepsine sahipsin, o yüzden Clout\'a dönüştü',
  'EASY': 'KOLAY',
  'MEDIUM': 'ORTA',
  'HARD': 'ZOR',
  'WEEKLY': 'HAFTALIK',
  'Secure {n} scrap value': '{n} değerinde hurdayı güvene al',
  'Kill {n} creatures': '{n} yaratık öldür',
  'Kill {n} creatures with melee': 'Yakın dövüşle {n} yaratık öldür',
  'Survive {n} day on a moon': 'Bir ayda {n} gün hayatta kal',
  'Survive {n} days on the moons': 'Aylarda {n} gün hayatta kal',
  'Sell {n} scrap value': '{n} değerinde hurda sat',
  'Open {n} chest': '{n} sandık aç',
  'Open {n} chests': '{n} sandık aç',
  'Catch {n} phish': '{n} phish yakala',
  'Extract {n} scrap value': '{n} değerinde hurda çıkar',
  'Survive an anomaly (reach GLITCHING and live through the day)': 'Bir anomaliden sağ çık (GLITCHING seviyesine ulaş ve günü atlat)',
  'Survive {n} anomalies (reach GLITCHING and live through the day)': '{n} anomaliden sağ çık (GLITCHING seviyesine ulaş ve günü atlat)',
  'Finish {n} facility minigames (vault / fuse)': '{n} tesis mini oyununu bitir (kasa / sigorta)',
  'Meet the quota with your crew': 'Ekibinle kotayı doldur',
  'Defeat a boss': 'Bir patronu yen',
  'Extract a facility core': 'Bir tesis çekirdeğini çıkar',
  'Clocked In': 'Mesaiye Başladı',
  'Overtime Legend': 'Fazla Mesai Efsanesi',
  'Employee of the Season': 'Sezonun Çalışanı',
  'Season tier {n} reached. Claim it in DAILY [F2].': 'Sezon kademesi {n} açıldı. GÜNLÜK [F2] bölümünden al.',
  'Weekly challenge complete': 'Haftalık görev tamam',
  'Challenge complete': 'Görev tamam',
  'QUOTA CRATE': 'KOTA SANDIĞI',
  'EARNED': 'KAZANILDI',
  'The Algorithm is pleased. A Quota Crate is waiting in DAILY [F2].': 'Algoritma memnun. GÜNLÜK [F2] bölümünde bir Kota Sandığı seni bekliyor.',
  '+1 skill point [K]': '+1 yetenek puanı [K]',
  'Level {n} milestone: a Supply Crate is waiting in DAILY [F2]': 'Seviye {n} kilometre taşı: GÜNLÜK [F2] bölümünde bir Malzeme Sandığı seni bekliyor',
  'Daily parcel delivered to the ship: {items}': 'Günlük paket gemiye teslim edildi: {items}',
  'DAILY REWARDS': 'GÜNLÜK ÖDÜLLER',
  'reward ready: press B to claim': 'ödül hazır: almak için B\'ye bas',
  'claimed today': 'bugün alındı',
  'Press B in the ship or HUD to open the DAILY panel.': 'GÜNLÜK panelini açmak için oyunda B\'ye bas.',
  'Your daily reward is ready. Press B to claim it.': 'Günlük ödülün hazır. Almak için B\'ye bas.',
  'Rewards are waiting in DAILY [F2].': 'Ödüller GÜNLÜK [F2] bölümünde bekliyor.',
});

addTranslations({
  'DAILY': 'ЕЖЕДНЕВНОЕ',
  'rewards · challenges · season': 'награды · задания · сезон',
  'Login rewards': 'Награды за вход',
  'Challenges': 'Задания',
  'Season': 'Сезон',
  'Crates': 'Ящики',
  'NEW!': 'НОВОЕ!',
  'Streak': 'Серия',
  'Season tier': 'Уровень сезона',
  'tier': 'уровень',
  'First win of the day: x2 XP ready': 'Первая победа дня: x2 опыта готово',
  'First win bonus used today': 'Бонус первой победы сегодня использован',
  'First win: XP x2': 'Первая победа: опыт x2',
  'FIRST WIN OF THE DAY': 'ПЕРВАЯ ПОБЕДА ДНЯ',
  'XP x2': 'Опыт x2',
  'First win of the day: this reward was doubled.': 'Первая победа дня: эта награда удвоена.',
  'CLAIMED': 'ПОЛУЧЕНО',
  'TODAY': 'СЕГОДНЯ',
  'CLAIM DAY {n}': 'ЗАБРАТЬ ДЕНЬ {n}',
  'CLAIM': 'ЗАБРАТЬ',
  'CLAIM ALL ({n})': 'ЗАБРАТЬ ВСЁ ({n})',
  'COLLECT': 'ЗАБРАТЬ',
  'REROLL': 'ЗАМЕНИТЬ',
  'Click or press Space to skip': 'Нажмите или Пробел, чтобы пропустить',
  'Your clock looks off. Rewards follow the latest date this account has seen.': 'Часы выглядят странно. Награды следуют последней дате, которую видел этот аккаунт.',
  'Grace day used: your streak is safe.': 'Льготный день использован: серия сохранена.',
  'Welcome back. A new week starts with a comeback bonus on day 1.': 'С возвращением. Новая неделя начнётся с бонуса за возвращение в день 1.',
  'A fresh week starts.': 'Начинается новая неделя.',
  'Day {n} claimed. See you tomorrow.': 'День {n} получен. До завтра.',
  'A cosmetic crate is waiting in CRATES.': 'Косметический ящик ждёт в разделе ЯЩИКИ.',
  'You missed a day. Your grace day keeps the streak alive if you claim now.': 'Вы пропустили день. Льготный день сохранит серию, если забрать награду сейчас.',
  'The streak ended, so the week starts over. No hard feelings: day 1 pays a comeback bonus.': 'Серия закончилась, неделя начнётся заново. Без обид: день 1 даёт бонус за возвращение.',
  'The week starts over from day 1.': 'Неделя начинается заново с дня 1.',
  'Today is claimed. Next reward in {h}h {m}m.': 'Сегодняшняя награда получена. Следующая через {h} ч {m} мин.',
  'Total logins': 'Всего входов',
  'Best streak': 'Лучшая серия',
  'Grace day ready: missing one day will not break the streak.': 'Льготный день готов: один пропуск не сломает серию.',
  'Grace day recharges after 3 days in a row.': 'Льготный день восстановится после 3 дней подряд.',
  'Waiting for the ship (delivered when you are in orbit)': 'Ждёт корабль (доставка на орбите)',
  'Reward': 'Награда',
  'season XP': 'опыт сезона',
  'Bonus crate earned. Open it in CRATES.': 'Получен бонусный ящик. Откройте его в разделе ЯЩИКИ.',
  'Challenge replaced.': 'Задание заменено.',
  'One reroll per day, already used': 'Одна замена в день, уже использована',
  'Swap this challenge for another of the same difficulty (once per day)': 'Заменить задание на другое той же сложности (раз в день)',
  'Daily challenges': 'Ежедневные задания',
  'Weekly challenges': 'Еженедельные задания',
  'same three for every player today · resets at midnight': 'сегодня одни и те же три задания у всех · обновление в полночь',
  'Finish and claim all three for a Supply Crate.': 'Выполните и заберите все три, чтобы получить Ящик припасов.',
  'resets in {n} days': 'обновится через {n} дн.',
  'Claim all three weekly challenges for a Weekly Crate (a rare-or-better cosmetic).': 'Заберите все три недельных задания и получите Недельный ящик (косметика редкого качества и выше).',
  '{n} days left · free track, earned by playing': 'осталось {n} дн. · бесплатная дорожка, за игру',
  'All tiers reached': 'Все уровни достигнуты',
  'Tier {tier} · {into} / {need} season XP to the next': 'Уровень {tier} · до следующего {into} / {need} опыта сезона',
  'Season crates are waiting in CRATES.': 'Сезонные ящики ждут в разделе ЯЩИКИ.',
  'Season crate earned. Open it in CRATES.': 'Получен сезонный ящик. Откройте его в разделе ЯЩИКИ.',
  '{tier} cosmetic': 'Косметика: {tier}',
  '{tier} cosmetic crate': 'Косметический ящик: {tier}',
  'Season XP comes from challenges, surviving days, quotas, kills and selling scrap. The track restarts every month; anything you earned but did not claim is collected for you.': 'Опыт сезона дают задания, выжитые дни, квоты, убийства и продажа хлама. Дорожка обновляется каждый месяц; всё заработанное, но не забранное, будет собрано за вас.',
  'Last season ended: {n} unclaimed tiers were collected for you (+{coin} Clout, {crates} crates).': 'Прошлый сезон закончился: {n} неполученных уровней собраны за вас (+{coin} Клаута, ящиков: {crates}).',
  'Supply Crate': 'Ящик припасов',
  'Cosmetic Crate': 'Косметический ящик',
  'Weekly Crate': 'Недельный ящик',
  'Season Crate': 'Сезонный ящик',
  'Quota Crate': 'Ящик квоты',
  'Parts, Clout and the odd cosmetic': 'Детали, Клаут и иногда косметика',
  'One cosmetic, guaranteed': 'Одна косметика, гарантированно',
  'A rare-or-better cosmetic': 'Косметика редкого качества или лучше',
  'A cosmetic of the tier shown': 'Косметика показанного качества',
  'earned by playing, never bought': 'зарабатываются игрой, не покупаются',
  'No crates yet. Day 7 of the login calendar, finishing all daily or weekly challenges, meeting a quota (once a day), season milestones and level milestones all award one.': 'Ящиков пока нет. Их дают: 7-й день календаря, все ежедневные или еженедельные задания, квота (раз в день), вехи сезона и уровней.',
  'Can contain': 'Может содержать',
  'Face': 'Лицо',
  'Back': 'Спина',
  'NEW COSMETIC': 'НОВАЯ КОСМЕТИКА',
  'PARTS': 'ДЕТАЛИ',
  'Parts': 'Детали',
  'CLOUT': 'КЛАУТ',
  'DUPLICATE': 'ДУБЛИКАТ',
  'Delivered to your ship': 'Доставляется на корабль',
  'Duplicate protection: you own everything, so it turned into Clout': 'Защита от дубликатов: у вас всё есть, поэтому это стало Клаутом',
  'EASY': 'ЛЕГКО',
  'MEDIUM': 'СРЕДНЕ',
  'HARD': 'СЛОЖНО',
  'Secure {n} scrap value': 'Доставьте хлама на {n}',
  'Kill {n} creatures': 'Убейте существ: {n}',
  'Kill {n} creatures with melee': 'Убейте существ в ближнем бою: {n}',
  'Survive {n} day on a moon': 'Переживите дней на луне: {n}',
  'Survive {n} days on the moons': 'Переживите дней на лунах: {n}',
  'Sell {n} scrap value': 'Продайте хлама на {n}',
  'Open {n} chest': 'Откройте сундуков: {n}',
  'Open {n} chests': 'Откройте сундуков: {n}',
  'Catch {n} phish': 'Поймайте phish: {n}',
  'Extract {n} scrap value': 'Вынесите хлама на {n}',
  'Survive an anomaly (reach GLITCHING and live through the day)': 'Переживите аномалию (достигните GLITCHING и доживите до конца дня)',
  'Survive {n} anomalies (reach GLITCHING and live through the day)': 'Переживите аномалий: {n} (достигните GLITCHING и доживите до конца дня)',
  'Finish {n} facility minigames (vault / fuse)': 'Завершите мини-игры на объекте: {n} (сейф / предохранитель)',
  'Meet the quota with your crew': 'Выполните квоту вместе с командой',
  'Defeat a boss': 'Победите босса',
  'Extract a facility core': 'Вынесите ядро объекта',
  'Clocked In': 'Отметился',
  'Overtime Legend': 'Легенда сверхурочных',
  'Employee of the Season': 'Работник сезона',
  'Season tier {n} reached. Claim it in DAILY [F2].': 'Открыт уровень сезона {n}. Заберите награду в ЕЖЕДНЕВНОМ [F2].',
  'Weekly challenge complete': 'Недельное задание выполнено',
  'Challenge complete': 'Задание выполнено',
  'QUOTA CRATE': 'ЯЩИК КВОТЫ',
  'EARNED': 'ПОЛУЧЕН',
  'The Algorithm is pleased. A Quota Crate is waiting in DAILY [F2].': 'Алгоритм доволен. Ящик квоты ждёт в ЕЖЕДНЕВНОМ [F2].',
  '+1 skill point [K]': '+1 очко навыков [K]',
  'Level {n} milestone: a Supply Crate is waiting in DAILY [F2]': 'Веха уровня {n}: Ящик припасов ждёт в ЕЖЕДНЕВНОМ [F2]',
  'Daily parcel delivered to the ship: {items}': 'Ежедневная посылка доставлена на корабль: {items}',
  'DAILY REWARDS': 'ЕЖЕДНЕВНЫЕ НАГРАДЫ',
  'reward ready: press B to claim': 'награда готова: нажмите B',
  'claimed today': 'сегодня получено',
  'Press B in the ship or HUD to open the DAILY panel.': 'Нажмите B в игре, чтобы открыть панель ЕЖЕДНЕВНОЕ.',
  'Your daily reward is ready. Press B to claim it.': 'Ваша ежедневная награда готова. Нажмите B, чтобы забрать.',
  'Rewards are waiting in DAILY [F2].': 'Награды ждут в ЕЖЕДНЕВНОМ [F2].',
}, 'ru');
