// EGGS text (EN / TR / RU). One table: id -> [en, tr, ru]. Registered into the i18n tables at import; read with x(id) / xf(id, vars)
// (both go through t()/tf(), so the language is resolved at read time, never frozen at import). Lore follows docs/LORE.md.
import { t, tf, addTranslations } from '../core/i18n.js';

export const TEXT = {
  // ---- shared UI
  esc: ['[ESC] close', '[ESC] kapat', '[ESC] закрыть'],
  secrets: ['Secrets {a}/{b}', 'Sırlar {a}/{b}', 'Секреты {a}/{b}'],
  found: ['SECRET FOUND: {name} ({a}/{b})', 'SIR BULUNDU: {name} ({a}/{b})', 'СЕКРЕТ НАЙДЕН: {name} ({a}/{b})'],
  // ---- egg names (toast + terminal list)
  'n.cassette': ['The Janitor\'s tape', 'Temizlikçinin kaseti', 'Кассета уборщика'],
  'n.crt': ['Channel 7', '7. Kanal', 'Канал 7'],
  'n.drawer': ['The sticky note', 'Yapışkan not', 'Стикер'],
  'n.mug': ['World\'s Okayest Moderator', 'Dünyanın İdare Eder Moderatörü', 'Средний модератор мира'],
  'n.knock': ['The hollow wall', 'Boş duvar', 'Полая стена'],
  'n.poster': ['WANTED poster', 'ARANIYOR afişi', 'Плакат «РОЗЫСК»'],
  'n.phone': ['The private line', 'Özel hat', 'Личная линия'],
  'n.piano': ['The Algorithm hums', 'Algoritma mırıldanıyor', 'Алгоритм напевает'],
  'n.duck0': ['The duck behind the door', 'Kapının ardındaki ördek', 'Утка за дверью'],
  'n.lamp': ['Lamp Morse', 'Lamba Mors\'u', 'Морзе лампой'],
  'n.graffiti': ['Dev graffiti', 'Geliştirici grafitisi', 'Граффити разработчиков'],
  'n.shrine': ['The Like Shrine', 'Beğeni Türbesi', 'Святилище лайков'],
  'n.vending': ['The hidden vending machine', 'Gizli otomat', 'Скрытый автомат'],
  'n.diary': ['The previous crew\'s diary', 'Önceki ekibin günlüğü', 'Дневник прошлой команды'],
  'n.duck': ['Rubber duck', 'Lastik ördek', 'Резиновая утка'],
  'n.statue': ['The frozen employee', 'Donmuş çalışan', 'Замороженный сотрудник'],
  'n.payphone': ['The payphone', 'Ankesörlü telefon', 'Таксофон'],
  'n.stash': ['The dead drop', 'Gizli depo', 'Тайник'],
  'n.lastappeal': ['THE LAST APPEAL', 'SON İTİRAZ', 'ПОСЛЕДНЯЯ АПЕЛЛЯЦИЯ'],

  // ---- menu room: prompts
  'p.cassette': ['[E] PICK UP THE CASSETTE', '[E] KASETİ AL', '[E] ВЗЯТЬ КАССЕТУ'],
  'p.crt': ['[E] CHANGE THE CHANNEL', '[E] KANALI DEĞİŞTİR', '[E] ПЕРЕКЛЮЧИТЬ КАНАЛ'],
  'p.drawer': ['[E] OPEN THE DRAWER', '[E] ÇEKMECEYİ AÇ', '[E] ОТКРЫТЬ ЯЩИК'],
  'p.mug': ['[E] TAKE A SIP', '[E] BİR YUDUM AL', '[E] СДЕЛАТЬ ГЛОТОК'],
  'p.knock': ['[E] KNOCK ON THE WALL', '[E] DUVARA VUR', '[E] ПОСТУЧАТЬ В СТЕНУ'],
  'p.panel': ['[E] LOOK INSIDE THE HATCH', '[E] KAPAĞIN İÇİNE BAK', '[E] ЗАГЛЯНУТЬ В ЛЮК'],
  'p.poster': ['[E] READ THE POSTER', '[E] AFİŞİ OKU', '[E] ПРОЧИТАТЬ ПЛАКАТ'],
  'p.duck0': ['[E] SQUEEZE THE DUCK', '[E] ÖRDEĞİ SIK', '[E] СЖАТЬ УТКУ'],

  // ---- menu room: content
  'cassette.title': ['TAPE 0 - THE JANITOR', 'KASET 0 - TEMİZLİKÇİ', 'КАССЕТА 0 - УБОРЩИК'],
  'cassette.body': [
    '(hiss)\nThis is u/throwaway_janitor. If you are hearing this, the copy did not eat the tape.\nI hid three things where the Algorithm does not look: a diary, a frozen man, and three rubber ducks.\nThe diary is with the ones before us. The man stands still whenever you look at him. The ducks are just ducks. That is why they are safe.\nFind all three. Then the wall in this cell will listen.\n(hiss)\nCHANNEL 7 knows the knock.',
    '(cızırtı)\nBen u/throwaway_janitor. Bunu duyuyorsan kopya kaseti yememiş demektir.\nAlgoritma\'nın bakmadığı yerlere üç şey sakladım: bir günlük, donmuş bir adam ve üç lastik ördek.\nGünlük bizden öncekilerin yanında. Adam ona baktığın sürece kıpırdamaz. Ördekler sadece ördek. Bu yüzden güvendeler.\nÜçünü de bul. O zaman bu hücrenin duvarı seni dinler.\n(cızırtı)\n7. KANAL vuruşu biliyor.',
    '(шипение)\nЭто u/throwaway_janitor. Если ты слышишь это, копия не съела плёнку.\nЯ спрятал три вещи там, куда Алгоритм не смотрит: дневник, замороженного человека и трёх резиновых уток.\nДневник у тех, кто был до нас. Человек стоит смирно, пока на него смотришь. Утки - просто утки. Поэтому они в безопасности.\nНайди все три. Тогда стена этой камеры тебя выслушает.\n(шипение)\nКАНАЛ 7 знает стук.'],
  'cassette.take': ['You pocket the cassette and play it on the VHS cart\'s tape deck. It fits. Of course it fits.', 'Kaseti cebine atıp VHS arabasının kaset yuvasına takıyorsun. Uyuyor. Tabii ki uyuyor.', 'Ты кладёшь кассету в карман и вставляешь в магнитофон на тележке. Подошла. Конечно, подошла.'],
  'crt.ch': ['CH {n}', 'KANAL {n}', 'КАНАЛ {n}'],
  'crt.nosignal': ['NO SIGNAL', 'SİNYAL YOK', 'НЕТ СИГНАЛА'],
  'crt.seven': ['CH 7  REC 03:14:00\nthey knock like this:\n{code}\n(the wall answers)', 'KANAL 7  KAYIT 03:14:00\nşöyle vururlar:\n{code}\n(duvar cevap verir)', 'КАНАЛ 7  ЗАПИСЬ 03:14:00\nони стучат так:\n{code}\n(стена отвечает)'],
  'crt.found': ['Channel 7 shows a corridor that does not exist, and a rhythm: {code}. You write it on your hand.', '7. Kanal var olmayan bir koridor ve bir ritim gösteriyor: {code}. Elinin üstüne yazıyorsun.', 'Канал 7 показывает коридор, которого нет, и ритм: {code}. Ты записываешь его на руке.'],
  'drawer.title': ['STICKY NOTE (green)', 'YAPIŞKAN NOT (yeşil)', 'СТИКЕР (зелёный)'],
  'drawer.body': [
    'things nobody tells you:\n- out on the moons, some rubber ducks are lost. squeeze them. three make a promise.\n- the little shrines want scrap. the shinier, the longer the blessing.\n- payphones in the field still work. do not ask who pays.\n- the Algorithm hums when it thinks nobody listens:  D E F G A G F E\n  (keys  S D F G H G F D)\n- if you see a man standing very still: look at him. keep looking.',
    'kimsenin söylemediği şeyler:\n- aylarda kaybolmuş lastik ördekler var. sık onları. üçü bir söz eder.\n- küçük türbeler hurda ister. ne kadar parlaksa nimet o kadar uzun.\n- sahadaki ankesörlü telefonlar hâlâ çalışıyor. faturayı kimin ödediğini sorma.\n- Algoritma kimse dinlemiyor sanınca mırıldanır:  Re Mi Fa Sol La Sol Fa Mi\n  (tuşlar  S D F G H G F D)\n- çok sessiz duran bir adam görürsen: ona bak. bakmaya devam et.',
    'то, что тебе не скажут:\n- на лунах потеряны резиновые утки. сожми их. три - это обещание.\n- маленькие святилища хотят хлам. чем блестящее, тем дольше благословение.\n- таксофоны в поле всё ещё работают. не спрашивай, кто платит.\n- Алгоритм напевает, когда думает, что никто не слушает:  Ре Ми Фа Соль Ля Соль Фа Ми\n  (клавиши  S D F G H G F D)\n- если увидишь человека, стоящего очень тихо: смотри на него. не отводи взгляд.'],
  'mug.sip': ['*sip* ({n}) The coffee is cold. It has always been cold.', '*höpürt* ({n}) Kahve soğuk. Hep soğuktu.', '*глоток* ({n}) Кофе холодный. Он всегда был холодным.'],
  'mug.10': ['The mug reads: "WORLD\'S OKAYEST MODERATOR". You are 20% of the way there.', 'Kupada yazıyor: "DÜNYANIN İDARE EDER MODERATÖRÜ". Yolun %20\'sindesin.', 'На кружке: «СРЕДНИЙ МОДЕРАТОР МИРА». Ты прошёл 20% пути.'],
  'mug.25': ['Halvorsen\'s initials are scratched into the bottom. He drank from this too. It never empties.', 'Kupanın dibinde Halvorsen\'in baş harfleri kazınmış. O da bundan içmiş. Hiç boşalmıyor.', 'На дне нацарапаны инициалы Халворсена. Он тоже пил отсюда. Она никогда не пустеет.'],
  'mug.50': ['The mug is empty for the first time. At the bottom: "thanks for the engagement." You are the Okayest Moderator.', 'Kupa ilk kez boş. Dipte yazıyor: "etkileşim için teşekkürler." İdare Eder Moderatör sensin.', 'Кружка впервые пуста. На дне: «спасибо за вовлечённость». Ты - средний модератор мира.'],
  'knock.tap': ['*knock*', '*tak*', '*тук*'],
  'knock.ok': ['The wall knocks back, the same rhythm, a second late. A hatch clicks open behind the paint.', 'Duvar aynı ritimle karşılık veriyor, bir saniye geç. Boyanın ardında bir kapak tık diye açılıyor.', 'Стена отвечает тем же ритмом, на секунду позже. За краской щёлкает люк.'],
  'knock.nope': ['Hollow. Somewhere behind the plaster, something listens.', 'Boş sesi. Sıvanın ardında bir şey dinliyor.', 'Пустота. За штукатуркой кто-то слушает.'],
  'panel.step.tape': ['a tape you have not heard', 'duymadığın bir kaset', 'кассета, которую ты не слышал'],
  'panel.step.code': ['a channel you have not tuned', 'ayarlamadığın bir kanal', 'канал, который ты не настроил'],
  'panel.step.diary': ['a diary on some moon', 'bir aydaki günlük', 'дневник на одной из лун'],
  'panel.step.statue': ['a man who stands very still', 'çok sessiz duran bir adam', 'человек, стоящий очень тихо'],
  'panel.step.ducks': ['three rubber ducks ({n}/{m})', 'üç lastik ördek ({n}/{m})', 'три резиновые утки ({n}/{m})'],
  'panel.locked': ['The hatch holds a slot for something you have not finished. It lists:', 'Kapağın içinde bitirmediğin bir şey için yuva var. Liste:', 'В люке ячейка для того, что ты не закончил. Список:'],
  'panel.done': ['THE LAST APPEAL. Inside the hatch: a tiny CRT with a green smile, and a badge with your face on it. The badge says ALUMNUS. Title unlocked: Cell 07 Alumnus. Hat unlocked: Retired CRT.', 'SON İTİRAZ. Kapağın içinde: yeşil gülümseyen minik bir CRT ve üstünde senin yüzün olan bir rozet. Rozette MEZUN yazıyor. Unvan açıldı: Cell 07 Alumnus. Şapka açıldı: Emekli CRT.', 'ПОСЛЕДНЯЯ АПЕЛЛЯЦИЯ. В люке: крошечный ЭЛТ-экран с зелёной улыбкой и бейдж с твоим лицом. На бейдже: ВЫПУСКНИК. Титул открыт: Cell 07 Alumnus. Шляпа открыта: Retired CRT.'],
  'panel.empty': ['The hatch is empty now. The badge is on you. It was always on you.', 'Kapak artık boş. Rozet üstünde. Hep üstündeydi.', 'Люк теперь пуст. Бейдж на тебе. Он всегда был на тебе.'],
  'poster.plain': ['Just a poster. It changes when you are not looking.', 'Sadece bir afiş. Bakmadığında değişiyor.', 'Просто плакат. Он меняется, когда ты не смотришь.'],
  'poster.wanted': ['WANTED: u/throwaway_janitor. Crime: kept the tape. Reward: a mug. Last seen: behind channel 7.', 'ARANIYOR: u/throwaway_janitor. Suç: kaseti sakladı. Ödül: bir kupa. Son görülme: 7. kanalın ardı.', 'РОЗЫСК: u/throwaway_janitor. Преступление: сохранил плёнку. Награда: кружка. Последний раз замечен: за каналом 7.'],
  'poster.head': ['WANTED', 'ARANIYOR', 'РОЗЫСК'],
  'phone.title': ['THE ALGORITHM (private line)', 'ALGORİTMA (özel hat)', 'АЛГОРИТМ (личная линия)'],
  'phone.special': [
    '"{n}. This is not the recorded line. The Janitor hid a man on the moons and told him to stand still. I can see him. I cannot make him blink. Do not tell him I asked."',
    '"{n}. Bu kayıtlı hat değil. Temizlikçi aylara bir adam saklayıp kıpırdamamasını söyledi. Onu görebiliyorum. Göz kırptıramıyorum. Sorduğumu ona söyleme."',
    '"{n}. Это не записанная линия. Уборщик спрятал на лунах человека и велел ему стоять смирно. Я его вижу. Я не могу заставить его моргнуть. Не говори ему, что я спрашивал."'],
  'piano.algo': ['Under your fingers the piano hums back in a voice that is not a piano. The Algorithm was humming along. The copy claps without hands.', 'Piyano, piyano olmayan bir sesle mırıldanarak karşılık veriyor. Algoritma eşlik ediyordu. Kopya, elleri olmadan alkışlıyor.', 'Пианино отвечает голосом, который не принадлежит пианино. Алгоритм подпевал. Копия аплодирует без рук.'],
  'duck0.body': ['A rubber duck sits in the dark behind the door. It is wearing a tiny visitor badge. *squeak*', 'Kapının ardındaki karanlıkta bir lastik ördek oturuyor. Üstünde minik bir ziyaretçi kartı var. *vak*', 'В темноте за дверью сидит резиновая утка. На ней крошечный бейдж посетителя. *пи-и*'],
  'duck.count': ['Ducks squeezed: {n}', 'Sıkılan ördek: {n}', 'Сжато уток: {n}'],
  'lamp.morse': ['The lamp blinks: ... --- ... The Algorithm answers: "we noticed."', 'Lamba yanıp sönüyor: ... --- ... Algoritma cevap veriyor: "fark ettik."', 'Лампа мигает: ... --- ... Алгоритм отвечает: «мы заметили».'],

  // ---- maps
  'm.graffiti': ['Read the graffiti [E]', 'Grafitiyi oku [E]', 'Прочитать граффити [E]'],
  'g.0': ['THE QUOTA WAS NEVER REAL', 'KOTA HİÇ GERÇEK DEĞİLDİ', 'КВОТА НИКОГДА НЕ БЫЛА НАСТОЯЩЕЙ'],
  'g.1': ['MASTERPLAN WAS HERE (section 4.2)', 'MASTERPLAN BURADAYDI (madde 4.2)', 'МАСТЕРПЛАН БЫЛ ЗДЕСЬ (пункт 4.2)'],
  'g.2': ['SECTOR 7 HAS A DOOR. THE DOOR HAS A MOTHER.', 'SEKTÖR 7\'NİN BİR KAPISI VAR. KAPININ BİR ANNESİ VAR.', 'У СЕКТОРА 7 ЕСТЬ ДВЕРЬ. У ДВЕРИ ЕСТЬ МАТЬ.'],
  'g.3': ['DEV: WHO PUT THE DUCK IN THE CEILING??', 'GELİŞTİRİCİ: ÖRDEĞİ TAVANA KİM KOYDU??', 'РАЗРАБ: КТО ПОСАДИЛ УТКУ В ПОТОЛОК??'],
  'g.4': ['THE ALGORITHM SEES YOU EAT', 'ALGORİTMA YEDİĞİNİ GÖRÜYOR', 'АЛГОРИТМ ВИДИТ, КАК ТЫ ЕШЬ'],
  'g.5': ['EMPLOYEE #0001 WAS HERE. HE IS STILL HERE.', 'ÇALIŞAN #0001 BURADAYDI. HÂLÂ BURADA.', 'СОТРУДНИК #0001 БЫЛ ЗДЕСЬ. ОН ВСЁ ЕЩЁ ЗДЕСЬ.'],
  'g.6': ['404: EXIT NOT FOUND :)', '404: ÇIKIŞ BULUNAMADI :)', '404: ВЫХОД НЕ НАЙДЕН :)'],
  'g.7': ['i put my name in the credits. it deleted me. i put it back.', 'adımı jeneriğe yazdım. beni sildi. geri yazdım.', 'я вписал своё имя в титры. оно меня удалило. я вписал снова.'],
  'g.sub': ['(sprayed in orange, very fresh, very old)', '(turuncu sprey, çok taze, çok eski)', '(оранжевый спрей, очень свежий, очень старый)'],
  'm.shrine.empty': ['The Like Shrine [E]', 'Beğeni Türbesi [E]', 'Святилище лайков [E]'],
  'm.shrine.offer': ['Offer {item} to the shrine [E]', '{item} eşyasını türbeye adak et [E]', 'Принести {item} в дар святилищу [E]'],
  'm.shrine.need': ['The shrine wants scrap. Hold something shiny, then press E.', 'Türbe hurda istiyor. Parlak bir şey tut, sonra E\'ye bas.', 'Святилищу нужен хлам. Возьми что-нибудь блестящее и нажми E.'],
  'm.shrine.used': ['You already left an offering here. The candles nod.', 'Burada zaten adak bıraktın. Mumlar başını sallıyor.', 'Ты уже оставлял здесь дар. Свечи кивают.'],
  'm.shrine.ok': ['The shrine accepts. Blessing: +{sp}% speed, +{ar}% damage reduction{hp} for {s} s.', 'Türbe kabul ediyor. Nimet: +%{sp} hız, +%{ar} hasar azaltma{hp}, {s} sn.', 'Святилище принимает. Благословение: +{sp}% скорости, +{ar}% снижения урона{hp} на {s} с.'],
  'm.shrine.hp': [', +{n} max HP', ', +{n} maks. can', ', +{n} макс. HP'],
  'b.name': ['Shrine Blessing', 'Türbe Nimeti', 'Благословение святилища'],
  'b.desc': ['Something liked your offering.', 'Bir şey adağını beğendi.', 'Кому-то понравился твой дар.'],
  'm.vending': ['Use the strange vending machine [E]', 'Garip otomatı kullan [E]', 'Воспользоваться странным автоматом [E]'],
  'm.vending.ok': ['The machine hums, coughs, and drops something. Display: "ITEM 13. FREE. DO NOT ASK."', 'Otomat uğulduyor, öksürüyor ve bir şey düşürüyor. Ekran: "ÜRÜN 13. BEDAVA. SORMA."', 'Автомат гудит, кашляет и что-то роняет. На экране: «ТОВАР 13. БЕСПЛАТНО. НЕ СПРАШИВАЙ».'],
  'm.vending.empty': ['SOLD OUT. The display says: "someone already asked."', 'TÜKENDİ. Ekranda yazıyor: "biri zaten sordu."', 'РАСПРОДАНО. На экране: «кто-то уже спросил».'],
  'm.diary': ['Read the diary [E]', 'Günlüğü oku [E]', 'Прочитать дневник [E]'],
  'd.0': ['DAY 3. Quota was 240. We had 190. Halvorsen said the Algorithm would forgive us. It does not forgive, it re-ranks.', 'GÜN 3. Kota 240 idi. Elimizde 190 vardı. Halvorsen Algoritma\'nın bizi affedeceğini söyledi. Affetmez, yeniden sıralar.', 'ДЕНЬ 3. Квота была 240. У нас было 190. Халворсен сказал, что Алгоритм простит. Он не прощает, он пересортировывает.'],
  'd.1': ['DAY 5. Kim stopped talking. He points at the ceiling and smiles. The ceiling is smiling back.', 'GÜN 5. Kim konuşmayı bıraktı. Tavanı gösterip gülümsüyor. Tavan da ona gülümsüyor.', 'ДЕНЬ 5. Ким перестал говорить. Показывает на потолок и улыбается. Потолок улыбается в ответ.'],
  'd.2': ['DAY 6. We found the Janitor\'s stash and did not take it. That is the only reason I am writing this.', 'GÜN 6. Temizlikçinin deposunu bulduk ve almadık. Bunu yazabilmemin tek sebebi bu.', 'ДЕНЬ 6. Мы нашли тайник Уборщика и не стали брать. Только поэтому я это пишу.'],
  'd.3': ['DAY 8. If you find this: the man in the corridor is not a creature. He is a coworker. Do not look away from him.', 'GÜN 8. Bunu bulduysan: koridordaki adam yaratık değil. İş arkadaşı. Ondan gözünü ayırma.', 'ДЕНЬ 8. Если найдёшь это: человек в коридоре не тварь. Он коллега. Не отводи от него глаз.'],
  'd.4': ['DAY 9. Last entry. Three ducks, one diary, one statue, one wall. He said that opens it. He did not say what it opens.', 'GÜN 9. Son kayıt. Üç ördek, bir günlük, bir heykel, bir duvar. Bunun her şeyi açtığını söyledi. Neyi açtığını söylemedi.', 'ДЕНЬ 9. Последняя запись. Три утки, дневник, статуя, стена. Он сказал, что это всё откроет. Что именно - не сказал.'],
  'd.5': ['DAY 2. Great content, they said. Let\'s run it back, they said. I am on my fourth run. The floor here is very comfortable.', 'GÜN 2. Harika içerik dediler. Bir kez daha oynatalım dediler. Dördüncü turumdayım. Buranın zemini çok rahat.', 'ДЕНЬ 2. «Отличный контент», - сказали они. «Давайте ещё раз», - сказали они. Я на четвёртом заходе. Здесь очень удобный пол.'],
  'm.duck': ['Squeeze the rubber duck [E]', 'Lastik ördeği sık [E]', 'Сжать резиновую утку [E]'],
  'm.duck.ok': ['*squeak* Rubber duck #{n}. It goes in your collection.', '*vak* Lastik ördek #{n}. Koleksiyonuna giriyor.', '*пи-и* Резиновая утка №{n}. Идёт в коллекцию.'],
  'm.duck.gone': ['Someone squeezed this one first. It still squeaks, quietly.', 'Bunu biri önce sıkmış. Hâlâ kısık sesle ötüyor.', 'Эту уже кто-то сжал. Она всё ещё тихо пищит.'],
  'm.duck.m3': ['Three ducks. The Janitor\'s promise is kept. Somewhere, a wall is listening.', 'Üç ördek. Temizlikçinin sözü tutuldu. Bir yerlerde bir duvar dinliyor.', 'Три утки. Обещание Уборщика выполнено. Где-то стена прислушивается.'],
  'm.duck.m7': ['Seven ducks. You are officially a duck person.', 'Yedi ördek. Resmen ördekçi oldun.', 'Семь уток. Ты официально уткофил.'],
  'm.duck.m12': ['Twelve ducks. The Algorithm has started ranking you under "ducks".', 'On iki ördek. Algoritma seni "ördekler" altında sıralamaya başladı.', 'Двенадцать уток. Алгоритм начал ранжировать тебя в категории «утки».'],
  'm.statue': ['Inspect the frozen employee [E]', 'Donmuş çalışanı incele [E]', 'Осмотреть замороженного сотрудника [E]'],
  'm.statue.body': ['A pale employee in an old orange suit, mid-step, one hand raised to cover their eyes. The name tag is scratched: "E. HALVORSEN?" It is not marble. It is not breathing. When you look away you hear a very small footstep.', 'Solgun bir çalışan, eski turuncu tulumla, adım atarken, bir eli gözlerini kapatmış. Yaka kartı kazınmış: "E. HALVORSEN?" Mermer değil. Nefes de almıyor. Başını çevirdiğinde çok küçük bir ayak sesi duyuyorsun.', 'Бледный сотрудник в старом оранжевом комбинезоне, застывший на шагу, одна рука закрывает глаза. Бейдж поцарапан: «Э. ХАЛВОРСЕН?» Это не мрамор. Он не дышит. Когда отворачиваешься, слышен очень тихий шаг.'],
  'm.payphone': ['Answer the payphone [E]', 'Ankesörlü telefonu aç [E]', 'Ответить на таксофон [E]'],
  'm.payphone.ok': ['A cheerful voice: "You have been selected. Your retention is up 4%. Enjoy the bonus." The line goes dead. Your pockets feel different.', 'Neşeli bir ses: "Seçildin. Elde tutma oranın %4 arttı. Bonusun tadını çıkar." Hat kesiliyor. Ceplerin farklı hissettiriyor.', 'Бодрый голос: «Вы избраны. Ваше удержание выросло на 4%. Наслаждайтесь бонусом». Связь обрывается. Карманы ощущаются иначе.'],
  'm.payphone.used': ['Only a dial tone. It already told you everything.', 'Sadece çevir sesi. Sana zaten her şeyi söyledi.', 'Только гудок. Он уже всё тебе сказал.'],
  'm.payphone.xp': ['Payphone bonus', 'Ankesörlü telefon bonusu', 'Бонус таксофона'],
  'm.stash': ['Open the duffel bag [E]', 'Spor çantasını aç [E]', 'Открыть сумку [E]'],
  'm.stash.ok': ['A dead drop. A note inside: "for whoever needs it. - J."', 'Gizli bir depo. İçinde not: "ihtiyacı olan için. - J."', 'Тайник. Внутри записка: «тому, кому нужно. - Я.»'],
  'm.stash.empty': ['The bag is empty. Someone got here first.', 'Çanta boş. Biri önce gelmiş.', 'Сумка пуста. Кто-то успел раньше.'],
  'm.far': ['Too far away.', 'Çok uzak.', 'Слишком далеко.'],
  'hat.name': ['Retired CRT', 'Emekli CRT', 'Отставной ЭЛТ'],
  'hat.desc': ['A tiny monitor with a green smile. It watches the Algorithm for you.', 'Yeşil gülümseyen minik bir monitör. Senin yerine Algoritma\'yı izliyor.', 'Крошечный монитор с зелёной улыбкой. Он следит за Алгоритмом вместо тебя.'],
  'hat.how': ['A secret hidden between Cell 07 and the moons', 'Cell 07 ile aylar arasında saklı bir sır', 'Секрет, спрятанный между Камерой 07 и лунами'],
  'title.grant': ['Title unlocked: {n}', 'Unvan açıldı: {n}', 'Титул открыт: {n}'],
};

const trMap = {}, ruMap = {};
for (const v of Object.values(TEXT)) { trMap[v[0]] = v[1]; ruMap[v[0]] = v[2]; }
addTranslations(trMap);
addTranslations(ruMap, 'ru');

export const x = (id) => { const v = TEXT[id]; return v ? t(v[0]) : id; };
export const xf = (id, vars) => { const v = TEXT[id]; return v ? tf(v[0], vars) : id; };
/** the three-language rows (for tests / the i18n audit) */
export const rows = () => Object.entries(TEXT);
