export const TR = {
 'Two clicks, then pursuit. Follow mint floor marks, break sight and stay quiet. Cover buys time; it can see you again.': 'İki tık, sonra takip. Mint rengi yer işaretlerini izle, görüşü kes ve sessiz kal. Siper zaman kazandırır; seni yeniden görebilir.',
 'Pursuit unavailable: need a clear marked route, quota 2+, and no active boss or bonus mission.': 'Takip kullanılamıyor: açık bir işaretli yol, kota 2+ ve aktif boss veya bonus görevi olmaması gerekir.',
 'No clear pursuit route here. Step into an open room and try again.': 'Burada açık bir takip yolu yok. Açık bir odaya geçip yeniden dene.',
 'Pursuit escaped. Collect the recording at the first shelter.': 'Takipten kaçtın. Kaydı ilk siper kabininden al.',
 'Pursuit ended. No recording this time.': 'Takip sona erdi. Bu kez kayıt kazanılmadı.',
 'Break sight and survive the search. Doors and quiet shelter buy escape.': 'Görüşü kes ve aramayı atlat. Kapılar ve sessiz siper kaçış için zaman kazandırır.',
 'Collect pursuit recording [E]': 'Takip kaydını al [E]',
 'A recording of a pursuit the Algorithm failed to finish. Sell it as salvage.': 'Algoritmanın tamamlayamadığı bir takibin kaydı. Hurda olarak sat.',
 'Signal Pursuit Recording': 'Sinyal Takip Kaydı',
 'was caught by the Signal Warden.': 'Sinyal Bekçisi tarafından yakalandı.',
 'Signal Warden': 'Sinyal Bekçisi',
 'Two clicks, then pursuit. Sprint, close doors and break sight. Enter a screening alcove to stay quiet; it searches before resting.': 'İki tık, sonra takip. Koş, kapıları kapat ve görüşü kes. Sessiz kalmak için siper kabinine gir; dinlenmeden önce çevreyi arar.',
 'Begin optional pursuit [E]': 'İsteğe bağlı takibi başlat [E]',
 'Enter screening alcove [E]': 'Siper kabinine gir [E]',
 'Leave alcove [E]': 'Kabinden çık [E]',
 'Stay quiet. Shelter lasts 20 seconds; movement is held. Press E to leave.': 'Sessiz kal. Siper 20 saniye sürer; hareket sabitlenir. Çıkmak için E’ye bas.',
 'It saw the shelter. It will check in three seconds; prepare to run.': 'Siperi gördü. Üç saniye sonra kontrol edecek; koşmaya hazırlan.',
 'Shelter ended. Run while the Warden resets.': 'Siper bitti. Bekçi toparlanırken kaç.',
 'Cannot enter: release heavy cargo, trolley or revive; one crewmate per alcove.': 'Girilemiyor: ağır yükü, arabayı veya canlandırmayı bırak; her kabine bir kişi.',
 'Pursuit unavailable: quota 2+, no active boss or bonus mission, and one attempt per landing.': 'Takip kullanılamıyor: kota 2+, aktif boss veya bonus görevi olmamalı; iniş başına bir deneme.'
};
export const RU = {
 'Two clicks, then pursuit. Follow mint floor marks, break sight and stay quiet. Cover buys time; it can see you again.': 'Два щелчка, затем погоня. Следуйте мятным меткам на полу, скройтесь и молчите. Укрытие даёт время; страж может снова вас увидеть.',
 'Pursuit unavailable: need a clear marked route, quota 2+, and no active boss or bonus mission.': 'Погоня недоступна: нужен свободный отмеченный путь, квота 2+ и отсутствие активного босса или бонусной миссии.',
 'No clear pursuit route here. Step into an open room and try again.': 'Здесь нет свободного пути для погони. Перейдите в открытую комнату и повторите.',
 'Pursuit escaped. Collect the recording at the first shelter.': 'Вы ушли от погони. Заберите запись у первого укрытия.',
 'Pursuit ended. No recording this time.': 'Погоня завершена. На этот раз записи нет.',
 'Break sight and survive the search. Doors and quiet shelter buy escape.': 'Скройтесь из виду и переживите поиск. Двери и тихое укрытие дают время для побега.',
 'Collect pursuit recording [E]': 'Забрать запись погони [E]',
 'A recording of a pursuit the Algorithm failed to finish. Sell it as salvage.': 'Запись погони, которую Алгоритм не завершил. Продайте как добычу.',
 'Signal Pursuit Recording': 'Запись сигнальной погони',
 'was caught by the Signal Warden.': 'попался Сигнальному стражу.',
 'Signal Warden': 'Сигнальный страж',
 'Two clicks, then pursuit. Sprint, close doors and break sight. Enter a screening alcove to stay quiet; it searches before resting.': 'Два щелчка, затем погоня. Бегите, закрывайте двери, скрывайтесь из виду. В укрытии молчите: страж сначала ищет, затем отдыхает.',
 'Begin optional pursuit [E]': 'Начать необязательную погоню [E]',
 'Enter screening alcove [E]': 'Войти в укрытие [E]',
 'Leave alcove [E]': 'Выйти из укрытия [E]',
 'Stay quiet. Shelter lasts 20 seconds; movement is held. Press E to leave.': 'Молчите. Укрытие действует 20 секунд; движение остановлено. Нажмите E, чтобы выйти.',
 'It saw the shelter. It will check in three seconds; prepare to run.': 'Страж увидел укрытие. Проверка через три секунды: приготовьтесь бежать.',
 'Shelter ended. Run while the Warden resets.': 'Укрытие закончилось. Бегите, пока страж восстанавливается.',
 'Cannot enter: release heavy cargo, trolley or revive; one crewmate per alcove.': 'Нельзя войти: отпустите тяжёлый груз, тележку или прекратите оживление; укрытие на одного.',
 'Pursuit unavailable: quota 2+, no active boss or bonus mission, and one attempt per landing.': 'Погоня недоступна: квота 2+, без активного босса или бонусной миссии; одна попытка за высадку.'
};
