// EXPEDITION MOONS: Turkish + Russian strings (English is the key). Registered from expeditions.js at import (moon names / descriptions are localized at registration).
export const TR = {
  'Sunken Server Barge': 'Batık Sunucu Mavnası', 'Dune Relay Caravan': 'Kum Rölesi Kervanı', 'Rooftop Blackout City': 'Çatı Karartma Şehri',
  BARGE: 'MAVNA', DUNE: 'KUM', ROOFS: 'ÇATILAR', 'Flooded Server Barge': 'Su Basmış Sunucu Mavnası', 'Dune Relay Route': 'Kum Rölesi Güzergâhı', 'Blackout City': 'Karartma Şehri',
  'A flooded server barge on the seabed. Your air is limited: refill at bubble vents and inside the cabins. Recover 3 data cores from the flooded decks. Currents pull, something hunts in the dark water.':
    'Deniz dibinde sular altında kalmış bir sunucu mavnası. Havan sınırlı: kabarcık bacalarından ve kabinlerin içinden doldur. Su basmış güvertelerden 3 veri çekirdeği çıkar. Akıntılar çekiyor, karanlık suda bir şey avlanıyor.',
  'The sun drains you: find shade, drink from canteens. Escort and repair the relay crawler across 3 checkpoints before the sandstorm buries it. Burrowers hunt by vibration.':
    'Güneş seni tüketir: gölge bul, mataradan su iç. Kum fırtınası gömmeden önce röle paletlisini 3 kontrol noktasından geçir ve tamir et. Kazıcılar titreşimle avlanır.',
  'A city in blackout. Cross the rooftops by plank and zip-line, carry the power cell and relight 4 billboards for the Algorithm. A fall hurts. Drones patrol the skyline.':
    'Karartmadaki bir şehir. Çatıları tahta ve tel hattıyla geç, enerji hücresini taşı ve Algoritma için 4 reklam panosunu yeniden yak. Düşmek acıtır. Dronlar gökyüzü hattında devriye gezer.',
  'Flooded Data Core': 'Sular Altındaki Veri Çekirdeği', 'A sealed server core from the sunken barge. The Algorithm wants it dry.': 'Batık mavnadan mühürlü bir sunucu çekirdeği. Algoritma onu kuru istiyor.',
  'Barnacled Server Blade': 'Midyeli Sunucu Kartı', 'A rack blade grown over with barnacles. Somebody will pay.': 'Midyelerle kaplanmış bir raf kartı. Biri para verir.',
  'Air Tank': 'Hava Tüpü', 'LMB: breathe from it, about 26 s of air. Single use.': 'Sol tık: soluk al, yaklaşık 26 sn hava. Tek kullanımlık.',
  'Sun-Fused Glass': 'Güneşte Kaynamış Cam', 'Sand fused by a lightning-hot dune. It glows when the sun hits it.': 'Yıldırım sıcaklığındaki bir kum tepesinde kaynayan kum. Güneş vurunca parlar.',
  'Relay Capacitor': 'Röle Kondansatörü', 'Pulled from the relay crawler at a checkpoint. Still warm.': 'Kontrol noktasında röle paletlisinden sökülmüş. Hâlâ sıcak.',
  'Canteen': 'Matara', 'LMB: drink. Cools you down. Single use.': 'Sol tık: iç. Seni serinletir. Tek kullanımlık.',
  'Power Cell': 'Enerji Hücresi', 'Carry it to a billboard kiosk [E] to relight it. It drains while carried; swap it at the generator.': 'Yakmak için bir pano kioskuna [E] taşı. Taşırken boşalır; jeneratörde değiştir.',
  'Ad Reel Spool': 'Reklam Makarası', 'A spool of unskippable ads. Collectors love it.': 'Geçilemeyen reklamlardan bir makara. Koleksiyoncılar bayılır.',
  'Dead Neon Letter': 'Sönük Neon Harf', 'A letter from a sign that used to say something.': 'Eskiden bir şey yazan tabeladan bir harf.',
  'Trench Eel': 'Hendek Yılanbalığı', 'It lives in the barge and hates the light. Bubble vents and air cabins keep it away; in the open dark water it is faster than you.': 'Mavnada yaşar ve ışıktan nefret eder. Kabarcık bacaları ve hava kabinleri onu uzak tutar; açık karanlık suda senden hızlıdır.',
  'was eaten by a trench eel.': 'bir hendek yılanbalığına yem oldu.', 'ran out of air.': 'havası bitti.', 'collapsed from the heat.': 'sıcaktan yığıldı.',
  EXPEDITION: 'SEFER', NEED: 'İHTİYAÇ', GOAL: 'HEDEF', Payout: 'Ödeme', 'scaled to the quota, plus unique loot': 'kotaya göre, artı özel ganimet',
  OXYGEN: 'OKSİJEN', HEAT: 'SICAKLIK', 'POWER CELL': 'ENERJİ HÜCRESİ',
  'Air: bubble vents, cabins': 'Hava: kabarcık bacaları, kabinler', 'Heat: shade, canteens': 'Sıcak: gölge, mataralar', 'Power cell drains': 'Enerji hücresi boşalır',
  'Recover 3 data cores': '3 veri çekirdeği çıkar', 'Escort the relay crawler': 'Röle paletlisine eşlik et', 'Relight 4 billboards': '4 panoyu yeniden yak',
  'Recover the 3 data cores and bring them to the ship': '3 veri çekirdeğini çıkar ve gemiye getir', 'Escort and repair the relay crawler across 3 checkpoints before the sandstorm': 'Kum fırtınasından önce röle paletlisine eşlik et ve 3 kontrol noktasında tamir et', 'Carry the power cell and relight the 4 billboards': 'Enerji hücresini taşı ve 4 panoyu yeniden yak',
  'Air only lasts about 30 s in the open water. Refill at a bubble vent or inside a cabin.': 'Açık suda hava yalnızca yaklaşık 30 sn yeter. Kabarcık bacasında ya da kabinin içinde doldur.',
  'The sun heats you up. Stand in shade, drink from a canteen.': 'Güneş seni ısıtır. Gölgede dur, mataradan iç.', 'The cell drains while carried. Swap it at the generator.': 'Hücre taşınırken boşalır. Jeneratörde değiştir.',
  CORES: 'ÇEKİRDEK', STORM: 'FIRTINA', NOW: 'ŞİMDİ', CELL: 'HÜCRE', ADS: 'PANO',
  'AIR LOW: find a bubble vent or a cabin': 'HAVA AZ: bir kabarcık bacası ya da kabin bul', 'Your air is already full.': 'Havan zaten dolu.', 'You breathe from the tank.': 'Tüpten soluk alıyorsun.',
  'You are not hot enough to drink now.': 'Şimdi içecek kadar sıcaklamadın.', 'You drink. The heat eases.': 'Su içtin. Sıcak hafifliyor.', 'You are overheating: find shade or drink': 'Aşırı ısınıyorsun: gölge bul ya da su iç',
  'Ride the zip-line [E]': 'Tel hattına bin [E]', 'Hold on. It is faster than the stairs.': 'Sıkı tut. Merdivenden hızlı.', 'Relight the billboard [E]': 'Panoyu yeniden yak [E]', 'The kiosk needs the power cell': 'Kiosk enerji hücresini bekliyor',
  'Swap the cell at the generator [E]': 'Hücreyi jeneratörde değiştir [E]', 'Take a canteen [E]': 'Matara al [E]', '{n} canteens left': '{n} matara kaldı',
  'All cores recovered. Head back to the ship.': 'Tüm çekirdekler alındı. Gemiye dön.', 'Recover the data cores: {n} / {of}': 'Veri çekirdeklerini çıkar: {n} / {of}',
  'Relay online. Get back to the ship before the storm.': 'Röle çevrimiçi. Fırtınadan önce gemiye dön.', 'The sandstorm buried the crawler. Get back to the ship.': 'Kum fırtınası paletliyi gömdü. Gemiye dön.',
  'Escort the relay crawler: checkpoint {n} / {of}': 'Röle paletlisine eşlik et: kontrol noktası {n} / {of}', 'Stay near the crawler to repair it: {n}%': 'Tamir için paletlinin yanında kal: {n}%',
  'The crawler waits for its escort: stay within 35 m': 'Paletli eşlikçisini bekliyor: 35 m içinde kal', 'Keep up with the crawler. Burrowers hunt by vibration: crouch.': 'Paletliye ayak uydur. Kazıcılar titreşimle avlanır: çömel.',
  'SANDSTORM incoming: finish before it peaks': 'KUM FIRTINASI geliyor: doruğa çıkmadan bitir', 'The billboards are lit. The Algorithm is pleased. Head back to the ship.': 'Panolar yandı. Algoritma memnun. Gemiye dön.',
  'Relight the billboards: {n} / {of}': 'Panoları yeniden yak: {n} / {of}', 'Fetch the power cell from the plaza next to the ship': 'Enerji hücresini gemi yanındaki meydandan al', 'Power cell: {n}%': 'Enerji hücresi: {n}%', 'a crewmate carries it': 'bir mürettebat taşıyor',
  'EXPEDITION CONTRACT: {@n} is listed in the moon list for today only. Type MOONS.': 'SEFER SÖZLEŞMESİ: {@n} yalnızca bugün ay listesinde. MOONS yaz.',
  'A contract just came in. A moon that is not on any map. Do not ask who signs it.': 'Bir sözleşme geldi. Hiçbir haritada olmayan bir ay. Kimin imzaladığını sorma.',
  'Core received. Dry, mostly. The viewers loved the bubbles.': 'Çekirdek teslim alındı. Çoğunlukla kuru. İzleyiciler kabarcıklara bayıldı.',
  'Repair done. The crawler is moving. Keep it company.': 'Tamir bitti. Paletli hareket ediyor. Ona eşlik et.', 'The sandstorm won. I will file that under weather.': 'Kum fırtınası kazandı. Bunu hava durumu altına kaydedeceğim.',
  'Billboard online. Somebody is being sold something.': 'Pano çevrimiçi. Birine bir şey satılıyor.',
  'ALL CORES RECOVERED': 'TÜM ÇEKİRDEKLER ALINDI', 'The Algorithm is pleased.': 'Algoritma memnun.', 'CHECKPOINT {n} / {of}': 'KONTROL NOKTASI {n} / {of}', 'RELAY ONLINE': 'RÖLE ÇEVRİMİÇİ',
  'The Algorithm has signal. Get to the ship.': 'Algoritmanın sinyali var. Gemiye git.', SANDSTORM: 'KUM FIRTINASI', 'The crawler is buried. Back to the ship.': 'Paletli gömüldü. Gemiye dön.', 'THE ADS ARE BACK': 'REKLAMLAR GERİ DÖNDÜ',
  'Expedition pay: ▮{n}': 'Sefer ödemesi: ▮{n}', 'Cell swapped. Fresh charge.': 'Hücre değişti. Taze şarj.', 'You need to carry the power cell.': 'Enerji hücresini taşıyor olmalısın.',
  'The cell is too weak. Swap it at the generator.': 'Hücre çok zayıf. Jeneratörde değiştir.', 'The generator is still recharging.': 'Jeneratör hâlâ şarj oluyor.', 'Nothing happens.': 'Hiçbir şey olmadı.',
};
export const RU = {
  'Sunken Server Barge': 'Затонувшая серверная баржа', 'Dune Relay Caravan': 'Караван дюнного ретранслятора', 'Rooftop Blackout City': 'Город блэкаута: крыши',
  BARGE: 'БАРЖА', DUNE: 'ДЮНЫ', ROOFS: 'КРЫШИ', 'Flooded Server Barge': 'Затопленная серверная баржа', 'Dune Relay Route': 'Маршрут дюнного ретранслятора', 'Blackout City': 'Город блэкаута',
  'A flooded server barge on the seabed. Your air is limited: refill at bubble vents and inside the cabins. Recover 3 data cores from the flooded decks. Currents pull, something hunts in the dark water.':
    'Затопленная серверная баржа на морском дне. Воздуха мало: пополняйте его у пузырьковых гейзеров и в каютах. Достаньте 3 ядра данных с затопленных палуб. Течения тянут, в тёмной воде кто-то охотится.',
  'The sun drains you: find shade, drink from canteens. Escort and repair the relay crawler across 3 checkpoints before the sandstorm buries it. Burrowers hunt by vibration.':
    'Солнце выматывает: ищите тень, пейте из фляг. Сопроводите и почините гусеничный ретранслятор через 3 контрольные точки, пока песчаная буря не засыпала его. Землерои охотятся по вибрации.',
  'A city in blackout. Cross the rooftops by plank and zip-line, carry the power cell and relight 4 billboards for the Algorithm. A fall hurts. Drones patrol the skyline.':
    'Город в блэкауте. Переходите по крышам по доскам и тросам, несите энергоячейку и снова зажгите 4 билборда для Алгоритма. Падение больно. Над горизонтом патрулируют дроны.',
  'Flooded Data Core': 'Затопленное ядро данных', 'A sealed server core from the sunken barge. The Algorithm wants it dry.': 'Герметичное серверное ядро с затонувшей баржи. Алгоритм хочет его сухим.',
  'Barnacled Server Blade': 'Блейд в ракушках', 'A rack blade grown over with barnacles. Somebody will pay.': 'Стоечный блейд, обросший ракушками. Кто-нибудь заплатит.',
  'Air Tank': 'Баллон с воздухом', 'LMB: breathe from it, about 26 s of air. Single use.': 'ЛКМ: дышать из него, около 26 с воздуха. Одноразовый.',
  'Sun-Fused Glass': 'Оплавленное солнцем стекло', 'Sand fused by a lightning-hot dune. It glows when the sun hits it.': 'Песок, сплавленный раскалённой дюной. Светится на солнце.',
  'Relay Capacitor': 'Конденсатор ретранслятора', 'Pulled from the relay crawler at a checkpoint. Still warm.': 'Снят с ретранслятора на контрольной точке. Ещё тёплый.',
  'Canteen': 'Фляга', 'LMB: drink. Cools you down. Single use.': 'ЛКМ: пить. Охлаждает. Одноразовая.',
  'Power Cell': 'Энергоячейка', 'Carry it to a billboard kiosk [E] to relight it. It drains while carried; swap it at the generator.': 'Отнесите к киоску билборда [E], чтобы зажечь его. Разряжается в пути; меняйте на генераторе.',
  'Ad Reel Spool': 'Катушка с рекламой', 'A spool of unskippable ads. Collectors love it.': 'Катушка нескипаемой рекламы. Коллекционеры в восторге.',
  'Dead Neon Letter': 'Мёртвая неоновая буква', 'A letter from a sign that used to say something.': 'Буква с вывески, которая когда-то что-то говорила.',
  'Trench Eel': 'Глубинный угорь', 'It lives in the barge and hates the light. Bubble vents and air cabins keep it away; in the open dark water it is faster than you.': 'Живёт в барже и ненавидит свет. Пузырьковые гейзеры и воздушные каюты держат его на расстоянии; в открытой тёмной воде он быстрее вас.',
  'was eaten by a trench eel.': 'был съеден глубинным угрём.', 'ran out of air.': 'остался без воздуха.', 'collapsed from the heat.': 'рухнул от жары.',
  EXPEDITION: 'ЭКСПЕДИЦИЯ', NEED: 'НУЖДА', GOAL: 'ЦЕЛЬ', Payout: 'Выплата', 'scaled to the quota, plus unique loot': 'по квоте, плюс уникальная добыча',
  OXYGEN: 'КИСЛОРОД', HEAT: 'ЖАРА', 'POWER CELL': 'ЭНЕРГОЯЧЕЙКА',
  'Air: bubble vents, cabins': 'Воздух: гейзеры, каюты', 'Heat: shade, canteens': 'Жара: тень, фляги', 'Power cell drains': 'Ячейка разряжается',
  'Recover 3 data cores': 'Достать 3 ядра данных', 'Escort the relay crawler': 'Сопроводить ретранслятор', 'Relight 4 billboards': 'Зажечь 4 билборда',
  'Recover the 3 data cores and bring them to the ship': 'Достаньте 3 ядра данных и принесите на корабль', 'Escort and repair the relay crawler across 3 checkpoints before the sandstorm': 'Сопроводите и почините ретранслятор через 3 точки до песчаной бури', 'Carry the power cell and relight the 4 billboards': 'Несите энергоячейку и зажгите 4 билборда',
  'Air only lasts about 30 s in the open water. Refill at a bubble vent or inside a cabin.': 'В открытой воде воздуха хватает секунд на 30. Пополняйте у гейзера или в каюте.',
  'The sun heats you up. Stand in shade, drink from a canteen.': 'Солнце нагревает вас. Стойте в тени, пейте из фляги.', 'The cell drains while carried. Swap it at the generator.': 'Ячейка разряжается в пути. Меняйте на генераторе.',
  CORES: 'ЯДРА', STORM: 'БУРЯ', NOW: 'СЕЙЧАС', CELL: 'ЯЧЕЙКА', ADS: 'РЕКЛАМА',
  'AIR LOW: find a bubble vent or a cabin': 'МАЛО ВОЗДУХА: найдите гейзер или каюту', 'Your air is already full.': 'Воздух уже полный.', 'You breathe from the tank.': 'Вы дышите из баллона.',
  'You are not hot enough to drink now.': 'Вам пока не так жарко, чтобы пить.', 'You drink. The heat eases.': 'Вы напились. Жара отступает.', 'You are overheating: find shade or drink': 'Вы перегреваетесь: найдите тень или выпейте',
  'Ride the zip-line [E]': 'Прокатиться по тросу [E]', 'Hold on. It is faster than the stairs.': 'Держитесь. Быстрее лестницы.', 'Relight the billboard [E]': 'Зажечь билборд [E]', 'The kiosk needs the power cell': 'Киоску нужна энергоячейка',
  'Swap the cell at the generator [E]': 'Сменить ячейку на генераторе [E]', 'Take a canteen [E]': 'Взять флягу [E]', '{n} canteens left': 'Осталось фляг: {n}',
  'All cores recovered. Head back to the ship.': 'Все ядра получены. Возвращайтесь на корабль.', 'Recover the data cores: {n} / {of}': 'Достаньте ядра данных: {n} / {of}',
  'Relay online. Get back to the ship before the storm.': 'Ретранслятор в сети. Вернитесь на корабль до бури.', 'The sandstorm buried the crawler. Get back to the ship.': 'Песчаная буря засыпала ретранслятор. Вернитесь на корабль.',
  'Escort the relay crawler: checkpoint {n} / {of}': 'Сопровождайте ретранслятор: точка {n} / {of}', 'Stay near the crawler to repair it: {n}%': 'Оставайтесь у ретранслятора для ремонта: {n}%',
  'The crawler waits for its escort: stay within 35 m': 'Ретранслятор ждёт эскорт: держитесь в 35 м', 'Keep up with the crawler. Burrowers hunt by vibration: crouch.': 'Не отставайте. Землерои охотятся по вибрации: присядьте.',
  'SANDSTORM incoming: finish before it peaks': 'ПЕСЧАНАЯ БУРЯ приближается: успейте до пика', 'The billboards are lit. The Algorithm is pleased. Head back to the ship.': 'Билборды горят. Алгоритм доволен. Возвращайтесь на корабль.',
  'Relight the billboards: {n} / {of}': 'Зажгите билборды: {n} / {of}', 'Fetch the power cell from the plaza next to the ship': 'Заберите энергоячейку на площади у корабля', 'Power cell: {n}%': 'Энергоячейка: {n}%', 'a crewmate carries it': 'её несёт напарник',
  'EXPEDITION CONTRACT: {@n} is listed in the moon list for today only. Type MOONS.': 'КОНТРАКТ НА ЭКСПЕДИЦИЮ: {@n} есть в списке лун только сегодня. Введите MOONS.',
  'A contract just came in. A moon that is not on any map. Do not ask who signs it.': 'Пришёл контракт. Луна, которой нет ни на одной карте. Не спрашивайте, кто подписал.',
  'Core received. Dry, mostly. The viewers loved the bubbles.': 'Ядро получено. В основном сухое. Зрителям понравились пузырьки.',
  'Repair done. The crawler is moving. Keep it company.': 'Ремонт завершён. Ретранслятор едет. Составьте ему компанию.', 'The sandstorm won. I will file that under weather.': 'Буря победила. Запишу это как погоду.',
  'Billboard online. Somebody is being sold something.': 'Билборд в сети. Кому-то что-то продают.',
  'ALL CORES RECOVERED': 'ВСЕ ЯДРА ПОЛУЧЕНЫ', 'The Algorithm is pleased.': 'Алгоритм доволен.', 'CHECKPOINT {n} / {of}': 'КОНТРОЛЬНАЯ ТОЧКА {n} / {of}', 'RELAY ONLINE': 'РЕТРАНСЛЯТОР В СЕТИ',
  'The Algorithm has signal. Get to the ship.': 'У Алгоритма есть сигнал. Идите к кораблю.', SANDSTORM: 'ПЕСЧАНАЯ БУРЯ', 'The crawler is buried. Back to the ship.': 'Ретранслятор погребён. Назад на корабль.', 'THE ADS ARE BACK': 'РЕКЛАМА ВЕРНУЛАСЬ',
  'Expedition pay: ▮{n}': 'Плата за экспедицию: ▮{n}', 'Cell swapped. Fresh charge.': 'Ячейка заменена. Свежий заряд.', 'You need to carry the power cell.': 'Нужно нести энергоячейку.',
  'The cell is too weak. Swap it at the generator.': 'Ячейка слишком слаба. Смените её на генераторе.', 'The generator is still recharging.': 'Генератор ещё перезаряжается.', 'Nothing happens.': 'Ничего не происходит.',
};
