// gear11_text (wave 11): TR + RU for the five new gadgets (English strings are the keys; see core/i18n.js).
import { addTranslations } from '../core/i18n.js';
import { ITEMS11 } from './gear11_core.js';

const I = ITEMS11;
const TR = {
  'Decoy Speaker': 'Tuzak Hoparlör', 'Door Jammer': 'Kapı Sıkıştırıcı', 'Scout Drone': 'Keşif Dronu', 'Glow Trail Spray': 'Parlak İz Spreyi', 'Zipline Kit': 'Zipline Kiti',
  'Plays your last recorded voice clip (or a fake "Hey, over here!") every 2.4 s for 12 s. Sound-hunting creatures rush to it.': 'Kaydettiği son ses klibini (yoksa sahte bir "Hey, buraya!") 12 sn boyunca 2,4 sn\'de bir çalar. Sese avlanan yaratıklar ona koşar.',
  [I.doorjammer.tip]: 'Sol tık: kapıya yapışır, 40 sn kapalı kalır. Yaratıklar da ekip de açamaz. Bitmeden önce hızlı bipler, sonra çığlık atar: gürültü yaratıkları çeker.',
  [I.scoutdrone.tip]: 'Sol tık: 30 sn uçur (pil). Bedenin yerinde durur ve vurulabilir. Sol tık tekrar: görüşteki eşyaları ve yaratıkları tüm ekip için işaretler. E: geri çağır. Gemi şarjında doldur.',
  [I.glowspray.tip]: 'Sol tık: 2 dakika boyunca ayak izlerin parlayan oklar bırakır. Herkes görür, geldiğin yolu gösterir, 3 dakika sonra söner.',
  [I.ziplinekit.tip]: 'Sol tık: 18 m içindeki duvara veya tavana nişan al (açık görüş): bir halat kurulur. İki uçtan E ile kay. Sefer başına tek hat. Eğil + E geri toplar. Ağır eşya kaymayı yavaşlatır.',
  'Hey, over here!': 'Hey, buraya!',
  'That door cannot be jammed.': 'Bu kapı sıkıştırılamaz.', 'Your trail is already glowing.': 'İzin zaten parlıyor.',
  'A zipline is already rigged on this landing. Retract it first (Crouch + E).': 'Bu inişte zaten bir zipline kurulu. Önce onu topla (Eğil + E).',
  'Aim at a wall or the ceiling, not the floor.': 'Zemine değil, duvara ya da tavana nişan al.', 'Too far. The anchor must be within 18 m.': 'Çok uzak. Çapa 18 m içinde olmalı.', 'No clear line to that spot.': 'O noktaya açık bir hat yok.',
  'Aim at a plain door within 3 m.': 'Sıradan bir kapıya (3 m içinde) nişan al.', 'Door jammed for 40 s.': 'Kapı 40 sn sıkıştırıldı.',
  'Glow trail on for 2 minutes.': 'Parlak iz 2 dakika açık.', '{name} is marking a glow trail.': '{name} parlak iz bırakıyor.',
  'Sliding. Space lets go.': 'Kayıyorsun. Boşluk tuşu bırakır.', 'Nothing to anchor to. Aim at a wall or the ceiling within 18 m.': 'Bağlanacak yer yok. 18 m içindeki duvara ya da tavana nişan al.',
  'Too close. Pick a spot at least 3 m away.': 'Çok yakın. En az 3 m uzakta bir nokta seç.',
  'Drone battery low. Charge it at the ship charger.': 'Dron pili düşük. Gemi şarj cihazında doldur.', 'Drone online. Your body is exposed - watch it.': 'Dron çevrimiçi. Bedenin açıkta - dikkat et.',
  'Your body was hit. Drone link cut!': 'Bedenin vuruldu. Dron bağlantısı koptu!', 'Drone destroyed. Its battery is fried.': 'Dron yok edildi. Pili yandı.', 'Drone battery empty. Recalled.': 'Dron pili bitti. Geri çağrıldı.',
  'Scan: nothing in sight.': 'Tarama: görüşte hiçbir şey yok.', "{name}'s drone scan: {n} marked.": '{name} dron taraması: {n} işaretlendi.', 'Scan marked {n} for the crew.': 'Tarama ekip için {n} hedef işaretledi.',
  'DRONE CAM': 'DRON KAM', 'BATTERY {s} s': 'PİL {s} sn', 'LINK {q}%': 'BAĞ {q}%', 'BODY {m} m': 'BEDEN {m} m', 'SCAN {s} s': 'TARAMA {s} sn', 'SCAN READY': 'TARAMA HAZIR',
  'WASD fly / Space up / C down': 'WASD uç / Boşluk yukarı / C aşağı', 'LMB scan / E recall': 'Sol tık tara / E geri çağır', 'HOSTILE NEAR YOUR BODY': 'BEDENİNİN YAKININDA DÜŞMAN',
  'Jammed shut': 'Sıkıştırıldı', 'Opens in {s} s': '{s} sn sonra açılır', 'Retract zipline [Crouch + E]': 'Zipline\'ı topla [Eğil + E]', 'Ride zipline [E]': 'Zipline\'da kay [E]', 'Crouch + E retracts it': 'Eğil + E toplar',
  'GLOW TRAIL {t}': 'PARLAK İZ {t}',
  '<b>[LMB]</b> jam the door in front of you (40 s)': '<b>[Sol tık]</b> önündeki kapıyı sıkıştır (40 sn)',
  '<b>[LMB]</b> launch the drone - your body stays put': '<b>[Sol tık]</b> dronu uçur - bedenin yerinde kalır',
  '<b>[LMB]</b> spray a glow trail (2 min)': '<b>[Sol tık]</b> parlak iz sık (2 dk)',
  '<b>[LMB]</b> aim at a wall / ceiling (18 m) to rig a zipline': '<b>[Sol tık]</b> zipline kurmak için duvara / tavana (18 m) nişan al',
  'hold <b>[LMB]</b> to aim, release to throw - it plays your voice': '<b>[Sol tık]</b> basılı tut: nişan, bırak: fırlat - senin sesini çalar',
  '<b>[Space]</b> let go': '<b>[Boşluk]</b> bırak',
};
const RU = {
  'Decoy Speaker': 'Ложный динамик', 'Door Jammer': 'Заклинивающая скоба', 'Scout Drone': 'Разведдрон', 'Glow Trail Spray': 'Спрей светящегося следа', 'Zipline Kit': 'Набор зиплайна',
  'Plays your last recorded voice clip (or a fake "Hey, over here!") every 2.4 s for 12 s. Sound-hunting creatures rush to it.': 'Каждые 2,4 с в течение 12 с проигрывает твою последнюю записанную фразу (или поддельное «Эй, я здесь!»). Существа, идущие на звук, бегут к нему.',
  [I.doorjammer.tip]: 'ЛКМ: прилипает к двери, она заперта 40 с. Ни существа, ни команда не откроют. Перед концом пищит чаще, потом орёт: шум привлекает существ.',
  [I.scoutdrone.tip]: 'ЛКМ: лети до 30 с (батарея). Тело стоит на месте и уязвимо. ЛКМ снова: метит предметы и существ в поле зрения для всей команды. E: вернуть. Заряжай на корабельной зарядке.',
  [I.glowspray.tip]: 'ЛКМ: 2 минуты твои шаги оставляют светящиеся стрелки. Их видят все, они указывают обратный путь и гаснут через 3 минуты.',
  [I.ziplinekit.tip]: 'ЛКМ по стене или потолку в 18 м (прямая видимость): натягивается трос. E на любом конце, чтобы скользить. Одна линия на посадку. Присесть + E свернёт её. Тяжёлый груз замедляет.',
  'Hey, over here!': 'Эй, я здесь!',
  'That door cannot be jammed.': 'Эту дверь нельзя заклинить.', 'Your trail is already glowing.': 'Твой след уже светится.',
  'A zipline is already rigged on this landing. Retract it first (Crouch + E).': 'На этой посадке уже натянут зиплайн. Сначала сверни его (Присесть + E).',
  'Aim at a wall or the ceiling, not the floor.': 'Целься в стену или потолок, а не в пол.', 'Too far. The anchor must be within 18 m.': 'Слишком далеко. Якорь должен быть в 18 м.', 'No clear line to that spot.': 'Нет прямой линии к этой точке.',
  'Aim at a plain door within 3 m.': 'Нацелься на обычную дверь в пределах 3 м.', 'Door jammed for 40 s.': 'Дверь заклинена на 40 с.',
  'Glow trail on for 2 minutes.': 'Светящийся след включён на 2 минуты.', '{name} is marking a glow trail.': '{name} оставляет светящийся след.',
  'Sliding. Space lets go.': 'Скольжение. Пробел отпускает.', 'Nothing to anchor to. Aim at a wall or the ceiling within 18 m.': 'Не за что зацепиться. Целься в стену или потолок в 18 м.',
  'Too close. Pick a spot at least 3 m away.': 'Слишком близко. Выбери точку не ближе 3 м.',
  'Drone battery low. Charge it at the ship charger.': 'Батарея дрона разряжена. Зарядь на корабельной зарядке.', 'Drone online. Your body is exposed - watch it.': 'Дрон в сети. Твоё тело беззащитно - следи за ним.',
  'Your body was hit. Drone link cut!': 'По твоему телу попали. Связь с дроном оборвана!', 'Drone destroyed. Its battery is fried.': 'Дрон разбит. Батарея сгорела.', 'Drone battery empty. Recalled.': 'Батарея дрона пуста. Возврат.',
  'Scan: nothing in sight.': 'Скан: в поле зрения ничего нет.', "{name}'s drone scan: {n} marked.": 'Скан дрона ({name}): отмечено {n}.', 'Scan marked {n} for the crew.': 'Скан отметил для команды: {n}.',
  'DRONE CAM': 'КАМЕРА ДРОНА', 'BATTERY {s} s': 'БАТАРЕЯ {s} с', 'LINK {q}%': 'СВЯЗЬ {q}%', 'BODY {m} m': 'ТЕЛО {m} м', 'SCAN {s} s': 'СКАН {s} с', 'SCAN READY': 'СКАН ГОТОВ',
  'WASD fly / Space up / C down': 'WASD полёт / Пробел вверх / C вниз', 'LMB scan / E recall': 'ЛКМ скан / E вернуть', 'HOSTILE NEAR YOUR BODY': 'ВРАГ РЯДОМ С ТЕЛОМ',
  'Jammed shut': 'Заклинена', 'Opens in {s} s': 'Откроется через {s} с', 'Retract zipline [Crouch + E]': 'Свернуть зиплайн [Присесть + E]', 'Ride zipline [E]': 'Скользить по зиплайну [E]', 'Crouch + E retracts it': 'Присесть + E сворачивает',
  'GLOW TRAIL {t}': 'СВЕТЯЩИЙСЯ СЛЕД {t}',
  '<b>[LMB]</b> jam the door in front of you (40 s)': '<b>[ЛКМ]</b> заклинить дверь перед собой (40 с)',
  '<b>[LMB]</b> launch the drone - your body stays put': '<b>[ЛКМ]</b> запустить дрона - тело остаётся на месте',
  '<b>[LMB]</b> spray a glow trail (2 min)': '<b>[ЛКМ]</b> оставить светящийся след (2 мин)',
  '<b>[LMB]</b> aim at a wall / ceiling (18 m) to rig a zipline': '<b>[ЛКМ]</b> целься в стену / потолок (18 м), чтобы натянуть зиплайн',
  'hold <b>[LMB]</b> to aim, release to throw - it plays your voice': 'удерживай <b>[ЛКМ]</b>, чтобы целиться, отпусти - бросок; он играет твой голос',
  '<b>[Space]</b> let go': '<b>[Пробел]</b> отпустить',
};
addTranslations(TR, 'tr'); addTranslations(RU, 'ru');
