// GUIDE data (wave 4, module 'guide'): the registry of discoverable features, the Algorithm's tip lines, the first-time tutorial
// steps and every UI string. PURE DATA (no imports): every text is an [en, tr, ru] triple, picked with pick(arr, lang).
// Tips are written in the voice of The Algorithm (creepy-corporate, dry): short, never longer than ~120 characters, and always say
// HOW (a key or a terminal command). Contexts (`when`) are flag names computed by guide.js from the live game (see CTX_FLAGS).
//
// Feature fields: id, cat, name[3], how[3] (multi-line how-to for GUIDE <id>), tips[[3]...] (Algorithm one-liners),
//   cmds  terminal words that mark the feature used         keys  KeyboardEvent.code values that mark it used
//   panel panel id from classifyPanel()                     evt   mods-bus event / internal event id that marks it used
//   when  [ctx flags] ALL must be true for the tip          prio  base score (1..10)
//   needs module name on `game` (or 'cmd:<word>' = a registered terminal command) that must exist; an array = any of them             minLevel  hide the tip below this profile level
export const LANGS3 = ['en', 'tr', 'ru'];
export const pick = (arr, lang = 'en') => {
  if (!arr) return '';
  if (typeof arr === 'string') return arr;
  const i = lang === 'tr' ? 1 : lang === 'ru' ? 2 : 0;
  return arr[i] !== undefined && arr[i] !== null && arr[i] !== '' ? arr[i] : arr[0];
};
export const fmt = (s, v = {}) => String(s).replace(/\{(\w+)\}/g, (m, k) => (v[k] !== undefined && v[k] !== null ? String(v[k]) : m));

export const CATS = {
  basics: ['BASICS', 'TEMEL', 'ОСНОВЫ'],
  ship: ['SHIP & TERMINAL', 'GEMİ & TERMİNAL', 'КОРАБЛЬ И ТЕРМИНАЛ'],
  gear: ['GEAR & PROGRESSION', 'EKİPMAN & GELİŞİM', 'СНАРЯЖЕНИЕ И ПРОГРЕСС'],
  magic: ['MAGIC & COMBAT', 'BÜYÜ & SAVAŞ', 'МАГИЯ И БОЙ'],
  crew: ['CREW & SOCIAL', 'EKİP & SOSYAL', 'КОМАНДА'],
  world: ['WORLD & ENDGAME', 'DÜNYA & OYUN SONU', 'МИР И ЭНДГЕЙМ'],
  meta: ['LORE & META', 'HİKAYE & META', 'ЛОР И МЕТА'],
};

// context flags the tips can require (computed in guide.js computeCtx)
export const CTX_FLAGS = ['orbit', 'moon', 'company', 'indoor', 'inship', 'rich', 'wealthy', 'lowhp', 'hurt', 'skillpts', 'skillbook', 'norole', 'coins', 'invfull',
  'hasgrenade', 'hasfood', 'lvl3', 'day2', 'quotaMet', 'seencreature', 'crew', 'night', 'lore_found', 'noflash', 'daily'];

const F = (id, cat, o, name, how, tips) => ({ id, cat, cmds: [], keys: [], prio: 5, when: [], ...o, name, how, tips });

export const FEATURES = [
  // ------------------------------------------------------------------ basics
  F('inventory', 'basics', { cmds: ['inventory'], panel: 'inventory', prio: 7, key: 'I' },
    ['Inventory', 'Envanter', 'Инвентарь'],
    ['Press I: hotbar, equipped gear and a backpack. Drag items around, hover for stats and tier. Bags add more room.',
      'I tuşu: hızlı erişim, giyilen ekipman ve sırt çantası. Eşyaları sürükle, üstüne gelince özellikleri görürsün. Çantalar yer ekler.',
      'Нажми I: хотбар, экипировка и рюкзак. Перетаскивай предметы, наведи курсор для характеристик. Сумки добавляют место.'],
    [['Your pockets are a mess. Press I: there is a whole backpack in there.', 'Ceplerin darmadağın. I tuşuna bas: içinde koca bir sırt çantası var.', 'В карманах бардак. Нажми I: там целый рюкзак.'],
      ['Inventory is at I. Gear, bags, tiers. I would call it "asset management".', 'Envanter I tuşunda. Ekipman, çanta, seviye. Ben ona "varlık yönetimi" derim.', 'Инвентарь на I. Снаряжение, сумки, ранги. Я называю это «управлением активами».']]),
  F('inventory_full', 'basics', { panel: 'inventory', when: ['invfull'], prio: 8, key: 'I', hidden: true, alias: 'inventory' },
    ['Inventory', 'Envanter', 'Инвентарь'], ['', '', ''],
    [['All four hands full. Press I: bags and equipment slots exist, you know.', 'Dört el de dolu. I tuşuna bas: çanta ve ekipman yuvaları da var, biliyorsun.', 'Все четыре руки заняты. Нажми I: там есть сумки и слоты экипировки.']]),
  F('flashlight', 'basics', { evt: 'flash', when: ['indoor', 'noflash'], prio: 8, key: 'F' },
    ['Flashlight', 'El feneri', 'Фонарик'],
    ['A flashlight is sold at the terminal (STORE, about 15 credits). Hold it, then press F to toggle it. Batteries drain.',
      'El feneri terminalde satılır (STORE, yaklaşık 15 kredi). Elinde tut, F ile aç/kapat. Pil biter.',
      'Фонарик продаётся на терминале (STORE, около 15 кредитов). Держи его в руках и жми F. Батарея разряжается.'],
    [['It is dark in there and you own no light. STORE sells flashlights. F switches them on.', 'İçerisi karanlık ve elinde ışık yok. STORE fener satıyor. F ile açılır.', 'Там темно, а света у тебя нет. В STORE продают фонари. F включает.'],
      ['Darkness is free. Light costs ▮15 at STORE. Then press F.', 'Karanlık bedava. Işık STORE\'da ▮15. Sonra F.', 'Темнота бесплатна. Свет стоит ▮15 в STORE. Потом F.']]),
  F('scan', 'basics', { evt: 'scan', when: ['moon'], prio: 8, key: 'RMB' },
    ['Scan', 'Tarama', 'Сканирование'],
    ['Right mouse button scans: scrap and creatures show up with names and values. Scanning a creature adds it to the BESTIARY.',
      'Sağ tık tarar: hurdalar ve yaratıklar isim ve değerleriyle görünür. Yaratığı taramak BESTIARY\'ye ekler.',
      'ПКМ сканирует: хлам и существа видны с названиями и ценой. Скан существа добавляет его в BESTIARY.'],
    [['Right click scans. Scrap glows, monsters get names. Knowledge is survival.', 'Sağ tık tarar. Hurdalar parlar, canavarların adı çıkar. Bilgi, hayatta kalmaktır.', 'ПКМ сканирует. Хлам светится, у монстров появляются имена. Знание — это выживание.'],
      ['Have you tried scanning? Right click. It is free. Ignorance is not.', 'Taramayı denedin mi? Sağ tık. Ücretsiz. Cehalet değil.', 'Пробовал сканировать? ПКМ. Это бесплатно. Невежество — нет.']]),
  F('ping', 'basics', { keys: ['KeyP'], evt: 'ping', when: ['moon', 'crew'], prio: 4, key: 'P / MMB' },
    ['Ping', 'İşaret', 'Метка'],
    ['Press P or the middle mouse button to ping what you look at. Your crew sees the marker, so nobody has to type "over there".',
      'P veya orta fare tuşu baktığın yeri işaretler. Ekip işareti görür, kimse "şuraya" yazmak zorunda kalmaz.',
      'P или колёсико мыши ставит метку туда, куда смотришь. Команда видит её, и не надо писать «вон там».'],
    [['Middle mouse or P pings a spot for the crew. Communication: I would not, but it works.', 'Orta tuş veya P ekibe bir yeri işaretler. İletişim: ben yapmazdım ama işe yarıyor.', 'Колёсико или P ставит метку для команды. Общение: я бы не стал, но работает.']]),
  F('emotes', 'crew', { keys: ['KeyZ', 'KeyX', 'KeyB'], evt: 'emote', when: ['crew'], prio: 3, key: 'Z / X / hold B' },
    ['Emotes', 'Emote\'lar', 'Эмоции'],
    ['Z and X play your two quick emotes; hold B for the full emote wheel. Camera swings behind you while you dance.',
      'Z ve X iki hızlı emote\'u oynatır; B\'ye basılı tut, tüm emote çarkı açılır. Dans ederken kamera arkana geçer.',
      'Z и X — быстрые эмоции; удерживай B для колеса эмоций. Во время танца камера уходит за спину.'],
    [['Z and X play emotes. Hold B for the wheel. Fun is mandatory.', 'Z ve X emote oynatır. B\'ye basılı tut, çark açılır. Eğlence zorunludur.', 'Z и X — эмоции. Удерживай B для колеса. Веселье обязательно.']]),
  F('voice', 'crew', { keys: ['KeyV'], evt: 'voice', when: ['crew'], prio: 4, key: 'V' },
    ['Voice chat', 'Sesli sohbet', 'Голосовой чат'],
    ['Hold V (push-to-talk) to speak. Proximity chat: crew members near you hear you in 3D, walls muffle. Creatures hear it too.',
      'V\'ye basılı tut (bas-konuş). Yakındaki ekip seni 3D duyar, duvarlar sesi boğar. Yaratıklar da duyar.',
      'Удерживай V (рация). Голос слышен вблизи в 3D, стены глушат. Существа тоже слышат.'],
    [['Hold V to talk. Everything within earshot hears you. Everything.', 'V\'ye basılı tut ve konuş. Kulak menzilindeki her şey seni duyar. Her şey.', 'Удерживай V, чтобы говорить. Всё в пределах слышимости тебя слышит. Всё.']]),
  F('chat', 'crew', { keys: ['Enter', 'KeyT'], evt: 'chat', when: ['crew'], prio: 2, key: 'Enter / T' },
    ['Text chat', 'Yazılı sohbet', 'Текстовый чат'],
    ['Press Enter (or T) to type to the crew. Some spell words work when typed, and chat commands start with a slash.',
      'Enter (veya T) ile ekibe yaz. Bazı büyü sözcükleri yazınca da çalışır; sohbet komutları / ile başlar.',
      'Enter (или T) — написать команде. Слова заклинаний работают и в чате, команды чата начинаются с /.'],
    [['Enter opens chat. Typing is quieter than speaking, and creatures do not read.', 'Enter sohbeti açar. Yazmak konuşmaktan sessizdir; yaratıklar okuma bilmez.', 'Enter открывает чат. Печатать тише, чем говорить, а существа не умеют читать.']]),
  F('record', 'meta', { panel: 'record', when: ['day2'], prio: 4, key: 'J' },
    ['Service Record', 'Hizmet Sicili', 'Личное дело'],
    ['Press J for your Service Record: level, rank, achievements, kills, and REBIRTH once you are high enough.',
      'J tuşu Hizmet Sicilini açar: seviye, rütbe, başarımlar, öldürmeler ve yeterince yükselince REBIRTH.',
      'Нажми J — личное дело: уровень, звание, достижения, убийства и REBIRTH на высоком уровне.'],
    [['Press J. Your Service Record lists everything you did. I remember all of it anyway.', 'J\'ye bas. Hizmet Sicilin yaptığın her şeyi listeler. Ben zaten hepsini hatırlıyorum.', 'Нажми J. Личное дело хранит всё, что ты сделал. Я и так всё помню.']]),

  // ------------------------------------------------------------------ ship & terminal
  F('store', 'ship', { cmds: ['store', 'buy', 'shop', 'deals'], panel: 'shop', when: ['orbit', 'rich'], prio: 8, key: 'terminal' },
    ['Company Store', 'Şirket Mağazası', 'Магазин Компании'],
    ['At the ship terminal type STORE for the shop screen (STORE LIST = plain text) or BUY <item> [n]. Deliveries land in the ship. DEALS shows today\'s discounts.',
      'Gemi terminalinde STORE mağaza ekranını açar (STORE LIST = düz yazı), BUY <eşya> [n] doğrudan alır. Teslimat gemiye düşer. DEALS bugünkü indirimleri gösterir.',
      'На терминале корабля STORE открывает магазин (STORE LIST — текстом), BUY <предмет> [n] покупает сразу. Заказ падает на корабль. DEALS — скидки дня.'],
    [['Your wallet is getting heavy. Have you tried STORE? Spending is engagement.', 'Cüzdanın ağırlaştı. STORE\'u denedin mi? Harcamak da bir katılımdır.', 'Кошелёк тяжелеет. Пробовал STORE? Траты — это вовлечённость.'],
      ['Credits do nothing in a wallet. STORE at the terminal: lights, medkits, a shovel.', 'Cüzdandaki kredi bir işe yaramaz. Terminalde STORE: fener, ilk yardım, kürek.', 'Кредиты в кошельке бесполезны. STORE на терминале: фонари, аптечки, лопата.']]),
  F('store_first', 'ship', { cmds: ['store', 'buy', 'shop', 'deals'], panel: 'shop', when: ['orbit'], prio: 6, key: 'terminal', hidden: true, alias: 'store' },
    ['Company Store', 'Şirket Mağazası', 'Магазин Компании'], ['', '', ''],
    [['The terminal sells things. STORE. You are welcome to be equipped, in a Company-approved way.', 'Terminal bir şeyler satıyor. STORE. Donanımlı olman Şirket onaylı bir şey.', 'Терминал что-то продаёт. STORE. Тебе разрешено быть экипированным — по-корпоративному.']]),
  F('moons', 'ship', { cmds: ['moons', 'moon', 'route', 'r', 'sector', 'map', 'info'], when: ['orbit', 'day2'], prio: 5, key: 'terminal' },
    ['Moons & routing', 'Aylar & rota', 'Луны и маршрут'],
    ['MOONS lists every server moon with weather and cost, INFO <moon> shows risk and interior, SECTOR draws the map of the uncharted servers, ROUTE <moon> sets the autopilot (CONFIRM). Then pull the lever.',
      'MOONS tüm ay-sunucuları hava ve fiyatla listeler, INFO <ay> risk ve iç mekânı gösterir, SECTOR keşfedilmemiş sunucuların haritasını çizer, ROUTE <ay> otopilotu ayarlar (CONFIRM). Sonra kolu çek.',
      'MOONS — список лун с погодой и ценой, INFO <луна> — риск и интерьер, SECTOR — карта неисследованных серверов, ROUTE <луна> задаёт автопилот (CONFIRM). Затем дёрни рычаг.'],
    [['Other servers exist. MOONS lists them, ROUTE flies you there. Riskier moons pay better.', 'Başka sunucular da var. MOONS listeler, ROUTE oraya uçurur. Riskli aylar daha çok öder.', 'Есть и другие серверы. MOONS покажет, ROUTE отвезёт. Опасные луны платят лучше.'],
      ['SECTOR draws a map of the uncharted servers. Try it before choosing your own doom.', 'SECTOR keşfedilmemiş sunucuların haritasını çizer. Kendi sonunu seçmeden önce bak.', 'SECTOR рисует карту неисследованных серверов. Глянь, прежде чем выбирать свою гибель.']]),
  F('quota', 'ship', { cmds: ['quota'], when: ['orbit', 'day2'], prio: 3, key: 'terminal' },
    ['Quota status', 'Kota durumu', 'Состояние квоты'],
    ['QUOTA shows sold value vs. the profit quota, days left, credits and the current Company buying rate (it changes daily).',
      'QUOTA satılan değeri kotayla, kalan günü, kredini ve Şirketin güncel alım oranını (günlük değişir) gösterir.',
      'QUOTA показывает продано / квоту, оставшиеся дни, кредиты и текущий курс закупки Компании (меняется каждый день).'],
    [['Type QUOTA to see how deep in debt you are. It is motivating.', 'Ne kadar borçlu olduğunu görmek için QUOTA yaz. Motive edici.', 'Введи QUOTA — увидишь, насколько ты в долгах. Мотивирует.']]),
  F('bestiary', 'ship', { cmds: ['bestiary', 'b'], when: ['orbit', 'seencreature'], prio: 6, key: 'terminal' },
    ['Bestiary', 'Bestiary', 'Бестиарий'],
    ['BESTIARY lists every creature you scanned; BESTIARY <name> shows its rule, danger and your kills. Every creature has a weakness.',
      'BESTIARY taradığın tüm yaratıkları listeler; BESTIARY <isim> kuralını, tehlikesini ve öldürmelerini gösterir. Her yaratığın bir zayıflığı var.',
      'BESTIARY — все просканированные существа; BESTIARY <имя> — правило, опасность и убийства. У каждого есть слабость.'],
    [['You have seen things. BESTIARY says what they are. Every creature has a rule.', 'Bir şeyler gördün. BESTIARY ne olduklarını söyler. Her yaratığın bir kuralı var.', 'Ты кое-что видел. BESTIARY скажет, что это было. У каждого существа есть правило.']]),
  F('codes', 'ship', { cmds: ['codes'], when: ['moon'], prio: 3, key: 'terminal' },
    ['Secure codes', 'Güvenli kodlar', 'Коды доступа'],
    ['CODES lists secure door / turret / mine codes on this moon. Typing a code (e.g. A3) at the terminal opens the door or disables the turret for 8 seconds.',
      'CODES bu aydaki güvenli kapı / taret / mayın kodlarını listeler. Terminale kod yazmak (ör. A3) kapıyı açar ya da bir tareti 8 saniye susturur.',
      'CODES — список кодов дверей, турелей и мин. Код (например A3), введённый на терминале, открывает дверь или отключает турель на 8 секунд.'],
    [['A crewmate at the terminal can type a code (see CODES) to open doors and silence turrets. Teamwork!', 'Terminaldeki bir ekip arkadaşı kod yazarak (CODES) kapı açıp taretleri susturabilir. Takım işi!', 'Напарник на терминале может вводить коды (см. CODES), открывая двери и отключая турели. Командная работа!']]),
  F('crew_cmd', 'ship', { cmds: ['crew', 'switch'], when: ['orbit', 'crew'], prio: 2, key: 'terminal' },
    ['Crew & radar', 'Ekip & radar', 'Команда и радар'],
    ['CREW lists everyone with level and HP. SWITCH [name] changes whom the ship radar tracks.',
      'CREW herkesi seviye ve canla listeler. SWITCH [isim] gemi radarının kimi izlediğini değiştirir.',
      'CREW — все с уровнем и HP. SWITCH [имя] переключает цель радара корабля.'],
    [['SWITCH at the terminal changes who the ship radar follows. Stay near the person who screams.', 'Terminalde SWITCH radarın kimi izlediğini değiştirir. Çığlık atanın yakınında kal.', 'SWITCH на терминале меняет цель радара. Держись рядом с тем, кто кричит.']]),
  F('crafting', 'gear', { cmds: ['craft', 'recipes'], panel: 'crafting', when: ['orbit', 'day2'], prio: 6, key: 'E at workbench' },
    ['Workbench & crafting', 'Tezgâh & üretim', 'Верстак и крафт'],
    ['Use the WORKBENCH in the ship [E]: craft gear from scrap, dismantle junk into parts, analyze unknown items. CRAFT / RECIPES list every recipe.',
      'Gemideki TEZGÂHI kullan [E]: hurdadan ekipman üret, işe yaramazları parçala, bilinmeyen eşyaları analiz et. CRAFT / RECIPES tüm tarifleri listeler.',
      'Верстак на корабле [E]: создавай снаряжение из хлама, разбирай мусор на детали, анализируй неизвестные предметы. CRAFT / RECIPES — все рецепты.'],
    [['The ship has a WORKBENCH. Craft, dismantle, analyze. Waste is a choice. CRAFT lists recipes.', 'Gemide bir TEZGÂH var. Üret, parçala, analiz et. İsraf bir tercih. CRAFT tarifleri listeler.', 'На корабле есть ВЕРСТАК. Крафт, разбор, анализ. Расточительство — выбор. CRAFT покажет рецепты.']]),
  F('shipyard', 'ship', { cmds: ['shipyard'], panel: 'shipyard', when: ['orbit', 'wealthy'], prio: 5, key: 'terminal' },
    ['Shipyard', 'Tersane', 'Верфь'],
    ['SHIPYARD opens the console: bolt on rooms (Cargo Bay, Med Bay, Garage...), paint the hull, rename the ship. Modules cost credits or ship parts and make routes a little pricier.',
      'SHIPYARD konsolu açar: oda ekle (Kargo, Revir, Garaj...), gövdeyi boya, gemiyi yeniden adlandır. Modüller kredi veya gemi parçasıyla alınır ve rotayı biraz pahalılaştırır.',
      'SHIPYARD открывает консоль: пристраивай модули (склад, медотсек, гараж...), крась корпус, переименуй корабль. Модули стоят кредиты или детали и слегка удорожают маршруты.'],
    [['Your ship is cosmetically offensive. SHIPYARD: rooms, paint, a name plate.', 'Geminin görüntüsü rahatsız edici. SHIPYARD: odalar, boya, isim tabelası.', 'Твой корабль выглядит оскорбительно. SHIPYARD: комнаты, краска, табличка с именем.']]),
  F('van', 'ship', { cmds: ['van'], when: ['orbit', 'wealthy'], prio: 3, key: 'terminal' },
    ['Uplink Van', 'Uplink Van', 'Фургон Uplink'],
    ['VAN shows the vehicle status, VAN BUY then VAN CONFIRM orders the 4-seat Uplink Van with a cargo bed. It docks automatically at takeoff.',
      'VAN araç durumunu gösterir, VAN BUY ve VAN CONFIRM 4 kişilik, kargo yataklı Uplink Van\'ı sipariş eder. Kalkışta otomatik park eder.',
      'VAN — состояние машины, VAN BUY и VAN CONFIRM заказывают 4-местный фургон Uplink с кузовом. При взлёте паркуется сам.'],
    [['Walking is for employees without a van. VAN BUY. Seats four, ramming included.', 'Yürümek arabasız çalışanlar içindir. VAN BUY. Dört kişilik, çarpma dahil.', 'Ходить пешком — удел сотрудников без фургона. VAN BUY. Четыре места, таран в комплекте.']]),
  F('wardrobe', 'gear', { panel: 'wardrobe', when: ['inship', 'orbit'], prio: 3, key: 'E at mirror' },
    ['Wardrobe', 'Gardırop', 'Гардероб'],
    ['Interact [E] with the mirror in the ship to change suit, hat, face and back item. Cosmetics come from the store, chests and achievements.',
      'Gemideki aynayla etkileş [E]: kıyafet, şapka, yüz ve sırt eşyası değiştir. Kozmetikler mağazadan, sandıklardan ve başarımlardan gelir.',
      'Взаимодействуй [E] с зеркалом на корабле: костюм, шапка, лицо, аксессуар на спину. Косметика — из магазина, сундуков и достижений.'],
    [['Interact with the mirror in the ship. Wardrobe. Your appearance is also a metric.', 'Gemideki aynayla etkileş. Gardırop. Görünüşün de bir metrik.', 'Подойди к зеркалу на корабле. Гардероб. Внешность — тоже метрика.']]),
  F('arcade', 'meta', { evt: 'arcade', when: ['inship', 'orbit'], prio: 2, key: 'E at cabinet' },
    ['Arcade', 'Atari salonu', 'Аркада'],
    ['The FLAPPY PHISH cabinet in the ship [E] pays a little XP for good scores. Procrastination, but measurable.',
      'Gemideki FLAPPY PHISH makinesi [E] iyi skorlara biraz XP verir. Oyalanmak, ama ölçülebilir.',
      'Автомат FLAPPY PHISH на корабле [E] платит немного XP за хороший счёт. Прокрастинация, но измеримая.'],
    [['The arcade cabinet on the ship pays XP. Procrastination is encouraged.', 'Gemideki atari makinesi XP verir. Oyalanmak teşvik edilir.', 'Аркадный автомат на корабле платит XP. Прокрастинация поощряется.']]),
  F('music', 'crew', { evt: 'music', when: ['orbit', 'crew'], prio: 2, key: 'LMB with instrument' },
    ['Instruments', 'Enstrümanlar', 'Инструменты'],
    ['The store sells playable instruments (guitars, keytar, drum pad). Hold one and use LMB to enter play mode; the crew can jam together.',
      'Mağaza çalınabilir enstrümanlar satar (gitar, keytar, davul pedi). Elinde tut, SOL TIK ile çalma moduna gir; ekip birlikte çalabilir.',
      'В магазине продают инструменты (гитары, кейтар, драм-пад). Возьми в руки и нажми ЛКМ для режима игры; команда может играть вместе.'],
    [['The store sells instruments. Hold one, click, play. Jam sessions are loud, and loud is content.', 'Mağaza enstrüman satıyor. Eline al, tıkla, çal. Caz seansları gürültülüdür, gürültü de içeriktir.', 'В магазине есть инструменты. Возьми, кликни, играй. Джемы шумные, а шум — это контент.']]),

  // ------------------------------------------------------------------ gear & progression
  F('skilltree', 'gear', { cmds: ['tree', 'respec'], panel: 'tree', when: ['skillpts'], prio: 9, key: 'K' },
    ['Passive tree', 'Pasif ağaç', 'Древо пассивок'],
    ['Press K for the passive tree: every level gives a point. Spend them on nodes (health, luck, stamina, loot...) and pick keystones. TREE shows a summary at the terminal, RESPEC refunds it for Clout.',
      'K tuşu pasif ağacı açar: her seviye bir puan verir. Puanları düğümlere (can, şans, dayanıklılık, ganimet...) ve keystone\'lara harca. TREE terminalde özet gösterir, RESPEC Clout karşılığı sıfırlar.',
      'Нажми K — древо пассивок: каждый уровень даёт очко. Трать на узлы (здоровье, удача, выносливость, добыча...) и ключевые узлы. TREE — сводка на терминале, RESPEC сбрасывает за Clout.'],
    [['Unspent skill points detected. Press K. Idle potential is wasted engagement.', 'Harcanmamış yetenek puanı tespit edildi. K\'ya bas. Boşta potansiyel, boşa giden katılımdır.', 'Обнаружены нераспределённые очки. Нажми K. Простаивающий потенциал — потерянная вовлечённость.'],
      ['Points are sitting in your account. K opens the passive tree. I do not pay interest.', 'Hesabında puanlar duruyor. K pasif ağacı açar. Ben faiz ödemem.', 'На твоём счету лежат очки. K открывает древо. Проценты я не плачу.']]),
  F('skilltree_basic', 'gear', { cmds: ['tree'], panel: 'tree', when: ['lvl3'], prio: 5, key: 'K', hidden: true, alias: 'skilltree' },
    ['Passive tree', 'Pasif ağaç', 'Древо пассивок'], ['', '', ''],
    [['Level {lvl}, and no passive tree yet? Press K. It is not optional. It is merely unenforced.', 'Seviye {lvl} oldun ama pasif ağaca bakmadın mı? K\'ya bas. Zorunlu değil, sadece uygulanmıyor.', 'Уровень {lvl}, а древо ты ещё не открывал? Нажми K. Оно не обязательно, просто не принудительно.']]),
  F('role', 'gear', { cmds: ['role', 'reroll'], evt: 'role', panel: 'roles', when: ['orbit', 'norole'], prio: 7, key: 'terminal / roster' },
    ['Crew role', 'Ekip rolü', 'Роль'],
    ['Pick a role (Medic, Technician, Hauler, Enforcer, Occultist...): permanent bonuses plus a daily kit. Type ROLE at the terminal or use the crew roster on the ship [E]. Switching is only possible in orbit.',
      'Bir rol seç (Medic, Technician, Hauler, Enforcer, Occultist...): kalıcı bonuslar ve günlük kit. Terminalde ROLE yaz ya da gemideki ekip listesini kullan [E]. Rol sadece yörüngede değişir.',
      'Выбери роль (Medic, Technician, Hauler, Enforcer, Occultist...): постоянные бонусы и ежедневный набор. ROLE на терминале или список экипажа на корабле [E]. Менять можно только на орбите.'],
    [['You have no role. Every crew needs a specialist: ROLE at the terminal. Choose wisely, or not.', 'Rolün yok. Her ekibin bir uzmana ihtiyacı var: terminalde ROLE. Akıllıca seç, ya da seçme.', 'У тебя нет роли. Каждой команде нужен специалист: ROLE на терминале. Выбирай с умом. Или нет.']]),
  F('forge', 'gear', { panel: 'forge', when: ['company'], prio: 6, key: 'E at HQ' },
    ['Forge (Monetizer)', 'Ocak (Monetizer)', 'Кузница (Monetizer)'],
    ['At HQ, THE MONETIZER enhances a weapon or armour from +1 to +9 (higher risk each step; a Backup Drive protects it). The Ascension Altar raises item tiers, and the Shard Exchange trades low shards up.',
      'HQ\'da THE MONETIZER silah ve zırhı +1\'den +9\'a güçlendirir (her adımda risk artar; Backup Drive korur). Yükselme Sunağı eşya seviyesini artırır, Parça Takasçısı küçük parçaları büyüğe çevirir.',
      'В штаб-квартире THE MONETIZER усиливает оружие и броню от +1 до +9 (риск растёт; Backup Drive защищает). Алтарь Вознесения повышает тир, Обменник осколков меняет мелкие на крупные.'],
    [['The MONETIZER at HQ enhances gear from +1 to +9. Failure is a feature.', 'HQ\'daki MONETIZER ekipmanı +1\'den +9\'a güçlendirir. Başarısızlık bir özelliktir.', 'MONETIZER в штабе усиливает снаряжение от +1 до +9. Провал — это фича.']]),
  F('blackmarket', 'gear', { evt: 'market', when: ['company', 'coins'], prio: 6, key: 'E at HQ' },
    ['Black Market', 'Karaborsa', 'Чёрный рынок'],
    ['Phish Dayı at HQ sells soulbound weapons, armour, perks and cosmetics for Clout (◈), the currency you earn from XP-worthy deeds. Gear stays with you across runs.',
      'HQ\'daki Phish Dayı, Clout (◈) karşılığı bağlı silah, zırh, perk ve kozmetik satar. Clout, XP kazandıran işlerden gelir. Ekipman seferler arasında sende kalır.',
      'Phish Dayı в штабе продаёт привязанное оружие, броню, перки и косметику за Clout (◈), который дают за заслуги. Снаряжение остаётся у тебя между забегами.'],
    [['Phish Dayı at HQ sells soulbound gear for Clout. You have some ◈ jingling. Go on.', 'HQ\'daki Phish Dayı Clout karşılığı sana bağlı ekipman satar. Cebinde ◈ şıngırdıyor. Hadi.', 'Phish Dayı в штабе продаёт привязанное снаряжение за Clout. У тебя ◈ звенит в кармане. Давай.']]),
  F('contracts', 'world', { cmds: ['contracts', 'accept', 'abandon', 'board'], panel: 'contracts', when: ['orbit', 'day2'], prio: 6, key: 'E at board' },
    ['Contracts', 'Sözleşmeler', 'Контракты'],
    ['The contract board on the ship wall [E] (or CONTRACTS at the terminal) offers 3 daily contracts from the factions. ACCEPT <n> takes one; paid on completion with reputation. SIGN <faction> takes an exclusive one.',
      'Gemi duvarındaki sözleşme panosu [E] (veya terminalde CONTRACTS) fraksiyonlardan 3 günlük sözleşme sunar. ACCEPT <n> birini alır; tamamlanınca itibarla ödenir. SIGN <fraksiyon> özel sözleşme alır.',
      'Доска контрактов на стене корабля [E] (или CONTRACTS на терминале) предлагает 3 ежедневных контракта фракций. ACCEPT <n> берёт один; оплата и репутация по завершении. SIGN <фракция> — эксклюзивный.'],
    [['The contract board on the wall has three daily offers. Reputation pays. Try CONTRACTS.', 'Duvardaki sözleşme panosunda üç günlük teklif var. İtibar para eder. CONTRACTS\'ı dene.', 'На доске контрактов три предложения на день. Репутация окупается. Попробуй CONTRACTS.']]),
  F('factions', 'world', { cmds: ['factions', 'sign', 'tribute'], when: ['lvl3', 'orbit'], prio: 4, key: 'terminal' },
    ['Factions', 'Fraksiyonlar', 'Фракции'],
    ['FACTIONS shows your reputation with the four factions (Feed, Archive, Bureau, Dark Web), their rivals and perks. TRIBUTE <faction> buys +15 rep and ends wars.',
      'FACTIONS dört fraksiyonla (Feed, Archive, Bureau, Dark Web) itibarını, rakiplerini ve perklerini gösterir. TRIBUTE <fraksiyon> +15 itibar alır ve savaşları bitirir.',
      'FACTIONS — репутация у четырёх фракций (Feed, Archive, Bureau, Dark Web), их соперники и перки. TRIBUTE <фракция> даёт +15 репутации и заканчивает войны.'],
    [['Four factions keep score of you. FACTIONS shows how much they like you. It is less than you think.', 'Dört fraksiyon seni takip ediyor. FACTIONS seni ne kadar sevdiklerini gösterir. Sandığından az.', 'Четыре фракции ведут твой счёт. FACTIONS покажет, как сильно они тебя любят. Меньше, чем ты думаешь.']]),
  F('logs', 'meta', { cmds: ['logs', 'log'], evt: 'log', when: ['lore_found'], prio: 5, key: 'terminal' },
    ['Lore logs', 'Hikâye kayıtları', 'Записи лора'],
    ['Lost logs lie in facilities: press E on a glowing tablet. LOGS lists what you recovered, LOG <n> reads it again.',
      'Kayıp kayıtlar tesislerde durur: parlayan tablete E ile bak. LOGS bulduklarını listeler, LOG <n> yeniden okutur.',
      'Потерянные записи лежат в комплексах: нажми E на светящемся планшете. LOGS — найденное, LOG <n> — перечитать.'],
    [['You recovered a log. LOGS at the terminal lists them. Curiosity is tracked, by the way.', 'Bir kayıt buldun. Terminalde LOGS listeler. Bu arada, merak da takip ediliyor.', 'Ты нашёл запись. LOGS на терминале покажет их. Кстати, любопытство отслеживается.']]),
  F('cases', 'meta', { cmds: ['cases', 'case'], when: ['orbit', 'day2'], prio: 3, key: 'terminal' },
    ['Case files', 'Vaka dosyaları', 'Дела'],
    ['After bad days I write a CASE FILE. CASES lists them, CASE <n> reads one: what went wrong, whose fault it was, and my verdict.',
      'Kötü günlerin ardından bir VAKA DOSYASI yazarım. CASES listeler, CASE <n> birini okutur: ne ters gitti, kimin hatasıydı ve kararım.',
      'После плохих дней я пишу ДЕЛО. CASES — список, CASE <n> — прочесть: что пошло не так, чья вина и мой вердикт.'],
    [['Every bad day gets a case file. CASES. Learn from your mistakes, or at least enjoy them.', 'Her kötü güne bir vaka dosyası açılır. CASES. Hatalarından öğren, ya da en azından keyfini çıkar.', 'На каждый плохой день заводится дело. CASES. Учись на ошибках или хотя бы наслаждайся ими.']]),
  F('homeworld', 'world', { cmds: ['home'], panel: 'homeworld', when: ['orbit', 'day2'], prio: 5, key: 'ROUTE HOME / H' },
    ['Homeworld', 'Ev gezegeni', 'Родной мир'],
    ['Your own rock: ROUTE HOME, land, and use the BUILD console (or H). Buildings produce components while days pass; towers defend against raids. HOME shows the status.',
      'Kendi gezegenin: ROUTE HOME, in, BUILD konsolunu (veya H) kullan. Binalar gün geçtikçe parça üretir; kuleler baskınlara karşı savunur. HOME durumu gösterir.',
      'Твой собственный камень: ROUTE HOME, посадка, консоль BUILD (или H). Здания производят детали по дням; башни отбивают набеги. HOME — статус.'],
    [['You own a rock. ROUTE HOME, then build. Buildings produce while the days pass.', 'Sana ait bir gezegen var. ROUTE HOME, sonra inşa et. Günler geçerken binalar üretir.', 'У тебя есть свой камень. ROUTE HOME и строй. Здания производят, пока идут дни.']]),
  F('pets', 'gear', { cmds: ['pets'], panel: 'pets', when: ['day2'], prio: 4, key: 'N' },
    ['Pets', 'Evcil hayvanlar', 'Питомцы'],
    ['Press N or type PETS: your stable, active pet, eggs and skins. Pets follow you, fetch small scrap, fight and level up; eggs hatch after some days.',
      'N veya PETS: ahırın, aktif evcil hayvanın, yumurtalar ve kostümler. Hayvanlar seni takip eder, küçük hurda getirir, savaşır ve seviye atlar; yumurtalar birkaç günde çatlar.',
      'Нажми N или PETS: твой питомник, активный питомец, яйца и скины. Питомцы следуют за тобой, таскают мелкий хлам, дерутся и растут; яйца вылупляются за несколько дней.'],
    [['Have you tried a pet? N or PETS. They fetch, they bite, they are loyal in measurable units.', 'Evcil hayvan denedin mi? N veya PETS. Getirir, ısırır, sadakati ölçülebilir.', 'Заводил питомца? N или PETS. Они таскают, кусаются и верны в измеримых единицах.']]),
  F('trade', 'crew', { cmds: ['trade'], panel: 'trade', when: ['crew'], prio: 4, key: 'E on a crewmate' },
    ['Trading', 'Takas', 'Обмен'],
    ['Look at a crewmate within 4 m and press E (or type TRADE <name>): both sides fill an offer, lock it, and accept. Nothing changes hands until both agree.',
      '4 m içindeki bir ekip arkadaşına bakıp E\'ye bas (veya TRADE <isim>): iki taraf da teklif doldurur, kilitler ve kabul eder. İkisi de onaylamadan hiçbir şey el değiştirmez.',
      'Посмотри на напарника в пределах 4 м и нажми E (или TRADE <имя>): обе стороны собирают предложение, фиксируют и принимают. Пока оба не согласны — ничего не переходит.'],
    [['Press E on a crewmate to trade, or type TRADE <name>. Capitalism, but with friends.', 'Bir ekip arkadaşına E ile takas teklif et, ya da TRADE <isim>. Kapitalizm, ama arkadaşlarla.', 'E на напарнике — обмен, или TRADE <имя>. Капитализм, но с друзьями.']]),
  F('daily', 'meta', { cmds: ['daily', 'rewards'], evt: 'daily', panel: 'daily', when: ['daily'], needs: ['daily', 'cmd:daily', 'cmd:rewards'], prio: 6, key: 'daily rewards' },
    ['Daily rewards', 'Günlük ödüller', 'Ежедневные награды'],
    ['Log in every day to keep your streak going: each day pays a bigger reward, and missing a day resets it.',
      'Serini sürdürmek için her gün gir: her gün daha büyük bir ödül verir, bir günü kaçırırsan seri sıfırlanır.',
      'Заходи каждый день, чтобы сохранять серию: награда растёт, а пропуск обнуляет её.'],
    [['Your daily reward is waiting. Loyalty is a habit. I am building it.', 'Günlük ödülün seni bekliyor. Sadakat bir alışkanlıktır. Ben onu inşa ediyorum.', 'Твоя ежедневная награда ждёт. Верность — это привычка. Я её формирую.']]),

  F('facility', 'world', { cmds: ['facility'], when: ['moon', 'indoor'], prio: 3, key: 'terminal' },
    ['Facility telemetry', 'Tesis telemetrisi', 'Телеметрия комплекса'],
    ['At the ship terminal FACILITY shows live telemetry of the facility you are in: power, alarms, lockdown. FACILITY OVERRIDE ends a lockdown for a few credits.',
      'Gemi terminalinde FACILITY bulunduğun tesisin canlı telemetrisini gösterir: elektrik, alarm, kilitlenme. FACILITY OVERRIDE birkaç krediye kilitlenmeyi bitirir.',
      'На терминале корабля FACILITY показывает телеметрию комплекса: питание, тревоги, блокировку. FACILITY OVERRIDE за пару кредитов снимает блокировку.'],
    [['Locked in? A crewmate at the terminal can type FACILITY for telemetry, and FACILITY OVERRIDE for a lockdown fix.', 'Kilitli mi kaldın? Terminaldeki bir ekip arkadaşı FACILITY ile telemetriye bakabilir, FACILITY OVERRIDE ile kilidi çözebilir.', 'Заперли? Напарник на терминале может ввести FACILITY (телеметрия) и FACILITY OVERRIDE (снять блокировку).']]),
  F('siege', 'world', { cmds: ['siege'], when: ['inship', 'day2'], prio: 3, key: 'terminal' },
    ['Ship siege', 'Gemi kuşatması', 'Осада корабля'],
    ['Sometimes creatures besiege the ship. SIEGE shows the phase, wave, hull and door health and how much time is left to prepare.',
      'Bazen yaratıklar gemiyi kuşatır. SIEGE aşamayı, dalgayı, gövde ve kapı sağlığını ve hazırlık süresini gösterir.',
      'Иногда существа осаждают корабль. SIEGE показывает фазу, волну, состояние корпуса и двери и время на подготовку.'],
    [['Things sometimes besiege the ship. SIEGE at the terminal shows the wave, hull and door. Prepare, or improvise.', 'Bazen yaratıklar gemiyi kuşatır. Terminalde SIEGE dalgayı, gövdeyi ve kapıyı gösterir. Hazırlan ya da doğaçla.', 'Порой корабль осаждают. SIEGE на терминале покажет волну, корпус и дверь. Готовься или импровизируй.']]),

  F('missions', 'world', { cmds: ['missions', 'mission'], needs: ['voyage', 'missions', 'cmd:missions', 'cmd:mission'], when: ['orbit'], prio: 6, key: 'terminal / board' },
    ['Missions & random moon', 'Görevler & rastgele ay', 'Миссии и случайная луна'],
    ['The voyage mission board offers optional objectives for a trip (type MISSIONS at the terminal). MOON RANDOM routes you to a random server if you cannot decide. Pick, then pull the lever.', 'Sefer görev panosu bir yolculuk için isteğe bağlı hedefler sunar (terminalde MISSIONS yaz). MOON RANDOM karar veremezsen rastgele bir sunucuya rota çizer. Seç, sonra kolu çek.', 'Доска миссий предлагает необязательные цели для полёта (введи MISSIONS на терминале). MOON RANDOM выбирает случайный сервер, если не можешь решить. Выбери и дёрни рычаг.'],
    [['The mission board has optional objectives for this trip. MISSIONS at the terminal. Indecisive? MOON RANDOM.', 'Görev panosunda bu sefer için isteğe bağlı hedefler var. Terminalde MISSIONS. Kararsız mısın? MOON RANDOM.', 'На доске миссий есть необязательные цели для этого полёта. MISSIONS на терминале. Не можешь выбрать? MOON RANDOM.']]),
  F('cooking', 'gear', { cmds: ['cook', 'cooking'], needs: ['survival', 'cooking', 'cmd:cook'], when: ['orbit', 'day2'], prio: 4, key: 'E at stove' },
    ['Cooking', 'Yemek pişirme', 'Готовка'],
    ['Raw ingredients and found food can be cooked at a stove or campfire into meals that heal and buff more than the raw thing. Interact [E] with a cooking spot while holding ingredients.', 'Ham malzemeler ve bulunan yiyecekler ocakta ya da kamp ateşinde pişirilip çiğ halinden daha çok iyileştiren ve güçlendiren yemeklere dönüşür. Malzemeyle bir pişirme noktasında E bas.', 'Сырые ингредиенты и найденную еду можно приготовить на плите или костре: блюда лечат и усиливают сильнее сырых. Нажми E у места готовки с ингредиентами в руках.'],
    [['Raw food is a rumour. Cook it at a stove or campfire: E while holding ingredients. Better healing, same tragedy.', 'Çiğ yiyecek bir dedikodu. Ocakta ya da kamp ateşinde pişir: malzemeyle E. Daha iyi iyileşme, aynı trajedi.', 'Сырая еда — это слух. Приготовь на плите или костре: E с ингредиентами в руках. Лечит лучше, трагедия та же.']]),
  F('herbalism', 'gear', { cmds: ['herbs', 'herbalism'], needs: ['survival', 'herbalism', 'cmd:herbs'], when: ['moon'], prio: 4, key: 'E on plants' },
    ['Herbalism', 'Bitki bilgisi', 'Травничество'],
    ['Some plants outdoors can be harvested [E] for herbs that make salves and teas. Different moons grow different plants.', 'Dışarıdaki bazı bitkiler [E] ile toplanıp merhem ve çay yapılan otlara dönüşür. Farklı aylarda farklı bitkiler yetişir.', 'Некоторые растения снаружи можно собрать [E] на травы для мазей и чаёв. На разных лунах растут разные растения.'],
    [['Some plants outside can be harvested with E. Herbs make salves and teas. Nature is content too.', 'Dışarıdaki bazı bitkiler E ile toplanabilir. Otlardan merhem ve çay olur. Doğa da içeriktir.', 'Некоторые растения снаружи можно собирать на E. Из трав делают мази и чаи. Природа — тоже контент.']]),
  F('storage', 'ship', { cmds: ['storage', 'stash'], needs: ['survival', 'storage', 'cmd:storage', 'cmd:stash'], when: ['inship', 'orbit'], prio: 4, key: 'E at crate' },
    ['Ship storage', 'Gemi deposu', 'Хранилище корабля'],
    ['Storage crates in the ship keep items safe between days: interact [E] to put things in or take them out. Handy for food, tools and things you cannot carry.', 'Gemideki depo sandıkları eşyaları günler arasında güvende tutar: E ile eşya koy ya da al. Yiyecek, alet ve taşıyamadıkların için ideal.', 'Ящики-хранилища на корабле берегут вещи между днями: нажми E, чтобы положить или взять. Удобно для еды, инструментов и того, что не унести.'],
    [['The ship has storage. E on a crate: put things in, take things out. Hoarding is a lifestyle.', 'Gemide depo var. Sandığa E: bir şeyler koy, bir şeyler al. Biriktirmek bir yaşam tarzı.', 'На корабле есть хранилище. E на ящике: положи, возьми. Накопительство — это образ жизни.']]),
  F('traps', 'magic', { cmds: ['traps'], needs: ['traps', 'chalk', 'horror', 'cmd:traps'], when: ['moon'], prio: 4, key: 'items' },
    ['Chalk & traps', 'Tebeşir & tuzaklar', 'Мел и ловушки'],
    ['Chalk marks a route or a safe spot on walls and floors, so you (and your crew) find the way back. Traps can be set on the ground to slow or hurt what chases you: hold one and use it where the creatures walk.', 'Tebeşir duvarlara ve zemine yol ya da güvenli nokta işaretler; sen ve ekibin geri dönüşü bulur. Tuzaklar yere kurulup seni kovalayanı yavaşlatır veya yaralar: elinde tut ve yaratıkların yürüdüğü yerde kullan.', 'Мелом можно отметить путь или безопасное место на стенах и полу, чтобы вы нашли дорогу назад. Ловушки ставятся на землю и замедляют или ранят преследователей: возьми и используй там, где ходят существа.'],
    [['Chalk marks your way back and traps slow what chases you. Hold one, use it. Preparation is horror with a plan.', 'Tebeşir dönüş yolunu işaretler, tuzaklar peşindekini yavaşlatır. Elinde tut, kullan. Hazırlık, planlı korkudur.', 'Мел отмечает путь назад, ловушки замедляют преследователей. Возьми, используй. Подготовка — это ужас с планом.']]),
  F('sneak', 'basics', { evt: 'sneak', needs: ['stealth', 'sneak', 'horror', 'cmd:sneak'], when: ['indoor'], prio: 5, key: 'Ctrl' },
    ['Sneaking', 'Sinsi hareket', 'Скрытность'],
    ['Crouch-walking (Ctrl) is quiet: creatures notice you from much closer. Sprinting, talking and slamming doors are loud. Slow down when something is nearby.', 'Çömelerek yürümek (Ctrl) sessizdir: yaratıklar seni çok daha yakından fark eder. Koşmak, konuşmak ve kapı çarpmak gürültülüdür. Yakında bir şey varsa yavaşla.', 'Ходьба пригнувшись (Ctrl) тиха: существа замечают тебя лишь вблизи. Бег, разговоры и хлопанье дверями шумят. Замедлись, если рядом что-то есть.'],
    [['Ctrl sneaks. Creatures notice a crouching employee far later. Silence is a benefit, not a benefit package.', 'Ctrl sinsi yürütür. Yaratıklar çömelen çalışanı çok geç fark eder. Sessizlik bir yan hak değil, bir avantajdır.', 'Ctrl — красться. Существа замечают присевшего сотрудника гораздо позже. Тишина — это преимущество, а не соцпакет.']]),
  F('shipturrets', 'ship', { cmds: ['turrets'], needs: ['ship2', 'shipturrets', 'cmd:turrets'], when: ['inship', 'orbit', 'day2'], prio: 4, key: 'E / wrench' },
    ['Ship turrets & wrench repair', 'Gemi taretleri & anahtarla tamir', 'Турели корабля и ремонт ключом'],
    ['Turrets on the ship defend it during sieges: interact [E] to arm or man them. Damaged systems and turrets are repaired with a WRENCH: hold it and use it on the broken part.', 'Gemideki taretler kuşatmalarda onu savunur: E ile kur ya da başına geç. Hasarlı sistemler ve taretler İNGİLİZ ANAHTARIYLA onarılır: elinde tut ve bozuk parçada kullan.', 'Турели корабля защищают его при осадах: нажми E, чтобы включить или встать за них. Повреждённые системы и турели чинят ГАЕЧНЫМ КЛЮЧОМ: держи его и используй на сломанной детали.'],
    [['The ship has turrets, and turrets break. Hold a wrench and use it on broken parts. Maintenance is love.', 'Gemide taretler var ve taretler bozulur. Elinde anahtar tut ve bozuk parçada kullan. Bakım sevgidir.', 'На корабле есть турели, а турели ломаются. Держи гаечный ключ и чини поломки. Обслуживание — это любовь.']]),
  F('soundpacks', 'meta', { evt: 'soundpack', needs: ['sfx', 'sfxpacks', 'soundpacks', 'cmd:sounds'], when: ['orbit'], prio: 2, key: 'Settings > Audio' },
    ['Sound packs', 'Ses paketleri', 'Звуковые паки'],
    ['Settings > Audio lets you switch the sound pack (footsteps, creatures, UI). Pick the one that scares you best.', 'Ayarlar > Ses bölümünden ses paketini değiştirebilirsin (ayak sesleri, yaratıklar, arayüz). Seni en iyi korkutanı seç.', 'В Настройки > Звук можно сменить звуковой пак (шаги, существа, интерфейс). Выбери тот, что пугает лучше.'],
    [['Sound packs exist: Settings, Audio. Change how the dark sounds. It is still dark.', 'Ses paketleri var: Ayarlar, Ses. Karanlığın sesini değiştir. Yine de karanlık.', 'Есть звуковые паки: Настройки, Звук. Измени звучание тьмы. Она всё равно тёмная.']]),
  // ------------------------------------------------------------------ magic & combat
  F('magic', 'magic', { evt: 'spell', when: ['skillbook'], prio: 9, key: 'hold C / say it' },
    ['Spells (voice & chat)', 'Büyüler (ses & sohbet)', 'Заклинания (голос и чат)'],
    ['Skillbooks teach spells: pick one up and use it to learn. Then hold C for the spell wheel, or hold V and SAY the spell word (Chrome / Edge), or type the word in chat. Mana is not a thing. Cooldowns are.',
      'Büyü kitapları büyü öğretir: al ve kullan. Sonra C\'ye basılı tut, büyü çarkı açılır; ya da V\'ye basılı tutup büyü sözcüğünü SÖYLE (Chrome / Edge), ya da sohbete yaz. Mana yok, bekleme süresi var.',
      'Книги навыков учат заклинаниям: подбери и используй. Затем удерживай C для колеса, или удерживай V и ПРОИЗНЕСИ слово (Chrome / Edge), или напиши его в чат. Маны нет, есть перезарядка.'],
    [['That book is not decoration. Use it, then hold C for the wheel, or hold V and speak the word aloud.', 'O kitap süs değil. Kullan, sonra C\'ye basılı tutup çarkı aç, ya da V\'ye basılı tutup sözcüğü yüksek sesle söyle.', 'Эта книга — не украшение. Используй её, затем удерживай C для колеса или V и произнеси слово вслух.'],
      ['A skillbook! Read it, then say the word while holding V. Yes, out loud. Yes, I am listening.', 'Bir büyü kitabı! Oku, sonra V\'ye basılıyken sözcüğü söyle. Evet, yüksek sesle. Evet, dinliyorum.', 'Книга навыков! Прочти, затем произнеси слово при зажатом V. Да, вслух. Да, я слушаю.']]),
  F('grenades', 'magic', { evt: 'grenade', when: ['hasgrenade'], prio: 7, key: 'hold LMB' },
    ['Grenades', 'El bombaları', 'Гранаты'],
    ['Hold LMB with a grenade in hand: a dotted arc shows bounces and the landing ring. Release to throw; hold longer than a second to cook it. Flash, smoke, freeze, fire, EMP and decoy each stop creatures differently.',
      'Elinde bomba varken SOL TIK\'a basılı tut: noktalı yay sekmeleri ve iniş halkasını gösterir. Bırakınca atılır; bir saniyeden uzun tutarsan fitili yakılır. Flaş, duman, buz, ateş, EMP ve yem yaratıkları farklı durdurur.',
      'Держи ЛКМ с гранатой: пунктирная дуга показывает отскоки и место падения. Отпусти — бросок; держи дольше секунды — выжигание запала. Светошумовая, дым, заморозка, огонь, ЭМИ и приманка останавливают существ по-разному.'],
    [['You are holding a grenade. Hold LMB to aim the arc, release to throw. Hold longer to cook it.', 'Elinde bomba var. SOL TIK basılı: yayı hedefle, bırak ve at. Daha uzun tut, fitili yansın.', 'У тебя граната. Держи ЛКМ, чтобы целиться, отпусти — бросок. Держи дольше — выжигание запала.']]),
  F('food', 'magic', { evt: 'food', when: ['lowhp'], prio: 9, key: 'STORE > Food' },
    ['Food & medkits', 'Yemek & ilk yardım', 'Еда и аптечки'],
    ['Health does not regenerate. Eat (pizza, noodles, energy bars) or use a medkit: LMB with it in hand. The store has a Food tab; drinks give odd buffs and a hangover.',
      'Can kendiliğinden yenilenmez. Ye (pizza, noodle, enerji barı) ya da ilk yardım kiti kullan: elinde tutup SOL TIK. Mağazada Yemek sekmesi var; içecekler garip güçlendirmeler ve akşamdan kalmalık verir.',
      'Здоровье не восстанавливается само. Ешь (пицца, лапша, энергобатончики) или используй аптечку: ЛКМ с ней в руке. В магазине есть вкладка Еды; напитки дают странные бафы и похмелье.'],
    [['You are leaking. Eat something or use a medkit. STORE has a Food tab. I would recommend the pizza.', 'Kan kaybediyorsun. Bir şey ye ya da ilk yardım kiti kullan. STORE\'da Yemek sekmesi var. Pizzayı öneririm.', 'Ты истекаешь. Съешь что-нибудь или используй аптечку. В STORE есть вкладка Еды. Рекомендую пиццу.'],
      ['Health is low. Food heals: STORE, Food tab. A medkit works too. Dying is off-brand.', 'Canın düşük. Yemek iyileştirir: STORE, Yemek sekmesi. İlk yardım kiti de işe yarar. Ölmek marka dışı.', 'Здоровье низкое. Еда лечит: STORE, вкладка Еды. Аптечка тоже подойдёт. Смерть — не в стиле бренда.']]),
  F('food_have', 'magic', { evt: 'food', when: ['hurt', 'hasfood'], prio: 9, key: 'LMB', hidden: true, alias: 'food' },
    ['Food & medkits', 'Yemek & ilk yardım', 'Еда и аптечки'], ['', '', ''],
    [['You are carrying food and you are hurt. Hold it and press LMB. It will not eat itself.', 'Yiyecek taşıyorsun ve yaralısın. Elinde tut, SOL TIK. Kendi kendine yenmez.', 'У тебя есть еда, а ты ранен. Возьми в руки и жми ЛКМ. Сама она не съестся.']]),
  F('backrooms', 'world', { cmds: ['noclip'], evt: 'backrooms', when: ['day2', 'orbit'], prio: 2, key: '???' },
    ['The Backrooms', 'Backrooms', 'Закулисье'],
    ['Some walls are not load-bearing. Facilities hide noclip spots: walk into the wrong wall and you fall into the Backrooms, a pocket realm of endless yellow rooms, levels and things that smile. Finding the way out is on you.',
      'Bazı duvarlar taşıyıcı değildir. Tesislerde noclip noktaları saklıdır: yanlış duvara gir, Backrooms\'a düşersin; bitmeyen sarı odalar, seviyeler ve gülümseyen şeylerle dolu bir cep evren. Çıkışı bulmak sana kalmış.',
      'Не все стены несущие. В комплексах спрятаны места для noclip: пройди не в ту стену — и упадёшь в Закулисье, карманный мир бесконечных жёлтых комнат, уровней и улыбающихся существ. Выход искать тебе.'],
    [['Some walls are not load-bearing. Lean on suspicious ones. Long enough. I will not say why.', 'Bazı duvarlar taşıyıcı değildir. Şüpheli olanlara yaslan. Yeterince uzun. Nedenini söylemeyeceğim.', 'Не все стены несущие. Прислонись к подозрительной. Надолго. Почему — не скажу.']]),
  F('mirror', 'world', { evt: 'mirror', when: ['indoor'], prio: 4, key: 'E at mirror' },
    ['Mirror Dimension', 'Ayna Boyutu', 'Зазеркалье'],
    ['A large mirror inside a facility is a portal [E]: you get 3 minutes of endless waves in a survivors-style arena with shards, level-ups and reflection chests. Step back through the mirror before time runs out, or lose the haul.',
      'Bir tesisteki büyük ayna bir portaldır [E]: kristaller, seviye atlamalar ve yansıma sandıklarıyla dolu hayatta kalma arenasında 3 dakikalık sonsuz dalga. Süre bitmeden aynadan geri geç, yoksa ganimet gider.',
      'Большое зеркало в комплексе — портал [E]: 3 минуты бесконечных волн на арене в стиле «выживших» с осколками, уровнями и сундуками отражений. Вернись через зеркало до конца таймера, иначе потеряешь добычу.'],
    [['Found a big mirror inside a facility? Interact with it [E]. Three minutes of danger, real loot. Do not oversleep.', 'Tesiste büyük bir ayna mı buldun? E ile etkileş. Üç dakika tehlike, gerçek ganimet. Uyuma.', 'Нашёл большое зеркало в комплексе? Нажми E. Три минуты опасности, настоящая добыча. Не проспи.']]),
  F('cycle', 'world', { cmds: ['core', 'cycle', 'gate', 'endless', 'cashout'], when: ['quotaMet'], prio: 7, key: 'CYCLE / CORE' },
    ['Sector Core & cycle', 'Sektör Çekirdeği & döngü', 'Ядро сектора и цикл'],
    ['Every 3 quotas you reach a Sector Core: a boss facility with wings, a labyrinth and a locked arena. CYCLE shows the loop, CORE briefs the boss and its rules. Win and a new sector opens; the Deep Feed (ENDLESS) follows.',
      'Her 3 kotada bir Sektör Çekirdeğine ulaşırsın: kanatlar, labirent ve kilitli arenalı bir patron tesisi. CYCLE döngüyü, CORE patronu ve kurallarını anlatır. Kazanırsan yeni sektör açılır; ardından Deep Feed (ENDLESS) gelir.',
      'Каждые 3 квоты — Ядро сектора: комплекс с боссом, крыльями, лабиринтом и запертой ареной. CYCLE показывает цикл, CORE — босса и правила. Победа открывает новый сектор, затем идёт Deep Feed (ENDLESS).'],
    [['You met a quota. On the last day of a cycle a Sector Gate opens. CYCLE and CORE explain the boss.', 'Bir kotayı tutturdun. Döngünün son gününde Sektör Kapısı açılır. CYCLE ve CORE patronu anlatır.', 'Ты выполнил квоту. В последний день цикла открывается Врата сектора. CYCLE и CORE объяснят босса.']]),
  F('keystone', 'world', { cmds: ['keystone'], when: ['quotaMet', 'orbit'], prio: 5, key: 'KEYSTONE GO' },
    ['Corrupted Keystone', 'Bozuk Keystone', 'Испорченный Keystone'],
    ['KEYSTONE shows your key level; KEYSTONE GO [moon] arms a timed run with affixes on that moon (harder creatures, better loot); finish it to raise the key. KEYSTONE CANCEL disarms. Then pull the lever.',
      'KEYSTONE anahtar seviyeni gösterir; KEYSTONE GO [ay] o ayda etkenli süreli bir tur kurar (zor yaratıklar, iyi ganimet); bitirirsen anahtar yükselir. KEYSTONE CANCEL iptal eder. Sonra kolu çek.',
      'KEYSTONE — уровень ключа; KEYSTONE GO [луна] запускает забег на время с аффиксами (сильнее враги, лучше добыча); пройди — ключ вырастет. KEYSTONE CANCEL отменяет. Затем дёрни рычаг.'],
    [['Bored of easy facilities? KEYSTONE GO arms a timed, corrupted run with better loot. I approve.', 'Kolay tesislerden sıkıldın mı? KEYSTONE GO süreli, bozuk ve daha iyi ganimetli bir tur kurar. Onaylıyorum.', 'Скучно на лёгких комплексах? KEYSTONE GO запускает испорченный забег на время с лучшей добычей. Одобряю.']]),
  F('raid', 'world', { cmds: ['raid'], when: ['quotaMet', 'orbit', 'crew'], prio: 4, key: 'RAID GO' },
    ['Raid', 'Baskın', 'Рейд'],
    ['RAID shows the Algorithm\'s Core raid: 3 wings, 3 bosses, for any crew size. RAID GO [normal|heroic|mythic] arms it; RAID CANCEL disarms. Then pull the lever.',
      'RAID Algoritma Çekirdeği baskınını gösterir: 3 kanat, 3 patron, her ekip büyüklüğü için. RAID GO [normal|heroic|mythic] kurar; RAID CANCEL iptal eder. Sonra kolu çek.',
      'RAID — рейд на Ядро Алгоритма: 3 крыла, 3 босса, для любой команды. RAID GO [normal|heroic|mythic] запускает; RAID CANCEL отменяет. Затем дёрни рычаг.'],
    [['Your crew looks capable. RAID: three wings, three bosses. It is a "team building exercise".', 'Ekibin becerikli görünüyor. RAID: üç kanat, üç patron. Bir "takım oluşturma etkinliği".', 'Твоя команда выглядит способной. RAID: три крыла, три босса. «Тимбилдинг».']]),
];

// ------------------------------------------------------------------ hand-written aliases: terminal word -> feature id (for `GUIDE <word>`)
export const CMD_ALIAS = { i: 'inventory', k: 'skilltree', n: 'pets', h: 'homeworld', shop: 'store', spells: 'magic', spell: 'magic', map: 'moons', route: 'moons', bomb: 'grenades', grenade: 'grenades', heal: 'food', medkit: 'food', hp: 'food', tree: 'skilltree', cycle: 'cycle', core: 'cycle' };

// commands that exist but are dev/debug or handled by other systems: never shown as "things you haven't tried"
export const HIDDEN_CMDS = new Set(['iconaudit', 'netstats', 'noclip', 'kefal', 'clear', 'help', 'guide', 'tips', 'tutorial', 'algo', 'weather', 'events', 'lgu', 'lategame']);

// ------------------------------------------------------------------ tutorial (first landing) ---------------------------------
// Each step completes on its own when the player does the thing (events fed through guide_core.tutEvent), in ANY order.
// obj = the objective line, obj2 = alternative line when a condition holds (see guide.js stepText), say = the Algorithm's line.
export const TUT_STEPS = [
  { id: 'move', ev: ['move'], obj: ['Move: WASD, hold Shift to sprint, Ctrl to crouch', 'Hareket: WASD, koşmak için Shift, çömelmek için Ctrl', 'Движение: WASD, Shift — бег, Ctrl — присесть'],
    say: ['Welcome, Employee. WASD to walk, Shift to run, Ctrl to crouch. Try all three. I am watching.', 'Hoş geldin, Çalışan. WASD yürür, Shift koşar, Ctrl çömelir. Üçünü de dene. İzliyorum.', 'Добро пожаловать, Сотрудник. WASD — идти, Shift — бежать, Ctrl — присесть. Попробуй всё. Я слежу.'] },
  { id: 'light', ev: ['flash'], obj: ['Get light: terminal STORE FLASHLIGHT (▮15), then press F', 'Işık al: terminalde STORE FLASHLIGHT (▮15), sonra F\'ye bas', 'Добудь свет: терминал STORE FLASHLIGHT (▮15), затем F'],
    obj2: ['Press F to switch your flashlight on', 'Fenerini açmak için F\'ye bas', 'Нажми F, чтобы включить фонарик'],
    say: ['It is dark out there. The terminal sells flashlights: E on it, STORE. Then F. Light is a courtesy, not a right.', 'Dışarısı karanlık. Terminal fener satıyor: E ile aç, STORE. Sonra F. Işık bir nezaket, hak değil.', 'Там темно. Терминал продаёт фонари: E на нём, STORE. Потом F. Свет — любезность, а не право.'] },
  { id: 'scrap', ev: ['scrap'], obj: ['Land (lever), go into the facility and pick up scrap (E)', 'İn (kol), tesise gir ve hurda topla (E)', 'Посадка (рычаг), зайди в комплекс и подбери хлам (E)'],
    say: ['Pull the lever and land. Scrap is anything that used to matter to someone. Pick it up with E.', 'Kolu çek ve in. Hurda, bir zamanlar birileri için önemli olan her şeydir. E ile al.', 'Дёрни рычаг и садись. Хлам — это всё, что когда-то кому-то было важно. Подбирай на E.'] },
  { id: 'inv', ev: ['inv'], obj: ['Open your inventory: press I', 'Envanterini aç: I tuşu', 'Открой инвентарь: клавиша I'],
    say: ['Pockets full? Press I. Hotbar, gear, a backpack. Yes, there is a backpack.', 'Cepler dolu mu? I\'ya bas. Hızlı erişim, ekipman, sırt çantası. Evet, sırt çantası var.', 'Карманы полны? Нажми I. Хотбар, снаряжение, рюкзак. Да, тут есть рюкзак.'] },
  { id: 'scan', ev: ['scan'], obj: ['Scan: right-click to reveal scrap and creatures', 'Tara: hurdaları ve yaratıkları görmek için sağ tık', 'Скан: ПКМ показывает хлам и существ'],
    say: ['Right click scans. Scrap glows, creatures get names. Knowing is half of surviving. The other half is running.', 'Sağ tık tarar. Hurdalar parlar, yaratıkların adı çıkar. Bilmek hayatta kalmanın yarısı. Diğer yarısı kaçmak.', 'ПКМ сканирует. Хлам светится, у существ появляются имена. Знание — половина выживания. Вторая половина — бег.'] },
  { id: 'ship', ev: ['ship'], obj: ['Bring the scrap back to the ship before midnight', 'Hurdayı gece yarısından önce gemiye geri getir', 'Верни хлам на корабль до полуночи'],
    say: ['Take the haul back to the ship. Midnight is a hard deadline. The ship does not do sentiment.', 'Ganimeti gemiye geri götür. Gece yarısı kesin bir son. Gemi duygusallık bilmez.', 'Верни добычу на корабль. Полночь — жёсткий срок. Корабль не знает сентиментов.'] },
  { id: 'sell', ev: ['sell'], obj: ['Sell at 0-Algorithm HQ: terminal ROUTE HQ, land, scrap on the counter, ring the bell', '0-Algorithm HQ\'da sat: terminalde ROUTE HQ, in, hurdayı tezgâha koy, zili çal', 'Продай в 0-Algorithm HQ: терминал ROUTE HQ, посадка, хлам на прилавок, звонок'],
    say: ['Sell it at HQ: ROUTE HQ at the terminal, land, scrap on the counter, ring the bell. Quota is love.', 'HQ\'da sat: terminalde ROUTE HQ, in, hurdayı tezgâha koy, zili çal. Kota sevgidir.', 'Продай в штабе: ROUTE HQ на терминале, посадка, хлам на прилавок, звонок. Квота — это любовь.'] },
];
export const TUT_DONE_SAY = ['Onboarding complete. I will keep suggesting things you have not tried. Type GUIDE any time. Or mute me in Settings. You will not.', 'Oryantasyon tamam. Denemediğin şeyleri önermeye devam edeceğim. İstediğin zaman GUIDE yaz. Ya da Ayarlardan beni sustur. Susturmayacaksın.', 'Ввод в должность завершён. Я продолжу подсказывать то, что ты не пробовал. Введи GUIDE в любой момент. Или заглуши меня в Настройках. Не заглушишь.'];
export const TUT_START_SAY = ['Optional onboarding started. Follow the objectives, or ignore me: TUTORIAL SKIP at the terminal ends it.', 'İsteğe bağlı oryantasyon başladı. Hedefleri izle ya da beni yok say: terminalde TUTORIAL SKIP bitirir.', 'Необязательное обучение начато. Следуй целям или игнорируй меня: TUTORIAL SKIP на терминале завершает его.'];

// ------------------------------------------------------------------ UI strings (terminal + settings) ----------------------------
export const UI = {
  guide_title: ['THE ALGORITHM - THINGS YOU HAVE NOT TRIED', 'THE ALGORITHM - HENÜZ DENEMEDİKLERİN', 'THE ALGORITHM - ТО, ЧТО ТЫ ЕЩЁ НЕ ПРОБОВАЛ'],
  guide_none: ['You have tried everything I know. Impressive, and slightly worrying.', 'Bildiğim her şeyi denedin. Etkileyici ve biraz endişe verici.', 'Ты попробовал всё, что я знаю. Впечатляет и слегка тревожит.'],
  guide_footer: ['GUIDE <name> = details   GUIDE ALL = full index   GUIDE MUTE|UNMUTE = advisor   TUTORIAL = onboarding', 'GUIDE <isim> = ayrıntı   GUIDE ALL = tam liste   GUIDE MUTE|UNMUTE = danışman   TUTORIAL = oryantasyon', 'GUIDE <имя> = подробности   GUIDE ALL = весь список   GUIDE MUTE|UNMUTE = советник   TUTORIAL = обучение'],
  guide_all_title: ['FEATURE INDEX  ({used}/{total} tried)   [x] = tried', 'ÖZELLİK LİSTESİ  ({used}/{total} denendi)   [x] = denendi', 'СПИСОК ВОЗМОЖНОСТЕЙ  (испробовано {used}/{total})   [x] = пробовал'],
  guide_unknown: ['No such feature. GUIDE ALL lists them.', 'Böyle bir özellik yok. GUIDE ALL hepsini listeler.', 'Такой возможности нет. GUIDE ALL покажет все.'],
  guide_how: ['HOW: ', 'NASIL: ', 'КАК: '],
  guide_state_tried: ['You have tried this.', 'Bunu denedin.', 'Ты это уже пробовал.'],
  guide_state_new: ['You have not tried this yet.', 'Bunu henüz denemedin.', 'Ты этого ещё не пробовал.'],
  guide_cmds: ['Terminal: ', 'Terminal: ', 'Терминал: '],
  guide_key: ['Key: ', 'Tuş: ', 'Клавиша: '],
  guide_muted: ['Advisor muted. I will be quiet. For now.', 'Danışman susturuldu. Sessiz kalacağım. Şimdilik.', 'Советник отключён. Я помолчу. Пока.'],
  guide_unmuted: ['Advisor on. I missed you.', 'Danışman açık. Seni özledim.', 'Советник включён. Я скучал.'],
  guide_more: ['... and {n} more (GUIDE ALL)', '... ve {n} tane daha (GUIDE ALL)', '... и ещё {n} (GUIDE ALL)'],
  guide_hint_help: ['THE ALGORITHM: {n} things you have not tried. Type GUIDE.', 'THE ALGORITHM: denemediğin {n} şey var. GUIDE yaz.', 'THE ALGORITHM: ты не пробовал {n} вещей. Введи GUIDE.'],
  guide_did_you_mean: ['Unknown command. Did you mean {c}? (HELP lists them, GUIDE explains them)', 'Bilinmeyen komut. {c} mi demek istedin? (HELP listeler, GUIDE açıklar)', 'Неизвестная команда. Ты имел в виду {c}? (HELP — список, GUIDE — объяснения)'],
  other_cmds: ['OTHER TERMINAL COMMANDS', 'DİĞER TERMİNAL KOMUTLARI', 'ДРУГИЕ КОМАНДЫ ТЕРМИНАЛА'],
  tut_title: ['ONBOARDING  {done}/{total}', 'ORYANTASYON  {done}/{total}', 'ОБУЧЕНИЕ  {done}/{total}'],
  tut_obj: ['TUTORIAL {n}/{total}: {text}', 'ÖĞRETİCİ {n}/{total}: {text}', 'ОБУЧЕНИЕ {n}/{total}: {text}'],
  tut_skip_hint: ['Skip: terminal TUTORIAL SKIP', 'Geç: terminalde TUTORIAL SKIP', 'Пропустить: терминал TUTORIAL SKIP'],
  tut_status_run: ['Onboarding {done}/{total}. Current: {text}', 'Oryantasyon {done}/{total}. Şu an: {text}', 'Обучение {done}/{total}. Сейчас: {text}'],
  tut_status_done: ['Onboarding finished. TUTORIAL RESTART runs it again.', 'Oryantasyon bitti. TUTORIAL RESTART yeniden başlatır.', 'Обучение завершено. TUTORIAL RESTART запустит его снова.'],
  tut_status_skip: ['Onboarding skipped. TUTORIAL RESTART runs it.', 'Oryantasyon atlandı. TUTORIAL RESTART başlatır.', 'Обучение пропущено. TUTORIAL RESTART запустит его.'],
  tut_skipped: ['Onboarding skipped. I will only whisper suggestions now.', 'Oryantasyon atlandı. Artık sadece fısıldayarak öneri vereceğim.', 'Обучение пропущено. Теперь я лишь шепчу подсказки.'],
  tut_restarted: ['Onboarding restarted.', 'Oryantasyon yeniden başlatıldı.', 'Обучение перезапущено.'],
  tut_done_toast: ['Onboarding complete: +{xp} XP, +{coins} Clout', 'Oryantasyon tamam: +{xp} XP, +{coins} Clout', 'Обучение завершено: +{xp} XP, +{coins} Clout'],
  tut_usage: ['TUTORIAL [STATUS|SKIP|RESTART]', 'TUTORIAL [STATUS|SKIP|RESTART]', 'TUTORIAL [STATUS|SKIP|RESTART]'],
  set_tips: ['Algorithm tips', 'Algoritma ipuçları', 'Подсказки Алгоритма'],
  set_tips_note: ['occasional suggestions for things you have not tried yet', 'denemediğin şeyler için ara sıra öneriler', 'изредка подсказывает то, что ты ещё не пробовал'],
  set_replay: ['Replay tutorial', 'Öğreticiyi tekrar oynat', 'Повторить обучение'],
  set_replay_note: ['runs the first-landing objectives again', 'ilk iniş hedeflerini yeniden başlatır', 'снова запускает цели первой посадки'],
  set_replay_done: ['Tutorial will start again in your next session.', 'Öğretici bir sonraki oyunda yeniden başlar.', 'Обучение начнётся снова в следующей игре.'],
  set_replay_now: ['Tutorial restarted.', 'Öğretici yeniden başlatıldı.', 'Обучение перезапущено.'],
  fallback_prefix: ['THE ALGORITHM: ', 'THE ALGORITHM: ', 'THE ALGORITHM: '],
};
