// HERO CONTENT strings (wave 8): Turkish + Russian names and tips of the twelve themed scrap items. English is the key (game/herocontent_core.js).
export const TR = {
  'Transit Card Reader': 'Bilet Kartı Okuyucu', 'Still says INSUFFICIENT FUNDS. It has said that since the last train.': 'Hâlâ YETERSİZ BAKİYE yazıyor. Son trenden beri hep aynı şeyi yazıyor.',
  'Rail Spike': 'Ray Çivisi', 'Heavy iron with a chalk mark. Somebody counted these.': 'Tebeşir işaretli ağır demir. Biri bunları saymış.',
  "Conductor's Lantern": 'Kondüktör Feneri', 'The flame is cold. It points down the tunnel, toward the next stop.': 'Alevi soğuk. Tünelin dibini, bir sonraki durağı gösteriyor.',
  'Lost-and-Found Bag': 'Kayıp Eşya Çantası', 'Unclaimed for 90 days, unclaimed for 9 years. You will not ask what is inside.': '90 gündür, 9 yıldır sahipsiz. İçinde ne olduğunu sormayacaksın.',
  'Grow Lamp': 'Yetiştirme Lambası', 'Purple light, zero plants. It is still working overtime.': 'Mor ışık, sıfır bitki. Hâlâ fazla mesai yapıyor.',
  'Seed Vault Canister': 'Tohum Kasası Kanisteri', 'The last seeds of a deleted forum. Sealed, labelled, very heavy for its size.': 'Silinmiş bir forumun son tohumları. Mühürlü, etiketli, boyuna göre çok ağır.',
  'Bonsai': 'Bonsai', 'Watered on schedule by nobody. It grows a little every time you look away.': 'Kimse tarafından düzenli sulanıyor. Ne zaman arkanı dönsen biraz büyüyor.',
  'Contraband Phone': 'Kaçak Telefon', 'Taped, wrapped and smuggled. One bar, and every bar is a ban appeal.': 'Bantlı, sarılı, kaçırılmış. Tek çubuk çekiyor ve her çubuk bir ban itirazı.',
  "Warden's Keyring": 'Gardiyan Anahtarlığı', 'Every key opens a cell. None of them opens the door out.': 'Her anahtar bir hücre açar. Hiçbiri dışarı çıkan kapıyı açmaz.',
  'Riot Shield': 'İsyan Kalkanı', 'Scuffed by a thousand report buttons. Heavy, awkward, and worth carrying.': 'Bin şikâyet düğmesinden çizilmiş. Ağır, tuhaf ve taşımaya değer.',
  'Brass Elevator Dial': 'Pirinç Asansör Kadranı', 'The needle sits between two floors that no longer exist.': 'İbre artık var olmayan iki katın arasında duruyor.',
  'Executive Nameplate': 'Yönetici İsimliği', 'Reads VICE PRESIDENT OF SYNERGY. Whoever it was, they left in a hurry.': 'SİNERJİ BAŞKAN YARDIMCISI yazıyor. Kim olduğu önemli değil, aceleyle gitmiş.',
  'Turnstile Gate': 'Turnike', 'Waist-high, tripod arms, one green light. It still counts everyone who ever passed.': 'Bel hizasında, üç kollu, tek yeşil ışıklı. Hâlâ geçen herkesi sayıyor.',
  'Ticket Kiosk': 'Bilet Kiosku', 'Sells single rides to a station that was renamed. Change not given.': 'Adı değiştirilmiş bir istasyona tek yolculuk satıyor. Para üstü verilmez.',
  'Giant Planter': 'Dev Saksı', 'A cracked terracotta pot with a fern that outgrew its forum thread.': 'Forum başlığından büyüyen bir eğrelti otu olan çatlak terakota saksı.',
  'Seed Terrarium': 'Tohum Teraryumu', 'Glass on all sides, humid inside, faintly green. Handle it like it can hear you.': 'Her yanı cam, içi nemli, hafif yeşil. Seni duyabiliyormuş gibi taşı.',
  'Evidence Locker': 'Delil Dolabı', 'Sealed with red tape and a stamp that says EXHIBIT A. There is no exhibit B.': 'Kırmızı bantla ve DELİL A yazan mühürle kapatılmış. Delil B yok.',
  'Yard Searchlight': 'Avlu Projektörü', 'It tracked every ban appeal across the yard. The lens is still warm.': 'Avludaki her ban itirazını takip ederdi. Merceği hâlâ sıcak.',
  "Founder's Bust": 'Kurucu Büstü', 'Marble, stern and slightly too polished. The nameplate has been replaced four times.': 'Mermer, sert bakışlı ve fazla parlatılmış. İsimlik dört kez değiştirilmiş.',
  'Executive Safe': 'Yönetici Kasası', 'Brass dial, heavy door, one bonus in it. It is not yours, and it is very heavy.': 'Pirinç kadran, ağır kapı, içinde bir prim. Senin değil ve çok ağır.',
};
export const RU = {
  'Turnstile Gate': 'Турникет', 'Waist-high, tripod arms, one green light. It still counts everyone who ever passed.': 'По пояс, три вертушки, один зелёный огонёк. Он всё ещё считает каждого, кто когда-либо проходил.',
  'Ticket Kiosk': 'Билетный автомат', 'Sells single rides to a station that was renamed. Change not given.': 'Продаёт билеты до станции, которую переименовали. Сдача не выдаётся.',
  'Giant Planter': 'Огромное кашпо', 'A cracked terracotta pot with a fern that outgrew its forum thread.': 'Треснувший терракотовый горшок с папоротником, переросшим свою ветку форума.',
  'Seed Terrarium': 'Террариум для семян', 'Glass on all sides, humid inside, faintly green. Handle it like it can hear you.': 'Стекло со всех сторон, внутри влажно, чуть зеленоватый. Обращайтесь так, будто он вас слышит.',
  'Evidence Locker': 'Шкаф для улик', 'Sealed with red tape and a stamp that says EXHIBIT A. There is no exhibit B.': 'Опечатан красной лентой и штампом «УЛИКА А». Улики Б нет.',
  'Yard Searchlight': 'Прожектор тюремного двора', 'It tracked every ban appeal across the yard. The lens is still warm.': 'Он выслеживал каждую апелляцию на бан по всему двору. Линза ещё тёплая.',
  "Founder's Bust": 'Бюст основателя', 'Marble, stern and slightly too polished. The nameplate has been replaced four times.': 'Мрамор, суровый и слишком уж отполированный. Табличку меняли четыре раза.',
  'Executive Safe': 'Сейф руководителя', 'Brass dial, heavy door, one bonus in it. It is not yours, and it is very heavy.': 'Латунный диск, тяжёлая дверь, внутри один бонус. Он не ваш, и он очень тяжёлый.',
  'Transit Card Reader': 'Считыватель проездных', 'Still says INSUFFICIENT FUNDS. It has said that since the last train.': 'Всё ещё пишет НЕДОСТАТОЧНО СРЕДСТВ. С самого последнего поезда.',
  'Rail Spike': 'Рельсовый костыль', 'Heavy iron with a chalk mark. Somebody counted these.': 'Тяжёлое железо с меловой меткой. Кто-то их пересчитывал.',
  "Conductor's Lantern": 'Фонарь проводника', 'The flame is cold. It points down the tunnel, toward the next stop.': 'Пламя холодное. Оно указывает вглубь тоннеля, к следующей остановке.',
  'Lost-and-Found Bag': 'Сумка из бюро находок', 'Unclaimed for 90 days, unclaimed for 9 years. You will not ask what is inside.': 'Не востребована 90 дней, не востребована 9 лет. Вы не спросите, что внутри.',
  'Grow Lamp': 'Лампа для растений', 'Purple light, zero plants. It is still working overtime.': 'Фиолетовый свет, ни одного растения. Всё ещё работает сверхурочно.',
  'Seed Vault Canister': 'Канистра из хранилища семян', 'The last seeds of a deleted forum. Sealed, labelled, very heavy for its size.': 'Последние семена удалённого форума. Запечатана, подписана, для своих размеров очень тяжёлая.',
  'Bonsai': 'Бонсай', 'Watered on schedule by nobody. It grows a little every time you look away.': 'Его поливают по расписанию, и никто. Стоит отвернуться, и он немного подрастает.',
  'Contraband Phone': 'Контрабандный телефон', 'Taped, wrapped and smuggled. One bar, and every bar is a ban appeal.': 'Примотан, завёрнут, пронесён тайком. Одно деление, и каждое деление — апелляция на бан.',
  "Warden's Keyring": 'Связка ключей надзирателя', 'Every key opens a cell. None of them opens the door out.': 'Каждый ключ открывает камеру. Ни один не открывает дверь наружу.',
  'Riot Shield': 'Щит для разгона толпы', 'Scuffed by a thousand report buttons. Heavy, awkward, and worth carrying.': 'Исцарапан тысячей кнопок «пожаловаться». Тяжёлый, неудобный, но стоит того, чтобы нести.',
  'Brass Elevator Dial': 'Латунный указатель лифта', 'The needle sits between two floors that no longer exist.': 'Стрелка замерла между двумя этажами, которых больше нет.',
  'Executive Nameplate': 'Табличка руководителя', 'Reads VICE PRESIDENT OF SYNERGY. Whoever it was, they left in a hurry.': 'Написано: ВИЦЕ-ПРЕЗИДЕНТ ПО СИНЕРГИИ. Кем бы он ни был, ушёл он в спешке.',
};
