// LABYR12 strings (wave 12): Turkish + Russian for The Dark Web and The Overload Hotel (names, blurbs, mechanic hints, prompts, toasts). English is the key.
// Registered by world/interiors/labyr12_themes.js at import, so the terminal moon list is translated before any module installs.
import { LAB12_HINT } from './labyr12_core.js';

export const TR = {
  'The Dark Web': 'Karanlık Web',
  'No lamps, no signal, no mercy. Knock to see the tunnels, and everything down here hears you knock.': 'Lamba yok, sinyal yok, merhamet yok. Tünelleri görmek için kapıyı çal; ama buradaki her şey seni duyar.',
  'The Overload Hotel': 'Aşırı Yük Oteli',
  'Check in any time. One elevator, one missing floor and a lot of doors that say DO NOT DISTURB.': 'İstediğin zaman giriş yap. Tek asansör, kayıp bir kat ve üzerinde RAHATSIZ ETMEYİN yazan bir sürü kapı.',
  [LAB12_HINT.darkweb]: 'Zifiri karanlık. M ile kapıyı çal: sonar darbesi tünelleri gösterir, ama yakındaki her şey duyar. Koşmak ve gürültülü sesler de darbe yollar.',
  [LAB12_HINT.hotel]: 'Katlara tek bir asansör hizmet eder. Kapılar zil sesinden 3 sn sonra kapanır. Panelde bir kat eksik: merdiveni bul.',
  'ECHO': 'YANKI',
  'Knock [M]': 'Kapıyı çal [M]',
  'ready': 'hazır',
  'Floor': 'Kat',
  'Up': 'Yukarı',
  'Down': 'Aşağı',
  'Call the elevator [E]': 'Asansörü çağır [E]',
  'Doors closing... step in or wait for the next car.': 'Kapılar kapanıyor... bin ya da sıradaki asansörü bekle.',
  'The car left without you. Call it back.': 'Asansör sensiz gitti. Geri çağır.',
  'The elevator motor echoes through the lobby.': 'Asansör motorunun sesi lobide yankılanıyor.',
  'DO NOT DISTURB': 'RAHATSIZ ETMEYİN',
  'Unlock the room with a master key [E]': 'Odanın kilidini ana anahtarla aç [E]',
  'Locked': 'Kilitli',
  'Needs a master key': 'Ana anahtar gerekir',
  'Room': 'Oda',
  'Floor 13: the button was never installed.': '13. kat: düğmesi hiç takılmamış.',
};
export const RU = {
  'The Dark Web': 'Тёмная сеть',
  'No lamps, no signal, no mercy. Knock to see the tunnels, and everything down here hears you knock.': 'Ни ламп, ни сигнала, ни пощады. Постучи, чтобы увидеть туннели, но всё здесь услышит твой стук.',
  'The Overload Hotel': 'Отель «Перегрузка»',
  'Check in any time. One elevator, one missing floor and a lot of doors that say DO NOT DISTURB.': 'Заселяйтесь в любое время. Один лифт, один пропавший этаж и множество дверей с табличкой «НЕ БЕСПОКОИТЬ».',
  [LAB12_HINT.darkweb]: 'Кромешная тьма. Нажми M, чтобы постучать: сонар покажет туннели, но всё вокруг услышит. Бег и громкие звуки тоже дают импульс.',
  [LAB12_HINT.hotel]: 'Этажи обслуживает один лифт. Двери закрываются через 3 с после сигнала. На панели не хватает этажа: найди лестницу.',
  'ECHO': 'ЭХО',
  'Knock [M]': 'Постучать [M]',
  'ready': 'готово',
  'Floor': 'Этаж',
  'Up': 'Вверх',
  'Down': 'Вниз',
  'Call the elevator [E]': 'Вызвать лифт [E]',
  'Doors closing... step in or wait for the next car.': 'Двери закрываются... входи или жди следующую кабину.',
  'The car left without you. Call it back.': 'Кабина уехала без тебя. Вызови её обратно.',
  'The elevator motor echoes through the lobby.': 'Гул лифтового мотора разносится по вестибюлю.',
  'DO NOT DISTURB': 'НЕ БЕСПОКОИТЬ',
  'Unlock the room with a master key [E]': 'Открыть номер мастер-ключом [E]',
  'Locked': 'Закрыто',
  'Needs a master key': 'Нужен мастер-ключ',
  'Room': 'Номер',
  'Floor 13: the button was never installed.': '13-й этаж: кнопку так и не установили.',
};
