// LCMONSTERS wave 8 - Turkish + Russian strings (keys = the English text used with t() / tf() / registerCreature / registerItem / IDENT).
export const TR = {
  "Blood Witch": "Kan Cadısı",
  "Lantern Keeper": "Fener Bekçisi",
  "Trick-or-Treater": "Şeker mi Şaka mı",
  "Rift Stalker": "Yarık Avcısı",
  "Loot Mimic": "Taklitçi Ganimet",
  "Masked": "Maskeli",
  "was hexed by the Blood Witch.": "Kan Cadısı tarafından lanetlendi.",
  "was marked by the Lantern Keeper.": "Fener Bekçisi tarafından işaretlendi.",
  "was tricked.": "kandırıldı.",
  "was dragged through the rift.": "yarıktan içeri çekildi.",
  "was bitten by a Loot Mimic.": "bir Taklitçi Ganimet tarafından ısırıldı.",
  "was hugged by a Masked.": "bir Maskeli tarafından sarıldı.",
  "A dusk streamer who never goes offline. She paints a blood circle around herself and stares. Stand in the circle while she can see you and the curse lands: you bleed. Break her line of sight (rocks, the ship, trees) and it fades.": "Hiç çevrimdışı olmayan bir alacakaranlık yayıncısı. Etrafına kandan bir daire çizer ve bakar. Daire içindeyken seni görürse lanet işler: kanarsın. Görüş hattını kes (kayalar, gemi, ağaçlar) ve lanet solar.",
  "Patrols the dark halls with a lit lantern. Its light does not hurt: it MARKS you, and everything nearby comes to look. Slip behind it and snatch the lantern (E) or smash it for a fat payout.": "Karanlık koridorlarda yanan bir fenerle devriye gezer. Işığı acıtmaz: seni İŞARETLER ve yakındaki her şey bakmaya gelir. Arkasına sıvış ve feneri kap (E) ya da kır, güzel bir ödül var.",
  "Knocks three times, then shuffles up holding a bucket. Take the treat (E) and it is a gamble: loot or credits... or a trick. Walking away is free.": "Üç kez kapı çalar, sonra elinde kovayla yaklaşır. İkramı al (E): kumar bu; ganimet ya da kredi... ya da bir şaka. Uzaklaşmak bedava.",
  "Steps out of the wall when the lights blink RUN. The lights flicker when it is near. Its petal face opens half a second before it bites: that is your window.": "Işıklar RUN diye yanıp sönünce duvardan çıkar. Yakındayken ışıklar titrer. Yaprak yüzü ısırmadan yarım saniye önce açılır: fırsatın bu.",
  "A scrap item that is not. It breathes and twitches when nobody grabs it. Grab it and it bites. Hit it first (or take a photo) to find out.": "Hurda olmayan bir hurda. Kimse tutmazken nefes alır ve seğirir. Tutarsan ısırır. Öğrenmek için önce vur (ya da fotoğrafını çek).",
  "A crewmate in the Company suit wearing a fan mask, walking slowly toward you with its arms out. Its grip is escapable (mash JUMP). If it finishes you, you wear the mask next.": "Şirket tulumlu, hayran maskeli bir mürettebat üyesi; kollarını açıp yavaşça sana yürür. Kavrayışından kurtulunabilir (ZIPLA'ya bas). Seni bitirirse sıradaki maskeli sen olursun.",
  "Keeper Lantern": "Bekçi Feneri",
  "Still warm. Pays well.": "Hâlâ sıcak. İyi öder.",
  "Mimic Fang": "Taklitçi Dişi",
  "It bit back. It sells.": "Karşılık verdi. Satılır.",
  "Fan Mask (smile)": "Hayran Maskesi (gülen)",
  "Fan Mask (cry)": "Hayran Maskesi (ağlayan)",
  "A streamer fan mask. It giggles. Carry it too long and it calls a friend.": "Bir yayıncı hayran maskesi. Kıkırdar. Çok uzun taşırsan bir arkadaşını çağırır.",
  "A streamer fan mask. It weeps. Carry it too long and it calls a friend.": "Bir yayıncı hayran maskesi. Ağlar. Çok uzun taşırsan bir arkadaşını çağırır.",
  "Her circle only works while she can see you. Break line of sight (rock, ship, tree).": "Dairesi ancak seni görürken işler. Görüş hattını kes (kaya, gemi, ağaç).",
  "Its light only marks you. Circle behind it and snatch the lantern (E) for loot.": "Işığı sadece seni işaretler. Arkasına dolan ve feneri kap (E), ganimet var.",
  "Harmless until you take the treat. Walking away is free.": "İkramı almadıkça zararsız. Uzaklaşmak bedava.",
  "Lights flicker when it is near. Its petals open 0.5 s before the bite.": "Yakındayken ışıklar titrer. Yaprakları ısırmadan 0,5 sn önce açılır.",
  "Loot that breathes and twitches. Hit it first, or photograph it.": "Nefes alan ve seğiren ganimet. Önce vur ya da fotoğrafını çek.",
  "Slow. Mash JUMP to break its grip. If it finishes you, you wear the mask.": "Yavaş. Kavrayışından kurtulmak için ZIPLA'ya bas. Seni bitirirse maskeyi sen takarsın.",
  "CURSED: BLEEDING": "LANETLİ: KANAMA",
  "MARKED": "İŞARETLİ",
  "creatures can find you": "yaratıklar seni bulabilir",
  "HEAVY CURSE": "AĞIR LANET",
  "You move slower.": "Daha yavaş hareket edersin.",
  "WHISPERING CURSE": "FISILTI LANETİ",
  "It whispers behind you.": "Arkanda fısıldar.",
  "HUNGRY CURSE": "AÇ LANET",
  "Creatures are drawn to you.": "Yaratıklar sana çekilir.",
  "TWISTED CURSE": "BÜKÜLMÜŞ LANET",
  "Controls flip for a moment.": "Kontroller bir an ters döner.",
  "THE MASK IS WARM": "MASKE SICAK",
  "The Blood Witch cursed you: you are bleeding. Break her line of sight!": "Kan Cadısı seni lanetledi: kanıyorsun. Görüş hattını kes!",
  "The lantern MARKED you. Everything nearby can find you.": "Fener seni İŞARETLEDİ. Yakındaki her şey seni bulabilir.",
  "You snatched the Keeper's lantern!": "Bekçinin fenerini kaptın!",
  "The mask is warm. It is watching you. Sell it or drop it.": "Maske sıcak. Seni izliyor. Sat ya da bırak.",
  "The mask called a friend.": "Maske bir arkadaşını çağırdı.",
  "The curse is lifted (-{n} credits).": "Lanet kalktı (-{n} kredi).",
  "Everything is backwards!": "Her şey ters!",
  "TREAT: +{n} credits!": "İKRAM: +{n} kredi!",
  "TREAT: a piece of loot!": "İKRAM: bir parça ganimet!",
  "TRICK: you were sent somewhere else!": "ŞAKA: başka bir yere gönderildin!",
  "TRICK: bugs!": "ŞAKA: böcekler!",
  "TRICK: your hands went numb!": "ŞAKA: ellerin uyuştu!",
  "TRICK: static!": "ŞAKA: parazit!",
  "TRICK!": "ŞAKA!",
  "Stay out of her circle while she can see you. Break line of sight.": "Seni görürken dairesinden uzak dur. Görüş hattını kes.",
  "Its light marks you for everything nearby. Get behind it and snatch the lantern.": "Işığı seni yakındaki her şeye işaretler. Arkasına geç ve feneri kap.",
  "Take the treat (E) and it is a gamble. Walking away is free.": "İkramı al (E): kumar bu. Uzaklaşmak bedava.",
  "It came through the wall. The lights flicker when it is close.": "Duvardan geçti. Yakınken ışıklar titrer.",
  "That scrap was breathing. Hit things before you grab them.": "O hurda nefes alıyordu. Tutmadan önce vur.",
  "Slow, arms out. Mash JUMP to break the hug. Do not let it finish you.": "Yavaş, kolları açık. Sarılmadan kurtulmak için ZIPLA'ya bas. Seni bitirmesine izin verme.",
  "Snatch the lantern [E]": "Feneri kap [E]",
  "Get behind it to snatch the lantern": "Feneri kapmak için arkasına geç",
  "It will shove you off": "Seni itecek",
  "Take the treat [E]": "İkramı al [E]",
  "Treat 55% / trick 45%": "İkram %55 / şaka %45",
  "Purge the curse (-{n} credits) [E]": "Laneti temizle (-{n} kredi) [E]",
  "Keeps most of the extra value": "Fazla değerin çoğunu korur",
  "something whispers": "bir şey fısıldıyor",
  "Not enough credits to purge the curse.": "Laneti temizlemeye yetecek kredi yok.",
};
export const RU = {
  "Blood Witch": "Кровавая ведьма",
  "Lantern Keeper": "Хранитель фонаря",
  "Trick-or-Treater": "Сладость или гадость",
  "Rift Stalker": "Охотник из разлома",
  "Loot Mimic": "Мимик-добыча",
  "Masked": "Маскированный",
  "was hexed by the Blood Witch.": "был проклят Кровавой ведьмой.",
  "was marked by the Lantern Keeper.": "был помечен Хранителем фонаря.",
  "was tricked.": "был обманут.",
  "was dragged through the rift.": "был утащен в разлом.",
  "was bitten by a Loot Mimic.": "был укушен мимиком-добычей.",
  "was hugged by a Masked.": "был обнят Маскированным.",
  "A dusk streamer who never goes offline. She paints a blood circle around herself and stares. Stand in the circle while she can see you and the curse lands: you bleed. Break her line of sight (rocks, the ship, trees) and it fades.": "Закатная стримерша, которая никогда не уходит в офлайн. Рисует вокруг себя кровавый круг и смотрит. Если ты в круге и она тебя видит, ложится проклятие: ты истекаешь кровью. Разорви линию взгляда (камни, корабль, деревья), и оно исчезнет.",
  "Patrols the dark halls with a lit lantern. Its light does not hurt: it MARKS you, and everything nearby comes to look. Slip behind it and snatch the lantern (E) or smash it for a fat payout.": "Патрулирует тёмные залы с зажжённым фонарём. Свет не ранит: он ПОМЕЧАЕТ тебя, и всё вокруг приходит посмотреть. Зайди за спину и выхвати фонарь (E) или разбей его ради жирной награды.",
  "Knocks three times, then shuffles up holding a bucket. Take the treat (E) and it is a gamble: loot or credits... or a trick. Walking away is free.": "Стучит три раза, затем подходит с ведёрком. Возьми угощение (E): это азартная игра, добыча или кредиты... или проказа. Уйти можно бесплатно.",
  "Steps out of the wall when the lights blink RUN. The lights flicker when it is near. Its petal face opens half a second before it bites: that is your window.": "Выходит из стены, когда свет мигает RUN. Рядом с ним свет мерцает. Лепестковое лицо раскрывается за полсекунды до укуса: это твой шанс.",
  "A scrap item that is not. It breathes and twitches when nobody grabs it. Grab it and it bites. Hit it first (or take a photo) to find out.": "Хлам, который не хлам. Дышит и подёргивается, пока его не трогают. Схватишь, и он укусит. Сначала ударь (или сфотографируй), чтобы проверить.",
  "A crewmate in the Company suit wearing a fan mask, walking slowly toward you with its arms out. Its grip is escapable (mash JUMP). If it finishes you, you wear the mask next.": "Член экипажа в костюме Компании и маске фаната медленно идёт к тебе с раскинутыми руками. Из хватки можно вырваться (жми ПРЫЖОК). Если он добьёт тебя, следующей маску наденешь ты.",
  "Keeper Lantern": "Фонарь хранителя",
  "Still warm. Pays well.": "Ещё тёплый. Хорошо платят.",
  "Mimic Fang": "Клык мимика",
  "It bit back. It sells.": "Он укусил в ответ. Продаётся.",
  "Fan Mask (smile)": "Маска фаната (улыбка)",
  "Fan Mask (cry)": "Маска фаната (плач)",
  "A streamer fan mask. It giggles. Carry it too long and it calls a friend.": "Маска фаната стримера. Хихикает. Носи слишком долго, и она позовёт друга.",
  "A streamer fan mask. It weeps. Carry it too long and it calls a friend.": "Маска фаната стримера. Плачет. Носи слишком долго, и она позовёт друга.",
  "Her circle only works while she can see you. Break line of sight (rock, ship, tree).": "Её круг работает, только пока она тебя видит. Разорви линию взгляда (камень, корабль, дерево).",
  "Its light only marks you. Circle behind it and snatch the lantern (E) for loot.": "Его свет лишь помечает тебя. Зайди за спину и выхвати фонарь (E) ради добычи.",
  "Harmless until you take the treat. Walking away is free.": "Безвредна, пока не возьмёшь угощение. Уйти можно бесплатно.",
  "Lights flicker when it is near. Its petals open 0.5 s before the bite.": "Рядом с ним свет мерцает. Лепестки раскрываются за 0,5 с до укуса.",
  "Loot that breathes and twitches. Hit it first, or photograph it.": "Добыча, которая дышит и подёргивается. Сначала ударь или сфотографируй.",
  "Slow. Mash JUMP to break its grip. If it finishes you, you wear the mask.": "Медленный. Жми ПРЫЖОК, чтобы вырваться. Если он добьёт тебя, маску наденешь ты.",
  "CURSED: BLEEDING": "ПРОКЛЯТИЕ: КРОВОТЕЧЕНИЕ",
  "MARKED": "ПОМЕЧЕН",
  "creatures can find you": "существа могут тебя найти",
  "HEAVY CURSE": "ТЯЖЁЛОЕ ПРОКЛЯТИЕ",
  "You move slower.": "Ты двигаешься медленнее.",
  "WHISPERING CURSE": "ШЁПОТ ПРОКЛЯТИЯ",
  "It whispers behind you.": "Оно шепчет за спиной.",
  "HUNGRY CURSE": "ГОЛОДНОЕ ПРОКЛЯТИЕ",
  "Creatures are drawn to you.": "Существа тянутся к тебе.",
  "TWISTED CURSE": "ИЗВРАЩЁННОЕ ПРОКЛЯТИЕ",
  "Controls flip for a moment.": "Управление на миг переворачивается.",
  "THE MASK IS WARM": "МАСКА ТЁПЛАЯ",
  "The Blood Witch cursed you: you are bleeding. Break her line of sight!": "Кровавая ведьма прокляла тебя: ты истекаешь кровью. Разорви линию взгляда!",
  "The lantern MARKED you. Everything nearby can find you.": "Фонарь ПОМЕТИЛ тебя. Всё вокруг может тебя найти.",
  "You snatched the Keeper's lantern!": "Ты выхватил фонарь хранителя!",
  "The mask is warm. It is watching you. Sell it or drop it.": "Маска тёплая. Она смотрит на тебя. Продай или брось её.",
  "The mask called a friend.": "Маска позвала друга.",
  "The curse is lifted (-{n} credits).": "Проклятие снято (-{n} кредитов).",
  "Everything is backwards!": "Всё наоборот!",
  "TREAT: +{n} credits!": "УГОЩЕНИЕ: +{n} кредитов!",
  "TREAT: a piece of loot!": "УГОЩЕНИЕ: кусок добычи!",
  "TRICK: you were sent somewhere else!": "ПРОКАЗА: тебя отправили в другое место!",
  "TRICK: bugs!": "ПРОКАЗА: жуки!",
  "TRICK: your hands went numb!": "ПРОКАЗА: руки онемели!",
  "TRICK: static!": "ПРОКАЗА: помехи!",
  "TRICK!": "ПРОКАЗА!",
  "Stay out of her circle while she can see you. Break line of sight.": "Не стой в её круге, пока она тебя видит. Разорви линию взгляда.",
  "Its light marks you for everything nearby. Get behind it and snatch the lantern.": "Его свет помечает тебя для всех рядом. Зайди за спину и выхвати фонарь.",
  "Take the treat (E) and it is a gamble. Walking away is free.": "Возьми угощение (E): это азарт. Уйти можно бесплатно.",
  "It came through the wall. The lights flicker when it is close.": "Оно пришло сквозь стену. Рядом с ним свет мерцает.",
  "That scrap was breathing. Hit things before you grab them.": "Этот хлам дышал. Бей, прежде чем хватать.",
  "Slow, arms out. Mash JUMP to break the hug. Do not let it finish you.": "Медленный, руки вперёд. Жми ПРЫЖОК, чтобы вырваться. Не дай ему добить тебя.",
  "Snatch the lantern [E]": "Выхватить фонарь [E]",
  "Get behind it to snatch the lantern": "Зайди за спину, чтобы выхватить фонарь",
  "It will shove you off": "Он оттолкнёт тебя",
  "Take the treat [E]": "Взять угощение [E]",
  "Treat 55% / trick 45%": "Угощение 55% / проказа 45%",
  "Purge the curse (-{n} credits) [E]": "Снять проклятие (-{n} кредитов) [E]",
  "Keeps most of the extra value": "Сохраняет большую часть надбавки",
  "something whispers": "что-то шепчет",
  "Not enough credits to purge the curse.": "Не хватает кредитов, чтобы снять проклятие.",
};
