// LOOP11 strings (wave 11, "THE LOOP"): English is the key, Turkish + Russian below. Registered with addTranslations() at install.
// Voice: the company's HR department, cheerful and legally unaccountable.

// ---- canvas texts (drawn on posters / signs, upper-cased with upperT at build time)
export const RULES = [
  'EMPLOYEE RE-ONBOARDING',
  '1. IF YOU NOTICE ANYTHING DIFFERENT, TURN BACK.',
  '2. IF NOTHING IS DIFFERENT, KEEP GOING.',
  '3. REACH EXIT 8.',
  'HR is not liable for anything you notice.',
];
export const NOTICE_BASE = ['NOTICE', 'Please wash your hands', 'Please smile at the cameras', 'The stairs are not an exit'];
// [line index to replace (1..3, 0 = any), replacement]
export const NOTICE_ALT = [[1, 'Please watch your hands'], [2, 'Please frown at the cameras'], [3, 'The stairs are an exit'], [2, 'We can hear you breathing'], [1, 'Please do not turn back'], [3, 'Somebody is still in here']];
export const POSTERS = ['Clock in. Clock out. Never clock off.', 'Report suspicious colleagues', 'Smile. The cameras are always on.'];
export const MASCOT = ['KIP THE KEFAL SAYS:', 'WE ARE ALL FAMILY HERE!'];
export const DOOR_NUMS = ['101', '102', '103', '104'];
export const DOOR_ALT = ['108', '1O3', '013', '404', '666', '110', '182', '162'];

// ---- anomaly catalogue (name + how to spot it), shown in the handbook tab and in the result toasts
export const ANOM_TEXT = {
  eyes: ['The Mascot Watches', 'Kip the Kefal has eyes on the poster. They are meant to stare straight ahead.'],
  doornum: ['Wrong Room Number', 'One office plaque reads a number that does not belong to the row.'],
  coworker: ['Extra Colleague', 'A colleague nobody hired stands at the end of the hall. He turns when you look away.'],
  breath: ['Breathing Lights', 'The ceiling lights swell and fade, slowly, as if the building were asleep.'],
  notice: ['Amended Notice', 'The notice board says something it did not say before.'],
  wetsign: ['Relocated Sign', 'The yellow wet floor sign is not where it stood.'],
  extinguisher: ['Upside-Down Extinguisher', 'The fire extinguisher hangs the wrong way up.'],
  clock: ['Backwards Clock', 'The second hand of the wall clock runs the wrong way.'],
  steps: ['Footsteps Behind You', 'Something walks when you walk and waits when you wait.'],
  lowceil: ['Lowered Ceiling', 'Part of the ceiling is a little lower than it was.'],
  carpet: ['Stained Carpet', 'A dark, wet patch on the carpet. Facilities will hear about this.'],
  shadow: ['Unowned Shadow', 'A silhouette on the wall with nobody to cast it. It creeps closer while unwatched.'],
  posters: ['Missing Poster', 'One of the three safety posters is gone. A paler patch remains.'],
  cooler: ['Red Water Cooler', 'The water cooler is full of something that is not water. It gurgles.'],
  ajar: ['Door Ajar', 'An office door stands open a hand-width. A red light is on inside.'],
  ceileyes: ['Missing Ceiling Tile', 'A ceiling tile is missing. Something in the dark blinks.'],
  mirror: ['Mirrored Corridor', 'Everything on the walls is on the opposite wall. The writing reads backwards.'],
  exitred: ['Red Exit Sign', 'The exit sign at the end of the hall glows red instead of green.'],
};

// ---- HUD / prompts / toasts
export const HUD = {
  title: 'RE-ONBOARDING',
  strikes: 'STRIKES {w}/{max}',
  crew: 'THE CREW IS ONE EMPLOYEE',
  door: 'Open the door: Employee Re-Onboarding [E]',
  doorSub: 'A door that was not here yesterday. Somebody is asking you to come back to work.',
  doorSealed: 'Re-onboarding suspended. HR will contact you.',
  doorDone: 'Re-onboarding complete. Certificate on file.',
  leave: 'Use the staff exit [E]',
  leaveSub: 'The loop keeps your progress until the ship leaves.',
  back: 'Return to work [E]',
  intro: 'If you notice anything different, turn back. If nothing is different, keep going.',
  okBack: 'Correct: {name} turned back. It was: {an}. Exit {n}/{goal}.',
  okOn: 'Correct: {name} kept going. Nothing was different. Exit {n}/{goal}.',
  badOn: 'Wrong: {name} kept going. It was: {an}. Strike {w}/{max}.',
  badBack: 'Wrong: {name} turned back. Nothing was different. Strike {w}/{max}.',
  warn: 'HR: Your performance is being reviewed.',
  support: 'HR: Someone from Support has been sent to check on you.',
  fired: 'TERMINATED. Your badge has been deactivated. Please leave the premises.',
  win: 'EXIT 8. Onboarding complete. Please collect your certificate.',
  rewardTitle: 'BREAK ROOM',
  rewardSub: 'Employees of the Loop only',
  badge: 'Perfect Attendance Badge',
  badgeTip: 'Laminated. Signed by nobody. The photo is of you, but you do not remember it being taken.',
  handbook: 'Handbook',
  handbookHead: 'EMPLOYEE HANDBOOK, APPENDIX 8: ON NOTICING',
  handbookBody: 'Noticing is a core competency. Failing to notice is a performance issue. Noticing too much is a different kind of performance issue, handled by a different department.',
  handbookLocked: 'Reach exit 8 to receive this appendix.',
  handbookNone: 'Nothing on file. Identify an anomaly by turning back when one is present.',
  unknown: '???',
  seenN: 'spotted {n}x',
  wins: 'Certificates: {n}',
  sign: 'EXIT',
  doorPlaque: 'EMPLOYEE RE-ONBOARDING',
  staff: 'STAFF EXIT',
  rewardPoster: 'EMPLOYEE OF THE LOOP',
  rewardPoster2: 'Attendance: perfect. Sleep: not recorded.',
  fire: 'FIRE',
};

export const TR = {
  'EMPLOYEE RE-ONBOARDING': 'ÇALIŞAN YENİDEN İŞE UYUM',
  '1. IF YOU NOTICE ANYTHING DIFFERENT, TURN BACK.': '1. FARKLI BİR ŞEY GÖRÜRSEN GERİ DÖN.',
  '2. IF NOTHING IS DIFFERENT, KEEP GOING.': '2. FARKLI BİR ŞEY YOKSA DEVAM ET.',
  '3. REACH EXIT 8.': '3. 8 NUMARALI ÇIKIŞA ULAŞ.',
  'HR is not liable for anything you notice.': 'İK, fark ettiğin hiçbir şeyden sorumlu değildir.',
  'NOTICE': 'DUYURU', 'Please wash your hands': 'Lütfen ellerinizi yıkayın', 'Please smile at the cameras': 'Lütfen kameralara gülümseyin', 'The stairs are not an exit': 'Merdivenler çıkış değildir',
  'Please watch your hands': 'Lütfen ellerinizi izleyin', 'Please frown at the cameras': 'Lütfen kameralara kaş çatın', 'The stairs are an exit': 'Merdivenler bir çıkıştır',
  'We can hear you breathing': 'Nefes alışını duyabiliyoruz', 'Please do not turn back': 'Lütfen geri dönmeyin', 'Somebody is still in here': 'Burada hâlâ biri var',
  'Clock in. Clock out. Never clock off.': 'Giriş yap. Çıkış yap. Asla kapatma.', 'Report suspicious colleagues': 'Şüpheli iş arkadaşlarını bildirin', 'Smile. The cameras are always on.': 'Gülümse. Kameralar hep açık.',
  'KIP THE KEFAL SAYS:': 'KEFAL KİP DİYOR Kİ:', 'WE ARE ALL FAMILY HERE!': 'BURADA HEPİMİZ AİLEYİZ!',
  'The Mascot Watches': 'Maskot İzliyor', 'Kip the Kefal has eyes on the poster. They are meant to stare straight ahead.': 'Afişteki Kefal Kip’in gözleri düz ileri bakmalı.',
  'Wrong Room Number': 'Yanlış Oda Numarası', 'One office plaque reads a number that does not belong to the row.': 'Bir ofis tabelasında sıraya ait olmayan bir numara yazıyor.',
  'Extra Colleague': 'Fazladan Meslektaş', 'A colleague nobody hired stands at the end of the hall. He turns when you look away.': 'Koridorun sonunda kimsenin işe almadığı bir meslektaş duruyor. Sen bakmayınca dönüyor.',
  'Breathing Lights': 'Nefes Alan Işıklar', 'The ceiling lights swell and fade, slowly, as if the building were asleep.': 'Tavan ışıkları bina uyuyormuş gibi yavaşça parlıyor ve sönüyor.',
  'Amended Notice': 'Değiştirilmiş Duyuru', 'The notice board says something it did not say before.': 'Duyuru panosu daha önce yazmadığı bir şey söylüyor.',
  'Relocated Sign': 'Yeri Değişmiş Tabela', 'The yellow wet floor sign is not where it stood.': 'Sarı “Kaygan Zemin” tabelası durduğu yerde değil.',
  'Upside-Down Extinguisher': 'Ters Yangın Tüpü', 'The fire extinguisher hangs the wrong way up.': 'Yangın tüpü baş aşağı asılı.',
  'Backwards Clock': 'Geri Giden Saat', 'The second hand of the wall clock runs the wrong way.': 'Duvar saatinin akrebi ters yöne dönüyor.',
  'Footsteps Behind You': 'Arkandaki Ayak Sesleri', 'Something walks when you walk and waits when you wait.': 'Yürüyünce yürüyen, durunca bekleyen bir şey var.',
  'Lowered Ceiling': 'Alçalmış Tavan', 'Part of the ceiling is a little lower than it was.': 'Tavanın bir kısmı eskisinden biraz daha alçak.',
  'Stained Carpet': 'Lekeli Halı', 'A dark, wet patch on the carpet. Facilities will hear about this.': 'Halıda koyu, ıslak bir leke. Tesis yönetimi bunu duyacak.',
  'Unowned Shadow': 'Sahipsiz Gölge', 'A silhouette on the wall with nobody to cast it. It creeps closer while unwatched.': 'Duvarda onu düşüren kimsesi olmayan bir gölge. Bakılmayınca yaklaşıyor.',
  'Missing Poster': 'Kayıp Afiş', 'One of the three safety posters is gone. A paler patch remains.': 'Üç güvenlik afişinden biri yok. Yerinde soluk bir iz kalmış.',
  'Red Water Cooler': 'Kırmızı Su Sebili', 'The water cooler is full of something that is not water. It gurgles.': 'Su sebilinde su olmayan bir şey var. Gurulduyor.',
  'Door Ajar': 'Aralık Kapı', 'An office door stands open a hand-width. A red light is on inside.': 'Bir ofis kapısı bir karış aralık. İçeride kırmızı bir ışık yanıyor.',
  'Missing Ceiling Tile': 'Eksik Tavan Karosu', 'A ceiling tile is missing. Something in the dark blinks.': 'Bir tavan karosu eksik. Karanlıkta bir şey göz kırpıyor.',
  'Mirrored Corridor': 'Aynalı Koridor', 'Everything on the walls is on the opposite wall. The writing reads backwards.': 'Duvardaki her şey karşı duvarda. Yazılar ters okunuyor.',
  'Red Exit Sign': 'Kırmızı Çıkış Tabelası', 'The exit sign at the end of the hall glows red instead of green.': 'Koridor sonundaki çıkış tabelası yeşil yerine kırmızı yanıyor.',
  'RE-ONBOARDING': 'YENİDEN UYUM', 'STRIKES {w}/{max}': 'İHTAR {w}/{max}', 'THE CREW IS ONE EMPLOYEE': 'EKİP TEK BİR ÇALIŞANDIR',
  'Open the door: Employee Re-Onboarding [E]': 'Kapıyı aç: Çalışan Yeniden Uyum [E]',
  'A door that was not here yesterday. Somebody is asking you to come back to work.': 'Dün burada olmayan bir kapı. Biri işe geri dönmeni istiyor.',
  'Re-onboarding suspended. HR will contact you.': 'Yeniden uyum askıya alındı. İK sizinle iletişime geçecek.',
  'Re-onboarding complete. Certificate on file.': 'Yeniden uyum tamamlandı. Sertifika dosyada.',
  'Use the staff exit [E]': 'Personel çıkışını kullan [E]', 'The loop keeps your progress until the ship leaves.': 'Döngü, gemi kalkana kadar ilerlemeni saklar.',
  'Return to work [E]': 'İşe geri dön [E]',
  'If you notice anything different, turn back. If nothing is different, keep going.': 'Farklı bir şey görürsen geri dön. Farklı bir şey yoksa devam et.',
  'Correct: {name} turned back. It was: {an}. Exit {n}/{goal}.': 'Doğru: {name} geri döndü. Şuydu: {an}. Çıkış {n}/{goal}.',
  'Correct: {name} kept going. Nothing was different. Exit {n}/{goal}.': 'Doğru: {name} devam etti. Farklı bir şey yoktu. Çıkış {n}/{goal}.',
  'Wrong: {name} kept going. It was: {an}. Strike {w}/{max}.': 'Yanlış: {name} devam etti. Şuydu: {an}. İhtar {w}/{max}.',
  'Wrong: {name} turned back. Nothing was different. Strike {w}/{max}.': 'Yanlış: {name} geri döndü. Farklı bir şey yoktu. İhtar {w}/{max}.',
  'HR: Your performance is being reviewed.': 'İK: Performansınız değerlendiriliyor.',
  'HR: Someone from Support has been sent to check on you.': 'İK: Yanınıza Müşteri Desteğinden biri gönderildi.',
  'TERMINATED. Your badge has been deactivated. Please leave the premises.': 'İŞTEN ÇIKARILDINIZ. Kartınız devre dışı bırakıldı. Lütfen binayı terk edin.',
  'EXIT 8. Onboarding complete. Please collect your certificate.': 'ÇIKIŞ 8. Uyum tamamlandı. Lütfen sertifikanızı alın.',
  'BREAK ROOM': 'DİNLENME ODASI', 'Employees of the Loop only': 'Yalnızca Döngü Çalışanları',
  'Perfect Attendance Badge': 'Kusursuz Devam Rozeti', 'Laminated. Signed by nobody. The photo is of you, but you do not remember it being taken.': 'Laminasyonlu. Kimse imzalamamış. Fotoğraf senin ama çekildiğini hatırlamıyorsun.',
  'Handbook': 'El Kitabı', 'EMPLOYEE HANDBOOK, APPENDIX 8: ON NOTICING': 'ÇALIŞAN EL KİTABI, EK 8: FARK ETME ÜZERİNE',
  'Noticing is a core competency. Failing to notice is a performance issue. Noticing too much is a different kind of performance issue, handled by a different department.': 'Fark etmek temel bir yetkinliktir. Fark edememek bir performans sorunudur. Fazla fark etmek başka bir tür performans sorunudur ve başka bir departman ilgilenir.',
  'Reach exit 8 to receive this appendix.': 'Bu eki almak için 8 numaralı çıkışa ulaş.',
  'Nothing on file. Identify an anomaly by turning back when one is present.': 'Dosyada bir şey yok. Bir anomali varken geri dönerek onu tespit et.',
  '???': '???', 'spotted {n}x': '{n} kez tespit', 'Certificates: {n}': 'Sertifika: {n}',
  'EXIT': 'ÇIKIŞ', 'STAFF EXIT': 'PERSONEL ÇIKIŞI', 'EMPLOYEE OF THE LOOP': 'DÖNGÜNÜN ÇALIŞANI', 'Attendance: perfect. Sleep: not recorded.': 'Devam: kusursuz. Uyku: kayıtlı değil.', 'FIRE': 'YANGIN',
};

export const RU = {
  'EMPLOYEE RE-ONBOARDING': 'ПОВТОРНАЯ АДАПТАЦИЯ СОТРУДНИКА',
  '1. IF YOU NOTICE ANYTHING DIFFERENT, TURN BACK.': '1. ЕСЛИ ЗАМЕТИЛ ЧТО-ТО НЕ ТАК, ВОЗВРАЩАЙСЯ.',
  '2. IF NOTHING IS DIFFERENT, KEEP GOING.': '2. ЕСЛИ ВСЁ КАК ОБЫЧНО, ИДИ ДАЛЬШЕ.',
  '3. REACH EXIT 8.': '3. ДОЙДИ ДО ВЫХОДА 8.',
  'HR is not liable for anything you notice.': 'Отдел кадров не отвечает за то, что вы заметите.',
  'NOTICE': 'ОБЪЯВЛЕНИЕ', 'Please wash your hands': 'Пожалуйста, мойте руки', 'Please smile at the cameras': 'Пожалуйста, улыбайтесь камерам', 'The stairs are not an exit': 'Лестница не является выходом',
  'Please watch your hands': 'Пожалуйста, следите за руками', 'Please frown at the cameras': 'Пожалуйста, хмурьтесь камерам', 'The stairs are an exit': 'Лестница является выходом',
  'We can hear you breathing': 'Мы слышим, как вы дышите', 'Please do not turn back': 'Пожалуйста, не оборачивайтесь', 'Somebody is still in here': 'Здесь всё ещё кто-то есть',
  'Clock in. Clock out. Never clock off.': 'Отметься. Уйди. Не выключайся.', 'Report suspicious colleagues': 'Сообщайте о подозрительных коллегах', 'Smile. The cameras are always on.': 'Улыбнись. Камеры всегда включены.',
  'KIP THE KEFAL SAYS:': 'КЕФАЛЬ КИП ГОВОРИТ:', 'WE ARE ALL FAMILY HERE!': 'ЗДЕСЬ МЫ ВСЕ ОДНА СЕМЬЯ!',
  'The Mascot Watches': 'Маскот наблюдает', 'Kip the Kefal has eyes on the poster. They are meant to stare straight ahead.': 'У Кефаля Кипа на плакате глаза. Они должны смотреть прямо перед собой.',
  'Wrong Room Number': 'Неверный номер кабинета', 'One office plaque reads a number that does not belong to the row.': 'На одной из табличек номер, которому не место в ряду.',
  'Extra Colleague': 'Лишний коллега', 'A colleague nobody hired stands at the end of the hall. He turns when you look away.': 'В конце коридора стоит коллега, которого никто не нанимал. Он оборачивается, когда вы отводите взгляд.',
  'Breathing Lights': 'Дышащие лампы', 'The ceiling lights swell and fade, slowly, as if the building were asleep.': 'Потолочные лампы медленно разгораются и гаснут, будто здание спит.',
  'Amended Notice': 'Исправленное объявление', 'The notice board says something it did not say before.': 'На доске объявлений написано то, чего раньше там не было.',
  'Relocated Sign': 'Перемещённый знак', 'The yellow wet floor sign is not where it stood.': 'Жёлтый знак «Мокрый пол» стоит не там, где стоял.',
  'Upside-Down Extinguisher': 'Огнетушитель вверх ногами', 'The fire extinguisher hangs the wrong way up.': 'Огнетушитель висит вверх дном.',
  'Backwards Clock': 'Часы назад', 'The second hand of the wall clock runs the wrong way.': 'Секундная стрелка настенных часов идёт в обратную сторону.',
  'Footsteps Behind You': 'Шаги за спиной', 'Something walks when you walk and waits when you wait.': 'Что-то идёт, когда идёте вы, и ждёт, когда вы стоите.',
  'Lowered Ceiling': 'Опущенный потолок', 'Part of the ceiling is a little lower than it was.': 'Часть потолка стала немного ниже.',
  'Stained Carpet': 'Пятно на ковре', 'A dark, wet patch on the carpet. Facilities will hear about this.': 'Тёмное мокрое пятно на ковре. Хозотдел об этом узнает.',
  'Unowned Shadow': 'Бесхозная тень', 'A silhouette on the wall with nobody to cast it. It creeps closer while unwatched.': 'Силуэт на стене, которого никто не отбрасывает. Пока не смотришь, он подкрадывается.',
  'Missing Poster': 'Пропавший плакат', 'One of the three safety posters is gone. A paler patch remains.': 'Одного из трёх плакатов по безопасности нет. Остался бледный след.',
  'Red Water Cooler': 'Красный кулер', 'The water cooler is full of something that is not water. It gurgles.': 'В кулере не вода. Оно булькает.',
  'Door Ajar': 'Приоткрытая дверь', 'An office door stands open a hand-width. A red light is on inside.': 'Дверь кабинета приоткрыта на ладонь. Внутри горит красный свет.',
  'Missing Ceiling Tile': 'Нет потолочной плитки', 'A ceiling tile is missing. Something in the dark blinks.': 'Не хватает потолочной плитки. В темноте что-то моргает.',
  'Mirrored Corridor': 'Зеркальный коридор', 'Everything on the walls is on the opposite wall. The writing reads backwards.': 'Всё со стен висит на противоположной стене. Надписи читаются задом наперёд.',
  'Red Exit Sign': 'Красный указатель выхода', 'The exit sign at the end of the hall glows red instead of green.': 'Указатель выхода в конце коридора горит красным вместо зелёного.',
  'RE-ONBOARDING': 'ПОВТОРНАЯ АДАПТАЦИЯ', 'STRIKES {w}/{max}': 'ВЫГОВОРЫ {w}/{max}', 'THE CREW IS ONE EMPLOYEE': 'КОМАНДА — ОДИН СОТРУДНИК',
  'Open the door: Employee Re-Onboarding [E]': 'Открыть дверь: повторная адаптация [E]',
  'A door that was not here yesterday. Somebody is asking you to come back to work.': 'Вчера этой двери не было. Кто-то просит вас вернуться к работе.',
  'Re-onboarding suspended. HR will contact you.': 'Адаптация приостановлена. Отдел кадров свяжется с вами.',
  'Re-onboarding complete. Certificate on file.': 'Адаптация завершена. Сертификат в деле.',
  'Use the staff exit [E]': 'Служебный выход [E]', 'The loop keeps your progress until the ship leaves.': 'Петля хранит ваш прогресс, пока корабль не улетел.',
  'Return to work [E]': 'Вернуться к работе [E]',
  'If you notice anything different, turn back. If nothing is different, keep going.': 'Заметили что-то не то — возвращайтесь. Всё как обычно — идите дальше.',
  'Correct: {name} turned back. It was: {an}. Exit {n}/{goal}.': 'Верно: {name} вернулся. Это было: {an}. Выход {n}/{goal}.',
  'Correct: {name} kept going. Nothing was different. Exit {n}/{goal}.': 'Верно: {name} пошёл дальше. Ничего не изменилось. Выход {n}/{goal}.',
  'Wrong: {name} kept going. It was: {an}. Strike {w}/{max}.': 'Неверно: {name} пошёл дальше. Это было: {an}. Выговор {w}/{max}.',
  'Wrong: {name} turned back. Nothing was different. Strike {w}/{max}.': 'Неверно: {name} вернулся. Ничего не изменилось. Выговор {w}/{max}.',
  'HR: Your performance is being reviewed.': 'Отдел кадров: ваша эффективность на рассмотрении.',
  'HR: Someone from Support has been sent to check on you.': 'Отдел кадров: к вам направили сотрудника поддержки.',
  'TERMINATED. Your badge has been deactivated. Please leave the premises.': 'УВОЛЕНЫ. Ваш бейдж деактивирован. Покиньте помещение.',
  'EXIT 8. Onboarding complete. Please collect your certificate.': 'ВЫХОД 8. Адаптация завершена. Заберите сертификат.',
  'BREAK ROOM': 'КОМНАТА ОТДЫХА', 'Employees of the Loop only': 'Только для сотрудников Петли',
  'Perfect Attendance Badge': 'Бейдж идеальной посещаемости', 'Laminated. Signed by nobody. The photo is of you, but you do not remember it being taken.': 'Заламинирован. Никем не подписан. На фото вы, но вы не помните, чтобы вас снимали.',
  'Handbook': 'Справочник', 'EMPLOYEE HANDBOOK, APPENDIX 8: ON NOTICING': 'СПРАВОЧНИК СОТРУДНИКА, ПРИЛОЖЕНИЕ 8: О ВНИМАТЕЛЬНОСТИ',
  'Noticing is a core competency. Failing to notice is a performance issue. Noticing too much is a different kind of performance issue, handled by a different department.': 'Внимательность — ключевая компетенция. Невнимательность — проблема эффективности. Излишняя внимательность — проблема иного рода, ею занимается другой отдел.',
  'Reach exit 8 to receive this appendix.': 'Дойдите до выхода 8, чтобы получить это приложение.',
  'Nothing on file. Identify an anomaly by turning back when one is present.': 'В деле пусто. Опознайте аномалию, вернувшись, когда она есть.',
  '???': '???', 'spotted {n}x': 'замечено {n} р.', 'Certificates: {n}': 'Сертификатов: {n}',
  'EXIT': 'ВЫХОД', 'STAFF EXIT': 'СЛУЖЕБНЫЙ ВЫХОД', 'EMPLOYEE OF THE LOOP': 'СОТРУДНИК ПЕТЛИ', 'Attendance: perfect. Sleep: not recorded.': 'Посещаемость: идеальная. Сон: не зафиксирован.', 'FIRE': 'ОГОНЬ',
};
