// REPOMAPS strings (wave 8): Turkish + Russian for the four themed interiors (names, blurbs, signature mechanics, moon descriptions), their loot and the runtime toasts.
// English is the key. Registered by world/interiors/themes_studio.js at import, so the terminal moon list is translated before any module installs.
export const TR = {
  'Influencer Mansion': 'Fenomen Konağı',
  'Content Academy': 'İçerik Akademisi',
  'Cold Storage Data Station': 'Soğuk Depo Veri İstasyonu',
  'Museum of Deleted Content': 'Silinmiş İçerik Müzesi',
  'A gaudy estate the Algorithm repossessed. Ring lights, trophy rooms, sponsored vases. Everything is fragile and everything is watching.': 'Algoritmanın haczettiği gösterişli bir konak. Halka ışıklar, kupa odaları, sponsorlu vazolar. Her şey kırılgan ve her şey seni izliyor.',
  'Where the Algorithm trains streamers. Lecture halls, detention, a library that will not stay where you left it.': 'Algoritmanın yayıncı yetiştirdiği yer. Amfiler, ceza sınıfı ve bıraktığın yerde durmayan bir kütüphane.',
  'A snowed-in server outpost. Freezer halls, glass-smooth ice, sleepers in the cryo bay. Do not thaw anything.': 'Karla kaplı bir sunucu karakolu. Dondurucu koridorlar, cam gibi buz, kriyo bölmesinde uyuyanlar. Hiçbir şeyi çözdürme.',
  'Every banned post, framed and lit. Laser-grid corridors, glass cases, and art that screams when you bump it.': 'Yasaklanan her gönderi, çerçeveli ve aydınlatılmış. Lazer ızgaralı koridorlar, cam vitrinler ve çarpınca çığlık atan sanat.',
  'VIRAL loot grows in value while you carry it, fastest under the studio ring lights. Every bump resets the hype.': 'VİRAL ganimet taşırken değer kazanır, en hızlı stüdyo halka ışıklarının altında. Her çarpma heyecanı azaltır.',
  'Library shelves slide on rails: the bell warns, then they shift. Watch the floor rails and do not stand in the track.': 'Kütüphane rafları raylarda kayar: zil uyarır, sonra yer değiştirirler. Zemindeki raylara dikkat et, rayın üstünde durma.',
  'FROZEN loot thaws (loses value) in the warm rooms and outside. Freezer floors and ice halls are slippery.': 'DONMUŞ ganimet sıcak odalarda ve dışarıda çözülür (değer kaybeder). Dondurucu zeminleri ve buz salonları kaygandır.',
  'ART loot sets off the alarm when it is bumped or broken. Laser grids guard the corridors.': 'SANAT ganimeti çarpılınca ya da kırılınca alarmı çalıştırır. Koridorları lazer ızgaraları korur.',
  'A frozen yearbook page: the Algorithm trains its streamers here. Lecture halls, detention and a library that rearranges itself. Trolls hunt at night.': 'Donmuş bir yıllık sayfası: Algoritma yayıncılarını burada eğitir. Amfiler, ceza sınıfı ve kendini yeniden düzenleyen bir kütüphane. Troller geceleri avlanır.',
  'Black forest under a dead sun. Everything lives here, and the Museum of Deleted Content keeps the best of it framed behind laser grids. Do not bump the art.': 'Ölü bir güneşin altında kara orman. Her şey burada yaşar ve Silinmiş İçerik Müzesi en iyilerini lazer ızgaralarının ardında çerçeveli tutar. Sanata çarpma.',
  'Gold Ring Light': 'Altın Halka Işık', 'A ring light plated in gold. Its follower count climbs while you carry it. Do not trip.': 'Altın kaplama halka ışık. Taşırken takipçi sayısı artar. Sakın düşme.',
  'Diamond Play Button': 'Elmas Oynat Düğmesi', 'Ten million subscribers, one very sharp edge. Grows in value while carried.': 'On milyon abone, çok keskin bir kenar. Taşırken değer kazanır.',
  'Sponsored Champagne': 'Sponsorlu Şampanya', 'Not for drinking: it is a prop with a sponsor. Value grows while you carry it, until it pops.': 'İçilmez: sponsorlu bir dekor. Taşırken değer kazanır, patlayana kadar.',
  'Gold Toilet (Sponsored)': 'Altın Klozet (Sponsorlu)', 'Worth more the longer it trends. Hauling it is the hard part.': 'Ne kadar gündemde kalırsa o kadar değerli. Zor kısım onu taşımak.',
  'Antique Globe': 'Antika Küre', 'Every country on it is a deleted channel now.': 'Üstündeki her ülke artık silinmiş bir kanal.',
  'Spelling Bee Trophy': 'Heceleme Yarışması Kupası', 'First place, engagement category.': 'Birincilik, etkileşim kategorisi.',
  'Detention Inkwell': 'Ceza Hokkası', 'Sixty thousand lines written with it: I WILL POST DAILY.': 'Onunla altmış bin satır yazıldı: HER GÜN PAYLAŞACAĞIM.',
  'Lab Microscope': 'Laboratuvar Mikroskobu', 'Used to study engagement up close. Lenses crack easily.': 'Etkileşimi yakından incelemek için kullanılır. Merceği kolay çatlar.',
  'Anatomy Skeleton': 'Anatomi İskeleti', 'Class mascot. It loses bones when dropped, and value with them.': 'Sınıfın maskotu. Düşünce kemik kaybeder, değeri de onlarla.',
  'Frozen Data Drive': 'Donmuş Veri Sürücüsü', 'FROZEN: thaws (loses value) in warm rooms and outside. Keep it moving.': 'DONMUŞ: sıcak odalarda ve dışarıda çözülür (değer kaybeder). Hareket halinde kal.',
  'Cryo Vial': 'Kriyo Şişesi', "FROZEN: a sleeper's backup. Thaws fast, breaks faster.": 'DONMUŞ: bir uyuyanın yedeği. Çabuk çözülür, daha çabuk kırılır.',
  'Ice-Locked Blade': 'Buza Hapsolmuş Blade', 'FROZEN: a server blade sealed in ice. Slowly turns to water.': 'DONMUŞ: buza gömülü bir sunucu bıçağı. Yavaşça suya dönüşür.',
  'Chilled Core Stack': 'Soğutulmuş Çekirdek Yığını', 'FROZEN: a whole data core. Get it to the ship before it warms up.': 'DONMUŞ: koca bir veri çekirdeği. Isınmadan gemiye ulaştır.',
  'Banned Canvas': 'Yasaklı Tuval', 'ART: it shrieks when bumped. The museum notices.': 'SANAT: çarpılınca çığlık atar. Müze fark eder.',
  'Cancelled Bust': 'İptal Edilmiş Büst', 'ART: marble, and very cancelled. Setting it down hard sets off the alarm.': 'SANAT: mermer ve çok iptal edilmiş. Sert bırakırsan alarm çalar.',
  'Framed Deleted Post': 'Çerçeveli Silinmiş Gönderi', 'ART: 4 likes, 0 replies, permanently archived. Fragile glass.': 'SANAT: 4 beğeni, 0 yanıt, kalıcı arşivde. Kırılgan cam.',
  'The Last Meme (Sculpture)': 'Son Meme (Heykel)', 'ART: the final meme, cast in bronze. The alarm is very loud.': 'SANAT: bronza dökülmüş son meme. Alarmı çok gürültülü.',
  'CLASS BELL: the shelves are about to shift': 'DERS ZİLİ: raflar yer değiştirmek üzere',
  'EXHIBIT ALARM': 'SERGİ ALARMI', 'Something in the museum was bumped. Expect company.': 'Müzede bir şeye çarpıldı. Misafir bekle.',
};

export const RU = {
  'Influencer Mansion': 'Особняк инфлюенсера',
  'Content Academy': 'Академия контента',
  'Cold Storage Data Station': 'Станция холодного хранения данных',
  'Museum of Deleted Content': 'Музей удалённого контента',
  'A gaudy estate the Algorithm repossessed. Ring lights, trophy rooms, sponsored vases. Everything is fragile and everything is watching.': 'Кричащая усадьба, изъятая Алгоритмом. Кольцевые лампы, залы трофеев, спонсорские вазы. Всё хрупкое, и за тобой наблюдает всё.',
  'Where the Algorithm trains streamers. Lecture halls, detention, a library that will not stay where you left it.': 'Здесь Алгоритм обучает стримеров. Лекционные залы, кабинет наказаний и библиотека, которая не стоит на месте.',
  'A snowed-in server outpost. Freezer halls, glass-smooth ice, sleepers in the cryo bay. Do not thaw anything.': 'Заснеженный серверный форпост. Морозильные залы, гладкий как стекло лёд, спящие в крио-отсеке. Ничего не размораживай.',
  'Every banned post, framed and lit. Laser-grid corridors, glass cases, and art that screams when you bump it.': 'Каждый забаненный пост в рамке и подсветке. Коридоры с лазерными сетками, стеклянные витрины и искусство, которое кричит, если его задеть.',
  'VIRAL loot grows in value while you carry it, fastest under the studio ring lights. Every bump resets the hype.': 'ВИРУСНАЯ добыча дорожает, пока ты её несёшь, быстрее всего под кольцевыми лампами студии. Каждый удар сбивает хайп.',
  'Library shelves slide on rails: the bell warns, then they shift. Watch the floor rails and do not stand in the track.': 'Полки библиотеки ездят по рельсам: звонок предупреждает, потом они сдвигаются. Следи за рельсами на полу и не стой на пути.',
  'FROZEN loot thaws (loses value) in the warm rooms and outside. Freezer floors and ice halls are slippery.': 'ЗАМОРОЖЕННАЯ добыча оттаивает (теряет цену) в тёплых комнатах и снаружи. Полы морозилок и ледяные залы скользкие.',
  'ART loot sets off the alarm when it is bumped or broken. Laser grids guard the corridors.': 'ИСКУССТВО включает тревогу, если его задеть или разбить. Коридоры охраняют лазерные сетки.',
  'A frozen yearbook page: the Algorithm trains its streamers here. Lecture halls, detention and a library that rearranges itself. Trolls hunt at night.': 'Замёрзшая страница школьного альбома: здесь Алгоритм учит стримеров. Лекционные залы, наказания и библиотека, которая переставляет себя. Тролли охотятся ночью.',
  'Black forest under a dead sun. Everything lives here, and the Museum of Deleted Content keeps the best of it framed behind laser grids. Do not bump the art.': 'Чёрный лес под мёртвым солнцем. Здесь живёт всё, а Музей удалённого контента хранит лучшее в рамах за лазерными сетками. Не задевай искусство.',
  'Gold Ring Light': 'Золотая кольцевая лампа', 'A ring light plated in gold. Its follower count climbs while you carry it. Do not trip.': 'Кольцевая лампа с золотым напылением. Пока несёшь, число подписчиков растёт. Не споткнись.',
  'Diamond Play Button': 'Алмазная кнопка Play', 'Ten million subscribers, one very sharp edge. Grows in value while carried.': 'Десять миллионов подписчиков и очень острый край. Дорожает, пока её несут.',
  'Sponsored Champagne': 'Спонсорское шампанское', 'Not for drinking: it is a prop with a sponsor. Value grows while you carry it, until it pops.': 'Пить нельзя: это реквизит со спонсором. Цена растёт, пока несёшь, пока оно не лопнет.',
  'Gold Toilet (Sponsored)': 'Золотой унитаз (спонсорский)', 'Worth more the longer it trends. Hauling it is the hard part.': 'Чем дольше в тренде, тем дороже. Тащить его тяжелее всего.',
  'Antique Globe': 'Антикварный глобус', 'Every country on it is a deleted channel now.': 'Каждая страна на нём теперь удалённый канал.',
  'Spelling Bee Trophy': 'Кубок конкурса по правописанию', 'First place, engagement category.': 'Первое место в категории вовлечённости.',
  'Detention Inkwell': 'Чернильница наказаний', 'Sixty thousand lines written with it: I WILL POST DAILY.': 'Ею написано шестьдесят тысяч строк: Я БУДУ ПОСТИТЬ КАЖДЫЙ ДЕНЬ.',
  'Lab Microscope': 'Лабораторный микроскоп', 'Used to study engagement up close. Lenses crack easily.': 'Им изучают вовлечённость вблизи. Линзы легко трескаются.',
  'Anatomy Skeleton': 'Анатомический скелет', 'Class mascot. It loses bones when dropped, and value with them.': 'Талисман класса. Если уронить, теряет кости, а с ними и цену.',
  'Frozen Data Drive': 'Замороженный накопитель', 'FROZEN: thaws (loses value) in warm rooms and outside. Keep it moving.': 'ЗАМОРОЖЕНО: оттаивает (теряет цену) в тёплых комнатах и снаружи. Не задерживайся.',
  'Cryo Vial': 'Крио-ампула', "FROZEN: a sleeper's backup. Thaws fast, breaks faster.": 'ЗАМОРОЖЕНО: резервная копия спящего. Быстро тает, ещё быстрее бьётся.',
  'Ice-Locked Blade': 'Блейд во льду', 'FROZEN: a server blade sealed in ice. Slowly turns to water.': 'ЗАМОРОЖЕНО: серверный блейд, запаянный в лёд. Медленно превращается в воду.',
  'Chilled Core Stack': 'Охлаждённый стек ядра', 'FROZEN: a whole data core. Get it to the ship before it warms up.': 'ЗАМОРОЖЕНО: целое ядро данных. Доставь на корабль, пока оно не нагрелось.',
  'Banned Canvas': 'Запрещённый холст', 'ART: it shrieks when bumped. The museum notices.': 'ИСКУССТВО: визжит, если его задеть. Музей замечает.',
  'Cancelled Bust': 'Отменённый бюст', 'ART: marble, and very cancelled. Setting it down hard sets off the alarm.': 'ИСКУССТВО: мрамор, и очень отменённый. Резко поставишь, сработает тревога.',
  'Framed Deleted Post': 'Удалённый пост в рамке', 'ART: 4 likes, 0 replies, permanently archived. Fragile glass.': 'ИСКУССТВО: 4 лайка, 0 ответов, навечно в архиве. Хрупкое стекло.',
  'The Last Meme (Sculpture)': 'Последний мем (скульптура)', 'ART: the final meme, cast in bronze. The alarm is very loud.': 'ИСКУССТВО: последний мем, отлитый в бронзе. Тревога очень громкая.',
  'CLASS BELL: the shelves are about to shift': 'ЗВОНОК: полки сейчас сдвинутся',
  'EXHIBIT ALARM': 'ТРЕВОГА В ЭКСПОЗИЦИИ', 'Something in the museum was bumped. Expect company.': 'В музее что-то задели. Жди гостей.',
};
