// SHIFT11 strings (wave 11): the RECYCLE BIN labyrinth. English is the key; Turkish + Russian below. PA voice is the facility's automated announcer (the Algorithm's janitor).
export const PA_LINES = [
  'Sector {s} is marked for permanent deletion. Please remove your personal belongings. They will be deleted anyway.',
  'Storage is 98% full. The Algorithm is making room for you. Not with you.',
  'Your files are important to us. Sector {s} files are now being deleted.',
  'Recovery of sector {s} is a premium feature. You are not premium.',
  '"Are you sure?" has been answered on your behalf. Sector {s} is going.',
  'Reminder: the recycle bin is not a hiding place. Sector {s} is emptying.',
];
export const RESTORE_LINES = [
  'Sector {s} restored from the bin. Some items may be missing. Some items may be new.',
  'Sector {s} has been recovered. The Algorithm regrets nothing.',
];

export const TR = {
  'RECYCLE BIN': 'GERİ DÖNÜŞÜM KUTUSU',
  'EMPTYING RECYCLE BIN IN {n}': 'GERİ DÖNÜŞÜM KUTUSU {n} SANİYEDE BOŞALTILIYOR',
  'SECTOR {s}': 'BÖLGE {s}',
  'SECTOR {s} - {d} m': 'BÖLGE {s} - {d} m',
  'MARKED FOR DELETION': 'SİLİNMEK ÜZERE İŞARETLİ',
  'RESTORING': 'GERİ YÜKLENİYOR',
  '{n} passage(s) rerouting': '{n} geçit yeniden yönlendiriliyor',
  'DELETED: SECTOR {s}': 'SİLİNDİ: BÖLGE {s}',
  'Leave the sector or grab what you can. Doors will seal.': 'Bölgeyi terk et ya da alabildiğini kap. Kapılar kapanacak.',
  'SECTOR {s} DELETED': 'BÖLGE {s} SİLİNDİ',
  'Everything inside is gone.': 'İçindeki her şey gitti.',
  'SECTOR {s} RESTORED': 'BÖLGE {s} GERİ YÜKLENDİ',
  'Fresh items appeared.': 'Yeni eşyalar belirdi.',
  'You were caught in a deleted sector and got ejected.': 'Silinen bir bölgede yakalandın ve dışarı atıldın.',
  'Recycle Bin PA': 'Geri Dönüşüm Anonsu',
  'Sector {s} is marked for permanent deletion. Please remove your personal belongings. They will be deleted anyway.': 'Bölge {s} kalıcı silinmek üzere işaretlendi. Lütfen kişisel eşyalarınızı alın. Zaten silinecekler.',
  'Storage is 98% full. The Algorithm is making room for you. Not with you.': 'Depolama %98 dolu. Algoritma sana yer açıyor. Seninle değil.',
  'Your files are important to us. Sector {s} files are now being deleted.': 'Dosyalarınız bizim için önemli. Bölge {s} dosyaları şimdi siliniyor.',
  'Recovery of sector {s} is a premium feature. You are not premium.': 'Bölge {s} kurtarma özelliği premiumdur. Sen premium değilsin.',
  '"Are you sure?" has been answered on your behalf. Sector {s} is going.': '"Emin misiniz?" sorusu sizin adınıza yanıtlandı. Bölge {s} gidiyor.',
  'Reminder: the recycle bin is not a hiding place. Sector {s} is emptying.': 'Hatırlatma: geri dönüşüm kutusu saklanma yeri değildir. Bölge {s} boşaltılıyor.',
  'Sector {s} restored from the bin. Some items may be missing. Some items may be new.': 'Bölge {s} kutudan geri yüklendi. Bazı eşyalar eksik olabilir. Bazıları yeni olabilir.',
  'Sector {s} has been recovered. The Algorithm regrets nothing.': 'Bölge {s} kurtarıldı. Algoritma hiçbir şeyden pişman değil.',
  'the junk towers': 'çöp kuleleri',
};
export const RU = {
  'RECYCLE BIN': 'КОРЗИНА',
  'EMPTYING RECYCLE BIN IN {n}': 'ОЧИСТКА КОРЗИНЫ ЧЕРЕЗ {n}',
  'SECTOR {s}': 'СЕКТОР {s}',
  'SECTOR {s} - {d} m': 'СЕКТОР {s} - {d} м',
  'MARKED FOR DELETION': 'ПОМЕЧЕН НА УДАЛЕНИЕ',
  'RESTORING': 'ВОССТАНОВЛЕНИЕ',
  '{n} passage(s) rerouting': 'Проходов перестраивается: {n}',
  'DELETED: SECTOR {s}': 'УДАЛЁН: СЕКТОР {s}',
  'Leave the sector or grab what you can. Doors will seal.': 'Покиньте сектор или хватайте что успеете. Двери запечатаются.',
  'SECTOR {s} DELETED': 'СЕКТОР {s} УДАЛЁН',
  'Everything inside is gone.': 'Всё внутри пропало.',
  'SECTOR {s} RESTORED': 'СЕКТОР {s} ВОССТАНОВЛЕН',
  'Fresh items appeared.': 'Появились свежие предметы.',
  'You were caught in a deleted sector and got ejected.': 'Вас застало в удаляемом секторе и выбросило наружу.',
  'Recycle Bin PA': 'Оповещение Корзины',
  'Sector {s} is marked for permanent deletion. Please remove your personal belongings. They will be deleted anyway.': 'Сектор {s} помечен на безвозвратное удаление. Заберите личные вещи. Их всё равно удалят.',
  'Storage is 98% full. The Algorithm is making room for you. Not with you.': 'Хранилище заполнено на 98%. Алгоритм освобождает место для вас. Не вместе с вами.',
  'Your files are important to us. Sector {s} files are now being deleted.': 'Ваши файлы важны для нас. Файлы сектора {s} сейчас удаляются.',
  'Recovery of sector {s} is a premium feature. You are not premium.': 'Восстановление сектора {s} — премиум-функция. Вы не премиум.',
  '"Are you sure?" has been answered on your behalf. Sector {s} is going.': 'На вопрос «Вы уверены?» ответили за вас. Сектор {s} уходит.',
  'Reminder: the recycle bin is not a hiding place. Sector {s} is emptying.': 'Напоминание: корзина — не укрытие. Сектор {s} очищается.',
  'Sector {s} restored from the bin. Some items may be missing. Some items may be new.': 'Сектор {s} восстановлен из корзины. Часть предметов может отсутствовать. Часть может быть новой.',
  'Sector {s} has been recovered. The Algorithm regrets nothing.': 'Сектор {s} восстановлен. Алгоритм ни о чём не жалеет.',
  'the junk towers': 'башни хлама',
};
