// STEALTH wave 4 - player-facing strings: EN keys -> TR / RU (registered with addTranslations by game/stealth.js).
export const TR = {
  'The Listener': 'Dinleyici',
  'made one noise too many for The Listener.': 'Dinleyici için bir ses fazla çıkardı.',
  'It has no eyes and does not need them. It creeps slowly through the halls, head tilted, waiting. The moment it hears you it sprints to the sound. Walk and it hears you at 6 m, run and it hears you at 15 m. Sneak (Alt) and it walks right past. Walls and doors muffle you. Throw something to send it the other way.':
    'Gözü yok ve ihtiyacı da yok. Başı yana eğik, koridorlarda yavaşça sürünür ve bekler. Bir ses duyduğu an sese doğru koşar. Yürürsen 6 m, koşarsan 15 m öteden duyar. Sessiz yürürsen (Alt) yanından geçip gider. Duvarlar ve kapılar sesi boğar. Onu başka yöne yollamak için bir şey fırlat.',
  'Blind. Hears you at walk 6 m / sprint 15 m. Sneak (Alt) or throw something to lure it.': 'Kör. Yürürken 6 m, koşarken 15 m öteden duyar. Sessiz yürü (Alt) ya da bir şey fırlatıp onu oyala.',
  'NOISE': 'SES', 'SILENT': 'SESSİZ', 'QUIET': 'KISIK', 'STEADY': 'NORMAL', 'LOUD': 'GÜRÜLTÜ', 'SNEAKING': 'SESSİZ YÜRÜYÜŞ',
  'heard within ~{n} m': '~{n} m öteden duyulursun',
  'Sneak (quiet)': 'Sessiz yürü',
  'Noisemaker': 'Gürültü Yapıcı',
  'Throw it far away: it clatters and rings for 9 s. Sound-hunting creatures rush to the noise, so you can slip past.': 'Uzağa fırlat: 9 sn boyunca çıngırdar ve çalar. Ses avcısı yaratıklar gürültüye koşar, sen de fark edilmeden geçersin.',
  'The floor plates here look loose. Sneak across (hold Alt).': 'Buradaki zemin plakaları gevşek görünüyor. Sessizce geç (Alt basılı tut).',
  'The floor gives way!': 'Zemin çöktü!',
  'Release the latch [E]': 'Mandalı çek [E]',
  'Opens the shortcut for everyone': 'Kısayolu herkes için açar',
  'The latch is on the other side': 'Mandal öbür tarafta',
  'A latch clicks open somewhere in the facility.': 'Tesisin bir yerinde bir mandal tık diye açıldı.',
  'Sneaking': 'Sessiz yürüyüş',
  'Hold Alt (or crouch-walk with Ctrl) to move almost silently. You are slow, but stamina recovers while you sneak.': 'Neredeyse sessiz hareket etmek için Alt basılı tut (ya da Ctrl ile çömelerek yürü). Yavaşsın ama sessiz yürürken dayanıklılık dolar.',
  'Noise meter': 'Ses göstergesi',
  'The NOISE meter on the right shows how far a listening creature can hear you. Sprinting is loud, carpet is quiet, metal floors and water are loud.': 'Sağdaki SES göstergesi, dinleyen bir yaratığın seni ne kadar uzaktan duyabileceğini gösterir. Koşmak gürültülü, halı sessiz; metal zemin ve su gürültülü.',
  'The Listener has no eyes. It creeps slowly until it hears something, then it sprints to the sound. Stand still or sneak and it will walk right past.': 'Dinleyicinin gözü yok. Bir şey duyana kadar yavaş sürünür, sonra sese doğru koşar. Hareketsiz dur ya da sessiz yürü, yanından geçer gider.',
  'Web Crawlers': 'Ağ Sürüngenleri',
  'Web Crawlers follow noise too: a Crawler that lost you searches the last sound. Break away quietly.': 'Ağ Sürüngenleri de sesi takip eder: seni kaybeden sürüngen son sese bakar. Sessizce uzaklaş.',
  'Lures': 'Oyalayıcılar',
  'Throw an item, a bottle or a Noisemaker to pull sound-hunters away. Walls and closed doors muffle sound, so lure them through a door.': 'Ses avcılarını uzaklaştırmak için bir eşya, şişe ya da Gürültü Yapıcı fırlat. Duvarlar ve kapalı kapılar sesi boğar; onları bir kapının ardına çek.',
  'Creaky floors': 'Gıcırdayan zeminler',
  'Striped floor plates in maze dead ends are loose. Sneak over them or you drop through to another part of the facility.': 'Labirent çıkmazlarındaki çizgili zemin plakaları gevşektir. Üstlerinden sessiz geç, yoksa tesisin başka bir yerine düşersin.',
  'Latch doors': 'Mandallı kapılar',
  'A door that says LOCKED but has a control panel beside it opens from the other side. Find the far side and pull the latch.': 'KİLİTLİ yazan ama yanında bir kontrol paneli olan kapı öbür taraftan açılır. Uzak tarafı bul ve mandalı çek.',
};
export const RU = {
  'The Listener': 'Слушатель',
  'made one noise too many for The Listener.': 'слишком громко шумел рядом со Слушателем.',
  'It has no eyes and does not need them. It creeps slowly through the halls, head tilted, waiting. The moment it hears you it sprints to the sound. Walk and it hears you at 6 m, run and it hears you at 15 m. Sneak (Alt) and it walks right past. Walls and doors muffle you. Throw something to send it the other way.':
    'У него нет глаз, и они ему не нужны. Он медленно бредёт по коридорам, склонив голову, и ждёт. Услышав вас, он несётся на звук. Шагом он слышит вас за 6 м, бегом за 15 м. Крадитесь (Alt), и он пройдёт мимо. Стены и двери глушат звук. Бросьте что-нибудь, чтобы отправить его в другую сторону.',
  'Blind. Hears you at walk 6 m / sprint 15 m. Sneak (Alt) or throw something to lure it.': 'Слепой. Слышит шаг за 6 м, бег за 15 м. Крадитесь (Alt) или бросьте что-нибудь, чтобы отвлечь.',
  'NOISE': 'ШУМ', 'SILENT': 'ТИХО', 'QUIET': 'ТИШЕ', 'STEADY': 'ОБЫЧНО', 'LOUD': 'ГРОМКО', 'SNEAKING': 'КРАДЁМСЯ',
  'heard within ~{n} m': 'слышно за ~{n} м',
  'Sneak (quiet)': 'Красться (тихо)',
  'Noisemaker': 'Шумелка',
  'Throw it far away: it clatters and rings for 9 s. Sound-hunting creatures rush to the noise, so you can slip past.': 'Бросьте подальше: она гремит и звенит 9 с. Существа, охотящиеся на звук, бегут к шуму, а вы проскальзываете мимо.',
  'The floor plates here look loose. Sneak across (hold Alt).': 'Плиты пола здесь шатаются. Пройдите тихо (удерживайте Alt).',
  'The floor gives way!': 'Пол проваливается!',
  'Release the latch [E]': 'Отпереть защёлку [E]',
  'Opens the shortcut for everyone': 'Откроет короткий путь для всех',
  'The latch is on the other side': 'Защёлка с другой стороны',
  'A latch clicks open somewhere in the facility.': 'Где-то на объекте щёлкнула защёлка.',
  'Sneaking': 'Скрытность',
  'Hold Alt (or crouch-walk with Ctrl) to move almost silently. You are slow, but stamina recovers while you sneak.': 'Удерживайте Alt (или идите пригнувшись с Ctrl), чтобы двигаться почти бесшумно. Вы медленны, но выносливость восстанавливается.',
  'Noise meter': 'Шкала шума',
  'The NOISE meter on the right shows how far a listening creature can hear you. Sprinting is loud, carpet is quiet, metal floors and water are loud.': 'Шкала ШУМ справа показывает, с какого расстояния вас слышат. Бег громкий, ковёр тихий, металл и вода громкие.',
  'The Listener has no eyes. It creeps slowly until it hears something, then it sprints to the sound. Stand still or sneak and it will walk right past.': 'У Слушателя нет глаз. Он медленно ползёт, пока не услышит звук, затем мчится к нему. Стойте или крадитесь, и он пройдёт мимо.',
  'Web Crawlers': 'Веб-краулеры',
  'Web Crawlers follow noise too: a Crawler that lost you searches the last sound. Break away quietly.': 'Веб-краулеры тоже идут на шум: потеряв вас, краулер проверяет последний звук. Уходите тихо.',
  'Lures': 'Приманки',
  'Throw an item, a bottle or a Noisemaker to pull sound-hunters away. Walls and closed doors muffle sound, so lure them through a door.': 'Бросьте предмет, бутылку или Шумелку, чтобы увести охотников на звук. Стены и закрытые двери глушат шум: заманивайте через дверь.',
  'Creaky floors': 'Скрипящий пол',
  'Striped floor plates in maze dead ends are loose. Sneak over them or you drop through to another part of the facility.': 'Полосатые плиты в тупиках лабиринта шатаются. Пройдите тихо, иначе провалитесь в другую часть объекта.',
  'Latch doors': 'Двери с защёлкой',
  'A door that says LOCKED but has a control panel beside it opens from the other side. Find the far side and pull the latch.': 'Дверь с надписью ЗАПЕРТО и панелью рядом открывается с другой стороны. Найдите обратную сторону и отоприте защёлку.',
};
