// STUDIO text pass (wave 8, docs/wave8/studio.md): one-line flavour / usage tips for items that had none, [en, tr, ru].
// Voice: docs/wave8/studio_style.md (dry, in-universe, one idea per line, no exclamation marks).
export const ITEM_TIPS = {
  // ---- classic scrap
  bolt: ['Still blinking. Nobody knows what it is waiting for.', 'Hâlâ yanıp sönüyor. Neyi beklediğini kimse bilmiyor.', 'Всё ещё мигает. Никто не знает, чего оно ждёт.'],
  axle: ['Hot-swappable. Nobody remembers what it was swapped out of.', 'Sıcak takılabilir. Neyden söküldüğünü kimse hatırlamıyor.', 'Горячая замена. Откуда его сняли, никто не помнит.'],
  bell: ['Rings for nothing. Someone always looks.', 'Boş yere çalar. Yine de hep biri bakar.', 'Звонит просто так. Кто-нибудь всё равно смотрит.'],
  register: ['Every ding was a click nobody made.', 'Her ding, kimsenin atmadığı bir tıklamaydı.', 'Каждый звон был кликом, которого никто не делал.'],
  goldbar: ['Awarded at 100 subscribers. Eleven of them were the same person.', '100 abonede verilir. On biri aynı kişiydi.', 'Вручается за 100 подписчиков. Одиннадцать из них были одним человеком.'],
  duck: ['Explain your code to it. It has heard worse.', 'Kodunu ona anlat. Daha kötüsünü dinledi.', 'Расскажи ей свой код. Она слышала и хуже.'],
  robot: ['Answers every question with a confident guess.', 'Her soruya kendinden emin bir tahminle cevap verir.', 'На любой вопрос отвечает уверенной догадкой.'],
  lamp: ['Warm, slow, and the only thing here that never went viral.', 'Sıcak, yavaş, burada hiç viral olmamış tek şey.', 'Тёплая, медленная и единственная здесь, что не стала вирусной.'],
  canned: ['Best before: a decade ago. Still works.', 'Son kullanma tarihi: on yıl önce. Hâlâ işe yarıyor.', 'Годен до: десять лет назад. Всё ещё работает.'],
  figurine: ['Much wow. Very fragile.', 'Vay be. Çok kırılgan.', 'Вау. Очень хрупкая.'],
  mug: ['Never washed. Moderators call it seasoning.', 'Hiç yıkanmamış. Moderatörler ona baharat der.', 'Ни разу не мытая. Модераторы называют это приправой.'],
  teeth: ['Wind it up and it complains in Morse.', 'Kur, mors alfabesiyle şikâyet eder.', 'Заведи, и она пожалуется азбукой Морзе.'],
  airhorn: ['Legally a musical instrument in three sectors.', 'Üç sektörde yasal olarak müzik aleti sayılır.', 'В трёх секторах юридически считается музыкальным инструментом.'],
  clownhorn: ['One honk carries through walls. Use it on purpose.', 'Tek bir korna duvarların ötesine ulaşır. Bilerek çal.', 'Один гудок слышно сквозь стены. Используй с умом.'],
  painting: ['Do not look at it twice. Do not save it either.', 'İki kez bakma. Kaydetme de.', 'Не смотри дважды. И не сохраняй.'],
  pickles: ['Nobody knows who put these up. Nobody dares to open it.', 'Kimin koyduğu bilinmiyor. Kapağını açmaya da kimse cesaret edemiyor.', 'Кто их закатал, неизвестно. Открыть банку никто не решается.'],
  bottles: ['Six cans, zero regrets, one heartbeat.', 'Altı kutu, sıfır pişmanlık, tek bir kalp atışı.', 'Шесть банок, ноль сожалений, один пульс.'],
  trophy: ['Everyone gets one. It shows.', 'Herkese bir tane verilir. Belli de oluyor.', 'Достаётся каждому. Это заметно.'],
  perfume: ['Smells like a follower count.', 'Takipçi sayısı kokar.', 'Пахнет числом подписчиков.'],
  flask: ['The label says NOT WATER. Somebody was thorough.', 'Etikette SU DEĞİL yazıyor. Biri titiz davranmış.', 'На этикетке: НЕ ВОДА. Кто-то был обстоятелен.'],
  cog: ['Turned for years. Never finished loading.', 'Yıllarca döndü. Yüklemeyi hiç bitirmedi.', 'Крутилась годами. Так и не загрузилась.'],
  phone: ['One bar of signal, and it is not from a tower.', 'Bir çubuk sinyal var ve bir vericiden gelmiyor.', 'Одно деление сигнала, и не от вышки.'],
  pot: ['Someone was streaming a recipe. The stream outlived the cook.', 'Biri tarif yayınlıyordu. Yayın aşçıdan uzun yaşadı.', 'Кто-то вёл стрим с рецептом. Стрим пережил повара.'],
  steering: ['Force feedback still works. It always pulls left.', 'Kuvvet geri bildirimi hâlâ çalışıyor. Hep sola çekiyor.', 'Обратная связь ещё работает. Тянет всегда влево.'],
  tv: ['Warm to the touch. For one frame it shows your face.', 'Dokununca sıcak. Bir kare boyunca senin yüzünü gösteriyor.', 'Тёплый на ощупь. На один кадр показывает твоё лицо.'],
  magnify: ['Makes everything look bigger than it is.', 'Her şeyi olduğundan büyük gösterir.', 'Делает всё больше, чем оно есть.'],
  skull: ['It used to mean "dying of laughter". Now it just means dead.', 'Eskiden "gülmekten ölüyorum" demekti. Şimdi sadece ölü demek.', 'Раньше значило «умираю со смеху». Теперь просто «мёртв».'],
  ring: ['A tiny blue check set in gold. Worth more than its owner.', 'Altına gömülü küçük mavi bir tik. Sahibinden daha değerli.', 'Крошечная синяя галочка в золоте. Стоит дороже владельца.'],
  reactor: ['Still running. Still hungry. Carry it like a sleeping animal.', 'Hâlâ çalışıyor. Hâlâ aç. Uyuyan bir hayvan gibi taşı.', 'Всё ещё работает. Всё ещё голоден. Неси как спящего зверя.'],
  // ---- big valuables
  vase: ['A calm marble face in a sunset it was never in.', 'Hiç bulunmadığı bir gün batımında sakin bir mermer yüz.', 'Спокойное мраморное лицо на закате, которого не было.'],
  statue: ['Watches the door. Judges everyone who uses it.', 'Kapıyı izler. Kullanan herkesi yargılar.', 'Следит за дверью. Судит каждого, кто ею пользуется.'],
  amphora: ['Blow on the cartridge. It works on the third try.', 'Kartuşa üfle. Üçüncü denemede çalışır.', 'Подуй на картридж. Заработает с третьего раза.'],
  server: ['Forty units of other people\'s memories.', 'Kırk ünite, başkalarının anıları.', 'Сорок юнитов чужих воспоминаний.'],
  aquarium: ['The fish have swum the same loop since 1998.', 'Balıklar 1998\'den beri aynı döngüde yüzüyor.', 'Рыбки плавают по одному кругу с 1998 года.'],
  cryptorig: ['The fans scream so nobody forgets it is working.', 'Fanlar, çalıştığı unutulmasın diye çığlık atar.', 'Вентиляторы орут, чтобы никто не забыл, что он работает.'],
  pctower: ['Survived every upgrade cycle by hiding in a closet.', 'Her yükseltme döngüsünden bir dolapta saklanarak sağ çıktı.', 'Пережил все обновления, прячась в шкафу.'],
  // ---- dead-internet scrap
  floppies: ['1.44 MB each. Mostly homework and one confession.', 'Her biri 1,44 MB. Çoğu ödev, biri itiraf.', 'По 1,44 МБ каждая. В основном домашки и одно признание.'],
  modem: ['Screams to connect. You will get used to it.', 'Bağlanmak için çığlık atar. Alışırsın.', 'Кричит, чтобы соединиться. Привыкнешь.'],
  keyboard: ['Half the keys are worn blank. The angry half.', 'Tuşların yarısı silinmiş. Öfkeli yarısı.', 'Половина клавиш стёрта. Злая половина.'],
  vhs: ['Be kind, rewind. Nobody was kind.', 'Lütfen geri sarın. Kimse sarmadı.', 'Будьте добры, перемотайте. Никто не был добр.'],
  nftframe: ['An empty frame that cost more than a house.', 'Bir evden pahalıya alınmış boş bir çerçeve.', 'Пустая рамка, стоившая как дом.'],
  playbutton: ['Awarded for a million views. Nobody kept the receipts.', 'Bir milyon izlenme için verilir. Makbuzu kimse saklamadı.', 'Выдана за миллион просмотров. Чеки никто не сохранил.'],
  liketrophy: ['A thumbs-up cast in metal. It never lets go.', 'Metalden dökülmüş bir başparmak. Asla bırakmaz.', 'Большой палец, отлитый в металле. Никогда не отпускает.'],
  memecart: ['One joke, compressed until it stopped being funny.', 'Tek bir şaka; komik olmaktan çıkana kadar sıkıştırılmış.', 'Одна шутка, сжатая до тех пор, пока не перестала быть смешной.'],
  flipphone: ['Snaps shut with a satisfying click. Calls only come from the past.', 'Tatmin edici bir tıkla kapanır. Aramalar yalnızca geçmişten gelir.', 'Защёлкивается с приятным щелчком. Звонят только из прошлого.'],
  webcam: ['The little light is on. It was on when you found it.', 'Küçük ışık yanıyor. Bulduğunda da yanıyordu.', 'Огонёк горит. Горел и когда ты её нашёл.'],
  gamingchair: ['Reclines to a dangerous angle. Racing stripes: decorative.', 'Tehlikeli bir açıya kadar yatar. Yarış şeritleri: süs.', 'Откидывается на опасный угол. Гоночные полосы: для красоты.'],
  ringlight: ['Flatters everyone. Especially whatever hides in it.', 'Herkesi güzel gösterir. En çok da içinde saklananları.', 'Льстит всем. Особенно тем, кто в нём прячется.'],
  usbidol: ['Plug it in and it sings one song. Everyone knows which.', 'Tak, tek bir şarkı söyler. Hangisi olduğunu herkes bilir.', 'Воткни, и она споёт одну песню. Все знают какую.'],
  chainletter: ['Forward to ten people, or else. It is a very old else.', 'On kişiye ilet, yoksa. Çok eski bir yoksa bu.', 'Перешли десяти людям, иначе. Это очень старое «иначе».'],
  gpu: ['Runs hot. Runs hotter if you ask what for.', 'Hararetli çalışır. Ne için diye sorarsan daha da hararetli.', 'Греется. Греется сильнее, если спросить зачем.'],
  hdd: ['It made a sound before it stopped. Yours will too.', 'Durmadan önce bir ses çıkardı. Seninki de çıkaracak.', 'Перед остановкой издал звук. Твой тоже издаст.'],
  headset: ['Still whispers a teammate\'s callouts. Nobody is there.', 'Hâlâ bir takım arkadaşının çağrılarını fısıldıyor. Ortada kimse yok.', 'Всё ещё шепчет подсказки тиммейта. Рядом никого.'],
  cdspindle: ['Fifty blank discs and one labelled MUSIC (DO NOT PLAY).', 'Elli boş disk ve bir tanesinde MÜZİK (ÇALMA) yazıyor.', 'Пятьдесят чистых дисков и один с надписью МУЗЫКА (НЕ ВКЛЮЧАТЬ).'],
  pocketpet: ['Hungry since 1997. Somewhere, it still beeps.', '1997\'den beri aç. Bir yerlerde hâlâ bip sesi çıkarıyor.', 'Голоден с 1997 года. Где-то он всё ещё пищит.'],
  pager: ['One unread message: CALL BACK.', 'Okunmamış tek mesaj: GERİ ARA.', 'Одно непрочитанное сообщение: ПЕРЕЗВОНИ.'],
  captcha: ['Select all squares with a person. There are more than there should be.', 'İnsan içeren tüm kareleri seç. Olması gerekenden fazla var.', 'Выберите все квадраты с человеком. Их больше, чем должно быть.'],
  animefig: ['Sealed in its box. The box is the collectible.', 'Kutusunda mühürlü. Koleksiyon parçası kutunun kendisi.', 'Запечатана в коробке. Коллекционная вещь здесь коробка.'],
  printer: ['PC LOAD LETTER. Nobody ever learned what it means.', 'PC LOAD LETTER. Ne demek olduğunu kimse öğrenmedi.', 'PC LOAD LETTER. Что это значит, так никто и не узнал.'],
  motherboard: ['Everything used to plug into this. Everything remembers.', 'Eskiden her şey buna takılırdı. Her şey hatırlıyor.', 'Раньше всё подключалось к ней. Всё помнит.'],
  cryptocoin: ['Worth a house last Tuesday. Worth nothing by lunch.', 'Geçen salı bir ev ediyordu. Öğlene sıfırdı.', 'В прошлый вторник стоила дом. К обеду не стоила ничего.'],
  // ---- fish and creature drops
  fish_kefal: ['It is not who it says it is.', 'Söylediği kişi değil.', 'Не тот, за кого себя выдаёт.'],
  fish_lufer: ['Grew fast on borrowed metrics.', 'Ödünç metriklerle hızla büyüdü.', 'Быстро вырос на чужих метриках.'],
  fish_levrek: ['You will not believe how it tastes.', 'Tadına inanamayacaksın.', 'Вы не поверите, какой он на вкус.'],
  fish_golden: ['The one that got away. Twice.', 'Kaçan balık. İki kere.', 'Та, что ушла. Дважды.'],
  fish_boot: ['Technically a catch.', 'Teknik olarak bir av.', 'Технически улов.'],
  fish_eel: ['Renders in two places at once.', 'Aynı anda iki yerde render olur.', 'Рендерится сразу в двух местах.'],
  drop_scuttler: ['Still trying to sell you something.', 'Hâlâ sana bir şey satmaya çalışıyor.', 'Всё ещё пытается тебе что-то продать.'],
  drop_spider: ['Sticky, strong, and full of tracking cookies.', 'Yapışkan, sağlam ve takip çerezleriyle dolu.', 'Липкая, прочная и полная трекинговых куки.'],
  drop_crawler: ['Indexes everything it touches.', 'Dokunduğu her şeyi indeksler.', 'Индексирует всё, до чего дотронется.'],
  drop_hound: ['Do not feed. Do not reply.', 'Besleme. Cevap da verme.', 'Не кормить. Не отвечать.'],
  drop_lurker: ['Blank on purpose. It watched more than it posted.', 'Bilerek boş. Paylaştığından fazlasını izledi.', 'Пустая намеренно. Смотрел больше, чем писал.'],
  drop_giant: ['Whitened past all reason.', 'Akla sığmayacak kadar beyazlatılmış.', 'Отбелён сверх всякого разумения.'],
  // ---- starter gear (the store showed these with no description)
  flashlight: ['Standard issue. On loan; the battery is your problem.', 'Standart teçhizat. Ödünç; pil senin sorunun.', 'Стандартная выдача. Взят взаймы; батарейка твоя проблема.'],
  proflash: ['A brighter beam, a longer life. Shows more of what looks back.', 'Daha parlak ışık, daha uzun ömür. Sana bakan şeyleri daha iyi gösterir.', 'Луч ярче, работает дольше. Лучше показывает то, что смотрит в ответ.'],
  walkie: ['Keeps the crew on one channel. Mostly static, sometimes a voice.', 'Ekibi tek kanalda tutar. Çoğu parazit, ara sıra bir ses.', 'Держит команду на одном канале. В основном шум, иногда голос.'],
  boombox: ['Music soothes some creatures. The rest just hear you.', 'Müzik bazı yaratıkları yatıştırır. Gerisi sadece seni duyar.', 'Музыка успокаивает одних существ. Остальные просто слышат тебя.'],
  spraypaint: ['Mark doors, corners and the way back.', 'Kapıları, köşeleri ve dönüş yolunu işaretle.', 'Помечай двери, углы и путь назад.'],
  glowstick: ['Throw it down a corridor. Watch where it lands.', 'Koridora fırlat. Nereye düştüğüne bak.', 'Брось по коридору. Смотри, куда упадёт.'],
  rod: ['For ponds, docks and the occasional bad decision.', 'Göletler, iskeleler ve arada bir kötü karar için.', 'Для прудов, причалов и редких дурных решений.'],
  key: ['Opens a locked door. Single use in every sense.', 'Kilitli bir kapıyı açar. Her anlamda tek kullanımlık.', 'Открывает запертую дверь. Одноразовый во всех смыслах.'],
  lockpick: ['Three tries before it snaps. Patience is a consumable.', 'Kırılmadan önce üç deneme. Sabır bir sarf malzemesidir.', 'Три попытки до поломки. Терпение это расходник.'],
  jetpack: ['Two hands, one battery, no landing plan.', 'İki el, tek pil, iniş planı yok.', 'Две руки, одна батарея, плана посадки нет.'],
  stungrenade: ['Blinds and deafens everything nearby. You too, if you stay.', 'Yakındaki her şeyi kör ve sağır eder. Kalırsan sen de dahilsin.', 'Слепит и глушит всё рядом. Тебя тоже, если останешься.'],
  medkit: ['Restores a good chunk of health. Use it before you need it.', 'Sağlığını epey doldurur. İhtiyaç duymadan önce kullan.', 'Восстанавливает изрядно здоровья. Используй до того, как понадобится.'],
  adrenaline: ['A short burst of speed and stamina. The crash is scheduled.', 'Kısa süreli hız ve dayanıklılık. Çöküş de programda.', 'Короткий рывок скорости и выносливости. Откат уже запланирован.'],
  shells: ['Two per barrel. The Double Barrel is picky.', 'Namlu başına iki. Çifte çok seçici.', 'По два на ствол. Двустволка разборчива.'],
  pipe: ['Cheap, heavy, always within reach. The classic.', 'Ucuz, ağır, hep elinin altında. Klasik.', 'Дёшево, тяжело, всегда под рукой. Классика.'],
  shovel: ['Hold to swing harder. Digs too, in theory.', 'Basılı tut, daha sert vurur. Teoride kazar da.', 'Удерживай для сильного удара. В теории ещё и копает.'],
  stopsign: ['Arrives with authority. Works on most things that do not obey it.', 'Otoriteyle gelir. Uymayan çoğu şeyde işe yarar.', 'Приходит с авторитетом. Работает на большинство тех, кто не подчиняется.'],
  machete: ['Fast and light. Trades reach for tempo.', 'Hızlı ve hafif. Menzili tempo ile takas eder.', 'Быстрый и лёгкий. Меняет длину на темп.'],
  sledge: ['Slow, heavy, two hands. Knocks things a long way back.', 'Yavaş, ağır, iki el. Şeyleri çok uzağa savurur.', 'Медленная, тяжёлая, двуручная. Отбрасывает далеко.'],
  taser: ['Stuns from a distance. Bring spare batteries and a plan.', 'Uzaktan sersemletir. Yedek pil ve bir plan getir.', 'Оглушает издалека. Возьми запасные батарейки и план.'],
  harpoon: ['Long range, one throw of patience. For things that need reporting.', 'Uzun menzil, tek atışlık sabır. Rapor edilmesi gereken şeyler için.', 'Большая дальность, терпения на один бросок. Для того, о чём нужно сообщить.'],
  shotgun: ['Two shots, then reload. Everything hears both.', 'İki atış, sonra doldur. Her şey ikisini de duyar.', 'Два выстрела, потом перезарядка. Услышат оба.'],
};
