// Curated issued-equipment silhouettes. Existing wardrobe ownership and follower milestones only.
import { addTranslations } from '../core/i18n.js';
const rows = [
 ['suit','dockrigger','Dock Rigger','Liman Armacısı','Портовый такелажник','common',180,3,'#655b49','Reinforced apron, shoulder straps and a clipped salvage tag.','Takviyeli önlük, omuz askıları ve hurda etiketi.','Усиленный фартук, плечевые ремни и бирка утилизации.'],
 ['suit','cablehand','Cable Hand','Kablo Ustası','Кабельщик','uncommon',260,5,'#414f59','Offset cable drum and insulated cuffs from the dock workshop.','Liman atölyesinden kablo makarası ve yalıtımlı manşetler.','Кабельная катушка и изолированные манжеты из портовой мастерской.'],
 ['suit','patchrunner','Patch Runner','Yama Kuryesi','Курьер патчей','uncommon',340,7,'#59654e','Cross-body dispatch satchel and a short split workcoat.','Çapraz kurye çantası ve kısa iş ceketi.','Курьерская сумка через плечо и короткая рабочая куртка.'],
 ['suit','filterkeeper','Filter Keeper','Filtre Bekçisi','Хранитель фильтров','rare',520,9,'#8c7654','High collar, ceramic chest filter and sealed knee guards.','Yüksek yaka, seramik göğüs filtresi ve kapalı dizlikler.','Высокий воротник, керамический нагрудный фильтр и закрытые наколенники.'],
 ['suit','archivist13','Archive Custodian','Arşiv Sorumlusu','Хранитель архива','rare',650,11,'#595366','Long divided coat, document cartridge and brass indexing plates.','Uzun parçalı ceket, belge kartuşu ve pirinç dizin plakaları.','Длинный разрезной плащ, картридж документов и латунные индексные пластины.'],
 ['suit','signaldiver','Signal Diver','Sinyal Dalgıcı','Ныряльщик сигнала','epic',950,14,'#345860','Segmented shoulder shell, pressure collar and a ceramic receiver.','Parçalı omuz kabuğu, basınç yakası ve seramik alıcı.','Сегментированные наплечники, герметичный воротник и керамический приёмник.'],
 ['suit','appealsclerk','Appeals Clerk','İtiraz Memuru','Клерк апелляций','epic',1250,17,'#655249','Angular lapels, stamped docket case and one red review stripe.','Köşeli yakalar, mühürlü dosya kutusu ve kırmızı inceleme şeridi.','Угловатые лацканы, опечатанный футляр дел и красная полоса проверки.'],
 ['suit','auditmarshal','Audit Marshal','Denetim Müfettişi','Маршал аудита','legendary',1800,21,'#373b42','Asymmetric inspection mantle and layered issue-number plates.','Asimetrik denetim pelerini ve katmanlı seri plakaları.','Асимметричная инспекторская накидка и многослойные номерные пластины.'],
 ['back','spoolpack13','Salvage Spool','Hurda Makarası','Катушка утилизации','uncommon',220,4,'#75634f','A strapped cable reel; appearance only, no extra capacity.','Askılı kablo makarası; yalnız görünüm, ek kapasite sağlamaz.','Катушка на ремнях; только внешний вид, без дополнительной вместимости.'],
 ['back','docketcase13','Sealed Docket','Mühürlü Dosya','Опечатанное дело','rare',440,8,'#65594b','A hard document case with an oversized stamped lock.','Büyük mühürlü kilidi olan sert belge kutusu.','Жёсткий футляр документов с крупным опечатанным замком.'],
 ['back','receiver13','Dead-Air Receiver','Ölü Yayın Alıcısı','Приёмник мёртвого эфира','rare',600,10,'#46616b','Folded aerial fins and a dark receiver grille.','Katlanmış anten kanatları ve karanlık alıcı ızgarası.','Сложенные антенные плавники и тёмная решётка приёмника.'],
 ['back','relayframe13','Relay Frame','Röle Çerçevesi','Релейная рама','epic',880,13,'#555b63','A skeletal transfer rack carrying three sealed canisters.','Üç mühürlü kapsül taşıyan iskelet aktarım rafı.','Каркасная передаточная рама с тремя запечатанными капсулами.'],
 ['skin','issuedsteel13','Issued Steel','Zimmetli Çelik','Табельная сталь','uncommon',260,5,'#8d979a','Brushed gunmetal with narrow inspection bands.','Dar denetim bantlı fırçalanmış silah çeliği.','Шлифованная оружейная сталь с узкими инспекционными полосами.'],
 ['skin','dockoxide13','Dock Oxide','Liman Oksidi','Портовый оксид','rare',420,8,'#688c83','Oxidised copper panels and preserved dark fasteners.','Oksitlenmiş bakır paneller ve koyu bağlantılar.','Окисленные медные панели и тёмные крепления.'],
 ['skin','redacted13','Redacted','Sansürlü','Засекречено','epic',780,12,'#bd493d','Matte archive-black with red censorship bars.','Kırmızı sansür şeritli mat arşiv siyahı.','Матовый архивный чёрный с красными полосами цензуры.'],
 ['skin','porcelain13','Ceramic Proof','Seramik Numune','Керамический образец','epic',1050,16,'#dad4c6','Ivory ceramic seams with blue quality-control marks.','Mavi kalite işaretli fildişi seramik dikişler.','Швы керамики цвета слоновой кости с синими отметками контроля.'],
];
export const C13 = rows.map(([slot,id,name,tr,ru,tier,price,minLevel,color,desc,dtr,dru]) => ({ slot,id,name,tier,price,minLevel,color,desc,src:'shop',how:slot==='skin'?'Rotating wardrobe shop':'Wardrobe follower milestones',collection:'Dock issue' }));
addTranslations(Object.fromEntries(rows.flatMap(r => [[r[2],r[3]],[r[9],r[10]]])), 'tr');
addTranslations(Object.fromEntries(rows.flatMap(r => [[r[2],r[4]],[r[9],r[11]]])), 'ru');
addTranslations({ 'Wardrobe follower milestones':'Gardırop takipçi eşikleri', 'Dock issue':'Liman serisi', 'Ready & next':'Hazır ve sıradaki', 'Owned only':'Yalnız sahip oldukların', 'Full catalog':'Tüm katalog', 'Preview only — equip to save':'Yalnız önizleme — kaydetmek için kuşan', 'Appearance only. No combat bonuses.':'Yalnız görünüm. Savaş bonusu yok.', 'Current kit':'Mevcut kıyafet', 'Reset preview':'Önizlemeyi sıfırla', 'Finish':'Kaplama' },'tr');
addTranslations({ 'Wardrobe follower milestones':'Пороги подписчиков гардероба', 'Dock issue':'Портовая серия', 'Ready & next':'Доступно и далее', 'Owned only':'Только ваши', 'Full catalog':'Весь каталог', 'Preview only — equip to save':'Только примерка — наденьте для сохранения', 'Appearance only. No combat bonuses.':'Только внешний вид. Без боевых бонусов.', 'Current kit':'Текущий комплект', 'Reset preview':'Сбросить примерку', 'Finish':'Покрытие' },'ru');
