// Turkish + Russian strings for worlds3 (keys = the English UI text).
export const TR = {
  "BACKROOMS": "ARKA ODALAR",
  "ROUTE: {name} - tier {tier}, {cost}. Type ROUTE LEVEL 0.": "ROTA: {name} - kademe {tier}, {cost}. ROUTE LEVEL 0 yaz.",
  "A flickering yellow WRONG DOOR appears in about every second facility (always on day 1). Follow the hum. Step through.": "Titreyen sarı bir YANLIŞ KAPI yaklaşık her ikinci tesiste çıkar (1. gün her zaman). Uğultuyu takip et. İçinden geç.",
  "Worlds behind the door: Level 0, Poolrooms, Data Center, Endless Hotel, Level Fun, Ward 13.": "Kapının ardındaki dünyalar: Seviye 0, Havuz Odaları, Veri Merkezi, Bitmeyen Otel, Eğlence Seviyesi, Koğuş 13.",
  "Every world has a green EXIT. Every world has a rule.": "Her dünyanın yeşil bir ÇIKIŞI var. Her dünyanın bir kuralı var.",
  "BACKROOMS - route to the Backrooms + how the wrong door works": "BACKROOMS - Arka Odalar rotası + yanlış kapı nasıl çalışır",
  "Yellow wallpaper. Damp carpet. The hum never stops.": "Sarı duvar kâğıdı. Nemli halı. Uğultu hiç durmuyor.",
  "LEVEL 37": "SEVİYE 37",
  "\"The Poolrooms\"": "\"Havuz Odaları\"",
  "White tiles, warm water. Deep patches pull you down. Sound carries far over water.": "Beyaz fayans, ılık su. Derin bölgeler seni aşağı çeker. Su sesi çok uzağa taşınır.",
  "SERVER 404": "SUNUCU 404",
  "\"The Algorithm's Data Center\"": "\"Algoritma'nın Veri Merkezi\"",
  "Flooded racks. The water bites back in pulses.": "Su basmış raflar. Su, darbeler halinde ısırır.",
  "FLOOR 404": "KAT 404",
  "\"The Endless Hotel\"": "\"Bitmeyen Otel\"",
  "Numbered doors, none of them yours. The lights go out on schedule; numbers and the EXIT distance lie.": "Numaralı kapılar, hiçbiri senin değil. Işıklar tarifeli olarak söner; numaralar ve çıkış mesafesi yalan söyler.",
  "LEVEL FUN": "EĞLENCE SEVİYESİ",
  "\"Party's Never Over\"": "\"Parti Asla Bitmez\"",
  "Somebody planned this for you. They are early. They are very early.": "Biri bunu senin için planlamış. Erken geldiler. Çok erken.",
  "WARD 13": "KOĞUŞ 13",
  "\"Saint Kefal Asylum\"": "\"Aziz Kefal Akıl Hastanesi\"",
  "The doors lock behind you. Find the ward key.": "Kapılar arkandan kilitlenir. Koğuş anahtarını bul.",
  "Open the wrong door [E]": "Yanlış kapıyı aç [E]",
  "The hum is coming from behind it.": "Uğultu kapının ardından geliyor.",
  "The ward doors are locked. Find the ward key.": "Koğuş kapıları kilitli. Koğuş anahtarını bul.",
  "THE WRONG DOOR": "YANLIŞ KAPI",
  "It was not here a second ago.": "Bir saniye önce burada değildi.",
  "That door is not on my blueprints. Do not open it. ...I will watch closely if you do.": "Bu kapı planlarımda yok. Açma. ...Açarsan çok yakından izlerim.",
  "Structural anomaly detected: a door. Nobody ordered a door. Please ignore it. Please.": "Yapısal anomali: bir kapı. Kimse kapı sipariş etmedi. Lütfen görmezden gel. Lütfen.",
  "I count one more door than the building owns. I would not knock.": "Binanın sahip olduğundan bir kapı fazla sayıyorum. Ben olsam çalmazdım.",
  "The level spat you back out.": "Seviye seni geri tükürdü.",
  "THE DOORS LOCK BEHIND YOU": "KAPILAR ARKANDAN KİLİTLENDİ",
  "Find the ward key.": "Koğuş anahtarını bul.",
  "The lights go out. Something checks in.": "Işıklar söndü. Biri giriş yapıyor.",
  "The ward doors give way. Somebody pities you.": "Koğuş kapıları açıldı. Biri sana acıdı.",
  "The ward doors unlock.": "Koğuş kapılarının kilidi açıldı.",
  "Find the ward key - the EXIT is locked": "Koğuş anahtarını bul - ÇIKIŞ kilitli",
  "Green EXIT sign: about {d} m": "Yeşil ÇIKIŞ tabelası: yaklaşık {d} m",
  "The wrong door: about {d} m away": "Yanlış kapı: yaklaşık {d} m uzakta",
  "Facility size: {c}": "Tesis boyutu: {c}",
  "SMALL": "KÜÇÜK",
  "MEDIUM": "ORTA",
  "LARGE": "BÜYÜK",
  "Gilded Pool Float": "Yaldızlı Havuz Simidi",
  "Rubber duck-shaped. Solid gold underneath. Do not ask.": "Lastik ördek şeklinde. Altı masif altın. Sorma.",
  "Lifeguard Whistle": "Cankurtaran Düdüğü",
  "Blow it and the water listens.": "Üfle, su dinler.",
  "Algorithm Core Drive": "Algoritma Çekirdek Sürücüsü",
  "Still warm. Something inside is reading you back.": "Hâlâ sıcak. İçindeki bir şey seni geri okuyor.",
  "Cooling Fan Array": "Soğutma Fanı Dizisi",
  "Spins on its own. Never stops.": "Kendi kendine döner. Hiç durmaz.",
  "Brass Room Key 404": "Pirinç Oda Anahtarı 404",
  "The door it opens is somewhere on this floor. Or it opens all of them.": "Açtığı kapı bu katta bir yerde. Ya da hepsini açıyor.",
  "Concierge Ledger": "Konsiyerj Defteri",
  "Every guest is written down. Your name is already on the last page.": "Her misafir yazılı. Adın son sayfada zaten var.",
  "Golden Birthday Cake": "Altın Doğum Günü Pastası",
  "It says HAPPY BIRTHDAY. The name has been scratched off.": "HAPPY BIRTHDAY yazıyor. İsim kazınmış.",
  "Pinata Prize": "Pinyata Ödülü",
  "Rattles. Someone was hit until it burst. It is still full.": "Şıkırdıyor. Biri patlayana dek vurulmuş. Hâlâ dolu.",
  "Patient File 13": "Hasta Dosyası 13",
  "Your name. Your handwriting. Dated next Tuesday.": "Adın. El yazın. Gelecek salı tarihli.",
  "Restraint Jacket": "Deli Gömleği",
  "The sleeves are already tied. From the inside.": "Kollar zaten bağlı. İçeriden.",
  "Ward Key": "Koğuş Anahtarı",
  "Opens the ward EXIT. Somebody kept it in the dark.": "Koğuşun ÇIKIŞ'ını açar. Biri karanlıkta saklamış.",
};
export const RU = {
  "BACKROOMS": "БЭКРУМС",
  "ROUTE: {name} - tier {tier}, {cost}. Type ROUTE LEVEL 0.": "МАРШРУТ: {name} - ранг {tier}, {cost}. Введи ROUTE LEVEL 0.",
  "A flickering yellow WRONG DOOR appears in about every second facility (always on day 1). Follow the hum. Step through.": "Мерцающая жёлтая НЕПРАВИЛЬНАЯ ДВЕРЬ есть почти в каждом втором комплексе (в первый день всегда). Иди на гул. Шагни внутрь.",
  "Worlds behind the door: Level 0, Poolrooms, Data Center, Endless Hotel, Level Fun, Ward 13.": "Миры за дверью: Уровень 0, Бассейны, Дата-центр, Бесконечный отель, Весёлый уровень, Палата 13.",
  "Every world has a green EXIT. Every world has a rule.": "В каждом мире есть зелёный ВЫХОД. В каждом мире есть правило.",
  "BACKROOMS - route to the Backrooms + how the wrong door works": "BACKROOMS - маршрут в Закулисье и как работает неправильная дверь",
  "Yellow wallpaper. Damp carpet. The hum never stops.": "Жёлтые обои. Сырой ковёр. Гул не смолкает.",
  "LEVEL 37": "УРОВЕНЬ 37",
  "\"The Poolrooms\"": "\"Бассейны\"",
  "White tiles, warm water. Deep patches pull you down. Sound carries far over water.": "Белая плитка, тёплая вода. Глубокие пятна тянут вниз. Звук над водой разносится далеко.",
  "SERVER 404": "СЕРВЕР 404",
  "\"The Algorithm's Data Center\"": "\"Дата-центр Алгоритма\"",
  "Flooded racks. The water bites back in pulses.": "Затопленные стойки. Вода бьёт импульсами.",
  "FLOOR 404": "ЭТАЖ 404",
  "\"The Endless Hotel\"": "\"Бесконечный отель\"",
  "Numbered doors, none of them yours. The lights go out on schedule; numbers and the EXIT distance lie.": "Пронумерованные двери, ни одна не твоя. Свет гаснет по расписанию; номера и расстояние до выхода лгут.",
  "LEVEL FUN": "ВЕСЁЛЫЙ УРОВЕНЬ",
  "\"Party's Never Over\"": "\"Вечеринка не кончается\"",
  "Somebody planned this for you. They are early. They are very early.": "Кто-то всё это для тебя устроил. Они пришли раньше. Намного раньше.",
  "WARD 13": "ПАЛАТА 13",
  "\"Saint Kefal Asylum\"": "\"Психбольница св. Кефала\"",
  "The doors lock behind you. Find the ward key.": "Двери запираются за тобой. Найди ключ от палаты.",
  "Open the wrong door [E]": "Открыть неправильную дверь [E]",
  "The hum is coming from behind it.": "Гул идёт из-за неё.",
  "The ward doors are locked. Find the ward key.": "Двери палаты заперты. Найди ключ.",
  "THE WRONG DOOR": "НЕПРАВИЛЬНАЯ ДВЕРЬ",
  "It was not here a second ago.": "Секунду назад её здесь не было.",
  "That door is not on my blueprints. Do not open it. ...I will watch closely if you do.": "Этой двери нет на моих чертежах. Не открывай. ...Если откроешь, буду смотреть очень внимательно.",
  "Structural anomaly detected: a door. Nobody ordered a door. Please ignore it. Please.": "Структурная аномалия: дверь. Никто не заказывал дверь. Пожалуйста, игнорируй её. Пожалуйста.",
  "I count one more door than the building owns. I would not knock.": "Я насчитал на одну дверь больше, чем есть в здании. Я бы не стучал.",
  "The level spat you back out.": "Уровень выплюнул тебя обратно.",
  "THE DOORS LOCK BEHIND YOU": "ДВЕРИ ЗАПЕРЛИСЬ ЗА ТОБОЙ",
  "Find the ward key.": "Найди ключ от палаты.",
  "The lights go out. Something checks in.": "Свет погас. Кто-то заселяется.",
  "The ward doors give way. Somebody pities you.": "Двери палаты поддались. Кто-то тебя пожалел.",
  "The ward doors unlock.": "Двери палаты отперты.",
  "Find the ward key - the EXIT is locked": "Найди ключ - ВЫХОД заперт",
  "Green EXIT sign: about {d} m": "Зелёный знак ВЫХОД: примерно {d} м",
  "The wrong door: about {d} m away": "Неправильная дверь: примерно в {d} м",
  "Facility size: {c}": "Размер комплекса: {c}",
  "SMALL": "МАЛЫЙ",
  "MEDIUM": "СРЕДНИЙ",
  "LARGE": "БОЛЬШОЙ",
  "Gilded Pool Float": "Позолоченный надувной круг",
  "Rubber duck-shaped. Solid gold underneath. Do not ask.": "В форме уточки. Внутри сплошное золото. Не спрашивай.",
  "Lifeguard Whistle": "Свисток спасателя",
  "Blow it and the water listens.": "Свистни, и вода послушает.",
  "Algorithm Core Drive": "Ядро-накопитель Алгоритма",
  "Still warm. Something inside is reading you back.": "Ещё тёплый. То, что внутри, читает тебя в ответ.",
  "Cooling Fan Array": "Блок вентиляторов",
  "Spins on its own. Never stops.": "Крутится сам. Никогда не останавливается.",
  "Brass Room Key 404": "Латунный ключ от номера 404",
  "The door it opens is somewhere on this floor. Or it opens all of them.": "Дверь, которую он открывает, где-то на этаже. Или он открывает все.",
  "Concierge Ledger": "Книга портье",
  "Every guest is written down. Your name is already on the last page.": "Каждый гость записан. Твоё имя уже на последней странице.",
  "Golden Birthday Cake": "Золотой праздничный торт",
  "It says HAPPY BIRTHDAY. The name has been scratched off.": "На нём надпись С ДНЁМ РОЖДЕНИЯ. Имя соскоблено.",
  "Pinata Prize": "Приз из пиньяты",
  "Rattles. Someone was hit until it burst. It is still full.": "Гремит. Кого-то били, пока не лопнуло. Оно всё ещё полное.",
  "Patient File 13": "История болезни 13",
  "Your name. Your handwriting. Dated next Tuesday.": "Твоё имя. Твой почерк. Датировано следующим вторником.",
  "Restraint Jacket": "Смирительная рубашка",
  "The sleeves are already tied. From the inside.": "Рукава уже завязаны. Изнутри.",
  "Ward Key": "Ключ от палаты",
  "Opens the ward EXIT. Somebody kept it in the dark.": "Открывает ВЫХОД палаты. Кто-то прятал его в темноте.",
};
