import './ship2_env.mjs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {Physics,initPhysics,G,groups} from '../../src/physics/physics.js';
import {Emitter} from '../../src/core/events.js';
import {installIndustry13} from '../../src/game/industry13.js';
import {createWitchModel} from '../../src/models/lcmonsters_models.js';
await initPhysics();
document.createTextNode=value=>({textContent:value});
document.head.append=()=>{};
const physics=new Physics(),mods=new Emitter(),group=new THREE.Group();
const game={mods,physics,unloadMap(){},run:{phase:'moon',moon:'hamsi'},shop:{open(){},hostCart(){}},terminal:{hostExecute(){}}};
const api=installIndustry13(game);
mods.emit('mapLoaded',{outdoor:{group,vendorSpace:{pos:[11,0,9]}},mapGroup:group},game);
physics.world.step();
assert.ok(physics.raycast({x:11,y:.7,z:12},{x:0,y:0,z:-1},4,G.STATIC),'real field counter must block native player approach');
const actor=physics.createKinematicCapsule({x:11,y:.92,z:11},.56,.34,G.PLAYER,G.STATIC);
const controller=physics.createController();physics.world.step();
controller.computeColliderMovement(actor.col,{x:0,y:0,z:-3},undefined,groups(G.PLAYER,G.STATIC));
assert.ok(controller.computedMovement().z> -1.3,'standing native capsule cannot walk through the counter');
game.unloadMap();physics.world.step();
assert.equal(physics.raycast({x:11,y:.7,z:12},{x:0,y:0,z:-1},4,G.STATIC),null,'map unload must release broker collision');
physics.world.removeCharacterController(controller);
api.dispose();physics.world.free();
const witch=createWitchModel();
for(const state of ['walk','ritual','stunned','dead'])witch.update(1/60,{state,time:1,speed:1});
witch.root.traverse(o=>{assert(!o.isLight);for(const v of [...o.position,...o.rotation.toArray().slice(0,3)])assert(Number.isFinite(v));});
witch.dispose();
console.log('art38: native broker counter collision and unload ownership passed');
