// Actual native catalog -> broker host cart -> pickup tray -> ItemManager custody, no second charge ledger.
import assert from 'node:assert/strict';
import './ship2_env.mjs';
import * as THREE from 'three';
import {Emitter} from '../../src/core/events.js';
import '../../src/game/grenades.js';
import {ITEMS} from '../../src/game/items.js';
import {installShop,catalogEntries} from '../../src/game/shop.js';
import {installIndustry13} from '../../src/game/industry13.js';
import {ItemManager} from '../../src/entities/items.js';
import {hostMethods} from '../../src/game/host.js';
import {Physics,initPhysics} from '../../src/physics/physics.js';
document.createTextNode=text=>({textContent:text});document.querySelectorAll=()=>[];document.head.append=()=>{};await initPhysics();
assert.equal(ITEMS.bouncebot?.price,90,'runtime registry exports native buyable bot');assert.equal(ITEMS.bouncebot.charges,1);
const entry=catalogEntries().find(e=>e.id==='bouncebot');assert.equal(entry.cat,'consumables');assert.equal(entry.base,90);
const physics=new Physics(),mods=new Emitter(),scene=new THREE.Scene(),events=[],handlers=new Map();
const player={pos:new THREE.Vector3(20,-1.25,12.6),dead:false,downed:false,inShip:false,slots:[]};
const g={creatures:{follow(){}},mods,physics,engine:{scene},ship:{group:new THREE.Group()},selfId:'crew',isHost:true,time:0,run:{runId:'boombot22-native',phase:'company',moon:'company',day:1,quotaIndex:0,credits:250,quota:330},player,remotes:new Map(),world:{company:{group:new THREE.Group(),groundY:-1.25}},hubgate:{shopLock:false},onboard:{unlocks:()=>({mode:'all'})},aiPlayerById:id=>id==='crew'?player:null,terminal:{hostExecute(){}},broadcastRun(){},hostSave(){},onItemHeld(it,id){assert.equal(id,'crew');player.slots.push(it.id);},onItemDropped(){},ui:{toast(){},sfx(){},closePanel(){},openShop(){},blocksInput:()=>false},audio:{ui(){},at(){},play(){}},net:{on_(){return()=>{}},handle(name,fn){handlers.set(name,fn)},sendTo(...a){events.push(a)},request(){},broadcast(name,d){events.push([name,d]);if(name==='it')g.items.onEvent(d);}},camera:new THREE.PerspectiveCamera()};
g.items=new ItemManager(g);g.shop=installShop(g);g.industry13=installIndustry13(g);mods.emit('mapLoaded',g.world);physics.addStaticBox(20,-2.25,12,8,1,8);physics.world.step();hostMethods.registerHandlers.call(g);
const stock=g.shop.stock().find(e=>e.id==='bouncebot');assert.ok(stock&&!stock.locked&&!stock.soldOut,'fresh day1/q0 bot is visible and buyable');assert.equal(stock.base,90);const price=stock.price;
const buy=(orderId)=>{let result;g.shop.hostCart({lines:[{id:'bouncebot',n:1}],orderId},'crew',(msg,err)=>result={msg,err});return result;};
const count=()=>[...g.items.all()].filter(it=>it.type==='bouncebot');
player.pos.set(100,0,100);const initial=g.run.credits;assert.equal(buy('far').err,true);assert.equal(g.run.credits,initial);assert.equal(count().length,0);
player.pos.set(20,-1.25,12.6);g.run.credits=price-1;assert.equal(buy('poor').err,true);assert.equal(count().length,0);assert.equal(g.run.credits,price-1);
g.run.credits=250;assert.ok(!buy('native-order').err);assert.equal(g.run.credits,250-price);assert.equal(count().length,1);const bot=count()[0],id=bot.id;assert.equal(bot.charges,1);assert.equal(bot.value,0);assert.equal(bot.state,'world');assert.ok(bot.obj.position.x>18&&bot.obj.position.z>13,'native pickup tray receives item');
const paid=g.run.credits;assert.equal(buy('native-order').err,true);assert.equal(g.run.credits,paid);assert.equal(count().length,1,'replayed order cannot spawn twice');
player.pos.copy(bot.obj.position);handlers.get('pick')({id,slot:0},'crew');assert.equal(g.items.get(id).holder,'crew');assert.equal(g.items.get(id).state,'held');assert.equal(g.items.get(id).charges,1,'native held custody retains single charge');
const spawn=events.find(e=>e[0]==='it'&&e[1].e==='sp'&&e[1].id===id)[1];g.items.onEvent(spawn);assert.equal(count().length,1,'duplicate native spawn event is idempotent');assert.equal(g.items.get(id).charges,1);
g.industry13.dispose();g.shop.dispose();for(const it of [...g.items.all()])g.items.onEvent({e:'rm',id:it.id});g.items.dispose();physics.dispose();console.log('boombot22 native fresh catalog, broker purchase/replay, pickup delivery and one-charge custody PASS');
