import assert from 'node:assert/strict';
import * as THREE from 'three';
import { Emitter } from '../../src/core/events.js';
import { installFeedcams } from '../../src/game/feedcams.js';
import { installBroadcast18 } from '../../src/game/broadcast18.js';
import { occupiesBroadcastGate } from '../../src/game/broadcast18_core.js';
import { tIn } from '../../src/core/i18n.js';
import { B18 } from '../../src/game/broadcast18_text.js';
const mods=new Emitter(),network=[],powered=[];
const player={id:'host',zone:'out',pos:new THREE.Vector3(0,0,1),eye:{y:1.4},dead:false,inShip:false};
const peer={...player,id:'peer',pos:new THREE.Vector3(0,0,1)};
const gate={pos:new THREE.Vector3(8,1.4,0),size:[3,2.8,.3],rotY:Math.PI/2,baseY:0};
const contract={plan:{console:new THREE.Vector3(0,1.4,0),shortcutDoor:gate},setPowered:value=>powered.push(value)};
const body={type:'body',state:'world',obj:{position:new THREE.Vector3(30,0,30)}};
let blocked=false;
const game={isHost:true,selfId:'host',time:10,mods,run:{phase:'moon',moon:'hamsi',seed:123,day:1,fc:{ck:10,off:0,c:[[0,0],[3,0],[4,0]],p:{},h:0,tx:0,lv:0}},world:{moonId:'hamsi',outdoor:{broadcast18:contract}},player,remotes:new Map([['peer',peer]]),physics:{raycast:()=>blocked?{}:null},items:{all:()=>[body]},aiPlayers:()=>[player,peer],aiPlayerById:id=>id==='host'?player:id==='peer'?peer:null,net:{broadcast:(...args)=>network.push(args),sendTo:(...args)=>network.push(args),on(){},on_(){},off(){}},broadcastRun:keys=>network.push(['run',keys])};
game.feedcams=installFeedcams(game);
const cams=JSON.stringify(game.run.fc.c);
// Native receipts never overwrite pre-existing or later interruption owners.
const receipt=game.feedcams.cutNetwork(500);assert.equal(receipt.until,160);assert.equal(game.feedcams.netOff(),true);assert.equal(JSON.stringify(game.run.fc.c),cams);
assert.equal(game.feedcams.restoreNetwork(receipt),true);assert.equal(game.run.fc.off,0);
game.run.fc.off=300;const borrowed=game.feedcams.cutNetwork(150);assert.equal(borrowed.owned,false);assert.equal(game.feedcams.restoreNetwork(borrowed),false);assert.equal(game.run.fc.off,300);
game.run.fc.off=50;const extended=game.feedcams.cutNetwork(150);assert.equal(game.feedcams.restoreNetwork(extended),true);assert.equal(game.run.fc.off,50);
game.run.fc.off=0;const owned=game.feedcams.cutNetwork(150);game.run.fc.off=200;assert.equal(game.feedcams.restoreNetwork(owned),false);assert.equal(game.run.fc.off,200);
game.isHost=false;assert.equal(game.feedcams.cutNetwork(150),null);assert.equal(game.feedcams.restoreNetwork(owned),false);game.isHost=true;game.run.fc.off=0;
const api=installBroadcast18(game),handlers=new Map();mods.emit('registerHandlers',(name,fn)=>handlers.set(name,fn),game);
const request=(op='cut',extra={})=>({token:api.state().token,rev:api.state().rev,op,...extra});
const hostRequest=handlers.get('b18req');assert.equal(typeof hostRequest,'function');assert.equal(api.powered(),true);
const interactions=[];mods.emit('interactables',interactions,game);assert.equal(interactions.length,1);assert.match(interactions[0].sub(),/150 seconds.*main return/);
assert.equal(hostRequest(request('cut',{token:'wrong'}),'peer'),false);assert.equal(hostRequest(request('cut',{rev:99}),'peer'),false);assert.equal(hostRequest(request(),'forged'),false);
peer.pos.set(10,0,10);assert.equal(hostRequest(request(),'peer'),false);peer.pos.set(0,0,1);
blocked=true;assert.equal(hostRequest(request(),'peer'),false);blocked=false;
peer.dead=true;assert.equal(hostRequest(request(),'peer'),false);peer.dead=false;game.downed={isDowned:id=>id==='peer'};assert.equal(hostRequest(request(),'peer'),false);game.downed=null;
peer.zone='in';assert.equal(hostRequest(request(),'peer'),false);peer.zone='out';
peer.pos.copy(gate.pos);peer.pos.y=0;assert.equal(hostRequest(request(),'host'),false);assert.equal(game.feedcams.netOff(),false);peer.pos.set(0,0,1);
body.obj.position.set(8,0,0);assert.equal(hostRequest(request(),'host'),false);body.obj.position.set(30,0,30);
const first=request();assert.equal(hostRequest(first,'peer'),true);assert.equal(game.feedcams.netOff(),true);assert.equal(powered.at(-1),false);assert.equal(hostRequest(first,'peer'),false);assert.equal(api.state().rev,1);
const peerPower=[];const clientGame={...game,isHost:false,selfId:'peer',mods:new Emitter(),run:JSON.parse(JSON.stringify(game.run)),world:{moonId:'hamsi',outdoor:{broadcast18:{plan:contract.plan,setPowered:v=>peerPower.push(v)}}}};
clientGame.feedcams=installFeedcams(clientGame);const client=installBroadcast18(clientGame);assert.equal(peerPower.at(-1),false,'replica shortcut follows synced native network outage');assert.equal(client.hostReq(request(),'peer'),false,'peer installer cannot authorize a cut');
clientGame.time=210;clientGame.mods.emit('update',.1,clientGame);assert.equal(clientGame.feedcams.netOff(),true,'late replica uses refreshed host clock, not raw local time');assert.equal(peerPower.at(-1),false);clientGame.isHost=true;clientGame.mods.emit('hostMigrated',clientGame,{self:true});
assert.equal(client.state().receipt.until,360);assert.equal(client.state().receipt.previous,0,'clock migration cannot invent a prior outage');assert.equal(clientGame.run.fc.off,360);assert.equal(client.hostReq({token:client.state().token,rev:client.state().rev,op:'restore'},'peer'),true);assert.equal(clientGame.run.fc.off,0);
clientGame.isHost=false;
const restore=request('restore');assert.equal(hostRequest(restore,'peer'),true);assert.equal(game.feedcams.netOff(),false);assert.equal(powered.at(-1),true);assert.equal(hostRequest(restore,'peer'),false);
clientGame.run=JSON.parse(JSON.stringify(game.run));clientGame.mods.emit('update',.1,clientGame);assert.equal(peerPower.at(-1),true);client.dispose();clientGame.feedcams.dispose();
assert.equal(hostRequest(request(),'host'),true);peer.pos.set(8,0,0);mods.emit('update',.1,game);assert.equal(powered.at(-1),true,'never close even if occupant arrives during a native outage');
peer.dead=true;mods.emit('update',.1,game);assert.equal(powered.at(-1),false,'dead-player last position cannot hold the shutter open after its corpse leaves');
body.obj.position.set(8,0,0);mods.emit('update',.1,game);assert.equal(powered.at(-1),true,'actual world corpse still protects the closing volume');body.obj.position.set(30,0,30);
peer.dead=false;mods.emit('update',.1,game);assert.equal(powered.at(-1),true,'living crew occupancy remains protected');peer.pos.set(0,0,1);mods.emit('update',.1,game);assert.equal(powered.at(-1),false);
game.time=161;mods.emit('update',.1,game);assert.equal(game.feedcams.netOff(),false);assert.equal(powered.at(-1),true);assert.equal(api.state().receipt,null);assert.equal(JSON.stringify(game.run.fc.c),cams);
// Main-route/world plan is never modified; inactive game updates cannot restart or cut the network.
assert.equal(contract.plan.shortcutDoor,gate);game.run.phase='orbit';mods.emit('update',1000,game);assert.equal(game.feedcams.netOff(),false);assert.equal(hostRequest({token:'hamsi:123:1',rev:4,op:'cut'},'peer'),false);
game.run.phase='moon';game.time=170;mods.emit('update',.1,game);assert.equal(hostRequest(request(),'host'),true);const expiry=game.run.fc.off;api.dispose();assert.equal(game.run.fc.off,0);assert.equal(powered.at(-1),true);
assert.ok(expiry>game.time);game.feedcams.dispose();
assert.equal(occupiesBroadcastGate(gate,new THREE.Vector3(8,0,1)),true);assert.equal(occupiesBroadcastGate(gate,new THREE.Vector3(15,0,0)),false);
for(const language of ['tr','ru'])for(const text of Object.values(B18))assert.notEqual(tIn(language,text),text);
console.log('broadcast18: native camera receipts, installed host authority/replay, physical choice, expiry and occupancy passed');
