import assert from 'node:assert/strict';
import {transact,walletFor,bindCasinoWallet,walletView,slotMultiplier,PACKET_CHANCES,houseFor,casinoPublicLedger,recoverCasinoRounds,casinoOutboundView} from '../../src/game/casino13_core.js';
import {blackjackValue,pokerRank,comparePoker,shuffledDeck,validDiscards} from '../../src/game/casino24_cards.js';
const c=(rank,suit=0)=>rank-2+13*suit;
assert.equal(blackjackValue([c(14),c(14),c(9)]),21);assert.equal(blackjackValue([c(14),c(6)]),17);
const examples=[[c(14),c(5),c(4),c(3),c(2)],[c(9),c(9,1),c(9,2),c(9,3),c(2)],[c(8),c(8,1),c(8,2),c(2),c(2,1)],[c(2),c(4),c(7),c(9),c(14)],[c(2),c(3,1),c(4,2),c(5),c(6)],[c(2),c(2,1),c(2,2),c(9),c(14)],[c(2),c(2,1),c(9),c(9,1),c(14)],[c(2),c(2,1),c(9),c(10),c(14)],[c(2),c(4,1),c(9),c(10),c(14)]];
examples.forEach((hand,i)=>assert.equal(pokerRank(hand)[0],8-i));assert.equal(pokerRank(examples[0])[1],5,'ace-low straight');assert.equal(comparePoker(examples[0],[c(3),c(4),c(5),c(6),c(7)]),-1);assert.equal(new Set(shuffledDeck(()=>.5)).size,52);
for(const bad of [[0,0],[-1],[5],[1.5],[0,1,2,3],{},null])assert.equal(validDiscards(bad),false);
let gross=0;for(let a=0;a<6;a++)for(let b=0;b<6;b++)for(let d=0;d<6;d++){const run={credits:0,casino13:{wallets:{p:{chips:25,round:null,seq:0}}}},values=[a,b,d];const result=transact(run,'p',{action:'play',game:'slots',amount:5,seq:0},()=> (values.shift()+.1)/6);gross+=result.paid/5;assert.equal(result.paid/5,slotMultiplier([a,b,d]));}assert.equal(gross,201);assert.equal(gross/216,201/216);
let wheel=0;for(let n=0;n<37;n++){const run={credits:0,casino13:{wallets:{p:{chips:25,round:null,seq:0}}}};wheel+=transact(run,'p',{action:'play',game:'wheel',choice:'red',amount:5,seq:0},()=> (n+.1)/37).paid/5;}assert.equal(wheel/37,36/37);
let ev=1;PACKET_CHANCES.forEach(p=>{ev*=p*2;assert(ev<=1,'all stopping strategies bounded');});
const fresh=()=>({credits:100,casino13:{wallets:{p:{chips:100,seq:0,round:null}}}});
let run=fresh();let deal=transact(run,'p',{action:'play',game:'blackjack',amount:10,seq:0},()=>.7);assert.equal(deal.wallet.round.kind,'blackjack');assert.equal(deal.wallet.round.dealer.length,1);assert.equal('deck' in deal.wallet.round,false);
const saved=JSON.parse(JSON.stringify(run)),before=JSON.stringify(saved);assert.equal(transact(saved,'p',{action:'play',game:'poker',amount:5,seq:1}),null);assert.equal(JSON.stringify(saved),before,'concurrent round rejection atomic');assert.equal(transact(saved,'p',{action:'hit',seq:0}),null);assert.equal(transact(saved,'other',{action:'hit',seq:0}),null);
const stood=transact(saved,'p',{action:'stand',seq:1});assert(stood.dealer.length>=2);assert.equal(stood.wallet.round,null);assert.equal(transact(saved,'p',{action:'stand',seq:2}),null,'no double settlement');assert.equal(recoverCasinoRounds(run),false,'private save preserves accepted hand');
const hitRun=fresh();transact(hitRun,'p',{action:'play',game:'blackjack',amount:10,seq:0},()=>.7);const hit=transact(hitRun,'p',{action:'hit',seq:1});assert.equal(hit.wallet.round,null,'hit20 bust settles without stand');assert.equal(hit.kind,'loss');const naturalRun=fresh(),natural=transact(naturalRun,'p',{action:'play',game:'blackjack',amount:10,seq:0},()=>.999);assert.equal(natural.kind,'win');assert.equal(natural.paid,20,'explicit integer-chip natural2x gross');assert.equal(natural.wallet.round,null);
const publicRun={credits:100,casino13:casinoPublicLedger(run.casino13)};assert.equal(JSON.stringify(publicRun).includes('deck'),false);assert.equal(recoverCasinoRounds(publicRun),true);assert.equal(publicRun.casino13.wallets.p.chips,100,'public-only migration refunds original stake');assert.equal(recoverCasinoRounds(publicRun),false,'refund not repeated');
run=fresh();deal=transact(run,'p',{action:'play',game:'poker',amount:10,seq:0},()=>.999);assert.equal(deal.wallet.round.player.length,5);assert.equal(deal.wallet.round.dealer.length,0);let snapshot=JSON.stringify(run);for(const discards of [[0,0],[5],[-1],[0,1,2,3],['1']]){assert.equal(transact(run,'p',{action:'draw',seq:1,discards}),null);assert.equal(JSON.stringify(run),snapshot);}
const resumed=JSON.parse(snapshot),drawn=transact(resumed,'p',{action:'draw',seq:1,discards:[0,1,2]});assert.equal(drawn.player.length,5);assert.equal(drawn.dealer.length,5);assert.equal(new Set([...drawn.player,...drawn.dealer]).size,10,'single deck custody');assert.equal(transact(resumed,'p',{action:'draw',seq:2,discards:[]}),null);assert.equal(resumed.credits,100,'games do not directly mutate Credits');
run={credits:0,casino13:{wallets:{p:{chips:10,seq:0,round:{step:1,pot:20}}}}};assert.equal(walletFor(run,'p').round.version,1);assert.equal(transact(run,'p',{action:'push',seq:0},()=>.5).wallet.round.pot,40,'legacy55% second push preserved');assert.equal(transact(run,'p',{action:'cash',seq:1}).wallet.chips,50);
run={credits:0,casino13:{wallets:{p:{chips:25,seq:0,round:null},q:{chips:25,seq:0,round:null}}}};transact(run,'p',{action:'play',game:'packet',amount:25,seq:0});assert.equal(houseFor(run).free,75);assert.equal(transact(run,'q',{action:'play',game:'packet',amount:25,seq:0}),null,'unfunded new liability refused before stake');assert.equal(run.casino13.wallets.q.chips,25);run.industry13={shift:1};assert.equal(houseFor(run).free,75,'new epoch subtracts accepted reservations');for(let seq=1;seq<=3;seq++)transact(run,'p',{action:'push',seq},()=>0);assert.equal(transact(run,'p',{action:'cash',seq:4}).paid,200,'accepted maximum paid despite low free reserve');assert.equal(houseFor(run).free,75);const free=houseFor(run).free;assert.equal(houseFor(JSON.parse(JSON.stringify(run))).free,free,'loading cannot refill house');assert.equal(transact(run,'p',{action:'redeem',amount:200,seq:5}).credits,200,'accepted winnings remain redeemable');
console.log('casino24 actual distributions/cards/private resume/replay/malformed/migration/reserve tests passed');

const hiddenRun=fresh();transact(hiddenRun,'p',{action:'play',game:'poker',amount:10,seq:0},()=>.7);const outgoing={run:hiddenRun,deadLetter:{nativeBackup:JSON.parse(JSON.stringify(hiddenRun))}};const sanitized=casinoOutboundView('welcome',outgoing);assert.equal(JSON.stringify(sanitized).includes('deck'),false);assert.equal(hiddenRun.casino13.wallets.p.round.deck.length,42,'outbound filtering cannot overwrite host private deck');const legacyView=casinoPublicLedger({wallets:{old:{chips:0,seq:0,round:{step:2,pot:40}}}});assert.equal(legacyView.wallets.old.round.kind,'packet');assert.equal(legacyView.wallets.old.round.pot,40);console.log('casino24 nested outbound privacy and first-action legacy view passed');
// Actual installed handler: phase/distance/downed/station routing and public output.
await import('./ship2_env.mjs');
const {Emitter}=await import('../../src/core/events.js');const THREE=await import('three');const {installCasino13}=await import('../../src/game/casino13.js');
const mods=new Emitter(),handlers=new Map(),received=[],wire=[],actor={pos:new THREE.Vector3(),dead:false,downed:false};let stamp=500;const originalPerformance=globalThis.performance,originalRandom=Math.random;globalThis.performance={now:()=>stamp};Math.random=()=>.7;
try{
 const oldView=(type,data)=>data;
 const game={mods,isHost:true,selfId:'p',profile:{id:'native-profile'},run:fresh(),net:{outboundView:oldView,on_(){},request(){},sendTo(...args){received.push(args)},broadcast(...args){wire.push(args)}},ui:{},aiPlayerById:id=>id==='p'?actor:null,broadcastRun(){},hostSave(){},playerName:()=> 'Crew'};
 game.run.phase='company';const api=installCasino13(game);mods.emit('mapLoaded',{company:{casinoSpace:{center:new THREE.Vector3(-29,-1.25,-23),groundY:-1.25},group:new THREE.Group()}});mods.emit('registerHandlers',(k,f)=>handlers.set(k,f));const host=handlers.get('c13');
 const go=id=>actor.pos.copy(api.spots.find(s=>s.id===id).pos),request=d=>{stamp+=120;host(d,'p');};go('blackjack');actor.pos.x+=10;request({station:'blackjack',action:'play',game:'blackjack',amount:10,seq:0});assert.equal(walletFor(game.run,'p').round,null,'actual handler rejects distance');go('blackjack');actor.downed=true;request({station:'blackjack',action:'play',game:'blackjack',amount:10,seq:0});assert.equal(walletFor(game.run,'p').round,null);actor.downed=false;
 request({station:'blackjack',action:'play',game:'blackjack',amount:10,seq:0});assert.equal(walletFor(game.run,'p').round.kind,'blackjack');assert.equal(received.at(-1)[2].wallet.round.dealer.length,1);assert.equal('deck' in received.at(-1)[2].wallet.round,false);
 go('poker');request({station:'poker',action:'stand',seq:1});assert.equal(walletFor(game.run,'p').round.kind,'blackjack','wrong physical table cannot settle another game');go('blackjack');request({station:'blackjack',action:'stand',seq:1});assert.equal(walletFor(game.run,'p').round,null);
 const blackjackRow=game.run.casino13.tables.blackjack;go('wheel');for(let n=0;n<4;n++)request({station:'wheel',action:'play',game:'wheel',choice:'black',amount:5,seq:walletFor(game.run,'p').seq});assert.equal(game.run.casino13.tables.blackjack,blackjackRow,'other tables never erase retained result');assert(wire.at(-1)[1].some(row=>row.station==='blackjack'));
 go('poker');request({station:'poker',action:'play',game:'poker',amount:10,seq:walletFor(game.run,'p').seq});assert.equal(walletFor(game.run,'p').round.kind,'poker');const pendingChips=walletFor(game.run,'p').chips;
 const reloadMods=new Emitter(),reloadHandlers=new Map(),reloadNet={players:new Map(),outboundView:null,on_(){},request(){},sendTo(...a){received.push(a)},broadcast(){}};
 const reloadGame={...game,mods:reloadMods,net:reloadNet,selfId:'changed-browser-peer',run:JSON.parse(JSON.stringify(game.run)),aiPlayerById:id=>['changed-browser-peer','duplicate-peer','foreign-peer'].includes(id)?actor:null};
 const reloadApi=installCasino13(reloadGame);reloadMods.emit('mapLoaded',{company:{casinoSpace:{center:new THREE.Vector3(-29,-1.25,-23),groundY:-1.25},group:new THREE.Group()}});reloadMods.emit('registerHandlers',(k,f)=>reloadHandlers.set(k,f));const reloadHost=reloadHandlers.get('c13'),savedCards=JSON.stringify(walletFor(game.run,'p').round),savedHouse=houseFor(game.run).free;
 stamp+=120;reloadHost({station:'poker',action:'status'},'changed-browser-peer');assert.equal(JSON.stringify(walletFor(reloadGame.run,'changed-browser-peer').round),savedCards,'actual native handler resolves changed browser peer to saved private hand');assert.equal(houseFor(reloadGame.run).free,savedHouse);
 reloadNet.players.set('duplicate-peer',{pid:'native-profile'});const count=received.length;stamp+=120;reloadHost({station:'poker',action:'draw',discards:[],seq:walletFor(reloadGame.run,'changed-browser-peer').seq},'duplicate-peer');assert.equal(received.length,count,'live duplicate native PID cannot access owner wallet');reloadNet.players.clear();reloadNet.players.set('foreign-peer',{pid:'foreign-profile'});stamp+=120;reloadHost({station:'poker',action:'draw',discards:[],seq:walletFor(reloadGame.run,'changed-browser-peer').seq,pid:'native-profile'},'foreign-peer');assert.equal(JSON.stringify(walletFor(reloadGame.run,'changed-browser-peer').round),savedCards,'request-provided PID cannot select another wallet');
 const seq=walletFor(reloadGame.run,'changed-browser-peer').seq;stamp+=120;reloadHost({station:'poker',action:'draw',discards:[],seq},'changed-browser-peer');assert.equal(walletFor(reloadGame.run,'changed-browser-peer').round,null);const settled=walletFor(reloadGame.run,'changed-browser-peer').chips;stamp+=120;reloadHost({station:'poker',action:'draw',discards:[],seq},'changed-browser-peer');assert.equal(walletFor(reloadGame.run,'changed-browser-peer').chips,settled);reloadApi.dispose();
game.run.casino13=casinoPublicLedger(game.run.casino13);mods.emit('hostMigrated',game,{});assert.equal(walletFor(game.run,'p').round,null);assert.equal(walletFor(game.run,'p').chips,pendingChips+10);mods.emit('hostMigrated',game,{});assert.equal(walletFor(game.run,'p').chips,pendingChips+10);
 api.dispose();assert.equal(game.net.outboundView,oldView,'composed transport hook restores original callback');
}finally{globalThis.performance=originalPerformance;Math.random=originalRandom;}
console.log('casino24 actual installed phase/distance/downed/station/retained tables/migration cleanup passed');

// Prospective native PID ownership survives a changed transport identity/private save.
const owned=fresh();const legacyWallet=owned.casino13.wallets.p;const bound=bindCasinoWallet(owned,'p','profile-1');assert.equal(bound,legacyWallet);assert.equal(Object.hasOwn(owned.casino13.wallets,'p'),false,'live legacy wallet moved once, not copied');
transact(owned,'p',{action:'play',game:'poker',amount:10,seq:0},()=>.7);const privateSaved=JSON.parse(JSON.stringify(owned)),exposure=houseFor(privateSaved).free;
const reloaded=bindCasinoWallet(privateSaved,'new-transport-peer','profile-1');assert.deepEqual(reloaded.round,owned.casino13.wallets['pid:profile-1'].round,'new peer retrieves exact private cards/deck');assert.equal(reloaded.chips,90);assert.equal(houseFor(privateSaved).free,exposure,'rebind does not duplicate house exposure');assert.equal(Object.values(privateSaved.casino13.wallets).length,1);
assert.equal(bindCasinoWallet(privateSaved,'new-transport-peer','other-profile'),null,'same peer cannot switch owner');bindCasinoWallet(privateSaved,'other-peer','other-profile');assert.equal(transact(privateSaved,'other-peer',{action:'draw',discards:[],seq:0}),null,'different native owner cannot settle another hand');
const outcome=transact(privateSaved,'new-transport-peer',{action:'draw',discards:[],seq:1});assert(outcome);assert.equal(transact(privateSaved,'p',{action:'draw',discards:[],seq:1}),null,'old alias replay cannot settle twice');
const orphan={credits:0,casino13:{wallets:{'old-unknown':{chips:45,seq:4,round:null}}}};bindCasinoWallet(orphan,'fresh-peer','new-profile');assert.equal(orphan.casino13.wallets['old-unknown'].chips,45,'unknown legacy orphan untouched');assert.equal(walletFor(orphan,'fresh-peer').chips,0);
const mappedPublic=casinoPublicLedger(owned.casino13);assert.equal(mappedPublic.peerKeys.p,'pid:profile-1');assert.equal(mappedPublic.wallets['pid:profile-1'].ownerPid,'profile-1');assert.equal('deck' in mappedPublic.wallets['pid:profile-1'].round,false);console.log('casino24 stable native profile binding/private reload/replay/orphan/exposure tests passed');
