import './ship2_env.mjs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {Physics,initPhysics} from '../../src/physics/physics.js';
import {buildCompany} from '../../src/world/company.js';
import {Session} from '../../src/net/session.js';
import {Emitter} from '../../src/core/events.js';
import {installCompany13} from '../../src/game/company13.js';
import {hostMethods} from '../../src/game/host.js';
import {itemDef} from '../../src/game/items.js';
await initPhysics();const physics=new Physics(),company=buildCompany({physics,lightPool:{add:x=>x,remove(){}}});physics.world.step();
const bell=company.interactables.find(i=>i.type==='bell'),mods=new Emitter(),net=new Session({strategy:'local',isHost:true,code:'bell38',profile:{}});net.selfId='host';
const player={id:'host',pos:new THREE.Vector3(bell.pos.x,-1.25,bell.pos.z+1.4),eye:1.62,dead:false};let calls=0,hurts=0,timers=[];
const game={mods,net,physics,selfId:'host',isHost:true,time:0,run:{phase:'company',company13:{ringers:{}}},world:{company},player,hostData:{},aiPlayers:()=>[player],hostSell(){calls++;},hostHurtPlayer:hostMethods.hostHurtPlayer,broadcastRun(){},later(fn,ms){timers.push({fn,ms});},remotes:new Map()};
net.on_('hurt',()=>hurts++);net.handle('bell',(_,from)=>game.hostSell(from));const api=installCompany13(game);
for(let i=0;i<6;i++){game.time=i*.25;net.request('bell');}
assert.equal(calls,6,'normal physical bell uses original native sell callback');
assert(timers.some(t=>t.ms===1100),'reckless repeated empty bell must schedule warned monster strike');
for(const timer of timers.splice(0))timer.fn();assert.equal(hurts,1,'real Session receives one bounded native claw hit');
game.run.company13.ringers={};game.time=20;
for(let i=0;i<6;i++)net.request('bell');player.pos.x+=10;
for(const timer of timers.splice(0))timer.fn();assert.equal(hurts,1,'moving away during claw warning avoids its native hit');
player.pos.x-=10;game.run.company13.ringers={};player.dead=true;net.request('bell');assert.equal(calls,12,'dead bell request rejected');player.dead=false;
const wall=physics.addStaticBox(player.pos.x,.1,player.pos.z-.65,.5,1.4,.06);physics.world.step();net.request('bell');assert.equal(calls,12,'native wall rejects bell interaction');physics.removeCollider(wall);physics.world.step();
player.pos.y+=2;net.request('bell');assert.equal(calls,12,'wrong native floor rejects bell interaction');player.pos.y-=2;
player.pos.x+=10;net.request('bell');assert.equal(calls,12,'remote bell rejected');
api.dispose();player.pos.x-=10;game.hostSell=hostMethods.hostSell;game.hostSave=()=>{};game.run={phase:'company',credits:0,sold:0,daysLeft:3,buyRnd:1};
const zone=company.interactables.find(i=>i.type==='sellzone');let cargo=[{id:'sale38',type:'bolt',def:itemDef('bolt'),value:100,state:'world',obj:{position:zone.pos.clone()}}];
game.items={all:()=>cargo};net.on_('it',d=>{if(d.e==='rm')cargo=cargo.filter(it=>it.id!==d.id);});const nativeApi=installCompany13(game);
net.request('bell');assert.equal(game.hostData.selling,true,'physical delivery enters actual native sale transaction');
for(const timer of timers.splice(0))timer.fn();assert(game.run.credits>0&&game.run.sold>0,'actual native sale pays existing economy');assert.equal(cargo.length,0,'actual Session removal callback consumes sold cargo');assert.equal(game.run.company13.ringers.host.count,0,'real delivery calms claw discipline');
mods.emit('update',.016,game);const claw=company.group.getObjectByName('companyclaw38');assert(claw,'native company owns visible attack presentation');const resources=new Set();claw.traverse(o=>{assert(!o.isLight);if(o.geometry)resources.add(o.geometry);if(o.material)resources.add(o.material);});let disposed=0;for(const resource of resources)resource.addEventListener('dispose',()=>disposed++);
nativeApi.dispose();nativeApi.dispose();company.dispose(physics);assert.equal(disposed,resources.size,'claw presentation resources dispose exactly once');physics.world.free();net.clear();console.log('companybell38: native physical bell sale, guards, warned claw and escape delivery passed');
