import assert from 'node:assert/strict';
import './ship2_env.mjs';
const {register}=await import('node:module');register('data:text/javascript,'+encodeURIComponent("export async function load(u,c,n){if(u.endsWith('.css'))return{format:'module',source:'export default {};',shortCircuit:true};return n(u,c)}"));
const THREE=await import('three'),{Physics,initPhysics,G,groups}=await import('../../src/physics/physics.js');await initPhysics();
const {Emitter}=await import('../../src/core/events.js'),{buildShip}=await import('../../src/world/ship.js'),{installShipyard}=await import('../../src/game/shipyard.js'),{FLEET13,fleetLayout}=await import('../../src/game/fleet13_core.js');
const {installDeadletter24}=await import('../../src/game/deadletter24.js'),{actionMethods}=await import('../../src/game/actions.js');
const {installTrophy}=await import('../../src/game/cycle3_trophy.js'),K=await import('../../src/game/cycle3_core.js');
for(const hull of Object.keys(FLEET13)){
 const physics=new Physics(),scene=new THREE.Scene(),lights={add:e=>e,remove(){}},ship=buildShip({physics,scene,lightPool:lights}),mods=new Emitter();mods.itemModels=new Map();mods.soundGens=new Map();
 const player={pos:new THREE.Vector3(-3.4,.05,0),dead:false,indoor:false,heldItem:()=>null};const game={isHost:true,selfId:'H',time:0,ship,physics,scene,lights,mods,player,run:{phase:'orbit',moon:'hamsi',seed:1,sy:fleetLayout(hull),credits:100},profile:{shipyard:fleetLayout(hull),name:'Host'},camera:new THREE.PerspectiveCamera(),ui:{toast(){}},items:{hostSpawn(){},all:()=>[].values(),get:()=>null},creatures:{host:new Map(),views:new Map(),speedMul:(c,s)=>s},net:{on(){},on_(){},off(){},broadcast(){},sendTo(){},request(){}},aiPlayers:()=>[],later:f=>f(),broadcastRun(){},hostOnCreatureKilled(){}};
 const sy=installShipyard(game);game.deadletter24=installDeadletter24(game);
 const c3={game,mods,K,interFns:[],ticks:[],disposers:[],phaseFns:[],hostStartFns:[],host:()=>false,enabled:()=>false,cycle:()=>null,on(){}};const trophy=installTrophy(c3);for(const f of c3.ticks)f();
 game.interactablesNow=()=>{const out=[];mods.emit('interactables',out,game);for(const f of c3.interFns)f(out,player);return out;};physics.world.step();
 const body=physics.createKinematicCapsule(new THREE.Vector3(-3.4,.865,0),.5,.35,G.PLAYER,G.STATIC),cc=physics.world.createCharacterController(.01);cc.enableAutostep(.2,.3,true);physics.world.step();player.col=body.col;
 const walk=(x,z)=>{for(let i=0;i<200;i++){const p=body.body.translation(),dx=x-p.x,dz=z-p.z,d=Math.hypot(dx,dz);if(d<.04)break;const q=Math.min(.08,d)/d;cc.computeColliderMovement(body.col,{x:dx*q,y:-.012,z:dz*q},undefined,groups(G.PLAYER,G.STATIC));const m=cc.computedMovement();body.body.setNextKinematicTranslation({x:p.x+m.x,y:p.y+m.y,z:p.z+m.z});physics.world.step();}const p=body.body.translation();assert(Math.hypot(p.x-x,p.z-z)<.08,`${hull} native cockpit path blocked`);player.pos.set(p.x,p.y-.815,p.z);};
 walk(-4.7,0);for(const [x,z] of [[-4.8,1.3],[-4.65,2.05]]){walk(x,z);const point=game.deadletter24.entryPoint();game.camera.position.copy(player.pos).add(new THREE.Vector3(0,1.55,0));game.camera.lookAt(point);game.camera.updateMatrixWorld(true);const hit=actionMethods.findInteraction.call(game);assert(hit?.label.includes('Dead Letter'),`${hull}: actual selector chose ${hit?.label}`);assert(physics.lineOfSight(game.camera.position,point,G.STATIC|G.DOOR),'real entry LOS');}
 assert(scene.getObjectByName('deadletter25-entry'),'visible authored entry plate');const entry=game.interactablesNow().find(i=>i.label.includes('Dead Letter'));assert(!entry.noLos);game.deadletter24.dispose();assert(!scene.getObjectByName('deadletter25-entry'));trophy.dispose();for(const f of c3.disposers)f();sy.dispose();physics.world.removeCharacterController(cc);physics.removeBody(body.body);ship.group.removeFromParent();const geometries=new Set();ship.group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);});for(const geometry of geometries)geometry.dispose();physics.world.free();
}
console.log('deadletter25 entry: all4 native fleet hulls, standing cockpit routes/two approaches, real selector+trophy, LOS and owned plate cleanup PASS');
