import assert from 'node:assert/strict';
import {Emitter} from '../../src/core/events.js';
import './ship2_env.mjs';
const {register}=await import('node:module');register('data:text/javascript,'+encodeURIComponent("export async function load(u,c,n){if(u.endsWith('.css'))return{format:'module',source:'export default {};',shortCircuit:true};return n(u,c)}"));
const {UI}=await import('../../src/ui/ui.js');
const {installDeadletter24Draft}=await import('../../src/ui/deadletter24.js');
const {makeOffer}=await import('../../src/game/deadletter24_core.js');
const {setLang}=await import('../../src/core/i18n.js');
function node(){const classes=new Set(),listeners=new Map();return {children:[],style:{},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)},setAttribute(k,v){this[k]=v;},appendChild(n){this.children.push(n);n.parent=this;},remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);},addEventListener(k,f){listeners.set(k,f);},focus(){this.focused=true;},click(){listeners.get('click')?.();},get textContent(){return this.children.map(c=>c.textContent||'').join(' ');}};}
globalThis.document={createElement:node,createTextNode:text=>({textContent:text}),getElementById:()=>null,head:node()};
let unlocks=0,locks=0,blocked=false;const ui=Object.create(UI.prototype);Object.assign(ui,{panelOpen:null,overlay:node(),app:{input:{unlock(){unlocks++;blocked=true;},lock(){locks++;blocked=false;}},game:{player:{dead:false}}},fullscreenOpen:()=>false});
const game={ui,player:{dead:false},mods:new Emitter()},draft=installDeadletter24Draft(game),offer=makeOffer({level:20,nonce:9,floor:2,seed:123});
for(const lang of ['en','tr','ru']){setLang(lang);assert(draft.openDraft({offer,build:{},onChoose:()=>false}));assert(draft.isOpen());assert(blocked);assert.equal(ui.panelOpen.children[2].children.length,3);assert(ui.panelOpen.children[2].children[0].focused);assert(ui.panelOpen.textContent.includes('0 → 1 / 5'));draft.close();assert(!blocked);}
let choices=[];draft.openDraft({offer,onChoose:c=>{choices.push(c);return true;}});const button=ui.panelOpen.children[2].children[0];button.click();button.click();assert.equal(choices.length,1);assert.deepEqual(choices[0],{id:offer.choices[0].id,nonce:9,level:20,floor:2});assert(!draft.isOpen());assert(!blocked);
const nextOffer={...offer,nonce:10};draft.openDraft({offer,onChoose:()=>{draft.openDraft({offer:nextOffer,onChoose:()=>false});return true;}});ui.panelOpen.children[2].children[0].click();assert(draft.isOpen(),'synchronous authoritative next offer must not be closed by old choice callback');assert(ui.panelOpen.textContent.includes('PERSONAL')||ui.panelOpen.textContent.length>0);draft.close();
ui.panelOpen=node();assert.equal(draft.openDraft({offer,onChoose(){}}),false,'cannot replace another native panel');ui.panelOpen=null;game.director={chaseLevel:()=>.8};assert.equal(draft.openDraft({offer,onChoose(){}}),false,'does not obscure actual threat');game.deadletter24={combatPaused:()=>true};assert.equal(draft.openDraft({offer,onChoose(){}}),true,'native expedition pause makes the live-enemy draft safe');draft.close();game.deadletter24={combatPaused:()=>false};assert.equal(draft.openDraft({offer,onChoose(){}}),false,'unpaused rescue/threat still prevents modal');game.director=null;
game.deadletter24={active:()=>true,combatPaused:()=>true};assert(draft.openDraft({offer,onChoose(){}}));game.deadletter24.combatPaused=()=>false;game.mods.emit('update',.016,game);assert(!draft.isOpen(),'unpaused crew rescue releases the draft even with distant enemies');assert.equal(draft.openDraft({offer,onChoose(){}}),false);game.deadletter24.combatPaused=()=>true;game.player.downed=true;assert.equal(draft.openDraft({offer,onChoose(){}}),false);game.player.downed=false;assert(draft.openDraft({offer,onChoose(){}}));game.player.dead=true;game.mods.emit('update',.016,game);assert(!draft.isOpen());game.player.dead=false;game.deadletter24=null;
draft.openDraft({offer,onChoose(){}});ui.closePanel();assert.equal(draft.isOpen(),false,'native Escape close contract releases draft');draft.dispose();assert.equal(document.head.children.length,0,'owned style disposed');assert.equal(draft.openDraft({offer,onChoose(){}}),false);assert(unlocks>0&&locks>0);
console.log('deadletter24 UI: actual native panel input lifecycle,3localizedrank/effect cards, one dispatch, foreignpanel/threat guards and style disposal PASS');
