import assert from 'node:assert/strict';
import * as THREE from 'three';
import {Objectives} from '../../src/game/objectives.js';
import {installOneGoal} from '../../src/game/onegoal.js';
import {HUD} from '../../src/ui/hud.js';
import {Emitter,errLog} from '../../src/core/events.js';
import {initPhysics,Physics,G,groups,RAPIER} from '../../src/physics/physics.js';
import {CreatureManager} from '../../src/entities/creatures.js';
import {ItemManager} from '../../src/entities/items.js';
import {installDeadletter24,DL24_GEAR} from '../../src/game/deadletter24.js';
import {newProgress} from '../../src/game/deadletter24_core.js';
import {createDeadletter24Projectiles,DL24_TYPES} from '../../src/game/deadletter24_combat.js';
import {CREATURES} from '../../src/game/creatures.js';
import {generateLayout,buildFacility} from '../../src/world/facility.js';
import {buildCompany} from '../../src/world/company.js';
import {installCargo13} from '../../src/game/cargo13.js';
import {installFleet13} from '../../src/game/fleet13.js';
import {installHostMig} from '../../src/game/hostmig.js';
import {hostMethods} from '../../src/game/host.js';
import {LandingQueue} from '../../src/game/landingq.js';
await initPhysics();
const oldDoc=globalThis.document,oldWin=globalThis.window,oldWidth=globalThis.innerWidth,oldHeight=globalThis.innerHeight,nativeErrorCount=errLog.total;
globalThis.innerWidth=1280;globalThis.innerHeight=720;
const ctx=new Proxy({},{get:(o,k)=>k==='measureText'?()=>({width:10}):k==='createImageData'||k==='getImageData'?()=>({data:new Uint8ClampedArray(1<<22),width:64,height:64}):k==='createLinearGradient'||k==='createRadialGradient'?()=>({addColorStop(){}}):()=>{},set:()=>true});
const domRoot={appendChild(){}};
globalThis.document={body:domRoot,getElementById:()=>domRoot,createElement:()=>({style:{},width:64,height:64,getContext:()=>ctx,remove(){}})};
globalThis.window={crypto:globalThis.crypto,performance:globalThis.performance,__kefalMods:{itemModels:new Map(),creatureModels:new Map()},KefalAPI:{THREE}};
const physics=new Physics(),scene=new THREE.Scene(),mods=new Emitter(),handlers=new Map(),listeners=new Map(),sent=[],spawnLog=[];
let hits=0,mainKills=0,mainSaves=0;
const me={id:'host',pos:new THREE.Vector3(0,.05,0),eye:new THREE.Vector3(0,1.67,0),look:new THREE.Vector3(0,0,-1),zone:'out',dead:false,downed:false};
const peer={id:'peer',pos:new THREE.Vector3(1,.05,0),eye:new THREE.Vector3(1,1.67,0),look:new THREE.Vector3(0,0,-1),zone:'out',dead:false,downed:false};
const player={pos:me.pos,vel:new THREE.Vector3(),hp:83,yaw:0,dead:false,stamina:100,slots:[null,null,null,null],slot:0,teleport(p,yaw){this.pos.copy(p);this.yaw=yaw;me.eye.copy(p).y+=1.62;me.zone=p.y<-200?'in':'out';},heldItem(){return this.slots[this.slot]?game.items.get(this.slots[this.slot]):null;}};
const net={hostId:'host',selfId:'host',handlers,broadcast(k,d){sent.push([k,structuredClone(d)]);if(k==='cev'&&d.e==='sp'&&game.creatures.host.get(d.id)?.data.waveIndex!==undefined)spawnLog.push({floor:game.run.deadletter24?.floor,wave:game.run.deadletter24?.wave,time:game.time});if(k==='it')game.items.onEvent(d);if(k==='cev'&&d.e!=='sp')game.creatures.onEvent(d);if(k==='phase'){game.run.phase=d.phase;Object.assign(game.run,d);game.deadletter24?.onPhase(d);}for(const fn of listeners.get(k)||[])fn(d);},sendTo(id,k,d){if(k==='hurt')hits++;},send(){},sendRows(){},on_(k,fn){let xs=listeners.get(k)||[];xs.push(fn);listeners.set(k,xs);},off(k,fn){const key=k.startsWith('msg:')?k.slice(4):k;listeners.set(key,(listeners.get(key)||[]).filter(f=>f!==fn));},request(k,d){handlers.get(k)?.(d,'host');}};
const game={isHost:true,selfId:'host',time:0,scene,engine:{scene,camera:new THREE.PerspectiveCamera(),fx:{}},camera:new THREE.PerspectiveCamera(),mods,physics,player,remotes:new Map([['peer',{id:'peer',pos:peer.pos,hp:91,yaw:0}]]),world:{},run:{phase:'orbit',moon:'hamsi',seed:1235,time:480,weather:'clear',powerOn:true,runId:'native-checkpoint',day:1,daysLeft:3,credits:777,quota:330,sold:17,casino13:{chips:88}},net,lights:{add:e=>e,remove(){}},ui:{toast(){},hud:{setDead(){}}},env:{},
 ship:{spawns:[new THREE.Vector3(0,.05,0)],points:{terminal:new THREE.Vector3(0,1.1,0)}},stats:{maxHp:100,maxStamina:100,speedMul:1,armor:0},downed:{isDowned:id=>id==='host'?me.downed:peer.downed,S:{book:{clear(){}}}},
 aiPlayers:()=>[me,peer],aiPlayerById:id=>id==='host'?me:peer,hostHurtPlayer:()=>hits++,hostOnCreatureKilled:()=>mainKills++,onCreatureKilled(){},onItemHeld(it,id){if(id==='host')player.slots[0]=it.id;},onItemDropped(it,id){if(id==='host')for(let i=0;i<4;i++)if(player.slots[i]===it.id)player.slots[i]=null;},refreshStats(){},refreshHeldVisuals(){},broadcastRun(){},hostSave(){mainSaves++;},hostSetPhase:hostMethods.hostSetPhase,markRunSent(){},hostAnnounce(){},unloadMap(){this.world.facility?.dispose(physics);this.world.facility=null;this.world.moonId=null;},hostSetDoor(){}};
game.loadMapFor=function(run){return this.deadletter24?.loadMapFor(run);};game.applyRunState=function(d){Object.assign(this.run,d);this.deadletter24?.onState(this.run);};let reentrantStates=0;net.on_('gs',d=>{reentrantStates++;game.applyRunState(d);});game.broadcastRun=hostMethods.broadcastRun;game.run.cargo13={map:'native-company',p:[8,0,7],yaw:0,ids:[],driver:null};game.profile={};game.progress={save(){}};
game.items=new ItemManager(game);game.creatures=new CreatureManager(game);game.deadletter24=installDeadletter24(game);for(const fn of mods._h.get('objectives')||[])fn._src='deadletter24';game.onegoal=installOneGoal(game);const nativeObjectives=Object.create(Objectives.prototype);nativeObjectives.game=game;const nativeCargo=installCargo13(game),nativeFleet=installFleet13(game);mods.emit('registerHandlers',(k,fn)=>handlers.set(k,fn),game);
try{
 // Saved-session fixture: retirement blocks new admission, but must retain the
 // native map/cargo/exit/migration lifecycle for sessions already in progress.
 function resumeSavedSession(){
  const backup={run:structuredClone(game.run),items:game.items.serialize(),players:{}};
  for(const p of game.aiPlayers())backup.players[p.id]={p:p.pos.toArray(),yaw:p.id==='host'?player.yaw:0,hp:p.id==='host'?player.hp:game.remotes?.get(p.id)?.hp||100,dead:false};
  const token=`legacy-fixture:${game.time}`;
  const players={host:newProgress({seed:101,floor:0}),peer:newProgress({seed:102,floor:0})};
  game.hostSetPhase('deadletter',{moon:'deadletter24',deadletter24:{version:1,token,seed:123,floor:0,floorRev:1,stage:'intro',elapsed:0,wave:0,spawned:0,kills:0,rareDrops:0,players,backup}});
  game.deadletter24.onState();return game.deadletter24.active();
 }
 assert.equal(game.deadletter24.start(),false,'retired mode rejects direct start even with an eligible host');
 assert.equal(game.deadletter24.requestStart(),false,'retired mode rejects stale ship/start callbacks');
 assert.equal(game.deadletter24.enterFromMenu(),false,'retired mode rejects stale pause callbacks');
 const mainId=game.items.hostSpawn('copper',new THREE.Vector3(0,1,0),{value:42,holder:'host',bag:[{ty:'bolt',v:9}],battery:23});const before=game.items.serialize(),nativeRun=structuredClone(game.run);
 const admissionQueue=new LandingQueue();game.landQ=admissionQueue;admissionQueue.add('pending-map-fixture',()=>{});
 assert.equal(game.deadletter24.menuStatus().enabled,false);assert.equal(game.deadletter24.enterFromMenu(),false,'native menu entry cannot race a pending map build');admissionQueue.clear();
 player.downed=true;assert.equal(me.downed,false,'cached crew fixture still reports living standing host');assert.equal(game.deadletter24.start(),false,'current native local downed flag rejects stale cached crew admission');player.downed=false;
 game.destroyed=true;assert.equal(game.deadletter24.enterFromMenu(),false,'stale native menu callback cannot enter a destroyed session');delete game.destroyed;
 game.isHost=false;assert.equal(game.deadletter24.enterFromMenu(),false,'peer cannot start from menu');game.isHost=true;
 const dockState=game.run.fleet13;game.run.fleet13={docked:true};assert.equal(game.deadletter24.start(),false,'fresh dock must finish actual boarding first');game.run.fleet13=dockState;
 assert.deepEqual(game.items.serialize(),before,'all rejected entries preserve actual item custody');assert.equal(mainSaves,0,'rejected menu entries never save or replace campaign state');
 assert(resumeSavedSession());assert(reentrantStates>0,'real cargo unload synchronously enters native gs/fleet applyRunState');assert.equal(scene.children.filter(o=>o===game.world.facility.group).length,1,'one actual facility despite reentrant delivery');assert.equal(game.run.phase,'deadletter');assert(game.world.facility.lab.arena);assert.equal(game.run.credits,777);assert.equal(game.run.casino13.chips,88);assert.equal(game.items.get(mainId),undefined);assert(game.items.all().some(it=>it.type===DL24_GEAR));assert.equal(mainSaves,0,'saved session loading does not create a new campaign save');
 const producedIntro=nativeObjectives.compute();for(const density of ['standard','full']){const displayed=game.onegoal.shown(producedIntro,density);assert.equal(displayed.length,2,'actual mode producer survives native OneGoal two-row display');assert(displayed.some(row=>/LMB/.test(row.text)&&/R:/.test(row.text)),'native display retains real combat controls');}assert.equal(game.onegoal.shown(producedIntro,'minimal').length,1);
 const objectiveRows=[];mods.emit('objectives',(line,role)=>objectiveRows.push([line,role]),game,'deadletter');assert.equal(objectiveRows.length,2,'mode owns two readable objective rows');assert(game.deadletter24.presentationQuiet(),'real entry is a quiet introductory presentation');me.downed=true;const rescueRows=[];mods.emit('objectives',(line,role)=>rescueRows.push([line,role]),game,'deadletter');assert.equal(rescueRows[1][1],'warn');assert(/recover|revive/i.test(rescueRows[1][0]),'rescue tells crew to recover instead of meet at cabinet');assert(!game.deadletter24.presentationQuiet());const displayedRescue=game.onegoal.shown(nativeObjectives.compute(),'standard');assert.equal(displayedRescue[0].kind,'warn');assert(/Recover/.test(displayedRescue[0].text));assert.equal(displayedRescue.length,2);me.downed=false;
 const st=game.deadletter24.state(),a=game.deadletter24.statsProgress().anchor;player.teleport(new THREE.Vector3().fromArray(a).setY(-299.98),0);peer.pos.copy(me.pos).add(new THREE.Vector3(1,0,0));peer.eye.copy(peer.pos).y+=1.62;peer.zone='in';
 function tick(n=1){for(let i=0;i<n;i++){game.time+=1/60;physics.step(1/60);game.deadletter24.hostTick(1/60);if(game.deadletter24.active()&&!game.deadletter24.combatPaused())game.creatures.hostUpdate(1/60);mods.emit('update',1/60,game);}}
 tick(400);assert(!game.deadletter24.presentationQuiet(),'native first wave is real combat attention');assert.equal(st.stage,'wave');assert.equal(spawnLog.length,2,'first manual-aim opening has only two scheduled arrivals by6.67s');assert(spawnLog[1].time-spawnLog[0].time>=2.58,'initial first-floor native stagger is2.6s');assert([...game.creatures.host.values()].some(c=>game.deadletter24.ownsCreature(c)),'actual host scheduler spawns a native killable actor');assert(!game.creatures.hostSpawn('scuttler',me.pos),'campaign ambient spawn rejected');
 // Actual host simulated card traverses native Rapier world; no client-reported hit.
 const spots=game.world.facility.lab.spawnSpots;let spot;
 for(const row of spots){const q=new THREE.Vector3(row.x,row.y,row.z);const p=q.clone().add(new THREE.Vector3(0,0,3));if(game.world.facility.nav.walkableAt(p.x,p.z)&&physics.lineOfSight(p.clone().add(new THREE.Vector3(0,1.62,0)),q.clone().add(new THREE.Vector3(0,1,0)),G.STATIC|G.DOOR)){spot=q;player.teleport(p,0);break;}}
 assert(spot);const c=game.creatures.hostSpawn('dl24_sorter',spot,{zone:'in',state:'warning',data:{dl24Token:st.token,floorRev:st.floorRev}});assert(c);game.balance={scale:()=>({speed:99,hp:99}),speedCap:()=>99};assert.equal(game.creatures.speedMul(c,3),3,'campaign speed multiplier cannot bleed into mode');delete game.balance;
 me.look.copy(spot.clone().add(new THREE.Vector3(0,.95,0)).sub(me.eye).normalize());game.camera.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),me.look);
 const oldHp=c.hp;assert(game.deadletter24.attack());tick(12);assert(c.hp<oldHp,'real projectile applies native damage');
 // Actual HUD admission while attention is hot: action feedback must not become stale routine backlog.
 const actionHud=Object.create(HUD.prototype),actionShown=[];actionHud.game=game;actionHud.cc={busy:()=>false};actionHud.gate=()=>false;actionHud.pendingToasts=[];actionHud.$={toasts:{children:[]}};actionHud.showToast=(...row)=>actionShown.push(row);const originalToast=game.ui.toast;game.director={chaseLevel:()=>.8};game.ui.toast=(...args)=>actionHud.toast(...args);game.ui.toast('Ordinary unrelated notice','info');assert.equal(actionHud.pendingToasts.length,1);
 // Real synchronous host receipt: blocked special keeps selection and does not consume cadence.
 tick(31);assert(game.deadletter24.special());const actualRay=physics.raycast.bind(physics);physics.raycast=()=>({normal:{y:0}});
 assert.equal(game.deadletter24.attack(),false,'blocked native muzzle rejects special');physics.raycast=actualRay;assert.equal(game.deadletter24.attack(),false,'bounded rejection retry avoids held-input network spam');tick(8);
 assert(game.deadletter24.attack(),'same selected special retries after short rejection backoff');
 const receipt=sent.filter(([k,d])=>k==='dl24fx'&&d.op==='throwAck').at(-1)[1];assert.equal(receipt.kind,'return');assert.equal(receipt.accepted,true);
 assert(game.deadletter24.special());const requestsBefore=sent.filter(([k,d])=>k==='dl24fx'&&d.op==='throwAck').length;
 assert.equal(game.deadletter24.attack(),false,'known special cooldown does not dispatch or consume selection');assert.equal(sent.filter(([k,d])=>k==='dl24fx'&&d.op==='throwAck').length,requestsBefore);
 tick(50);assert.equal(game.deadletter24.attack(),false,'cooldown feedback becomes visible after bounded notice throttle');
 game.time+=4.01;assert(game.deadletter24.attack(),'selected special survives cooldown');assert.equal(sent.filter(([k,d])=>k==='dl24fx'&&d.op==='throwAck').at(-1)[1].kind,'return');
 // Remote dispatch remains pending until an addressed host receipt; other owners cannot consume it.
 tick(31);game.time+=4.01;assert(game.deadletter24.special());const nativeRequest=net.request;let outbound;net.request=(key,data)=>{outbound=data;};game.isHost=false;assert(game.deadletter24.attack());game.isHost=true;net.request=nativeRequest;
 net.broadcast('dl24fx',{op:'throwAck',token:st.token,rev:st.floorRev,owner:'peer',seq:outbound.seq,kind:outbound.kind,accepted:true,wait:4});assert.equal(game.deadletter24.attack(),false,'foreign addressed receipt cannot clear in-flight throw');assert(game.deadletter24.hostReq(outbound,'host'),'native host validates remote-shaped request');assert(!game.deadletter24.hostReq(outbound,'host'),'same accepted request cannot replay');tick(31);assert(game.deadletter24.attack());assert.equal(sent.filter(([k,d])=>k==='dl24fx'&&d.op==='throwAck').at(-1)[1].kind,'std','only actual owner accepted receipt consumes special');
 assert(actionShown.some(row=>row[0]==='Returning slip'&&row[1]==='warn'&&row[2]===1200),'actual R selection reaches hot HUD immediately');assert(actionShown.some(row=>row[0].startsWith('Special ready in')&&row[1]==='warn'&&row[2]===1200),'actual cooldown reaches hot HUD immediately');assert(actionShown.some(row=>row[0].startsWith('Throw blocked')&&row[1]==='warn'&&row[2]===1200),'actual rejected throw reaches hot HUD immediately');assert.deepEqual(actionHud.pendingToasts.map(row=>row[0]),['Ordinary unrelated notice'],'combat feedback never enters deferred routine queue');game.ui.toast=originalToast;delete game.director;
 const pr=st.players.host,peerPr=st.players.peer;game.creatures.damage(c.id,999,'host');assert(pr.xp>0);assert.equal(mainKills,0);assert.equal(sent.filter(([k,d])=>k==='cev'&&d.e==='die').at(-1)[1].xp,0);
 for(const mob of [...game.creatures.host.values()])if(!mob.dead)game.creatures.damage(mob.id,999,'host');assert(pr.offer);assert.equal(pr.offer.choices.length,3);assert.equal(peerPr.offer.choices.length,3);assert(game.deadletter24.combatPaused());const hpNow=player.hp;tick(100);assert.equal(player.hp,hpNow);
 let seq=100;const choice={op:'choose',token:st.token,rev:st.floorRev,seq:seq++,...pr.offer,id:pr.offer.choices[0].id};assert(game.deadletter24.hostReq(choice,'host'));assert(!game.deadletter24.hostReq(choice,'host'),'replay rejected');assert(!game.deadletter24.hostReq({...choice,seq:seq++,nonce:999},'peer'),'other personal nonce rejected');
 function drain(){for(const id of ['host','peer']){const p=st.players[id];while(p.pending){const offer=p.offer;assert(game.deadletter24.hostReq({op:'choose',token:st.token,rev:st.floorRev,seq:seq++,...offer,id:offer.choices[0].id},id));}}}
 drain();assert(!game.deadletter24.combatPaused());assert(game.deadletter24.stats(game.stats).maxHp>=100);assert(game.deadletter24.playerDamage('host',999)<=40);
 // Full three-wave and native boss flow through real installer scheduling. Damage
 // uses native manager calls as a labelled accelerated-combat fixture, not a fake boss death/state.
 let guard=0;while(st.stage!=='boss'&&guard++<1800){tick(20);for(const mob of [...game.creatures.host.values()])if(!mob.dead&&!mob.def.boss)game.creatures.damage(mob.id,999,'host');drain();}
 const warden=game.creatures.host.get(st.boss);assert(warden&&!warden.dead,'scheduler produces living native Warden');const born=warden.pos.clone();const initialDistance=warden.pos.distanceTo(me.pos);tick(240);assert(warden.pos.distanceTo(born)>1,'actual native Warden traverses generated map without forced AI state');assert(warden.pos.distanceTo(me.pos)<initialDistance,'actual chase closes distance to standing target');
 // Native telegraph affords a physically walked retreat; no player teleport during chase.
 let approach=0;while(warden.state!=='windup'&&approach++<1500)tick();assert.equal(warden.state,'windup','sustained chase reaches real warned strike');
 const {body:retreatBody,col:retreatCol}=physics.createKinematicCapsule({x:me.pos.x,y:me.pos.y+.92,z:me.pos.z},.56,.34,G.PLAYER,G.STATIC|G.DOOR),retreatController=physics.createController();physics.step(1/60);let retreatHits=0;const originalHurt=game.hostHurtPlayer;game.hostHurtPlayer=(id,...args)=>{if(id==='host')retreatHits++;originalHurt(id,...args);};
 const retreatDir=me.pos.clone().sub(warden.pos).setY(0).normalize();
 for(let frame=0;frame<88;frame++){retreatController.computeColliderMovement(retreatCol,{x:retreatDir.x*8.2/60,y:0,z:retreatDir.z*8.2/60},undefined,groups(G.PLAYER,G.STATIC|G.DOOR));const movement=retreatController.computedMovement(),position=retreatBody.translation(),next={x:position.x+movement.x,y:position.y+movement.y,z:position.z+movement.z};retreatBody.setNextKinematicTranslation(next);retreatBody.setTranslation(next,true);physics.world.propagateModifiedBodyPositionsToColliders?.();me.pos.set(next.x,next.y-.92,next.z);me.eye.copy(me.pos).y+=1.62;tick();}
 assert.equal(retreatHits,0,'actual sprint retreat escapes telegraphed strike');game.hostHurtPlayer=originalHurt;physics.removeBody(retreatBody);
 me.downed=true;peer.downed=true;game.creatures.hostUpdate(1/60);assert.equal(warden.target,null,'native Warden never targets downed crew');me.downed=false;peer.downed=false;
 // True host card trajectory kill; fixed standing aim fixture is not a survival/playtest claim.
 let throws=0;while(!warden.dead&&throws++<300){const direction=warden.pos.clone().add(new THREE.Vector3(0,1,0)).sub(me.eye).normalize();me.look.copy(direction);game.camera.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),direction);assert(game.deadletter24.hostReq({op:'throw',token:st.token,rev:st.floorRev,seq:seq++,dir:direction.toArray(),kind:'std'},'host'));tick(31);}
 assert(warden.dead,'real native projectile damage kills Warden without damage injection');drain();
 assert.deepEqual([0,1,2].map(w=>spawnLog.filter(s=>s.floor===0&&s.wave===w).length),[3,5,7],'first floor has actual3/5/7 scheduled waves');assert.equal(st.stage,'cleared','native wave scheduler reaches actual killed boss');assert(st.boss);assert.equal(mainKills,0);drain();player.teleport(new THREE.Vector3().fromArray(a).setY(-299.98),0);peer.pos.copy(me.pos).add(new THREE.Vector3(1,0,0));peer.eye.copy(peer.pos).y+=1.62;
 assert(game.deadletter24.hostReq({op:'next',token:st.token,rev:st.floorRev,seq:seq++},'host'));assert.equal(st.floor,1);assert.equal(game.world.facility.lab.id,'mutedswitch24');assert(!game.deadletter24.hostReq({...choice,seq:seq++,rev:1},'host'),'old floor request rejected');
 tick(800);const later=spawnLog.filter(s=>s.floor===1&&s.wave===0);assert.equal(later.length,5,'second floor retains the previous five-actor opening');assert(later[1].time-later[0].time>=1.58&&later[1].time-later[0].time<1.7,'later floor native stagger remains1.6s');const b=game.deadletter24.statsProgress().anchor;player.teleport(new THREE.Vector3().fromArray(b).setY(-299.98),0);assert(game.deadletter24.hostReq({op:'exit',token:st.token,rev:st.floorRev,seq:seq++},'host'));assert.equal(game.run.phase,'orbit');const campaignRows=nativeObjectives.compute();assert(!campaignRows.some(row=>row.src==='deadletter24'),'exit restores native campaign objectives');assert(game.onegoal.shown(campaignRows,'standard').length>0);assert.deepEqual(game.run,nativeRun);assert.deepEqual(game.items.serialize(),before,'exact main item IDs/held bag/battery restored');assert.equal(player.hp,83);assert.equal(mainKills,0);assert(!game.deadletter24.acceptItemEvent({e:'sp',ty:DL24_GEAR}));
 game.opts={deadletter:true};player.inShip=true;mods.emit('update',1/60,game);assert.equal(game.run.phase,'orbit','accepted manual menu entry consumes title auto-start intent and cannot reopen after native exit');delete player.inShip;game.opts={};
 const savedStorage=globalThis.localStorage,writes=[];globalThis.localStorage={getItem:()=>null,setItem:(...a)=>writes.push(a)};game.opts={deadletter:true};hostMethods.hostSave.call(game);assert.equal(writes.length,0,'native temporary expedition hostSave preserves all campaign slots even after exit');game.opts={};globalThis.localStorage=savedStorage;

 // A genuine peer installer builds its streamed floor and restores real Company
 // geometry before original held/inventory rows and player position are applied.
 const peerPhysics=new Physics(),peerScene=new THREE.Scene(),peerMods=new Emitter(),peerListeners=new Map();
 const peerMode=structuredClone(st);peerMode.backup.run={...nativeRun,phase:'company',moon:'hq'};
 const pp={...player,pos:new THREE.Vector3(1,.05,0),vel:new THREE.Vector3(),slots:[null,null,null,null],slot:2,hp:91,stamina:61,teleport(p,yaw){this.pos.copy(p);this.yaw=yaw;}};
 const pg={...game,isHost:false,selfId:'peer',physics:peerPhysics,scene:peerScene,engine:{scene:peerScene,fx:{}},player:pp,mods:peerMods,world:{},remotes:new Map([['host',{pos:new THREE.Vector3(),hp:83}]]),run:{...nativeRun,phase:'deadletter',moon:'deadletter24',deadletter24:peerMode},net:{on_(k,fn){peerListeners.set(k,fn);},off(){},send(){},broadcast(){}},aiPlayers:()=>[],onItemHeld(){},onItemDropped(){},unloadMap(){this.world.facility?.dispose(peerPhysics);this.world.facility=null;this.world.moonId=null;},loadMapFor(run){if(run.phase!=='company')return;this.world.company=buildCompany({physics:peerPhysics,lightPool:this.lights});this.world.moonId=run.moon;peerScene.add(this.world.company.group);}};
 pg.items=new ItemManager(pg);pg.creatures=new CreatureManager(pg);pg.deadletter24=installDeadletter24(pg);pg.deadletter24.onState();assert(pg.world.facility.lab);assert.equal(pg.world.company,undefined);
 pg.run={...peerMode.backup.run};pg.deadletter24.onPhase({phase:'company'});peerListeners.get('dl24end')({token:peerMode.token,backup:peerMode.backup});assert(pg.world.company,'peer restores actual native Company builder');for(let i=0;i<4;i++)peerPhysics.step(1/60);
 const ground=peerPhysics.raycast(new THREE.Vector3(16,6,4),new THREE.Vector3(0,-1,0),10,G.STATIC|G.DOOR);assert(ground,'Company colliders really exist after peer exit');assert.equal(pg.items.get(mainId).holder,'host');assert.equal(pp.hp,91);assert.equal(pp.stamina,61);assert.equal(pg.run.credits,777);const restoredCount=pg.items.all().length;peerListeners.get('dl24end')({token:peerMode.token,backup:peerMode.backup});assert.equal(pg.items.all().length,restoredCount,'same completed end packet cannot restore twice');
 pg.deadletter24.dispose();pg.items.clearAll();pg.world.company.dispose(peerPhysics);peerPhysics.world.free();
 // Wipe restores only through host tick; a death callback cannot restore and then
 // have the native death tail destroy that restored state.
 me.dead=false;peer.dead=false;assert(resumeSavedSession());me.downed=true;peer.downed=true;tick(250);assert.equal(game.run.phase,'orbit');assert.deepEqual(game.items.serialize(),before);me.downed=false;peer.downed=false;

 // Drive the real native host-migration installer, not an invented mode event.
 assert(resumeSavedSession());const originalNetOn=net.on;net.on=()=>()=>{};net.relayTypes=new Set();net.players=new Map([['peer',{id:'peer',name:'Departed'}],['host',{id:'host',name:'Successor'}]]);net.isHost=false;net.hostId='peer';net.hostEpoch=0;net.connected=true;net.lost=new Set();net.transport={peers:new Set(['peer'])};net.migrateTo=(id,epoch)=>{net.isHost=true;net.hostId=id;net.hostEpoch=epoch;game.isHost=true;return net.players.get('peer');};
 game.isHost=false;game.freshDayStats=()=>({collected:0,kills:0,deaths:[],per:{}});game.registerHandlers=()=>mods.emit('registerHandlers',(k,fn)=>handlers.set(k,fn),game);game.hostOnPlayerLeave=()=>{};game.opts={};game.config={};game.voice={removePeer(){}};
 const hm=installHostMig(game);hm.becomeHost();assert.equal(game.run.phase,'orbit','actual HMX takeover safely ends mode');assert.deepEqual(game.run,nativeRun);assert.equal(game.items.get(mainId).holder,'host');assert.equal(player.hp,83);hm.dispose();net.on=originalNetOn;
 // Fresh installed mode with an actual native checkpoint tests Host-form launch intent.
 game.deadletter24.dispose();game.deadletter24=installDeadletter24(game);game.opts={deadletter:true};player.inShip=true;game.ui.blocksInput=()=>false;
 const restoredFleet=game.run.fleet13;game.run.fleet13={docked:true};mods.emit('update',1/60,game);assert.equal(game.run.phase,'orbit','automatic mode waits for genuine fleet boarding');game.run.fleet13=restoredFleet;
 game.terminal={active:true};mods.emit('update',1/60,game);assert.equal(game.run.phase,'orbit','automatic mode waits for an open terminal');game.terminal.active=false;
 game.minigame={};mods.emit('update',1/60,game);assert.equal(game.run.phase,'orbit','automatic mode waits for a native minigame');game.minigame=null;
 game.ui.blocksInput=()=>true;mods.emit('update',1/60,game);assert.equal(game.run.phase,'orbit','automatic mode waits for owned modal input');game.ui.blocksInput=()=>false;
 mods.emit('update',1/60,game);assert.equal(game.run.phase,'orbit','retired title intent cannot auto-launch');assert(resumeSavedSession());const freshAnchor=game.deadletter24.statsProgress().anchor;player.teleport(new THREE.Vector3().fromArray(freshAnchor).setY(-299.98),0);
 assert(game.deadletter24.exitFromMenu());assert.equal(game.run.phase,'orbit');player.inShip=true;mods.emit('update',1/60,game);assert.equal(game.run.phase,'orbit','automatic launch is consumed exactly once across actual exit');assert.deepEqual(game.items.serialize(),before,'automatic mode returns exact campaign/native fixture cargo');
 game.opts={};delete player.inShip;delete game.ui.blocksInput;delete game.terminal;game.minigame=null;
 // Captured browser poses, labelled seed17 reconstruction (not the unretained browser RNG seed).
 const slidePhysics=new Physics(),slideScene=new THREE.Scene(),slideFac=buildFacility(generateLayout(17,'deadletter24',.8),{physics:slidePhysics,lightPool:game.lights});slideScene.add(slideFac.group);
 const standing={id:'slidehost',pos:new THREE.Vector3(-.7891812324523926,-299.98,-25.8360004425),eye:new THREE.Vector3(-.7891812324523926,-298.36,-25.8360004425),zone:'in',look:new THREE.Vector3(0,0,-1),dead:false,downed:false};
 const sg={...game,time:0,selfId:standing.id,scene:slideScene,engine:{scene:slideScene},physics:slidePhysics,world:{facility:slideFac},mods:new Emitter(),run:{phase:'deadletter',deadletter24:{token:'slide-regression',floorRev:1,players:{}}},net:{broadcast(){},on_(){},off(){},sendTo(){},send(){},sendRows(){}},aiPlayers:()=>[standing],aiPlayerById:id=>id===standing.id?standing:null,downed:{isDowned:()=>false},hostHurtPlayer(){},hostSetDoor(id,open){const d=slideFac.doors.find(q=>q.id===id);if(d){d.open=open;if(open&&d.collider){slidePhysics.removeCollider(d.collider);d.collider=null;}}}};sg.creatures=new CreatureManager(sg);sg.deadletter24=installDeadletter24(sg);sg.run.deadletter24.players[standing.id]={build:{},pending:0};
 const auditor=sg.creatures.hostSpawn('dl24_auditor',new THREE.Vector3(-46.70567762297785,-300,-31.09130048246664),{zone:'in',state:'warning',data:{dl24Token:'slide-regression',floorRev:1}});assert(auditor);const capturedDistance=auditor.pos.distanceTo(standing.pos);let penetrating=0,minDistance=capturedDistance,frameCasts=0,maxFrameCasts=0;const nativeSlideCast=slidePhysics.world.castShape.bind(slidePhysics.world);slidePhysics.world.castShape=(...args)=>{frameCasts++;return nativeSlideCast(...args);};for(const type of DL24_TYPES){assert.equal(CREATURES[type].noScan,true);assert.equal(CREATURES[type].noIdentify,true);}
 for(let frame=0;frame<3600;frame++){frameCasts=0;sg.time+=1/60;slidePhysics.step(1/60);sg.creatures.hostUpdate(1/60);maxFrameCasts=Math.max(maxFrameCasts,frameCasts);minDistance=Math.min(minDistance,auditor.pos.distanceTo(standing.pos));const shape=new RAPIER.Capsule(Math.max(.01,auditor.def.height/2-auditor.def.radius),auditor.def.radius);if(slidePhysics.world.intersectionWithShape({x:auditor.pos.x,y:auditor.pos.y+auditor.def.height/2+.02,z:auditor.pos.z},{x:0,y:0,z:0,w:1},shape,undefined,groups(0xffff,G.STATIC|G.DOOR)))penetrating++;}
 assert(minDistance<capturedDistance-8,`captured native Auditor resumes substantial pursuit instead of perpetual divider rollback: start=${capturedDistance} min=${minDistance} pos=${auditor.pos.toArray()} state=${auditor.state} target=${auditor.target}`);assert.equal(penetrating,0,'complete native creature capsule never penetrates static/doors during slide pursuit');assert(maxFrameCasts<=3,'blocked movement has at most two additional native casts');console.log('captured Auditor reconstruction',JSON.stringify({seconds:60,startDistance:capturedDistance,minDistance,final:auditor.pos.toArray(),penetrating,maxFrameCasts}));sg.deadletter24.dispose();sg.creatures.clearAll();slideFac.dispose(slidePhysics);slidePhysics.world.free();
 // Native geometry negative control: a thin true collider prevents card damage.
 const wall=physics.addStaticBox(0,1,0,.06,2,2);physics.step(1/60);const actor={id:'test',pos:new THREE.Vector3(1,0,0),def:{height:2,radius:.4},dead:false};let landed=0;const projectileGame={...game,isHost:true,scene,creatures:{host:new Map([['test',actor]])}};let projectiles;projectiles=createDeadletter24Projectiles(projectileGame,{ownsCreature:()=>true,damage:()=>landed++,send:d=>projectiles?.event(d)});projectiles.fire({origin:new THREE.Vector3(-1,1,0),direction:new THREE.Vector3(1,0,0),owner:'host'});for(let i=0;i<10;i++)projectiles.update(1/60);assert.equal(landed,0);physics.removeCollider(wall);physics.step(1/60);projectiles.fire({origin:new THREE.Vector3(-1,1,0),direction:new THREE.Vector3(1,0,0),owner:'host'});for(let i=0;i<10;i++)projectiles.update(1/60);assert.equal(landed,1,'removing real wall permits actual trajectory');projectiles.clear();
 assert.equal(errLog.total,nativeErrorCount,'native event callbacks must not hide caught fixture or product errors');
 console.log('deadletter24: native scheduled waves/boss, card/wall damage, personal drafts/replay, pause, floor, exact campaign custody and wipe pass');
}catch(e){console.error('ACTUAL ERROR',e);throw e;}finally{game.onegoal.dispose();nativeFleet.dispose();nativeCargo.dispose();game.deadletter24.dispose();game.items.clearAll();game.world.facility?.dispose(physics);game.creatures.clearAll();try{physics.world.free();}catch{}globalThis.document=oldDoc;globalThis.window=oldWin;globalThis.innerWidth=oldWidth;globalThis.innerHeight=oldHeight;}
