import assert from 'node:assert/strict';
import * as THREE from 'three';
import {Emitter} from '../../src/core/events.js';
import {initPhysics,Physics,G} from '../../src/physics/physics.js';
import {CreatureManager} from '../../src/entities/creatures.js';
import {ItemManager} from '../../src/entities/items.js';
import {installDeadletter24,DL24_GEAR} from '../../src/game/deadletter24.js';
import {createDeadletter24Projectiles,DL24_TYPES} from '../../src/game/deadletter24_combat.js';
import {CREATURES} from '../../src/game/creatures.js';
import {buildCompany} from '../../src/world/company.js';
import {installCargo13} from '../../src/game/cargo13.js';
import {installFleet13} from '../../src/game/fleet13.js';
import {installHostMig} from '../../src/game/hostmig.js';
import {hostMethods} from '../../src/game/host.js';
await initPhysics();
const oldDoc=globalThis.document,oldWin=globalThis.window;
const ctx=new Proxy({},{get:(o,k)=>k==='measureText'?()=>({width:10}):k==='createImageData'||k==='getImageData'?()=>({data:new Uint8ClampedArray(1<<22),width:64,height:64}):k==='createLinearGradient'||k==='createRadialGradient'?()=>({addColorStop(){}}):()=>{},set:()=>true});
globalThis.document={createElement:()=>({style:{},width:64,height:64,getContext:()=>ctx})};
globalThis.window={crypto:globalThis.crypto,performance:globalThis.performance,__kefalMods:{itemModels:new Map(),creatureModels:new Map()},KefalAPI:{THREE}};
const physics=new Physics(),scene=new THREE.Scene(),mods=new Emitter(),handlers=new Map(),listeners=new Map(),sent=[],spawnLog=[];
let hits=0,mainKills=0,mainSaves=0;
const me={id:'host',pos:new THREE.Vector3(0,.05,0),eye:new THREE.Vector3(0,1.67,0),look:new THREE.Vector3(0,0,-1),zone:'out',dead:false,downed:false};
const peer={id:'peer',pos:new THREE.Vector3(1,.05,0),eye:new THREE.Vector3(1,1.67,0),look:new THREE.Vector3(0,0,-1),zone:'out',dead:false,downed:false};
const player={pos:me.pos,vel:new THREE.Vector3(),hp:83,yaw:0,dead:false,stamina:100,slots:[null,null,null,null],slot:0,teleport(p,yaw){this.pos.copy(p);this.yaw=yaw;me.eye.copy(p).y+=1.62;me.zone=p.y<-200?'in':'out';},heldItem(){return this.slots[this.slot]?game.items.get(this.slots[this.slot]):null;}};
const net={hostId:'host',selfId:'host',handlers,broadcast(k,d){sent.push([k,structuredClone(d)]);if(k==='cev'&&d.e==='sp'&&game.creatures.host.get(d.id)?.data.waveIndex!==undefined)spawnLog.push({floor:game.run.deadletter24?.floor,wave:game.run.deadletter24?.wave,time:game.time});if(k==='it')game.items.onEvent(d);if(k==='cev'&&d.e!=='sp')game.creatures.onEvent(d);if(k==='phase'){game.run.phase=d.phase;Object.assign(game.run,d);game.deadletter24?.onPhase(d);}for(const fn of listeners.get(k)||[])fn(d);},sendTo(id,k,d){if(k==='hurt')hits++;},send(){},sendRows(){},on_(k,fn){let xs=listeners.get(k)||[];xs.push(fn);listeners.set(k,xs);},off(k,fn){const key=k.startsWith('msg:')?k.slice(4):k;listeners.set(key,(listeners.get(key)||[]).filter(f=>f!==fn));},request(k,d){handlers.get(k)?.(d,'host');}};
const game={isHost:true,selfId:'host',time:0,scene,engine:{scene,camera:new THREE.PerspectiveCamera(),fx:{}},camera:new THREE.PerspectiveCamera(),mods,physics,player,remotes:new Map([['peer',{id:'peer',pos:peer.pos,hp:91,yaw:0}]]),world:{},run:{phase:'orbit',moon:'hamsi',seed:1235,time:480,weather:'clear',powerOn:true,runId:'native-checkpoint',day:1,daysLeft:3,credits:777,quota:330,sold:17,casino13:{chips:88}},net,lights:{add:e=>e,remove(){}},ui:{toast(){},hud:{setDead(){}}},env:{},
 ship:{spawns:[new THREE.Vector3(0,.05,0)],points:{terminal:new THREE.Vector3(0,1.1,0)}},stats:{maxHp:100,maxStamina:100,speedMul:1,armor:0},downed:{isDowned:id=>id==='host'?me.downed:peer.downed,S:{book:{clear(){}}}},
 aiPlayers:()=>[me,peer],aiPlayerById:id=>id==='host'?me:peer,hostHurtPlayer:()=>hits++,hostOnCreatureKilled:()=>mainKills++,onCreatureKilled(){},onItemHeld(it,id){if(id==='host')player.slots[0]=it.id;},onItemDropped(it,id){if(id==='host')for(let i=0;i<4;i++)if(player.slots[i]===it.id)player.slots[i]=null;},refreshStats(){},refreshHeldVisuals(){},broadcastRun(){},hostSave(){mainSaves++;},hostSetPhase:hostMethods.hostSetPhase,markRunSent(){},hostAnnounce(){},unloadMap(){this.world.facility?.dispose(physics);this.world.facility=null;this.world.moonId=null;},hostSetDoor(){}};
game.loadMapFor=function(run){return this.deadletter24?.loadMapFor(run);};game.applyRunState=function(d){Object.assign(this.run,d);this.deadletter24?.onState(this.run);};let reentrantStates=0;net.on_('gs',d=>{reentrantStates++;game.applyRunState(d);});game.broadcastRun=hostMethods.broadcastRun;game.run.cargo13={map:'native-company',p:[8,0,7],yaw:0,ids:[],driver:null};game.profile={};game.progress={save(){}};
game.items=new ItemManager(game);game.creatures=new CreatureManager(game);game.deadletter24=installDeadletter24(game);const nativeCargo=installCargo13(game),nativeFleet=installFleet13(game);mods.emit('registerHandlers',(k,fn)=>handlers.set(k,fn),game);
try{
 const mainId=game.items.hostSpawn('copper',new THREE.Vector3(0,1,0),{value:42,holder:'host',bag:[{ty:'bolt',v:9}],battery:23});const before=game.items.serialize(),nativeRun=structuredClone(game.run);
 assert(game.deadletter24.start());assert(reentrantStates>0,'real cargo unload synchronously enters native gs/fleet applyRunState');assert.equal(scene.children.filter(o=>o===game.world.facility.group).length,1,'one actual facility despite reentrant delivery');assert.equal(game.run.phase,'deadletter');assert(game.world.facility.lab.arena);assert.equal(game.run.credits,777);assert.equal(game.run.casino13.chips,88);assert.equal(game.items.get(mainId),undefined);assert(game.items.all().some(it=>it.type===DL24_GEAR));assert.equal(mainSaves,1);
 const st=game.deadletter24.state(),a=game.deadletter24.statsProgress().anchor;player.teleport(new THREE.Vector3().fromArray(a).setY(-299.98),0);peer.pos.copy(me.pos).add(new THREE.Vector3(1,0,0));peer.eye.copy(peer.pos).y+=1.62;peer.zone='in';
 function tick(n=1){for(let i=0;i<n;i++){game.time+=1/60;physics.step(1/60);game.deadletter24.hostTick(1/60);if(game.deadletter24.active()&&!game.deadletter24.combatPaused())game.creatures.hostUpdate(1/60);mods.emit('update',1/60,game);}}
 tick(400);assert.equal(st.stage,'wave');assert.equal(spawnLog.length,2,'first manual-aim opening has only two scheduled arrivals by6.67s');assert(spawnLog[1].time-spawnLog[0].time>=2.58,'initial first-floor native stagger is2.6s');assert([...game.creatures.host.values()].some(c=>game.deadletter24.ownsCreature(c)),'actual host scheduler spawns a native killable actor');assert(!game.creatures.hostSpawn('scuttler',me.pos),'campaign ambient spawn rejected');
 // Actual host simulated card traverses native Rapier world; no client-reported hit.
 const spots=game.world.facility.lab.spawnSpots;let spot;
 for(const row of spots){const q=new THREE.Vector3(row.x,row.y,row.z);const p=q.clone().add(new THREE.Vector3(0,0,3));if(game.world.facility.nav.walkableAt(p.x,p.z)&&physics.lineOfSight(p.clone().add(new THREE.Vector3(0,1.62,0)),q.clone().add(new THREE.Vector3(0,1,0)),G.STATIC|G.DOOR)){spot=q;player.teleport(p,0);break;}}
 assert(spot);const c=game.creatures.hostSpawn('dl24_sorter',spot,{zone:'in',state:'warning',data:{dl24Token:st.token,floorRev:st.floorRev}});assert(c);game.balance={scale:()=>({speed:99,hp:99}),speedCap:()=>99};assert.equal(game.creatures.speedMul(c,3),3,'campaign speed multiplier cannot bleed into mode');delete game.balance;
 me.look.copy(spot.clone().add(new THREE.Vector3(0,.95,0)).sub(me.eye).normalize());game.camera.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),me.look);
 const oldHp=c.hp;assert(game.deadletter24.attack());tick(12);assert(c.hp<oldHp,'real projectile applies native damage');
 const pr=st.players.host,peerPr=st.players.peer;game.creatures.damage(c.id,999,'host');assert(pr.xp>0);assert.equal(mainKills,0);assert.equal(sent.filter(([k,d])=>k==='cev'&&d.e==='die').at(-1)[1].xp,0);
 for(const mob of [...game.creatures.host.values()])if(!mob.dead)game.creatures.damage(mob.id,999,'host');assert(pr.offer);assert.equal(pr.offer.choices.length,3);assert.equal(peerPr.offer.choices.length,3);assert(game.deadletter24.combatPaused());const hpNow=player.hp;tick(100);assert.equal(player.hp,hpNow);
 let seq=100;const choice={op:'choose',token:st.token,rev:st.floorRev,seq:seq++,...pr.offer,id:pr.offer.choices[0].id};assert(game.deadletter24.hostReq(choice,'host'));assert(!game.deadletter24.hostReq(choice,'host'),'replay rejected');assert(!game.deadletter24.hostReq({...choice,seq:seq++,nonce:999},'peer'),'other personal nonce rejected');
 function drain(){for(const id of ['host','peer']){const p=st.players[id];while(p.pending){const offer=p.offer;assert(game.deadletter24.hostReq({op:'choose',token:st.token,rev:st.floorRev,seq:seq++,...offer,id:offer.choices[0].id},id));}}}
 drain();assert(!game.deadletter24.combatPaused());assert(game.deadletter24.stats(game.stats).maxHp>=100);assert(game.deadletter24.playerDamage('host',999)<=40);
 // Full three-wave and native boss flow through real installer scheduling. Damage
 // uses native manager calls as a labelled accelerated-combat fixture, not a fake boss death/state.
 let guard=0;while(st.stage!=='cleared'&&guard++<1800){tick(20);for(const mob of [...game.creatures.host.values()])if(!mob.dead)game.creatures.damage(mob.id,999,'host');drain();}
 assert.deepEqual([0,1,2].map(w=>spawnLog.filter(s=>s.floor===0&&s.wave===w).length),[3,5,7],'first floor has actual3/5/7 scheduled waves');assert.equal(st.stage,'cleared','native wave scheduler reaches actual killed boss');assert(st.boss);assert.equal(mainKills,0);drain();player.teleport(new THREE.Vector3().fromArray(a).setY(-299.98),0);peer.pos.copy(me.pos).add(new THREE.Vector3(1,0,0));peer.eye.copy(peer.pos).y+=1.62;
 assert(game.deadletter24.hostReq({op:'next',token:st.token,rev:st.floorRev,seq:seq++},'host'));assert.equal(st.floor,1);assert.equal(game.world.facility.lab.id,'mutedswitch24');assert(!game.deadletter24.hostReq({...choice,seq:seq++,rev:1},'host'),'old floor request rejected');
 tick(800);const later=spawnLog.filter(s=>s.floor===1&&s.wave===0);assert.equal(later.length,5,'second floor retains the previous five-actor opening');assert(later[1].time-later[0].time>=1.58&&later[1].time-later[0].time<1.7,'later floor native stagger remains1.6s');const b=game.deadletter24.statsProgress().anchor;player.teleport(new THREE.Vector3().fromArray(b).setY(-299.98),0);assert(game.deadletter24.hostReq({op:'exit',token:st.token,rev:st.floorRev,seq:seq++},'host'));assert.equal(game.run.phase,'orbit');assert.deepEqual(game.run,nativeRun);assert.deepEqual(game.items.serialize(),before,'exact main item IDs/held bag/battery restored');assert.equal(player.hp,83);assert.equal(mainKills,0);assert(!game.deadletter24.acceptItemEvent({e:'sp',ty:DL24_GEAR}));

 // A genuine peer installer builds its streamed floor and restores real Company
 // geometry before original held/inventory rows and player position are applied.
 const peerPhysics=new Physics(),peerScene=new THREE.Scene(),peerMods=new Emitter(),peerListeners=new Map();
 const peerMode=structuredClone(st);peerMode.backup.run={...nativeRun,phase:'company',moon:'hq'};
 const pp={...player,pos:new THREE.Vector3(1,.05,0),vel:new THREE.Vector3(),slots:[null,null,null,null],slot:2,hp:91,stamina:61,teleport(p,yaw){this.pos.copy(p);this.yaw=yaw;}};
 const pg={...game,isHost:false,selfId:'peer',physics:peerPhysics,scene:peerScene,engine:{scene:peerScene,fx:{}},player:pp,mods:peerMods,world:{},remotes:new Map([['host',{pos:new THREE.Vector3(),hp:83}]]),run:{...nativeRun,phase:'deadletter',moon:'deadletter24',deadletter24:peerMode},net:{on_(k,fn){peerListeners.set(k,fn);},off(){},send(){},broadcast(){}},aiPlayers:()=>[],onItemHeld(){},onItemDropped(){},unloadMap(){this.world.facility?.dispose(peerPhysics);this.world.facility=null;this.world.moonId=null;},loadMapFor(run){if(run.phase!=='company')return;this.world.company=buildCompany({physics:peerPhysics,lightPool:this.lights});this.world.moonId=run.moon;peerScene.add(this.world.company.group);}};
 pg.items=new ItemManager(pg);pg.creatures=new CreatureManager(pg);pg.deadletter24=installDeadletter24(pg);pg.deadletter24.onState();assert(pg.world.facility.lab);assert.equal(pg.world.company,undefined);
 pg.run={...peerMode.backup.run};pg.deadletter24.onPhase({phase:'company'});peerListeners.get('dl24end')({token:peerMode.token,backup:peerMode.backup});assert(pg.world.company,'peer restores actual native Company builder');for(let i=0;i<4;i++)peerPhysics.step(1/60);
 const ground=peerPhysics.raycast(new THREE.Vector3(16,6,4),new THREE.Vector3(0,-1,0),10,G.STATIC|G.DOOR);assert(ground,'Company colliders really exist after peer exit');assert.equal(pg.items.get(mainId).holder,'host');assert.equal(pp.hp,91);assert.equal(pp.stamina,61);assert.equal(pg.run.credits,777);const restoredCount=pg.items.all().length;peerListeners.get('dl24end')({token:peerMode.token,backup:peerMode.backup});assert.equal(pg.items.all().length,restoredCount,'same completed end packet cannot restore twice');
 pg.deadletter24.dispose();pg.items.clearAll();pg.world.company.dispose(peerPhysics);peerPhysics.world.free();
 // Wipe restores only through host tick; a death callback cannot restore and then
 // have the native death tail destroy that restored state.
 me.dead=false;peer.dead=false;assert(game.deadletter24.start());me.downed=true;peer.downed=true;tick(250);assert.equal(game.run.phase,'orbit');assert.deepEqual(game.items.serialize(),before);me.downed=false;peer.downed=false;

 // Drive the real native host-migration installer, not an invented mode event.
 assert(game.deadletter24.start());const originalNetOn=net.on;net.on=()=>()=>{};net.relayTypes=new Set();net.players=new Map([['peer',{id:'peer',name:'Departed'}],['host',{id:'host',name:'Successor'}]]);net.isHost=false;net.hostId='peer';net.hostEpoch=0;net.connected=true;net.lost=new Set();net.transport={peers:new Set(['peer'])};net.migrateTo=(id,epoch)=>{net.isHost=true;net.hostId=id;net.hostEpoch=epoch;game.isHost=true;return net.players.get('peer');};
 game.isHost=false;game.freshDayStats=()=>({collected:0,kills:0,deaths:[],per:{}});game.registerHandlers=()=>mods.emit('registerHandlers',(k,fn)=>handlers.set(k,fn),game);game.hostOnPlayerLeave=()=>{};game.opts={};game.config={};game.voice={removePeer(){}};
 const hm=installHostMig(game);hm.becomeHost();assert.equal(game.run.phase,'orbit','actual HMX takeover safely ends mode');assert.deepEqual(game.run,nativeRun);assert.equal(game.items.get(mainId).holder,'host');assert.equal(player.hp,83);hm.dispose();net.on=originalNetOn;
 // Native geometry negative control: a thin true collider prevents card damage.
 const wall=physics.addStaticBox(0,1,0,.06,2,2);physics.step(1/60);const actor={id:'test',pos:new THREE.Vector3(1,0,0),def:{height:2,radius:.4},dead:false};let landed=0;const projectileGame={...game,isHost:true,scene,creatures:{host:new Map([['test',actor]])}};let projectiles;projectiles=createDeadletter24Projectiles(projectileGame,{ownsCreature:()=>true,damage:()=>landed++,send:d=>projectiles?.event(d)});projectiles.fire({origin:new THREE.Vector3(-1,1,0),direction:new THREE.Vector3(1,0,0),owner:'host'});for(let i=0;i<10;i++)projectiles.update(1/60);assert.equal(landed,0);physics.removeCollider(wall);physics.step(1/60);projectiles.fire({origin:new THREE.Vector3(-1,1,0),direction:new THREE.Vector3(1,0,0),owner:'host'});for(let i=0;i<10;i++)projectiles.update(1/60);assert.equal(landed,1,'removing real wall permits actual trajectory');projectiles.clear();
 console.log('deadletter24: native scheduled waves/boss, card/wall damage, personal drafts/replay, pause, floor, exact campaign custody and wipe pass');
}catch(e){console.error('ACTUAL ERROR',e);throw e;}finally{nativeFleet.dispose();nativeCargo.dispose();game.deadletter24.dispose();game.items.clearAll();game.world.facility?.dispose(physics);game.creatures.clearAll();try{physics.world.free();}catch{}globalThis.document=oldDoc;globalThis.window=oldWin;}
