import assert from 'node:assert/strict';
const f=await import('../../src/game/endless41_core.js').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
assert.equal(typeof f.newEndless41,'function','Endless requires isolated authoritative temporary progression');
const a=f.newEndless41('RUN',123),b=f.newEndless41('RUN',123);
assert.deepEqual(a,b);assert.equal(a.grace,90);assert.equal(a.shipHp,300);
const p=f.admitPlayer41(a,'P','profile');assert.equal(p.level,1);assert.equal(f.admitPlayer41(a,'P','profile'),p);
f.gainXp41(a,'P',30);assert.equal(p.level,2);assert.equal(p.offer.choices.length,3);assert.equal(new Set(p.offer.choices.map(c=>c.id)).size,3);
const offer=structuredClone(p.offer),choice=offer.choices[0];
assert(!f.resolveOffer41(a,'unknown',{...offer,id:choice.id},'choose'));
assert(!f.resolveOffer41(a,'P',{...offer,token:'old',id:choice.id},'choose'));
assert(!f.resolveOffer41(a,'P',{...offer,id:'invented'},'choose'));
assert(f.resolveOffer41(a,'P',{...offer,id:choice.id},'choose'));assert.equal(p.perks[choice.id],1);
assert(!f.resolveOffer41(a,'P',{...offer,id:choice.id},'choose'),'replay cannot buy another rank');
f.gainXp41(a,'P',100);const before=structuredClone(p.offer);assert(f.resolveOffer41(a,'P',before,'reroll'));assert.equal(p.rerolls,1);assert(!f.resolveOffer41(a,'P',before,'skip'));assert(f.resolveOffer41(a,'P',p.offer,'skip'));
const gameProfile={id:'owner',name:'Owner',level:90,coins:999,rpg:{nodes:['power']},shipyard:{m:{}}};
const copy=f.sessionProfile41(gameProfile,{host:true,mode:'endless'});assert.notEqual(copy,gameProfile);assert.equal(copy._noSave,true);assert.equal(copy.level,1);assert.equal(gameProfile.level,90);
const join=f.sessionProfile41(gameProfile,{host:false});assert.equal(join.level,90);assert.equal(join._noSave,true);f.resetEndlessProfile41(join);assert.equal(join.level,1);assert.equal(join.id,'owner');assert.equal(gameProfile.coins,999);
assert.equal(f.sessionProfile41(gameProfile,{host:true}),gameProfile);
const {createRpgController}=await import('../../src/game/rpgctl.js');const pending=f.sessionProfile41(gameProfile,{host:false}),ctl=createRpgController(pending);pending.codex={moons:{},scrap:{}};pending.crew={xp:0,members:{}};pending.weekly={boards:{}};pending.login={day:1};pending.achievements={};const shapes=[pending.codex,pending.crew,pending.weekly,pending.login,pending.achievements];f.resetEndlessProfile41(pending,{preserveExtensions:true});assert.deepEqual([pending.codex,pending.crew,pending.weekly,pending.login,pending.achievements],shapes,'late reset preserves installed extension shapes and references');assert.equal(ctl.role(),null,'initialized unknown-peer controller survives authoritative temporary-profile reset');assert.deepEqual(ctl.state().nodes,[]);const {shouldRun}=await import('../../src/game/onboard_core.js');assert.equal(shouldRun({profile:pending,isHost:true,phase:'orbit',day:1,quotaIndex:0}).run,false,'real menu Endless boot skips Hiring Day without a DEV shortcut');assert.equal(pending.prestige.stars,0);
for(const n of [NaN,Infinity,-10])assert.equal(f.gainXp41(a,'P',n),false);
console.log('PASS endless41 seeded distinct offers, finite branches, stale/replay/unknown guards and profile isolation');
