import './ship2_env.mjs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {Physics,initPhysics} from '../../src/physics/physics.js';
import {generateLayout,buildFacility} from '../../src/world/facility.js';
import {hazardPlan38,pullClear38,installHazard38} from '../../src/game/hazard38.js';
import {Emitter} from '../../src/core/events.js';
import {Session} from '../../src/net/session.js';
import {hostMethods} from '../../src/game/host.js';
import {HoldBook} from '../../src/game/balance_rules.js';
import {buildHazards38} from '../../src/models/hazards38.js';
await initPhysics();const physics=new Physics(),layout=generateLayout(42,'factory',.68),facility=buildFacility(layout,{physics,lightPool:{add:x=>x,remove(){}}});physics.world.step();
const game={physics,world:{facility},items:{all:()=>[]},descent21:{plan:()=>({roomId:0})}};
const plan=hazardPlan38(game);assert(plan?.ceiling,'native reachable room has real ceiling attachment');
const c=plan.ceiling,p={pos:new THREE.Vector3(c.x,c.y,c.z)};
assert(pullClear38(game,p,p.pos.clone().add(new THREE.Vector3(0,.05,0))),'native standing capsule has a clear short upward pull');
const obstruction=physics.addStaticBox(c.x,c.y+1.86,c.z,.6,.025,.6);physics.world.step();assert(!pullClear38(game,p,p.pos.clone().add(new THREE.Vector3(0,.1,0))),'native capsule ceiling obstruction prevents pulling through geometry');physics.removeCollider(obstruction);
const root=new THREE.Group(),model=buildHazards38(root,c,plan.voidSpot),resources=new Set();root.traverse(o=>{assert(!o.isLight);if(o.geometry)resources.add(o.geometry);if(o.material)resources.add(o.material);});let disposed=0;for(const r of resources)r.addEventListener('dispose',()=>disposed++);model.dispose();model.dispose();assert.equal(disposed,resources.size);assert.equal(root.children.length,0);
const mods=new Emitter(),net=new Session({strategy:'local',isHost:true,code:'hazard38',profile:{}});net.selfId='host';
const actor={id:'host',pos:new THREE.Vector3(c.x,c.y,c.z),zone:'in',dead:false,inShip:false};let holds=0,hurt=0,removed=[];
net.on_('hold',()=>holds++);net.on_('hurt',()=>hurt++);net.on_('it',d=>{if(d.e==='rm')removed.push(d.id);});
const live={...game,mods,net,time:0,selfId:'host',isHost:true,run:{runId:'hazard',day:1,phase:'moon',moon:'hamsi',seed:42},world:{...game.world,moonId:'hamsi',seed:42,descent21Depth:2},aiPlayers:()=>[actor],hostHoldPlayer:hostMethods.hostHoldPlayer,hostHurtPlayer:hostMethods.hostHurtPlayer,broadcastRun(){},hostSave(){}};
const api=installHazard38(live);mods.emit('update',.1,live);live.time=.7;mods.emit('update',.1,live);assert(holds>0&&hurt>0,'real Session receives native hold and bounded hurt');
const heldBefore=holds;actor.dead=true;live.time=.8;mods.emit('update',.1,live);assert.equal(holds,heldBefore,'dead crew cannot be caught');actor.dead=false;
live.balRules={book:new HoldBook()};live.balRules.book.free('host',.8);live.time=.9;mods.emit('update',.1,live);assert.equal(holds,heldBefore,'native balance immunity prevents renewed tongue catches');delete live.balRules;
const v=api.plan.voidSpot;assert(v,'native optional side room exists');live.time=36;mods.emit('update',.1,live);assert.equal(live.run.hazard38.stage,'warning');
const cargo=[{id:'scrap',type:'bolt',value:10,def:{kind:'scrap'},obj:{position:new THREE.Vector3(v.x,v.y,v.z)}},{id:'core',type:'reactor',value:500,def:{kind:'scrap'},obj:{position:new THREE.Vector3(v.x,v.y,v.z)}}];
live.items={all:()=>cargo};live.time=42;mods.emit('update',.1,live);assert.equal(live.run.hazard38.stage,'active');assert.deepEqual(removed,['scrap'],'native remove message only targets loose scrap and preserves reactor');
api.dispose();net.clear();
facility.dispose(physics);physics.world.free();console.log('hazard38: native ceiling attachment, capsule swept pull obstruction and once-only model disposal passed');
