import assert from 'node:assert/strict';
import {createInventoryFeedback16} from '../../src/game/inventory_feedback16.js';
import {installLoaner,loanerNeed} from '../../src/game/loaner.js';
import {Emitter} from '../../src/core/events.js';
const copper={id:'copper',value:30,type:'copper',holder:'me',state:'held',inv:{k:'bag'},def:{kind:'scrap',name:'Copper'}};
const torch={id:'torch',type:'flashlight',state:'held',holder:'me',battery:10,def:{kind:'tool',name:'Flashlight'}};
const all=[copper,torch],toasts=[],drops=[];
const game={selfId:'me',player:{pos:{x:0,y:0,z:0},slots:['torch',null,null,null],heldItem(){return all.find(it=>it.id===this.slots[0]);}},settings:{keys:{inventory:'KeyB',drop:'KeyH',hotbar2:'Digit7'}},items:{all:()=>all},ui:{toast:m=>toasts.push(m)},dropHeld(){drops.push(this.player.heldItem()?.id);}};
const original=game.dropHeld,api=createInventoryFeedback16(game);
assert.equal(api.location({id:'pending'}),'Carrying','unassigned held item cannot imply Hotbar 0');
api.confirmed({...copper,id:'free-kit',value:0});api.confirmed({...copper,id:'soul',soulbound:true});api.confirmed({...copper,id:'body',type:'body'});api.confirmed({...copper,id:'remote',holder:'friend'});assert.equal(toasts.length,0,'remote, zero-value gifts, bound gear and bodies are not extraction salvage');
api.confirmed(copper); assert.match(toasts.at(-1),/bag.*\[B\].*\[H\]/);assert.equal(game.player.slots[0],'torch','feedback cannot displace selected gear');
api.confirmed(copper);assert.equal(toasts.length,1,'duplicate host-held replay is quiet');
game.dropHeld();assert.deepEqual(drops,['torch'],'drop remains native selected tool');assert.match(toasts.at(-1),/Salvage.*bag/);
game.dropHeld();assert.equal(toasts.length,2,'drop reminder bounded');
copper.inv=null;game.player.slots[1]='copper';api.changed();assert.match(toasts.at(-1),/hotbar 2.*\[7\]/);assert.equal(game.player.slots[0],'torch');
copper.value=0;copper.inv={k:'bag'};game.player.slots[1]=null;const quiet=createInventoryFeedback16(game);const count=toasts.length;game.dropHeld();assert.equal(toasts.length,count,'zero-value bag item must not trigger drop reminder');quiet.dispose();
api.dispose();assert.equal(game.dropHeld,original,'lifecycle restores hook');
copper.value=30;
const mods=new Emitter(),spawned=[],sent=[];
Object.assign(game,{mods,isHost:true,remotes:new Map([['friend',{}]]),world:{facility:{}},onboard:{fr:{stage:()=> 'fresh'}},net:{broadcast:(...a)=>sent.push(a)}});
game.items.hostSpawn=(type,pos,opts)=>{const id=`loan${spawned.length}`;spawned.push({id,type,pos,opts});return id;};game.items.get=id=>spawned.find(i=>i.id===id);
assert.equal(loanerNeed(game),1,'charged carried purchased torch excludes one crew loan');
torch.battery=0;assert.equal(loanerNeed(game),2,'exhausted light still needs assistance');
const floor={id:'floor',type:'proflash',state:'world',battery:20,obj:{position:{x:0,y:0,z:0}}};all.push(floor);assert.equal(loanerNeed(game),1,'available charged ship-floor torch covers one missing crew');
const loan=installLoaner(game);mods.emit('phase','landing',game);mods.emit('phase','moon',game);assert.equal(spawned.length,1);assert.equal(spawned[0].opts.battery,70);assert.equal(sent.filter(x=>x[0]==='sys').length,1);
mods.emit('phase','takeoff',game);assert.equal(sent.filter(x=>x[1]?.e==='rm').length,1,'only temporary loan is removed');
torch.battery=30;mods.emit('phase','landing',game);mods.emit('phase','moon',game);assert.equal(spawned.length,1,'adequately lit crew receives no redundant loan');assert.equal(sent.filter(x=>x[0]==='sys').length,1,'no false floor-loan announcement');
loan.dispose();console.log('inventory feedback and conditional loaner tests passed');
