import assert from 'node:assert/strict';
import './ship2_env.mjs';
import * as THREE from 'three';
import {generateLayout,buildFacility} from '../../src/world/facility.js';
import {initPhysics,Physics,G,groups,RAPIER} from '../../src/physics/physics.js';
import {buildDescent21} from '../../src/world/descent21.js';
import {LAB24_IDS} from '../../src/world/interiors/deadletter24.js';
import {LAB24_MOON_DEFS,LAB24_FIELD_MOON_DEFS,registerLab24Moons} from '../../src/game/lab24_moons.js';
import {MOONS,MOON_ORDER} from '../../src/game/moons.js';
await initPhysics();
function walk(ph,L,path,label){assert(path.length>1,label+' path exists');const start=path[0],actor=ph.createKinematicCapsule(new THREE.Vector3(start.x,L.y+.92,start.z),.56,.34,G.PLAYER,G.STATIC),cc=ph.createController(.02);cc.enableAutostep(.2,.3,true);ph.world.step();try{for(const target of path.slice(1)){for(let k=0,max=Math.ceil(Math.hypot(target.x-actor.body.translation().x,target.z-actor.body.translation().z)/.1)+160;k<max;k++){const p=actor.body.translation(),dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz);if(d<.08)break;const q=Math.min(.1,d)/d;cc.computeColliderMovement(actor.col,{x:dx*q,y:-.012,z:dz*q},undefined,groups(G.PLAYER,G.STATIC));const m=cc.computedMovement();actor.body.setNextKinematicTranslation({x:p.x+m.x,y:p.y+m.y,z:p.z+m.z});ph.world.step();}const p=actor.body.translation();assert(Math.hypot(p.x-target.x,p.z-target.z)<.12,label+' body route at '+JSON.stringify(target)+' actual '+JSON.stringify(p));}}finally{ph.removeBody(actor.body);ph.world.removeCharacterController(cc);}}
let total=0;
for(const id of LAB24_IDS)for(const [seed,size] of [[17,1.1],[42,1.1],[77,.75]]){
 const L=generateLayout(seed,id,size),ph=new Physics(),fac=buildFacility(L,{physics:ph,lightPool:{add:e=>e,remove(){}}});ph.world.step();const lab=fac.lab;assert.equal(lab.id,id);assert(lab.arena?.radius>=3.2);assert(lab.spawnSpots.length>=10);assert(lab.cover.length>=2);assert(lab.metrics.batches<=5);assert.equal(lab.metrics.emitters,0);assert(lab.metrics.triangles<1200);assert(!fac.doors.some(d=>d.kind==='door'&&d.locked&&!d.info?.shortcut&&!d.info?.treasure&&!d.info?.arena),'ordinary main graph needs no core/key lock');
 const distance=path=>path.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-path[i].x,p.z-path[i].z),0);assert(distance(lab.routes.covered)>distance(lab.routes.exposed)+1,'covered detour is a distinct longer route');walk(ph,L,lab.routes.exposed,id+'/direct');walk(ph,L,lab.routes.covered,id+'/covered');walk(ph,L,[...lab.routes.covered].reverse(),id+'/return');
 for(let i=0;i<8;i++){const a=i*Math.PI/4,p={x:lab.arena.x+Math.cos(a)*lab.arena.radius,z:lab.arena.z+Math.sin(a)*lab.arena.radius};assert(fac.nav.walkableAt(p.x,p.z),'broad boss arena floor continuous');let blocked=false;ph.world.intersectionsWithShape({x:p.x,y:L.y+.94,z:p.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.56,.35),()=>{blocked=true;return false;},undefined,groups(G.PLAYER,G.STATIC));assert(!blocked,'boss arena perimeter body-clear');}
 for(const p of lab.spawnSpots){assert(fac.nav.findPath(lab.arena.x,lab.arena.z,p.x,p.z,90000),'native mob navigation connects each authored spawn');let blocked=false;ph.world.intersectionsWithShape({x:p.x,y:L.y+.94,z:p.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.56,.35),()=>{blocked=true;return false;},undefined,groups(G.PLAYER,G.STATIC));assert(!blocked,'standing native creature spawn clear');}
 const cover=lab.cover[0],delta=new THREE.Vector3(cover.size[0]+.5,0,0),origin=new THREE.Vector3(cover.x,cover.y,cover.z).sub(delta);assert(ph.raycast(origin,new THREE.Vector3(1,0,0),delta.length()+1,G.STATIC),'cover is physically solid');assert(!fac.nav.walkableAt(cover.x,cover.z),'cover native navigation agrees');
 const lobby=buildDescent21({facility:fac,physics:ph,floor:2});assert(lobby,'actual safe return cabin exists');ph.world.step();for(const route of lobby.plan.routeProof.spawnPaths)walk(ph,L,route,id+'/cabin');lobby.dispose();
 const resources=new Set();fac.group.getObjectByName('lab24-'+id).traverse(o=>{if(o.geometry)resources.add(o.geometry);if(o.material)resources.add(o.material);});assert(resources.size>=6,'actual authored geometry/material ownership captured');let released=0;for(const r of resources)r.addEventListener('dispose',()=>released++);fac.dispose(ph);assert.equal(released,resources.size);assert.equal(ph.info.size,0,'all native/cover/lift colliders disposed');ph.world.free();total++;
}
registerLab24Moons();for(const def of LAB24_MOON_DEFS){assert.equal(MOONS[def.id].interior,def.interior);assert(def.instance&&def.deadletter24);assert.equal(def.power,0);assert(!MOON_ORDER.includes(def.id),'empty trial excluded from native route list');}
for(const def of LAB24_FIELD_MOON_DEFS){assert(MOON_ORDER.includes(def.id));assert(!def.instance&&!def.deadletter24);assert(def.power>0&&def.scrapCount[0]>=12&&Object.keys(def.creatures).length>=6,'ordinary expedition has native loot and finite ambient budget');assert(LAB24_IDS.includes(MOONS[def.id].interior));}
console.log(`lab24: PASS (${total} real facilities, native direct/cover/return/cabin controllers, solid cover/nav, spawn clearance and cleanup)`);
