import assert from 'node:assert/strict';
import './ship2_env.mjs';
import * as THREE from 'three';
import {generateLayout,buildFacility} from '../../src/world/facility.js';
import {initPhysics,Physics,G,groups,RAPIER} from '../../src/physics/physics.js';
import {buildDescent21} from '../../src/world/descent21.js';
import {LAB24_IDS} from '../../src/world/interiors/deadletter24.js';
import {LAB24_MOON_DEFS,LAB24_FIELD_MOON_DEFS,registerLab24Moons} from '../../src/game/lab24_moons.js';
import {createDeadletter24Projectiles} from '../../src/game/deadletter24_combat.js';
import {deadletter24Cabinet} from '../../src/game/deadletter24_view.js';
import {getLang,setLang} from '../../src/core/i18n.js';
import {MOONS,MOON_ORDER} from '../../src/game/moons.js';
await initPhysics();
function walk(ph,L,path,label){assert(path.length>1,label+' path exists');const start=path[0],actor=ph.createKinematicCapsule(new THREE.Vector3(start.x,L.y+.92,start.z),.56,.34,G.PLAYER,G.STATIC),cc=ph.createController(.02);cc.enableAutostep(.2,.3,true);ph.world.step();try{for(const target of path.slice(1)){for(let k=0,max=Math.ceil(Math.hypot(target.x-actor.body.translation().x,target.z-actor.body.translation().z)/.1)+160;k<max;k++){const p=actor.body.translation(),dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz);if(d<.08)break;const q=Math.min(.1,d)/d;cc.computeColliderMovement(actor.col,{x:dx*q,y:-.012,z:dz*q},undefined,groups(G.PLAYER,G.STATIC));const m=cc.computedMovement();actor.body.setNextKinematicTranslation({x:p.x+m.x,y:p.y+m.y,z:p.z+m.z});ph.world.step();}const p=actor.body.translation();assert(Math.hypot(p.x-target.x,p.z-target.z)<.12,label+' body route at '+JSON.stringify(target)+' actual '+JSON.stringify(p));}}finally{ph.removeBody(actor.body);ph.world.removeCharacterController(cc);}}
function coverProof(ph,L,cover,id){
 const origin=(eye)=>new THREE.Vector3(cover.x,L.y+eye,cover.z-1.6),end=(eye)=>new THREE.Vector3(cover.x,L.y+eye,cover.z+1.6),low=id==='deadletter24';
 assert.equal(ph.lineOfSight(origin(1.62),end(1.62),G.STATIC|G.DOOR),low,'standing cover LOS reflects actual low/tall height');assert.equal(ph.lineOfSight(origin(.95),end(.95),G.STATIC|G.DOOR),false,'crouched eye is protected by actual case/partition');
 for(const [half,y]of [[.56,.92],[.22,.58]]){let blocked=false;const o=origin(0);ph.world.intersectionsWithShape({x:o.x,y:L.y+y,z:o.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(half,.34),()=>{blocked=true;return false;},undefined,groups(G.PLAYER,G.STATIC));assert(!blocked,'standing/crouched body fits real cover approach');}
 for(const eye of [1.62,.95]){let hits=0;const target={id:'cover-target',pos:new THREE.Vector3(cover.x,L.y,cover.z+1.6),def:{height:2,radius:.4},dead:false},g={isHost:true,physics:ph,scene:new THREE.Scene(),creatures:{host:new Map([[target.id,target]])}};let projectiles;projectiles=createDeadletter24Projectiles(g,{ownsCreature:()=>true,damage:()=>hits++,send:d=>projectiles?.event(d)});const o=origin(eye),aim=target.pos.clone().add(new THREE.Vector3(0,1,0)).sub(o).normalize();projectiles.fire({origin:o,direction:aim,owner:'host'});for(let n=0;n<30;n++)projectiles.update(1/60);assert.equal(hits,low&&eye===1.62?1:0,'native card trajectory follows low/tall crouch-cover decision');projectiles.clear();assert.equal(g.scene.children.length,0);}
}
let total=0;
for(const id of LAB24_IDS)for(const [seed,size] of [[17,1.1],[42,1.1],[77,.75]]){
 const L=generateLayout(seed,id,size),ph=new Physics(),fac=buildFacility(L,{physics:ph,lightPool:{add:e=>e,remove(){}}});ph.world.step();const lab=fac.lab;assert.equal(lab.id,id);assert(lab.arena?.radius>=3.2);assert(lab.spawnSpots.length>=10);assert(lab.cover.length>=2);assert(lab.metrics.batches<=5);assert.equal(lab.metrics.emitters,0);assert.equal(lab.metrics.atlasPixels,512*128);assert(lab.landmark.kind);assert.equal(lab.landmark.coveredDirection,'west');assert.equal(lab.landmark.directDirection,id==='permissions24'?'east':'south');assert.equal(lab.landmark.lowCover,id==='deadletter24');assert(fac.nav.walkableAt(lab.landmark.junction.x,lab.landmark.junction.z),'landmark is at native route fork');assert.equal(lab.landmark.junction.z,lab.arena.z);assert.equal(lab.landmark.junction.x,lab.arena.x);assert.equal(lab.bossSpots.length,8);assert(lab.metrics.triangles<1200);assert(!fac.doors.some(d=>d.kind==='door'&&d.locked&&!d.info?.shortcut&&!d.info?.treasure&&!d.info?.arena),'ordinary main graph needs no core/key lock');
 const anchor=new THREE.Vector3(lab.arena.x,L.y+1.1,lab.arena.z+Math.min(4,lab.arena.h/2-2)+.45),cabinet=deadletter24Cabinet({physics:ph,scene:new THREE.Scene()},anchor);ph.world.step();const arrival=anchor.clone().add(new THREE.Vector3(0,.52,2.4));assert(ph.lineOfSight(arrival,new THREE.Vector3(lab.landmark.position.x,lab.landmark.position.y,lab.landmark.position.z),G.STATIC|G.DOOR),'signature is visible from actual mode arrival over native cabinet');cabinet.dispose();ph.world.step();
 const distance=path=>path.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-path[i].x,p.z-path[i].z),0);assert(distance(lab.routes.covered)>distance(lab.routes.exposed)+1,'covered detour is a distinct longer route');walk(ph,L,lab.routes.exposed,id+'/direct');walk(ph,L,lab.routes.covered,id+'/covered');walk(ph,L,[...lab.routes.covered].reverse(),id+'/return');
 for(let i=0;i<8;i++){const a=i*Math.PI/4,p={x:lab.arena.x+Math.cos(a)*lab.arena.radius,z:lab.arena.z+Math.sin(a)*lab.arena.radius};assert(fac.nav.walkableAt(p.x,p.z),'broad boss arena floor continuous');let blocked=false;ph.world.intersectionsWithShape({x:p.x,y:L.y+.94,z:p.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.56,.35),()=>{blocked=true;return false;},undefined,groups(G.PLAYER,G.STATIC));assert(!blocked,'boss arena perimeter body-clear');}
 for(const p of lab.spawnSpots){assert(fac.nav.findPath(lab.arena.x,lab.arena.z,p.x,p.z,90000),'native mob navigation connects each authored spawn');let blocked=false;ph.world.intersectionsWithShape({x:p.x,y:L.y+.94,z:p.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.56,.35),()=>{blocked=true;return false;},undefined,groups(G.PLAYER,G.STATIC));assert(!blocked,'standing native creature spawn clear');}
 for(const p of lab.bossSpots){assert.equal(p.room,lab.arena.room);assert(Math.hypot(p.x-lab.arena.x,p.z-lab.arena.z)<=lab.arena.radius+.001);let blocked=false;ph.world.intersectionsWithShape({x:p.x,y:L.y+1.07,z:p.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.5,.55),()=>{blocked=true;return false;},undefined,groups(G.PLAYER,G.STATIC));assert(!blocked,'native Warden body clears authored boss spot '+id+'/'+seed+' '+JSON.stringify(p));assert(fac.nav.findPath(p.x,p.z,lab.arena.x,lab.arena.z,90000));}assert(lab.bossSpots.some(p=>Math.hypot(p.x-lab.arena.x,p.z-lab.arena.z)>=8-.001),'central crew can permit a boss at the native8m safety gap');
 const cover=lab.cover[0],delta=new THREE.Vector3(cover.size[0]+.5,0,0),origin=new THREE.Vector3(cover.x,cover.y,cover.z).sub(delta);assert(ph.raycast(origin,new THREE.Vector3(1,0,0),delta.length()+1,G.STATIC),'cover is physically solid');assert(!fac.nav.walkableAt(cover.x,cover.z),'cover native navigation agrees');
 coverProof(ph,L,cover,id);
 const previousLang=getLang(),draws=lab.metrics.signDraws;setLang('tr');const trDraws=lab.metrics.signDraws;setLang('tr');assert.equal(lab.metrics.signDraws,trDraws,'unchanged language does not redraw route atlas');setLang('ru');setLang(previousLang);assert(lab.metrics.signDraws>=draws+2);
 const lobby=buildDescent21({facility:fac,physics:ph,floor:2});assert(lobby,'actual safe return cabin exists');ph.world.step();for(const route of lobby.plan.routeProof.spawnPaths)walk(ph,L,route,id+'/cabin');lobby.dispose();
 const resources=new Set();fac.group.getObjectByName('lab24-'+id).traverse(o=>{if(o.geometry)resources.add(o.geometry);if(o.material){resources.add(o.material);if(o.material.map)resources.add(o.material.map);}});assert(resources.size>=6,'actual authored geometry/material ownership captured');let released=0;for(const r of resources)r.addEventListener('dispose',()=>released++);fac.dispose(ph);assert.equal(released,resources.size);const stopped=lab.metrics.signDraws;setLang('tr');assert.equal(lab.metrics.signDraws,stopped,'disposed route sign unsubscribes language listener');setLang('en');assert.equal(ph.info.size,0,'all native/cover/lift colliders disposed');ph.world.free();total++;
}
registerLab24Moons();for(const def of LAB24_MOON_DEFS){assert.equal(MOONS[def.id].interior,def.interior);assert(def.instance&&def.deadletter24);assert.equal(def.power,0);assert(!MOON_ORDER.includes(def.id),'empty trial excluded from native route list');}
for(const def of LAB24_FIELD_MOON_DEFS){assert(MOON_ORDER.includes(def.id));assert(!def.instance&&!def.deadletter24);assert(def.power>0&&def.scrapCount[0]>=12&&Object.keys(def.creatures).length>=6,'ordinary expedition has native loot and finite ambient budget');assert(LAB24_IDS.includes(MOONS[def.id].interior));}
console.log(`lab24: PASS (${total} real facilities, native direct/cover/return/cabin controllers, solid cover/nav, spawn clearance and cleanup)`);
