import './ship2_env.mjs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {Physics,initPhysics} from '../../src/physics/physics.js';
import {Emitter} from '../../src/core/events.js';
import {Session} from '../../src/net/session.js';
import {installOxygen38} from '../../src/game/oxygen38.js';
import {generateLayout,buildFacility} from '../../src/world/facility.js';
await initPhysics();const physics=new Physics();physics.addStaticBox(0,-.1,0,10,.1,10);physics.world.step();
document.body.append=()=>{};
const mods=new Emitter(),net=new Session({strategy:'local',isHost:true,code:'air38',profile:{}}),player={pos:new THREE.Vector3(0,0,0),indoor:true,dead:false,inShip:false,eye:1.62};
net.isHost=true;net.selfId='airhost';
const layout=generateLayout(5,'factory',.68),facility=buildFacility(layout,{physics,lightPool:{add:x=>x,remove(){}}});physics.world.step();player.pos.y=layout.y;
const game={mods,net,physics,selfId:'airhost',isHost:true,time:0,run:{phase:'moon',moon:'hamsi',seed:5,runId:'air',day:1},world:{moonId:'hamsi',seed:5,facility},player,remotes:new Map(),aiPlayers:()=>[{...player,id:'airhost'}],broadcastRun(){},hostSave(){},hostHurtPlayer(){this.hurts=(this.hurts||0)+1;}};
const api=installOxygen38(game);mods.emit('registerHandlers',(k,fn)=>net.handle(k,fn),game);
for(let i=0;i<241;i++){game.time++;mods.emit('update',1,game);}
assert.equal(game.run.oxygen38.players.airhost,0,'normal indoor exploration exhausts finite air');assert(game.hurts>0,'zero air uses native hurt path');
player.indoor=false;game.time++;mods.emit('update',1,game);assert(game.run.oxygen38.players.airhost>0,'outside refills air');
const before=game.run.oxygen38.players.airhost;player.indoor=true;player.dead=true;game.time++;mods.emit('update',1,game);assert.equal(game.run.oxygen38.players.airhost,before,'dead players do not drain');
player.dead=false;assert(api.bottles.length>0&&api.bottles.length<=3,'native certified floor has bounded refill cylinders');
const bottle=api.bottles[0],receipt={key:api.key,id:bottle.id};
player.pos.copy(bottle.pos).add(new THREE.Vector3(0,-.78,1));physics.world.step();
game.run.oxygen38.players.airhost=10;net.request('o38refill',{...receipt,key:'old-floor'});assert.equal(game.run.oxygen38.players.airhost,10,'stale floor receipt rejected');
net.request('o38refill',receipt);assert.equal(game.run.oxygen38.players.airhost,240,'real Session self request consumes a physical cylinder');
game.run.oxygen38.players.airhost=9;net.request('o38refill',receipt);assert.equal(game.run.oxygen38.players.airhost,9,'same supply cannot refill twice');
api.clear();game.time++;mods.emit('update',1,game);assert(game.run.oxygen38.used[`${receipt.key}:${receipt.id}`],'map reentry retains spent supply');
const other=api.bottles[1];assert(other);
const nextReceipt={key:api.key,id:other.id};game.run.oxygen38.players.airhost=20;
player.pos.copy(other.pos).add(new THREE.Vector3(0,-.78,1));
player.dead=true;net.request('o38refill',nextReceipt);assert.equal(game.run.oxygen38.players.airhost,20);player.dead=false;
player.pos.y+=2;net.request('o38refill',nextReceipt);assert.equal(game.run.oxygen38.players.airhost,20,'other native floor rejected');player.pos.y-=2;
const wall=physics.addStaticBox(other.pos.x,other.floor+1.1,other.pos.z+.5,.5,1.1,.06);physics.world.step();
net.request('o38refill',nextReceipt);assert.equal(game.run.oxygen38.players.airhost,20,'native wall blocks refill request');physics.removeCollider(wall);physics.world.step();
net.handlers.get('o38refill')(nextReceipt,'disconnected');assert.equal(game.run.oxygen38.players.airhost,20,'missing peer rejected');
player.pos.x+=8;net.request('o38refill',nextReceipt);assert.equal(game.run.oxygen38.players.airhost,20,'remote bottle cannot refill');
api.dispose();facility.dispose(physics);physics.world.free();net.clear();console.log('oxygen38: native host air drain, zero-air damage, outside refill and dead guard passed');
