import './ship2_env.mjs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {hostMethods} from '../../src/game/host.js';
import {initPhysics,Physics} from '../../src/physics/physics.js';
import {generateLayout,buildFacility} from '../../src/world/facility.js';
import {certifiedFuse38} from '../../src/game/power38.js';
import {LightPool} from '../../src/render/lightpool.js';
import {Session} from '../../src/net/session.js';
const handlers=new Map(),events=[];
const panel={id:'fuse0',type:'fuse',pos:new THREE.Vector3(0,-78.5,0)};
const g={selfId:'H',isHost:true,run:{phase:'moon',moon:'hamsi',seed:123,powerOn:false},world:{facility:{interactables:[panel],doors:[]},descent21Depth:0},player:{pos:new THREE.Vector3(0,-80,1),eye:1.62,dead:false},remotes:new Map(),hostData:{},physics:{raycast:()=>null},net:{handle:(k,f)=>handlers.set(k,f),broadcast:(...a)=>events.push(a),sendTo:(...a)=>events.push(a)},playerName:()=> 'Crew',hostSetPower:hostMethods.hostSetPower};
hostMethods.registerHandlers.call(g);
handlers.get('fuse')({fuse:panel.id,moon:'hamsi',seed:123,depth:0},'intruder');
assert.equal(g.run.powerOn,false,'unknown actor cannot restore power or claim fuse XP');
g.player.pos.set(40,-80,40);
handlers.get('fuse')({fuse:panel.id,moon:'hamsi',seed:123,depth:0},'H');
assert.equal(g.run.powerOn,false,'remote stale minigame completion must be rejected');
g.player.pos.set(0,-80,1);
const request={fuse:panel.id,moon:'hamsi',seed:123,depth:0};
handlers.get('fuse')({...request,seed:122},'H');assert.equal(g.run.powerOn,false,'old map receipt rejected');
g.physics.raycast=()=>({distance:.1});handlers.get('fuse')(request,'H');assert.equal(g.run.powerOn,false,'wall blocks native restore');
g.physics.raycast=()=>null;handlers.get('fuse')(request,'H');assert.equal(g.run.powerOn,true);
assert.equal(events.filter(e=>e[0]==='power').length,1,'real power broadcast once');
handlers.get('fuse')(request,'H');assert.equal(events.filter(e=>e[0]==='xp').length,1,'diagnostic replay cannot farm reward');
console.log('power38 native host fuse authority PASS');
const scheduled=[],departureEvents=[];
const departure={isHost:true,run:{phase:'moon'},hostData:{},broadcastRun:()=>{},net:{broadcast:(...a)=>departureEvents.push(a)},hostSetPhase(p){this.run.phase=p;},later:(f,ms)=>scheduled.push({f,ms}),hostFinishTakeoff(){},hostBeginTakeoff:hostMethods.hostBeginTakeoff};
departure.hostBeginTakeoff('midnight');assert.equal(departure.run.phase,'moon','clock never forces departure');assert.equal(scheduled.length,0);
departure.hostBeginTakeoff('lever');assert.equal(departure.run.phase,'moon','crew boarding window remains on moon');assert.equal(departure.run.departure38.seconds,8);assert.equal(departureEvents.length,0,'door stays open during boarding countdown');
departure.hostBeginTakeoff('lever');assert.equal(departure.run.departure38,null,'repeat lever cancels boarding countdown');
assert.equal(scheduled.length,1,'cancel adds no replacement timer');
scheduled.shift().f();assert.equal(departure.run.phase,'moon','abandoned timer cannot depart');
departure.hostBeginTakeoff('lever');assert.equal(departure.run.departure38.seconds,8,'fresh lever starts a new full countdown');
for(let n=0;n<8;n++){const next=scheduled.shift();assert.equal(next.ms,1000);next.f();}
assert.equal(departure.run.phase,'takeoff');assert.equal(departureEvents[0][0],'door');assert.equal(scheduled[0].ms,7000,'native flight still seven seconds');
console.log('power38 explicit crew departure countdown PASS');
await initPhysics();
const physics=new Physics(),lights=new LightPool(new THREE.Scene());
const fac=buildFacility(generateLayout(1235,'factory',20),{physics,lightPool:lights});
physics.world.step();
const certified=certifiedFuse38({world:{facility:fac},physics});
assert.ok(certified,'actual factory seed has a native capsule/range/LOS reachable restoration panel');
const facilityEmitter=[...lights.emitters].find(e=>e.group==='facility');assert.ok(facilityEmitter);
lights.globalDim=0;assert.equal(lights.groupFactor(facilityEmitter),0);assert.equal(lights.groupFactor({group:'ship'}),1);assert.equal(lights.groupFactor({group:'exit'}),1);
lights.globalDim=1;assert.equal(lights.groupFactor(facilityEmitter),1,'native facility lighting actually returns');
fac.dispose(physics);physics.world.free();
console.log('power38 actual factory capsule certificate and facility light restoration PASS');
const session=new Session({strategy:'local',isHost:true,code:'door38'});session.selfId=session.hostId='H';
g.net=session;g.run={phase:'orbit',fleet13:{docked:true}};g.world.moonId='__relay13';g.ship={points:{doorOpen:new THREE.Vector3(0,1.3,0)},doorOutside:new THREE.Vector3(0,0,2),door:{open:true}};g.player.pos.set(0,0,1);g.physics.raycast=()=>null;
session.on_('door',d=>{g.ship.door.open=d.open;});hostMethods.registerHandlers.call(g);
try{
 session.request('shipdoor',{open:false});assert.equal(g.ship.door.open,false,'real Session self callback closes dock ship');
 session.request('shipdoor',{open:true});assert.equal(g.ship.door.open,true,'real Session self callback opens dock ship');
 g.run.fleet13.docked=false;session.request('shipdoor',{open:false});assert.equal(g.ship.door.open,true,'orbit in space remains sealed');
 g.run.fleet13.docked=true;g.player.pos.set(50,0,50);session.request('shipdoor',{open:false});assert.equal(g.ship.door.open,true,'remote requests cannot close door');
}finally{session.transport.leave();session.clear();}
console.log('power38 real Session dock door controls PASS');
