"""
Registry of every downloaded pack: credits/licensing metadata shared by the processing scripts
and the CREDITS.md generator. `raw` is the folder under tools/raw/, `slug` the folder under
public/assets/ext/<category>/.
"""

PACKS = {
    # ---------------------------------------------------------------- textures
    "sbs_tiny1": dict(name="Tiny Texture Pack 1", author="Screaming Brain Studios",
                      url="https://screamingbrainstudios.itch.io/tiny-texture-pack",
                      license="CC0", raw="screamingbrainstudios__tiny-texture-pack", slug="sbs-tiny-1"),
    "sbs_tiny2": dict(name="Tiny Texture Pack 2", author="Screaming Brain Studios",
                      url="https://screamingbrainstudios.itch.io/tiny-texture-pack-2",
                      license="CC0", raw="screamingbrainstudios__tiny-texture-pack-2", slug="sbs-tiny-2"),
    "sbs_tiny3": dict(name="Tiny Texture Pack 3", author="Screaming Brain Studios",
                      url="https://screamingbrainstudios.itch.io/tiny-texture-pack-3",
                      license="CC0", raw="screamingbrainstudios__tiny-texture-pack-3", slug="sbs-tiny-3"),
    "sbs_horror": dict(name="Horror Texture Pack", author="Screaming Brain Studios",
                       url="https://screamingbrainstudios.itch.io/horror-texture-pack",
                       license="CC0", raw="screamingbrainstudios__horror-texture-pack", slug="sbs-horror"),
    "sbs_mini1": dict(name="Mini Texture Pack 1: Tile Floors", author="Screaming Brain Studios",
                      url="https://screamingbrainstudios.itch.io/mini-texture-pack-1",
                      license="CC0", raw="screamingbrainstudios__mini-texture-pack-1", slug="sbs-mini-floors"),
    "flakdeau_px": dict(name="1000+ Pixel Art Texture - 256x256", author="FlakDeau",
                        url="https://flakdeau19.itch.io/pixel-art-texture-pack-256x256",
                        license="CC0", raw="flakdeau19__pixel-art-texture-pack-256x256", slug="flakdeau-pixel"),
    # ---------------------------------------------------------------- sounds
    "obx_horror": dict(name="Horror SFX Volume 1 (Free Pack, Drones 1, Stingers 2)", author="ObsydianX",
                       url="https://obsydianx.itch.io/horror-sfx-volume-1",
                       license="CC-BY 4.0", credit="Horror SFX Volume 1 by ObsydianX (CC-BY 4.0)",
                       raw="obsydianx__horror-sfx-volume-1", slug="obsydianx-horror"),
    "obx_ui": dict(name="Interface SFX Pack 1", author="ObsydianX",
                   url="https://obsydianx.itch.io/interface-sfx-pack-1",
                   license="CC0", raw="obsydianx__interface-sfx-pack-1", slug="obsydianx-ui"),
    "liminal_horror": dict(name="FREE HORROR SFX - Scary Sound Effects (vol 1+2)", author="Liminal Games",
                           url="https://liminal-space-dev.itch.io/free-horror-sfx-sounds",
                           license="CC0 (author asks not to resell/redistribute the pack itself)",
                           raw="liminal-space-dev__free-horror-sfx-sounds", slug="liminal-horror"),
    "phlegm_horror": dict(name="Horror Sound Pack", author="Phlegmlee",
                          url="https://phlegmlee.itch.io/horror-sound-pack",
                          license="CC0", raw="phlegmlee__horror-sound-pack", slug="phlegmlee-horror"),
    "goofy_monsters": dict(name="Goofy Sounds for Scary Monsters", author="Stormyman (C. Hahn et al.)",
                           url="https://stormyman.itch.io/goofy-sounds-for-scary-monsters",
                           license="CC0", raw="stormyman__goofy-sounds-for-scary-monsters", slug="goofy-monsters"),
    "cluck_rain": dict(name="Rain and Thunder", author="cluckfox",
                       url="https://cluckfox.itch.io/rain-and-thunder",
                       license="CC0", raw="cluckfox__rain-and-thunder", slug="cluckfox-rain"),
    "kronbits_sfx": dict(name="200 Free SFX", author="Kronbits",
                         url="https://kronbits.itch.io/freesfx",
                         license="CC0", raw="kronbits__freesfx", slug="kronbits-sfx"),
    "loadless_scifi": dict(name="Sci-fi SFX (Part 1)", author="loadless (Paul Timings)",
                           url="https://loadless.itch.io/scifi-sfx-1",
                           license="Free incl. commercial use with credit to \"Paul Timings\" + link",
                           credit="Sci-fi SFX by Paul Timings (loadless) - https://loadless.itch.io/scifi-sfx-1",
                           raw="loadless__scifi-sfx-1", slug="loadless-scifi"),
    "nihilex_facility": dict(name="Underground Facility Ambient Pack (Free Audio Asset Collection)", author="Nihilex",
                             url="https://nihil-existentia.itch.io/free-audio-asset-collection",
                             license="CC0", raw="nihil-existentia__free-audio-asset-collection", slug="nihilex-facility"),
    # ---------------------------------------------------------------- models
    "q_monsters": dict(name="LowPoly Animated Monsters", author="Quaternius",
                       url="https://quaternius.itch.io/lowpoly-animated-monsters",
                       license="CC0", raw="quaternius__lowpoly-animated-monsters", slug="quaternius-monsters"),
    "q_enemies": dict(name="LowPoly Animated Easy Enemies", author="Quaternius",
                      url="https://quaternius.itch.io/animated-easy-enemies",
                      license="CC0", raw="quaternius__animated-easy-enemies", slug="quaternius-enemies"),
    "q_robot": dict(name="LowPoly Robot", author="Quaternius",
                    url="https://quaternius.itch.io/lowpoly-robot",
                    license="CC0", raw="quaternius__lowpoly-robot", slug="quaternius-robot"),
    "q_fish": dict(name="LowPoly Animated Fish", author="Quaternius",
                   url="https://quaternius.itch.io/lowpoly-animated-fish",
                   license="CC0", raw="quaternius__lowpoly-animated-fish", slug="quaternius-fish"),
    "q_trees": dict(name="Textured LowPoly Trees", author="Quaternius",
                    url="https://quaternius.itch.io/textured-lowpoly-trees",
                    license="CC0", raw="quaternius__textured-lowpoly-trees", slug="quaternius-trees"),
    "q_nature": dict(name="150+ LowPoly Nature Models", author="Quaternius",
                     url="https://quaternius.itch.io/150-lowpoly-nature-models",
                     license="CC0", raw="quaternius__150-lowpoly-nature-models", slug="quaternius-nature"),
    "k_survival": dict(name="Survival Kit", author="Kenney",
                       url="https://kenney-assets.itch.io/survival-kit",
                       license="CC0", raw="kenney-assets__survival-kit", slug="kenney-survival"),
    "k_station": dict(name="Space Station Kit", author="Kenney",
                      url="https://kenney-assets.itch.io/space-station-kit",
                      license="CC0", raw="kenney-assets__space-station-kit", slug="kenney-space-station"),
    "k_conveyor": dict(name="Conveyor Kit", author="Kenney",
                       url="https://kenney-assets.itch.io/conveyor-kit",
                       license="CC0", raw="kenney-assets__conveyor-kit", slug="kenney-conveyor"),
    "dj_furniture": dict(name="PSX Derelict Furniture (Standard)", author="Daniel Jurys",
                         url="https://daniel-jurys.itch.io/psx-derelict-furniture",
                         license="CC0", raw="daniel-jurys__psx-derelict-furniture", slug="jurys-derelict-furniture"),
    "dj_waste": dict(name="PSX Waste", author="Daniel Jurys",
                     url="https://daniel-jurys.itch.io/psx-waste",
                     license="CC0", raw="daniel-jurys__psx-waste", slug="jurys-waste"),
    "cd_plumbing": dict(name="3D Retro Plumbing, Wiring & Machinery", author="chilly_durango",
                        url="https://chilly-durango.itch.io/3d-retro-plumbing-wiring",
                        license="CC0", raw="chilly-durango__3d-retro-plumbing-wiring", slug="chilly-plumbing"),
    "vk_vents": dict(name="PSX style modular vents", author="valsekamerplant",
                     url="https://valsekamerplant.itch.io/psx-style-modular-vents",
                     license="CC0", raw="valsekamerplant__psx-style-modular-vents", slug="valse-vents"),
    "vk_barriers": dict(name="PSX style barriers", author="valsekamerplant",
                        url="https://valsekamerplant.itch.io/psx-style-barriers",
                        license="CC0", raw="valsekamerplant__psx-style-barriers", slug="valse-barriers"),
    "kkryy_interior": dict(name="Retro Model Pack Interior", author="Kkryy",
                           url="https://kkryy.itch.io/retro-interior-pack",
                           license="CC0", raw="kkryy__retro-interior-pack", slug="kkryy-interior"),
    "ggf_industrial": dict(name="PSX Industrial Environment Asset Pack", author="godgoldfear",
                           url="https://godgoldfear.itch.io/psx-industrial-environment-asset-pack",
                           license="CC-BY 4.0", credit="PSX Industrial Environment Asset Pack by godgoldfear (CC-BY 4.0)",
                           raw="godgoldfear__psx-industrial-environment-asset-pack", slug="godgoldfear-industrial"),
    "styloo_random": dict(name="Random Objects", author="styloo",
                          url="https://styloo.itch.io/random",
                          license="CC0", raw="styloo__random", slug="styloo-random"),
    "kk_spacebase": dict(name="KayKit : Space Base Bits (Free)", author="Kay Lousberg",
                         url="https://kaylousberg.itch.io/space-base-bits",
                         license="CC0", raw="kaylousberg__space-base-bits", slug="kaykit-space-base"),
    "kk_resource": dict(name="KayKit : Resource Bits (Free)", author="Kay Lousberg",
                        url="https://kaylousberg.itch.io/resource-bits",
                        license="CC0", raw="kaylousberg__resource-bits", slug="kaykit-resources"),
    # ---------------------------------------------------------------- round 2 (new interior themes)
    "tfg_custom": dict(name="TFG Custom (made for this game)", author="TFG team (Blender / Python, tools/blender/tfg_props.py)",
                       url="tools/blender/tfg_props.py + tools/assets/tfg_textures.py + tools/assets/tfg_audio.py",
                       license="CC0", raw="tfg_model_tex", slug="tfg-custom"),
    "kenney_furniture": dict(name="Furniture Kit GLB Pack (Kenney Furniture Kit)", author="Kenney (GLB repack by Eclair Assets)",
                             url="https://eclair-assets.itch.io/furniture-kit-glb-pack-140-free-cc0-3d-models",
                             license="CC0", raw="eclair-assets__furniture-kit-glb-pack-140-free-cc0-3d-models",
                             slug="kenney-furniture"),
    "ggbot_cars": dict(name="PSX Style Cars", author="GGBotNet",
                       url="https://ggbot.itch.io/psx-style-cars",
                       license="CC0", raw="ggbot__psx-style-cars", slug="ggbot-cars"),
    "tilt_boxes": dict(name="PSX | Boxes", author="Tiltamoose",
                       url="https://tiltamoose.itch.io/psx-boxes",
                       license="CC0", raw="tiltamoose__psx-boxes", slug="tiltamoose-boxes"),
    "kk_halloween": dict(name="KayKit : Halloween Bits (Free)", author="Kay Lousberg",
                         url="https://kaylousberg.itch.io/halloween-bits",
                         license="CC0", raw="kaylousberg__halloween-bits", slug="kaykit-halloween"),
    "gibbon_backrooms": dict(name="Low-res Backrooms and Poolrooms textures", author="GibbonGL",
                             url="https://gibbongl.itch.io/backrooms-low-res-textures",
                             license="CC0", raw="gibbongl__backrooms-low-res-textures", slug="gibbongl-backrooms"),
    "nb_backrooms": dict(name="Backrooms Asset Pack", author="NaiveGoblin",
                         url="https://naivegoblin.itch.io/cc0-backrooms-asset-pack",
                         license="CC-BY 4.0", credit="Backrooms Asset Pack by NaiveGoblin (CC-BY 4.0)",
                         raw="naivegoblin__cc0-backrooms-asset-pack", slug="naivegoblin-backrooms"),
    "gq_water": dict(name="Free Water Stream Sounds", author="Gregor Quendel",
                     url="https://gregor-quendel.itch.io/free-water-stream-sounds",
                     license="CC-BY 4.0", credit="Free Water Stream Sounds by Gregor Quendel (CC-BY 4.0)",
                     raw="gregor-quendel__free-water-stream-sounds", slug="quendel-water"),
}
